### ISSUE TITLE
Add option to specify date in getSignedUrl

### ISSUE THREAD

**Issue by nknotts** [googleapis/nodejs-storage#1041]
https://cloud.google.com/storage/docs/access-control/signed-urls

From the documentation, signed urls support the following headers.
```
X-Goog-Date: The date and time the signed URL became usable, in the ISO 8601 basic format YYYYMMDD'T'HHMMSS'Z'.

X-Goog-Expires: The length of time the signed URL remained valid, measured in seconds from the value in X-Goog-Date. In this example the Signed URL expires in 15 minutes. The longest expiration value is 604800 seconds (7days).
```

However, with respect to the javascript api, only the expiration is a valid input

https://github.com/googleapis/nodejs-storage/blob/b1c60bbfb11319a6543b0f137e3c2e3d1db9dd11/src/file.ts#L68

```
export interface GetSignedUrlConfig {
  action: 'read' | 'write' | 'delete' | 'resumable';
  version?: 'v2' | 'v4';
  cname?: string;
  contentMd5?: string;
  contentType?: string;
  expires: string | number | Date;
  extensionHeaders?: http.OutgoingHttpHeaders;
  promptSaveAs?: string;
  responseDisposition?: string;
  responseType?: string;
}
```

In the code, `X-Goog-Date` is always set to `Date.now` and `X-Goog-Expires` is calculated relative to `Date.now`.

I propose adding an option to specify the the `date` field and default it to `Date.now`. 

My use case is, for a short time, I would like the same call to `getSignedUrl` to return the same value. As is, this is impossible, since `Date.now` is forever changing.

I can take a stab at adding this feature if it is accepted.

**Comment by jkwlui** [comment]
Hi @nknotts! Thanks for raising the request. I think the proposed change is reasonable and should be easy to make the change in a non-breaking way. Would you like to submit a PR for this?

**Comment by nknotts** [comment]
Great! I will submit a PR in a few days.

**Comment by rhodgkins** [comment]
@nknotts did you manage to get around to the PR?

**Comment by houglum** [comment]
Let's hold off on merging the PR.  Upon talking to @frankyn and reviewing this feature request, we found that there's a bug in the service's validation code where the start date isn't actually enforced currently (for Googlers, the bug number is 149866950).  In the spirit of not breaking users that are currently relying on this bug without realizing it, I'd rather minimize the set of affected users and not make it easier for more people to start doing it.  Let's not make this functionality available in the client libraries until we can fix the validation behavior.

**Comment by frankyn** [comment]
Thanks @houglum. Marked issue as blocked for now. Will surfaced this in the related PR.
