### ISSUE TITLE
getting issue in uploadFile.js -> (node:3552) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'D:/nodejs/file.txt' 

### ISSUE THREAD

**Issue by Anuradha677** [googleapis/nodejs-storage#1054]
(node:3552) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'D:/nodejs/file.txt'
(node:3552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
#### Steps to reproduce

  1. I have used uploadFile.js
  2.  used the const filename = 'D:/nodejs/test2.txt';. here this file is present in this path but still shows the error.

Thanks!

**Comment by laljikanjareeya** [comment]
Message that explain that file or directory is not found on specified Path.
I try putting catch on below location and it gives the clear message:

https://github.com/googleapis/nodejs-storage/blob/719beca5f89743b01aab7375663b371db6548b6e/samples/uploadFile.js#L47

Error while File not available on specific Path:
```ts
[Error: ENOENT: no such file or directory, stat 'F:\storage-files\958\test1.txt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'F:\\storage-files\\958\\test1.txt'
}
```
I will shortly add the PR to remove `UnhandledPromiseRejectionWarning`.

while file is properly available on specific Path it gives following output:
```
F:/storage-files/958/test.txt uploaded to task-958.
```
can you please cross check your file path again.

**Comment by Anuradha677** [comment]
Hi Lalji,

Thanks for replying.

I was using cloud Shell and trying to upload a file from the laptop's local directory which is not possible in cloud shell. 
I have used Cloud SDK and put the code in local directory. Now I am able to add files from the local directory.
Hence, closing the issue.
