### ISSUE TITLE
react native application fs could not be found within the project

### ISSUE THREAD

**Issue by saeromCho** [googleapis/nodejs-storage#1057]
<img width="379" alt="스크린샷 2020-01-31 오전 4 42 29" src="https://user-images.githubusercontent.com/28703206/73485021-b915b200-43e5-11ea-8732-fb1f2bd9bec0.png">

I used yarn to install the module and run the simulator within my current Reactive Native project, but there was a photo error.
I looked at the issues, but there were no issues like me.
How do we deal with it?
This module don't use the 'fs' module on the package.json module.
However /storage/build/src/bucket.js uses the 'fs' module.
It's strange.
Is the version of the google-cloud module I installed strange?
It's @4.3.0, and it's the latest version, but it's like a stable version.
My node version is 10.16.3, react-native 0.61.5. 
I'll talk to you as soon as I have additional versions of the modules that I need to deal with this issue.
Guys and sir, please help me. 

Thank you bro!

**Comment by laljikanjareeya** [comment]
Please refer the below comment:
https://github.com/googleapis/nodejs-pubsub/issues/742#issuecomment-531732267
