### ISSUE TITLE
creating signedUrl's even file is not available/found

### ISSUE THREAD

**Issue by rakyesh22** [googleapis/nodejs-storage#1061]
As i am working on firebase storage with firebase node sdk.
So when i am creating file **signed url link**  (`(getSignedUrl(optionData)`), it creating link url for all file names.
but when i pass file name **which doesn't exist in firebase storage**, it also creating **signed url link**.
**instead it should error/exception for file not found**.

**Comment by AVaksman** [comment]
I believe not returning/throwing an error for a non-existing file is normal behavior .
Please refer to a similar question [here](https://github.com/googleapis/nodejs-storage/issues/762).
