### ISSUE TITLE
docs: explain that the IAM scope is required

### ISSUE THREAD

**Issue by imathews** [googleapis/nodejs-storage#107]
#### Environment details

  - OS: GKE cos
  - Node.js version: 8.6
  - npm version: 5.0.3
  - @google-cloud/storage version: 1.5.1

#### Steps to reproduce

I'm trying to generate a signed url from within my node app running on a GKE cluster; I'm getting the error `Request had insufficient authentication scopes`. I'm wondering which scope(s) are necessary to enable signing; my cluster has "full" permissions for storage. 

Many thanks for your help!

**Comment by stephenplusplus** [comment]
When a `keyFilename` is not directly provided, such as in automatically-authenticated environments like GKE, we call the [signBlob API](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob#authorization-scopes) to create a signed URL. That API requires either the `https://www.googleapis.com/auth/iam` or `https://www.googleapis.com/auth/cloud-platform` scope.

**Comment by imathews** [comment]
Thanks @stephenplusplus — I updated the scopes on the pools in my GKE cluster, and now it's working as expected. 

I don't think this is in the docs; was a bit confusing to me that scopes outside of `storage` were necessary to get this to work.

**Comment by stephenplusplus** [comment]
I agree, we should make that more clear. Glad to hear it's working now!
