### ISSUE TITLE
V4 responseDisposition breaks signature validation

### ISSUE THREAD

**Issue by Tallyrald** [googleapis/nodejs-storage#1073]
I am running into a v2 vs v4 issue with the responseDisposition field when generating signedURLs. Please consider the following:

```typescript
const bucketName = 'some-bucket-name';
const fileName = 'some-file-name';
// Authorize for 15 minutes
const MINUTES = 15;
const SECONDS = 60;
const MILLISECONDS = 1000;

const options: GetSignedUrlConfig = {
	action: 'read',
	expires: Date.now() + MINUTES * SECONDS * MILLISECONDS,
	responseDisposition: `attachment; filename="some-file-name"`,
	version: 'v4',
};

const [url] = await storage
.bucket(bucketName)
.file(fileName)
.getSignedUrl(options);
```

Using the URL results in a SignatureDoesNotMatch error. Changing version to v2 solves to problem.

Important note:
I know that this very issue has been somewhat referenced in #682 however that issue was closed due to backend not supporting this function at that time. Since then the linked documentation [in this comment](https://github.com/googleapis/nodejs-storage/issues/682#issuecomment-497457654) has been changed and it does not state the missing functionality anymore. This is why I expect the above code to work.

The same observation was made in #859 as well [in this comment](https://github.com/googleapis/nodejs-storage/issues/859#issuecomment-548745287) after that issue was closed.

I also found the workaround [seen in this comment](https://github.com/googleapis/nodejs-storage/issues/682#issuecomment-492960264) but as that is not actually a solution, I am reluctant implementing it.

Could anyone please explain what is the state of this feature and what to expect in the future?
Thank you!

#### Environment details

  - OS: Windows 10 1907
  - Node.js version: 13.7.0
  - npm version: 6.12.0
  - `@google-cloud/storage` version: 4.3.0

**Comment by jkwlui** [comment]
Hi @Tallyrald, thanks for your bug report. This is due to a bug because we are not signing query parameters, which is a requirement for v4 signed URLs.

We have #1072 under review right now which would resolve this issue. I appreciate your patience while we're working to get this out.

**Comment by jkwlui** [comment]
@Tallyrald Thank you for your patience. We just launched v4.5.0 of the library which contains fixes to v4 signing mechanism, which should resolve your issue. Please have a try and feel free to reopen this issue if you're experiencing further issues.
