### ISSUE TITLE
Downloading the file from metadata

### ISSUE THREAD

**Issue by abutreca** [googleapis/nodejs-storage#1078]
According to google documentation: https://cloud.google.com/storage/docs/json_api/v1/objects

When you [list the object](https://github.com/googleapis/nodejs-storage/blob/master/samples/listFiles.js) there's a mediaLink to provide the requester with a download link. The problem is that when I try to download it, says: "Anonymous caller does not have storage.objects.get access".

I suppose I have to send an access token somehow to get authentication. How do I do that?

**Comment by laljikanjareeya** [comment]
@abutreca you can generate download link for file using `getSignedUrl` please refer [this](https://github.com/googleapis/nodejs-storage/blob/master/samples/generateV4ReadSignedUrl.js) sample for same.

**Comment by abutreca** [comment]
> 
> 
> @abutreca you can generate download link for file using `getSignedUrl` please refer [this](https://github.com/googleapis/nodejs-storage/blob/master/samples/generateV4ReadSignedUrl.js) sample for same.

Thats a solution, but mediaLinks cant be used for the same result?

**Comment by laljikanjareeya** [comment]
You can do using OAuth 2.0, Please refer [this question](https://stackoverflow.com/questions/25381139/google-cloud-storage-medialink-http-1-1-401-unauthorized) and [OAuth 2.0](https://cloud.google.com/storage/docs/authentication#oauth).
