### ISSUE TITLE
Typescript 3.7 support

### ISSUE THREAD

**Issue by Legogris** [googleapis/nodejs-storage#1083]
We're not stuck on 4.1.3 as of https://www.github.com/googleapis/nodejs-storage/issues/952 (and actually are not having issues on 4.1.3 despite being on typescript 3.7.5). 

What's blocking this restriction to be lifted?

**Comment by bcoe** [comment]
:wave: there were breaking changes between TypeScript 3.6 and 3.7, which caused issues for users running Angular.

In the next major version bump (when we drop Node 8) we will unpin TypeScript.

**Comment by stephenplusplus** [comment]
TypeScript has been unpinned!
