### ISSUE TITLE
Bucket name validation

### ISSUE THREAD

**Issue by kojnp** [googleapis/nodejs-storage#109]
I would like the bucket name to be validated (src/bucket.js) and some meaningful error shown. A common error may be including "gs://" in the beginning.

Not validating the bucket name can lead to cryptic errors down the line like:
> Error: Not Found
    at Request._callback ([....]/node_modules/gcs-resumable-upload/index.js:283:25)
    at Request.self.callback ([....]/node_modules/request/request.js:186:22)

I am not a great js dev, but this at the minimum (and it works, inserted at line 91) :
`if (name.indexOf("gs://") > -1){
         throw new TypeError("don't include gs:// in the bucket name");
 }`

**Comment by stephenplusplus** [comment]
Thanks for the suggestion. I think we should just handle `gs://{bucketName}` input correctly, and strip the leading `gs://`.
