### ISSUE TITLE
Getting "TypeError: The header content contains invalid characters" error for getFiles() function

### ISSUE THREAD

**Issue by ils-sapnaj** [googleapis/nodejs-storage#113]
#### Environment details

  - OS: Windows 10
  - Node.js version: v6.11.2
  - npm version: 3.10.10
  - @google-cloud/storage version:1.5.1

#### Steps to reproduce

  1. Run the examples mentioned in this repo for get list of files from bucket. Don't specify any Delimiter or prefix filter and you will get this error -

ERROR: TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:359:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:202:15)
    at Request.start (D:\XXX\XXX\node_modules\request\request.js:748:32)
    at Request.end (D:\XXX\XXX\node_modules\request\request.js:1512:10)
    at end (D:\XXX\XXX\node_modules\request\request.js:561:14)
    at Immediate.<anonymous> (D:\XXX\XXXX\node_modules\request\request.js:575:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)

I want to know, am I missing something or why I am getting this error. I am not setting any header in the request and I found that it is an issue within google cloud package where it is calling request module. 
@google-cloud\storage\src\bucket.js +1262

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Sorry for the trouble. Could you paste the code you are using?

**Comment by ils-sapnaj** [comment]
const Storage = require('@google-cloud/storage');

  // Creates a client
 var storage = Storage
  ({
      projectId: "CODE-XXX",
     keyFilename: './GCP_credentials.json'
  });

 var bucketName = storage.bucket("BUCKET-NAME-XXX");
  // Lists files in the bucket
  storage
    .bucket(bucketName)
    .getFiles()
    .then(results => {
      const files = results[0];

      console.log('Files:');
      files.forEach(file => {
        console.log(file.name);
      });
    })
    .catch(err => {
      console.error('ERROR:', err);
    });

**Comment by stephenplusplus** [comment]
Can you try again with these changes?

```diff
const Storage = require('@google-cloud/storage');

  // Creates a client
- var storage = Storage
+ var storage = new Storage
  ({
      projectId: "CODE-XXX",
     keyFilename: './GCP_credentials.json'
  });

- var bucketName = storage.bucket("BUCKET-NAME-XXX");
+ var bucketName = "BUCKET-NAME-XXX";
  // Lists files in the bucket
  storage
    .bucket(bucketName)
    .getFiles()
    .then(results => {
      const files = results[0];
      console.log('Files:');
      files.forEach(file => {
        console.log(file.name);
      });
    })
    .catch(err => {
      console.error('ERROR:', err);
    });
```

**Comment by ils-miteshs** [comment]
Thank you for the update, I will try and get back you soon.

**Comment by ils-sapnaj** [comment]
@stephenplusplus I am still getting the same error.

**Comment by ils-sapnaj** [comment]
@stephenplusplus I have tried your code but it is also not working. Are you able to recreate my issue ??

**Comment by ils-sapnaj** [comment]
@stephenplusplus Could you please help me to figure out this issue.

**Comment by stephenplusplus** [comment]
Sorry, I have not been able to recreate. Could you put together a repo or gist I can clone and run to see the error?

**Comment by stephenplusplus** [comment]
Without further help, I'm unfortunately unable to reproduce. I will gladly re-open if you can provide a sample repo or gist that can demonstrate the problem.
