### ISSUE TITLE
Google storage getFiles

### ISSUE THREAD

**Issue by Coldplayer1995** [googleapis/nodejs-storage#1146]
Hopefully this is something silly which I cannot find out.
code which does not work:

```js
admin.storage().bucket("gs://nameofthebucket.appspot.com")
  .getFiles().
  then(function(data) {
      //const files = data[0];
      response.send(data);
    }).catch(ex =>{ 
      response.send(ex);
    });
```

In the postman, the function returns an empty object.

This code though works fine
 
```js
const myFile = admin.storage().bucket("gs://nameofbucket.appspot.com").file('Scan.pdf')
response.send(myFile);
```

Does anyone have any clues why getFiles return empty obj?

EDIT : If someone would be wondering why I need this function I am planning to generate signed URL in order to display in this case all files as a gallery on the website. I have a plan to create a gallery folder and put them there but at this moment even that functionality is not working. If that should be done the other way around I am also open for suggestions.
Thanks Again!

**Comment by stephenplusplus** [comment]
I'm not sure why the array won't work as opposed to a single object. That may have to do with the layer you're using to send the response with (i.e., where is `response.send()` from?)
