### ISSUE TITLE
Implement File.update

### ISSUE THREAD

**Issue by flunderpero** [googleapis/nodejs-storage#1149]
We have a bucket full of objects with `metadata.contentDisposition` set. Now we want to change our
implementation to use `responseDisposition` with `File.getSignedUrl`.

But in order to use this, we have to *clear* `metadata.contentDisposition` which is impossible with the current API.  All we can do, is use `File.setMetadada({contentDisposition: ""})` but this will not *remove* `metadata.contentDisposition` but set it to an empty string. 

Because the content-disposition set in an object's metadata always takes precedence over `File.getSignedUrl({responseDisposition: ...})` the resulting `Content-Disposition`-header is always an empty string.

Reading on the JSON-API I see that there is actually a `update` operation that allows to completely (re-)set an object's metadata. But this operation is not exposed in the NodeJS-API.

Any hint to a workaround for the meantime would be greatly appreciated.

**Comment by flunderpero** [comment]
FYI, the workaround for my current problem (Content-Disposition cannot be removed) is as follows:
```
        const [metadata] = await file.getMetadata()
        const [acl] = await file.acl.get()
        delete metadata.contentDisposition
        await (file as any).request({
            method: "PUT",
            uri: "",
            qs: {
                userProject: blob_bucket.userProject,
            },
            json: {
                acl,
                ...metadata,
            },
        })

```

**Comment by itsbrianburton** [comment]
You should be setting contentDisposition to null to delete it.  From the docs:
```
      /* // Assuming current metadata = { hello: 'world', unsetMe: 'will do' }
       * file.setMetadata({
       *   metadata: {
       *     abc: '123', // will be set.
       *     unsetMe: null, // will be unset (deleted).
       *     hello: 'goodbye' // will be updated from 'world' to 'goodbye'.
       *   }
       * }, function(err, apiResponse) {
       *   // metadata should now be { abc: '123', hello: 'goodbye' }
       */ });
```

**Comment by flunderpero** [comment]
Stupid me. This works totally fine. I close this issue now.
