### ISSUE TITLE
ConfigurationObject has no export member

### ISSUE THREAD

**Issue by Justinio99** [googleapis/nodejs-storage#1150]
#### Environment details

  - OS: Windows 10
  - Node.js version: 12.13.0
  - npm version: 6.12.0
  - `@google-cloud/storage` version: 4.7.0

#### Steps to reproduce

  1. Install @google-cloud/storag
  2. Import as such import { Storage } from '@google-cloud/storage';

Typescript is complaining: node_modules/@google-cloud/storage/build/src"' has no exported member 'ConfigurationObject'. 

Thanks!

**Comment by willianVx** [comment]
I have the same issue.

**Comment by willianVx** [comment]
Hi, I've fix this with the follow code: 
`import * as GCloudSorage from '@google-cloud/storage';`
`const { Storage } = GCloudSorage.default || GCloudSorage;
`
I dont know if is the best solution, but works for me.

**Comment by Justinio99** [comment]
> Hi, I've fix this with the follow code:
> `import * as GCloudStorage from '@google-cloud/storage';`
> `const { Storage } = GCloudStorage.default || GCloudStorage; `
> I dont know if is the best solution, but works for me.

**Comment by Justinio99** [comment]
@willianVx dosen't work for me. If I do so I get "default does not exist on type"

**Comment by Justinio99** [comment]
Any updates on that issue?

**Comment by wcjord** [comment]
I've also got this issue

**Comment by raj2399** [comment]
This was happening when I added @google-cloud/storage into my project, and the solution was to add @types/google-cloud__storage. So the only thing you need to do is run:
npm add @types/google-cloud__storage'', this works fine for me.
