### ISSUE TITLE
HMAC authentication

### ISSUE THREAD

**Issue by srunicornio** [googleapis/nodejs-storage#117]
I want to use HMAC authentication. The problem is that I can't find any information about where to put Access Key and Secret. What is the way to introduce the Interoperable storage access keys?

**Comment by stephenplusplus** [comment]
cc @alexander-fenster @frankyn - we don't have support for this currently. Is it possible?

**Comment by frankyn** [comment]
Hi @srunicornio!

Clarifying question, do you want to use HMAC authentication with the NodeJS client library for Google Cloud Storage or a different client library?

**Comment by srunicornio** [comment]
Hi @franklyn

I’m looking for use HMAC with Nodejs client library for Google cloud storage. I was using the Rails library with HMAC authentication and I very liked.

**Comment by frankyn** [comment]
Thanks for clarifying @srunicornio.

HMAC is mainly used for interoperability with non-google Cloud Storage client libraries trying to use Google Cloud Storage using the XML API. This library is designed around the JSON API and as far as I know does not support HMAC for authentication.

When using this client library, you should use a service account as described in the Google Cloud API [Authentication documentation](https://cloud.google.com/docs/authentication/). It provides more information given different Google Cloud environments.

If you're having trouble with setting this up please let me know.

**Comment by srunicornio** [comment]
I just try it like as described in authentication documentation and it's works fine. 
Thank you @frankyn!
