### ISSUE TITLE
Customizing API endpoint is not working correctly

### ISSUE THREAD

**Issue by ojhaujjwal** [googleapis/nodejs-storage#1178]
#### Environment details

  - OS: Mac
  - Node.js version: 12.16.1
  - npm version:6.13.4
  - `@google-cloud/storage` version: 4.7.0

#### Steps to reproduce

  1. Customize `apiEndpoint`to use a fake GCS server like https://github.com/fsouza/fake-gcs-server
  2. Attempt to upload object

Works fine for bucket listing; but not for object creation.

**Comment by ojhaujjwal** [comment]
Looks like there there is some work being done on this here #1161

**Comment by frankyn** [comment]
Deduplicate: https://github.com/googleapis/nodejs-storage/issues/898
