### ISSUE TITLE
bucket.setCorsConfiguration is Not a function

### ISSUE THREAD

**Issue by WonderfulOlanrewaju** [googleapis/nodejs-storage#1181]
I read in the documentation that I can set Cors header for my bucket using bucket.setCorsConfiguration(configOptions) ..

But when I did this the package says bucket.setCorsConfiguration() is not a function, is that the method has been deprecated?

**Comment by laljikanjareeya** [comment]
@WonderfulOlanrewaju  `CORS` configuration support has been introduce in `@google-cloud/storage` [version 4.3.0](https://github.com/googleapis/nodejs-storage/releases/tag/v4.3.0) so make sure your installed package is `4.3.0` or above. 

Here is complete working example:
```ts
import { Storage } from '@google-cloud/storage';

async function setCros() {

    const bucketName = "task-1181"
    const storage = new Storage();
    
    const [metadata] = await storage.bucket(bucketName).setCorsConfiguration([
        {
            maxAgeSeconds: 10,
            origin:[
                'http://loccalhost:4200/'
            ]
        }
    ])

    console.log(`cors added to ${bucketName}.`);
}

setCros().catch(console.error);

```
**Output**
`cors added to task-1181.`

**Comment by stephenplusplus** [comment]
@WonderfulOlanrewaju please let us know if this doesn't resolve the issue.

**Comment by WonderfulOlanrewaju** [comment]
I already found another way to do it using the gsutil Cli.

I believe this should work too, the project is using version 4.1.3 That is why the method was not workind.
