### ISSUE TITLE
How to upload a file in chunks?

### ISSUE THREAD

**Issue by gajus** [googleapis/nodejs-storage#1192]
I am loosing my mind here, since I think I've tried absolutely everything and I still cannot figure out what is the proper way to do it.

Suppose I have a 0.9MB file.

```bash
$ ll
-rw-r--r--@  1 gajus  staff   921K 13 May 14:38 test.png

```

I then split that file into 2 chunks:

```bash
$ split -b 1000000 test.png
$ ll
-rw-r--r--@  1 gajus  staff   921K 13 May 14:38 test.png
-rw-r--r--   1 gajus  staff   488K 13 May 14:56 xaa
-rw-r--r--   1 gajus  staff   433K 13 May 14:56 xab

```

Assuming I only have access to the resulting chunks (and they might be on different servers, i.e. must be two distinct operations), what is the correct way to upload test.png?

Here is what I tried:

```js
(async () => {
  const googleStorageBucket = googleStorage.bucket('contrawork');
  const file = googleStorageBucket.file('images/test.png');
  const uri = (await file.createResumableUpload())[0];

  await googleStorageBucket.upload('./xaa', {
    gzip: false,
    offset: 0,
    predefinedAcl: 'publicRead',
    resumable: true,
    uri,
    validation: false,
  });

  await googleStorageBucket.upload('./xab', {
    gzip: false,
    offset: 500000,
    predefinedAcl: 'publicRead',
    resumable: true,
    uri,
    validation: false,
  });
})();

```

However, this uploads only first image. The second file is never appended.

[images_test.png.zip](https://github.com/googleapis/google-cloud-node/files/4624954/images_test.png.zip)

**Comment by stephenplusplus** [comment]
Thanks for the detailed write up. As it stands, we aren't currently able to handle this. There are a few potential solutions I can think of:

My thoughts:

- Save the chunks remotely, then combine them when complete (`bucket.combine([fileFragment1, fileFragment2])`)
  - Downsides: Cost penalty to create multiple files
- Save the object remotely, and overwrite it to append it with the next chunk
  - Downsides: Cost/performance penalty to download and upload a growing file
- Modify `gcs-resumable-upload` to handle this behavior (or a new method/library)
  - Downsides: Unsure this is a proper usage. Resumable uploads appear to have a minimum chunk size of 262144 bytes, so depending on the file, this could be unrealistic.

@frankyn is there a better way to handle this scenario? Also, please correct any mistakes I may have made in my breakdown above.

**Comment by frankyn** [comment]
The main issue with using resumable upload in this scenario is that they're sequential, meaning you can't set the offset to where you'd like it to be in different servers. 

Your best bet will be to use @stephenplusplus's first suggestion using `combine()`. What you would do is the following:

1. Upload chunks from each server to a GCS bucket.
1. After chunks are uploaded, call bucket.combine() on 32 objects at a time. (Order them in sequential order to be concatenated correctly.)
1. Resulting combined object will be used in subsequent bucket.combine() calls to concatenate remaining objects.
1. Delete the unnecessary chunks.

The nice part of this design is that your chunks can all be upload to GCS from different services without having to deal with ordering in terms of offsets. You'd need to order them more likely by the name of the object. GCS will handle concatenating the objects in atomic operations and provide the resulting object.

**Comment by gajus** [comment]
Doesn't this incur a significant additional cost?

**Comment by gajus** [comment]
This would be easily possible if the arbitrary (?) 262144 bytes minimum chunk restriction did not exist. With that restriction, it is impossible to develop this functionality.

The use case is a distributed file upload system.

**Comment by stephenplusplus** [comment]
Because there's nothing we can do from our library, I'm going to close the issue. If anyone would like to chime in with more information or ideas, please feel free.

**Comment by frankyn** [comment]
A lot of stuff has been going on and got behind on these issues.

@stephenplusplus, is it possible to make chunk size modifiable? IIUC, 256 KB multiple is a perf guidance but can be smaller.

If @gajus is willing to implement the necessary distributed file system without a compose it could be helpful in this case.

**Comment by gajus** [comment]
For a bit of context, this is what I was developing.

https://github.com/gajus/express-tus

The limitation of minimum per-chunk upload size made it impossible to use with Google Storage in a distributed system. The only way to make it work is by first uploading the file to our local storage and _then_ upload it to Google Storage, which is far from perfect.

**Comment by stephenplusplus** [comment]
> IIUC, 256 KB multiple is a perf guidance but can be smaller.

Sorry @frankyn, I missed this tag. The 256kb isn't our limit from this library, but from the upstream API.

**Comment by danielduhh** [comment]
FYI @gajus, `chunkSize` is now supported as an optional resumable upload parameter in the latest version of the client. See [docs](https://googleapis.dev/nodejs/storage/latest/global.html#CreateRe) for details on usage.

**Comment by Chethan-sn** [comment]
Hi @danielduhh,
Could you please provide an example of how to use it? "chunkSize" is mentioned in CreateResumableUploadOptions. Even after mentioning the chunkSize it appears to be pushing only first chunk. I am trying to upload a file of 85MB and dividing it into 32MB chunks except last one.
Thanks

**Comment by Ranjeetvit453** [comment]
https://github.com/ranjeetvit2012/node-media-chunk-fs
