### ISSUE TITLE
commit file created with createWriteStream to make it accessible

### ISSUE THREAD

**Issue by Fxlr8** [googleapis/nodejs-storage#1205]
Hi. I am trying to create a game replay file that is created on-the-fly.
I create a `writableStream` with `File.createWriteStream` and write my game's state to that stream on every tick. 

I don't need the file's end to start playing the replay. But I can't access the file in the storage until I `.end()` the `writableStream`.

The first idea was to call `.end()` every N frames and resume the writing process with `offset` option. This kinda works, but sometimes it crashes with `The uploaded data did not match the data from the server.` I think this happens because the stream needs some time to finish uploading the data. Maybe I open the next one too early. 

Do I miss something here? Is there a simpler way?

**Comment by stephenplusplus** [comment]
@Fxlr8 I'm not familiar with the goal, but it's interesting. Could you explain in more detail what you're doing exactly? Alternatively, this could be a better question for StackOverflow, as they can advise better how to adapt different solutions to unique scenarios like this.

In case this is helpful, the error message (`The uploaded data...`) can be circumvented by setting `validation: false`. Of course, if you're concerned with that error, that won't be helpful at all!

**Comment by Fxlr8** [comment]
@stephenplusplus, sure

I want my players to be able to watch replays after the match ends.
My game server produces about 4000 bytes of replay data 20 times per second. When my game server starts it creates a `writableStream` with `File.createWriteStream`. On every update I serialize my game state and `.write()` it to that stream. 

Everything works as expected. But the replay file is only available after the game end and `writableStream.end()` call. So I can't see what is happening in the game until it is finished.

Then I got an idea. I could call `end()` every let's say 100 game updates. Then create a new stream from the same place to continue writing the replay. That way I can create a readable stream from my game client to start playing the replay. This also allows to watch the live game, but with a little delay. But I can't reliably resume the stream after I end it.

**Comment by stephenplusplus** [comment]
Thanks for the details. I'm not sure this is the best fit for that use case. Could that work better in a database solution? Or, creating multiple, unique files in a GCS folder, e.g. "{gameId}/{sessionId}/state0", "{gameId}/{sessionId}/state1", etc.? Resumable streams [come with overhead](https://github.com/googleapis/gcs-resumable-upload#how-it-works), and I'm not sure the resumable API would be able to keep up with the frequency of your calls.

I think this is a better question for StackOverflow using the tag here: https://stackoverflow.com/questions/tagged/google-cloud-storage. I'll close this issue, as I don't believe this is an issue with our library, but please feel free to come back and share what you've found for anyone else who might be interested.
