### ISSUE TITLE
Bucket exists method privileges

### ISSUE THREAD

**Issue by konraddysput** [googleapis/nodejs-storage#1219]
Hey,

I'm trying to validate if credentials to google bucket are valid in my configuration file. One of the acceptations criteria for this feature is to check if a bucket exists. `Bucket` class has method `exists` that ideally matches my criteria, however, to check if bucket exists I need to add storage admin privilege? There is no other way to avoid adding more privileges that we should to the bucket to validate connection with the bucket?

**Comment by stephenplusplus** [comment]
Thanks for the question @konraddysput.

@frankyn, is this a library question or a matter of IAM and how roles match permissions? Is there a better way to validate that a Bucket exists without requiring any permissions?

**Comment by frankyn** [comment]
Hi @konraddysput,

Thanks for the questions. If you don't find the permissions associated to `roles/storage.admin` suitable, you could try creating a Custom IAM Role (https://cloud.google.com/iam/docs/understanding-custom-roles) and select the permissions you want such as `storage.buckets.get` which is necessary for bucket existing. 

An alternative would be creating a sentinel object in your bucket to confirm the bucket exists by verifying if the object exists. Then you would only need `roles/storage.objectViewer` role permissions.

Please let me know if this helps, or if I misunderstood. Cheers!

**Comment by konraddysput** [comment]
Thanks @frankyn for explanation!

**Comment by konraddysput** [comment]
@JustinBeckwith I closed an issue - thanks for giving me enough context, but I'm not sure why you keep reassigning me to it :(

**Comment by JustinBeckwith** [comment]
Apologies - just a robot run amok.  Feel free to ignore!  🤖
