### ISSUE TITLE
Deployment with Authentication Key Files

### ISSUE THREAD

**Issue by atmortensen** [googleapis/nodejs-storage#123]
I'm confused about how we should deploy with the way Google does authentication. With S3 I've always used a secret key that I can set as an environment variable on my server so it doesn't get pushed up to GitHub. With this library you have to use a json file to use for authentication. I'm assuming that the key file shouldn't be pushed up to GitHub so how should I get that file to my server securely?

**Comment by stephenplusplus** [comment]
The answer would depend on your deployment libraries and environment. This is probably a better question for the wider community of users of those tools on StackOverflow. If you do post, please link back here.
