### ISSUE TITLE
Update `getSignedUrl` to use non-deprecated API endpoint in Google Cloud Platform environments

### ISSUE THREAD

**Issue by kimroen** [googleapis/nodejs-storage#1231]
The `getSignedUrl` methods on `File` and `Bucket` calls to the Cloud IAM API `projects.serviceAccounts.signBlob` method when running in a Google Cloud platform environment. This API is deprecated.

If possible it would be nice if this method was updated to use the new endpoint, or alternatively provide a way to opt-in to the new endpoint to allow for gradual migration.

Thanks!

📝 [Migration guide](https://cloud.google.com/iam/docs/migrating-to-credentials-api)
📝 [Cloud IAM docs for `projects.serviceAccounts.signBlob`](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/signBlob) (note the deprecation notices)
📝 [`getSignedUrl` API reference](https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl)

> In Google Cloud Platform environments, such as Cloud Functions and App Engine, you usually don't provide a keyFilename or credentials during instantiation. In those environments, we call the signBlob API to create a signed URL.

### Environment details
  - OS: Google Cloud Platform environment
  - Node.js version: 10
  - `@google-cloud/storage` version: 5.1.1

**Comment by jkwlui** [comment]
We're already using iamcredentials API to sign in nodejs-storage:

https://github.com/googleapis/google-auth-library-nodejs/pull/908

**Comment by kimroen** [comment]
Aha, okay I think I understand. So the recommended API is what is referred to as "v4" in the code base, and the old one is "v2"? Or is that unrelated to this change?

Sounds to me like this is just a documentation issue then, because the API reference documentation for all of these methods state that they are using the old API (they link to the one I included a link to in the first post here).

Thanks!
