### ISSUE TITLE
Support other ways to pass credentials

### ISSUE THREAD

**Issue by AntonioCS** [googleapis/nodejs-storage#1232]
Hey,

It seems there is no other besides doing the following to pass credentials:

```
new Storage({keyFilename: "key.json"});
```

I am running in a google cloud function so I don't have access to files (as far as I know).
I am also using a google sheets api module and that allows me to just pass the credentials in a an object.

Would it be possible to add this? Something like
new Storage({
cred: xxx,
etc..
});

**Comment by AntonioCS** [comment]
After reading the code, I saw the `credentials` property in `GoogleAuthOptions`

**Comment by andreynocap** [comment]
Thank you @AntonioCS !! Was going down rabbit hole of using google-auth-library until I found your issue
