### ISSUE TITLE
Error while loading module: const {Storage} = require('@google-cloud/storage');

### ISSUE THREAD

**Issue by justanotheruser8** [googleapis/nodejs-storage#1237]
To be honest i am fairly new. But i can't find any bugfix for this.
I am using Node.js v13.3.0.

These are the dependencies in my package.json
```
"dependencies": {
    "@google-cloud/storage": "^5.1.1",
    "express": "^4.17.1",
    "mysql": "^2.17.1",
    "pg": "^8.2.1",
    "uuid": "^3.4.0"
  }
```

When i load @google-cloud/storage in my routes like that:

```
router.get('/justanendpoint', (req, res) => {
   
    const {Storage} = require('@google-cloud/storage') 

})
```

i get the following error when calling the endpoint:

> C:\Users\xx\xx\xx\node_modules\teeny-request\node_modules\uuid\dist\esm-browser\index.js:1
> export { default as v1 } from './v1.js';
> ^^^^^^
> 
> SyntaxError: Unexpected token 'export'
>     at wrapSafe (internal/modules/cjs/loader.js:1050:16)
>     at Module._compile (internal/modules/cjs/loader.js:1098:27)
>     at Module.load (internal/modules/cjs/loader.js:983:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:891:14)
>     at Module.require (internal/modules/cjs/loader.js:1023:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (C:\Users\xx\xx\xx\node_modules\teeny-request\build\src\index.js:21:14)
>     at Module._compile (internal/modules/cjs/loader.js:1128:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
>     at Module.load (internal/modules/cjs/loader.js:983:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:891:14)
>     at Module.require (internal/modules/cjs/loader.js:1023:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (C:\Users\xx\xx\xx\node_modules\@google-cloud\common\build\src\util.js:25:25)
>     at Module._compile (internal/modules/cjs/loader.js:1128:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
>     at Module.load (internal/modules/cjs/loader.js:983:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:891:14)
>     at Module.require (internal/modules/cjs/loader.js:1023:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (C:\Users\xx\xx\xx\node_modules\@google-cloud\common\build\src\service-object.js:23:16)

Is there anything obvious i am missing? I appreciate any help.

**Comment by jkwlui** [comment]
Looks like the culprit here is the Node.js version (reproducible in v13.3.0, not in v14.5.0). Here's a related thread: https://github.com/strongloop/loopback-next/issues/5381

It's recommended to use *even* versions of Node.js, even for non-production use: https://nodejs.org/en/about/releases/.
