### ISSUE TITLE
Support for additional request options applied to download request when bucket.upload() is called with URL

### ISSUE THREAD

**Issue by ImmaculatePine** [googleapis/nodejs-storage#124]
This is an enhancement for `bucket.upload()` function when it is called with URL as the first argument.

Here is a real-world example: I'm trying to upload file to Google Storage from Dropbox link. Unfortunately, by default it responds with preview HTML page (which is uploaded to the bucket in current implementation). Obviously, this is not what I want to be saved. Though Dropbox will redirect to the original file when `User-Agent` header is set to `curl/version`. ;)

So, I added a `request` option to the `bucket.upload()` function where you can specify any custom request options.

Example:

```javascript
const storage = new Storage()
const url = 'https://www.dropbox.com/s/link-to-my-file'
storage
  .bucket('test')
  .upload(url, {
    request: {
      headers: { 'User-Agent': 'curl/7.54.0' }
    }
  })
```

Implementation: https://github.com/ImmaculatePine/nodejs-storage/commit/8e884e7e948f57ab37d1f3decc4aa83d7632d7c0

I'd love to hear your thoughts about this patch. Is it worth to submit a Pull Request?

**Comment by stephenplusplus** [comment]
This makes sense to me. Let's call it `options.requestOptions` and mention the request module in the parameter description (if there's a link to where request's options are outlined, even better)

Thank you for the idea. Looking forward to the PR!

**Comment by ImmaculatePine** [comment]
@stephenplusplus Thanks for your feedback.

Make changes: done.
Add test for this case: done.
Submit PR: done.

Link: https://github.com/googleapis/nodejs-storage/pull/125
