### ISSUE TITLE
Need npm package for vueJs typescript.

### ISSUE THREAD

**Issue by RupeshSeth** [googleapis/nodejs-storage#1269]
Hello,
My name is Rupesh Kumar from Bangalore (India). 
I am a web developer and currently creating a web app using vueJs (typescript). I  am using google cloud storage for storing images, audio and document. 

Now all this handling using backend but now there is a new requirement. Client need the files to be upload directly from frontend without any interaction using backend. I used AWS in my previous projects and there I found the npm package for uploading files directly to aws bucket and the npm package is (aws-s3). I want just like aws-s3 npm package which will work same as aws upload files from front end without any interaction of my backend. I also emailed google support team. they suggest me to create a support request here. 

thanks

**Comment by shaffeeullah** [comment]
Hi @RupeshSeth , this feature is currently in our backlog, but not prioritized. You can find it [here](https://issuetracker.google.com/issues/170983274). In the meantime, our recommendation is for you to use the[ firestore for firebase webclient](https://firebase.google.com/docs/storage/web/start). Alternatively, you can use the [XML API ](https://cloud.google.com/storage/docs/xml-api/post-object)to make a POST request from the client side.
