### ISSUE TITLE
Provide a way to pass in an authenticated auth client

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#1284]
In the GAPIC clients, I can do something like this:

```ts
const {GoogleAuth} = require('google-auth-library');
const {CloudBuildClient} = require('@google-cloud/cloudbuild');

const auth = new GoogleAuth();
const buildy = new CloudBuildClient({ auth: auth });
```

This is nice because I can create a single auth client, and then share it across multiple services.  It drastically reduces process startup when metadata servers are involved.  However ... I can't seem to find a way to do this with our hand written libraries :(  Is there a way I don't know about to pass a pre-obtained auth client?

**Comment by stephenplusplus** [comment]
This was meant to be possible, so I'm not sure if we lost it along the way, or we accidentally left some wires unconnected. But it should be easy enough. PR coming!

**Comment by stephenplusplus** [comment]
PR sent: https://github.com/googleapis/nodejs-common/pull/623

**Comment by stephenplusplus** [comment]
This was released in [@google-cloud/common@3.4.0](https://github.com/googleapis/nodejs-common/releases/tag/v3.4.0) and is usable immediately with new @google-cloud/storage installations:

```js
const {GoogleAuth} = require('google-auth-library');
new Storage({ authClient: new GoogleAuth() });
```

**Comment by oscar60310** [comment]
Hi @stephenplusplus , it seems we need to use `ServiceOptions` instead of `GoogleAuthOptions` as the base interface of storage options to apply your [changes](https://github.com/googleapis/nodejs-common/pull/623) at nodejs-common.

https://github.com/googleapis/nodejs-storage/blob/master/src/storage.ts#L48

**Comment by stephenplusplus** [comment]
@oscar60310 thanks! I sent a PR here: https://github.com/googleapis/nodejs-storage/pull/1391, please take a look!
