### ISSUE TITLE
Their should be a function to rename file

### ISSUE THREAD

**Issue by Malikx-Alee** [googleapis/nodejs-storage#1308]
Their should be a method to rename the existing file rather than copying it with different name and the deleting the previous version. Like we have the rename functionality in the developer console.

**Comment by stephenplusplus** [comment]
I like it! Any interest in putting a PR together? No worries if not :)

**Comment by Malikx-Alee** [comment]
@stephenplusplus  Sorry, currently i am very occupied with things... so cannot create a PR.

**Comment by laljikanjareeya** [comment]
@stephenplusplus I do agree that we can rename existing file from console UI but, In backend we have two [methods](https://cloud.google.com/storage/docs/json_api/v1/objects#methods) for object [copy](https://cloud.google.com/storage/docs/json_api/v1/objects/copy) and [rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) in both the case we need to delete the existing file.
I think this needed backend implementation.
/cc
@frankyn

**Comment by frankyn** [comment]
IIUC the feature request is to provide a helper to rename objects which requires calling rewrite + delete operations. We have a similar helper in Python: https://googleapis.dev/python/storage/latest/buckets.html#google.cloud.storage.bucket.Bucket.rename_blob

**Comment by AVaksman** [comment]
I believe [file.move()](https://googleapis.dev/nodejs/storage/latest/File.html#move) helper does exactly that.

**Comment by stephenplusplus** [comment]
We could probably add a "file.rename()" alias to that. 🤷🏻‍♂️

**Comment by frankyn** [comment]
oh nice, +1 to @stephenplusplus, it would be helpful to have an alias if it's light-weight in terms of maintainability.

**Comment by ds185359** [comment]
Hi. I'm guessing this feature is at [here](https://github.com/googleapis/nodejs-storage/blob/HEAD/samples/moveFile.js). It's not working for me. Is this still active? I keep getting 404 Not found where I verified all my resources are present and I'm using correct paths and credentials. 

Also, found mistake in documentation - you are using a different variable name in comments guide [here]( https://github.com/googleapis/nodejs-storage/blob/67f2e16dc91f3544893a8e22960eb3943d8c62dd/samples/moveFile.js#L33) and different in actual code over [here](https://github.com/googleapis/nodejs-storage/blob/67f2e16dc91f3544893a8e22960eb3943d8c62dd/samples/moveFile.js#L49).
