### ISSUE TITLE
better defaults for file.save

### ISSUE THREAD

**Issue by calvinmetcalf** [googleapis/nodejs-storage#131]
`file.save` should probably default to `{resumable: false}`, as far as I know resumablility is not going to give any benefit to uploading files in single chunks but can have some performance penalties.  In a test I wrote where I had to upload 100 small text files turning resumability off speed the test up from over a minute to a couple seconds.

**Comment by stephenplusplus** [comment]
Thanks for contributing!

@alexander-fenster wdyt? For historical reference:

- https://github.com/GoogleCloudPlatform/google-cloud-node/pull/299
- https://github.com/GoogleCloudPlatform/google-cloud-node/issues/399

**Comment by calvinmetcalf** [comment]
at the very least improving the documentation to make it clear that this setting is available and should be turned off.

**Comment by stephenplusplus** [comment]
We have a blurb about it in the method description here: https://cloud.google.com/nodejs/docs/reference/storage/1.4.x/File.html#createWriteStream

But the docs are very broken in that *none* of the options to a method are documented. We have an issue about that here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783
