### ISSUE TITLE
baseurl is not quite right when using STORAGE_EMULATOR_HOST

### ISSUE THREAD

**Issue by jpambrun** [googleapis/nodejs-storage#1314]
I think this [line](https://github.com/googleapis/nodejs-storage/blob/d854c2609eb87886a010e726daa5f1339ee9ea38/src/storage.ts#L404) should read:

``` js
    const baseUrl = `${EMULATOR_HOST}/storage/v1` || `${options.apiEndpoint}/storage/v1`;
```

I guess the intend was to have configurable path, not only the host, but it breaks either bucket api or the object api.

Currently, with the default url, we get 
``` js
config = {
 apiEndpoint: 'https://storage.googleapis.com',
 baseUrl: 'https://storage.googleapis.com/storage/v1',
 //...
}
```
while with a `EMULATOR_HOST= https://exmaple.com` we get 
``` js
config = {
 apiEndpoint: 'https://exmaple.com',
 baseUrl: 'https://exmaple.com',
 //...
}
```

As a result, when EMULATOR_HOST is set with `https://exmaple.com` I can create buckets (the url starts with `/storage/v1`), but can't upload/download file (url starts with `/upload/storage/v1`). If I set EMULATOR_HOST to https://exmaple.com/v1/storage/ I have the inverse problem (can't create bucket, but can upload/download)

**Comment by stephenplusplus** [comment]
cc @jkwlui @frankyn this is the origin discussion: https://github.com/googleapis/nodejs-storage/pull/1161#discussion_r412951088

**Comment by stephenplusplus** [comment]
Thanks for reporting @jpambrun!
