### ISSUE TITLE
Cannot find module '@google-cloud/storage' or its corresponding type declarations.

### ISSUE THREAD

**Issue by nickfla1** [googleapis/nodejs-storage#1319]
#### Environment details

  - OS: macOS 10.15.14, using Docker 19.03.13, image: **node:12.19.0**
  - Node.js version: 12.19.0
  - npm version: 6.14.8 (not used)
  - yarn version: 1.22.5
  - TypeScript version: 3.9.7
  - NestJs Cli version: 7.5.1
  - NestJs version: 7.4.4
  - `@google-cloud/storage` version: 5.3.0

#### Steps to reproduce

  1. Install nest's cli `yarn global add @nestjs/cli`
  2. Create a new nestjs project `nest new test-proj`
  3. Install @google-cloud/storage with `yarn add @google-cloud/storage`
  4. `import {Storage} from '@google-cloud/storage';` in any file results in the error above.

**EDIT**: more environment details and steps

**Comment by mesqueeb** [comment]
+1

**Comment by nickfla1** [comment]
Mine was a problem with my Docker configuration. 
If you're using Docker as well, try running `yarn install` or `npm install` inside your Docker container.
