### ISSUE TITLE
file creation options

### ISSUE THREAD

**Issue by calvinmetcalf** [googleapis/nodejs-storage#132]
the documentation for the options available for when you create a file are lacking, ~~do I need to get my company to sign the CLA for me to do some documentation pull requests ?~~ I've already signed the CLA for some other project it looks like.

**Comment by stephenplusplus** [comment]
Feel free to PR away, that would be great. 👍

**Comment by calvinmetcalf** [comment]
yeah looks like this is more of an issue with the doc generation then the code itself

**Comment by stephenplusplus** [comment]
*tagging for pressure: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783*
