### ISSUE TITLE
getSignedUrl returning `SigningError: Requested entity was not found.` on attempt to create/write file

### ISSUE THREAD

**Issue by ezRAez** [googleapis/nodejs-storage#1326]
What is the requested entity that's not found? I assume the file, but I can't seem to find anything on this error in the documentation.

```
    const storage = new Storage();
    const bucket = storage.bucket(TEMP_IMAGES_BUCKET);
    const options: GetSignedUrlConfig = {
      version: 'v4',
      action: 'write',
      expires: Date.now() + 15 * 60 * 1000,
    };
    const fileName = this.getDisputeDocumentFileName(disputeId, uniqueName);
    return bucket.file(fileName).getSignedUrl(options);
```

I'm trying to create the file so the user can write to it from our FE client. Do I need to create a blank file first? I know I have access to the bucket b/c I can read files from it.

**Comment by laljikanjareeya** [comment]
@ezRAez Thanks for the Report.
In order to generate Signed URL you don't need to create blank file, but in your case it seems like bucket is not there.
you need to create bucket first.
