### ISSUE TITLE
Support some way to preload metadata when listing files (`getFiles`)

### ISSUE THREAD

**Issue by davidswinegar** [googleapis/nodejs-storage#1334]
Hi, I'd like a way to list all files in the bucket with all metadata requested together. Using the JSON api (https://cloud.google.com/storage/docs/json_api/v1/objects/list) it seems as though I could use the `projection` field to request the `metadata` field while listing all objects in the bucket. However, it seems as though there is no `projection` field in the `getFiles` request options, so I would have to use the `getMetadata` function on each `File` object. This would result in O(N) requests, where N is the number of files requested.

Instead I would like a `projection` field on the `getFiles` request options. `getMetadata` could return a promise, as it currently does, but as long as I can guarantee that all of the data is already loaded in one request.

Thanks! Please let me know if you have any questions about this!

**Comment by stephenplusplus** [comment]
Hi @davidswinegar! I believe what you're looking for comes through already. Here's a test I ran:

```js
const file = bucket.file('test');
await file.save('test', {metadata: {metadata: {testValue: true}}});
const [files] = await bucket.getFiles({maxResults: 1});
console.log(files[0].metadata);
// Output:
{
  kind: 'storage#object',
  id: 'storage-tests-bbbf5430-bbbf7b40/test/1605114176931631',
  selfLink: 'https://www.googleapis.com/storage/v1/b/storage-tests-bbbf5430-bbbf7b40/o/test',
  mediaLink: 'https://storage.googleapis.com/download/storage/v1/b/storage-tests-bbbf5430-bbbf7b40/o/test?generation=1605114176931631&alt=media',
  name: 'test',
  bucket: 'storage-tests-bbbf5430-bbbf7b40',
  generation: '1605114176931631',
  metageneration: '1',
  storageClass: 'STANDARD',
  size: '4',
  md5Hash: 'CY9rzUYh03PK3k6DJie09g==',
  crc32c: 'hqBywA==',
  etag: 'CK+O3KL8+uwCEAE=',
  timeCreated: '2020-11-11T17:02:56.931Z',
  updated: '2020-11-11T17:02:56.931Z',
  timeStorageClassUpdated: '2020-11-11T17:02:56.931Z',
  metadata: { testValue: 'true' }
}
```

So, `file.metadata` is the big object, which is the remote representation of the file, and `file.metadata.metadata` is the user-defined metadata properties.
