### ISSUE TITLE
Sequential requests when downloading file

### ISSUE THREAD

**Issue by mattzeunert** [googleapis/nodejs-storage#1338]
I'm using the `File.download` method and was wondering if its performance could be improved.

Currently it makes two requests sequentially: 

1. /storage/.../key?alt=media to download the file
2. /storage/.../key to download file metadata

Would it be possible to make those requests in parallel? The second request adds another 20 - 250ms to the download.

**Comment by stephenplusplus** [comment]
I believe this is happening because of our check for data integrity after the download is completed. With the latest metadata, we get the most recent hash of the remote object. It does indeed seem that we could make those requests in parallel, getting the metadata at the same time the download request starts. Thank you for the suggestion, I'll take a look at this soon!

**Comment by danvk** [comment]
Even better, could we make this second request optional? When you download a file, you just get the Buffer, you don't get the metadata. I'd rather not pay the cost of getting the metadata just on the off chance I might use it.

**Comment by stephenplusplus** [comment]
@danvk we do the metadata request for the sake of data integrity-- did we give you the exact file the server is storing. However, we should definitely stop making that request if you disable validation (`file.createReadStream({validation: false}`).

**Comment by danvk** [comment]
Yes, I appreciate your concern for my data integrity :) I'd just like an option to let you play fast and loose.

Here's my hack to disable this second RPC. ⚠️ Use at your own peril! ⚠️ 

```ts
/**
 * This is a hack to avoid issuing a second RPC to cloud storage for file metadata that we don't
 * use. This RPC is done in serial after the content is downloaded and is unconditional.
 * Whatever you do, don't use the file object after you patch it, other than to call
 * createReadStream or download!
 */
export function patchFileForSpeedyDownload(file: File) {
  // See https://github.com/googleapis/nodejs-storage/issues/1338
  (file.getMetadata as any) = (options: any, callback: () => void) => callback();
}
```

**Comment by danvk** [comment]
I was following through some `@google-cloud/storage` code in my debugger today and noticed that the `?alt=media` request already returns the crc/md5 hashes in response headers (`x-goog-hash`):

![image](https://user-images.githubusercontent.com/98301/107079527-fa415e80-67bd-11eb-8e48-0f1288e79f99.png)

So even when you _are_ doing validation, the second metadata request isn't needed.

**Comment by stephenplusplus** [comment]
Great find. PR sent: #1419

**Comment by danvk** [comment]
And this is now [released in 5.8.2][1]. Thanks for pushing this through @stephenplusplus, I'm very excited to delete my `patchFileForSpeedyDownload` hack :)

[1]: https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md#582-2021-03-23

**Comment by mattzeunert** [comment]
Thanks @stephenplusplus for implementing this, and thanks @danvk for pointing out the second request isn't necessary!

Just deployed this earlier and reads are now 50% faster.

![Screenshot 2021-03-25 at 09 09 01](https://user-images.githubusercontent.com/1303660/112448162-07081a80-8d4a-11eb-84fc-865a95a0e973.png)

Also seems like some metadata requests were really slow, and now the max duration is down significantly.

![Screenshot 2021-03-25 at 09 08 50](https://user-images.githubusercontent.com/1303660/112448156-053e5700-8d4a-11eb-8082-706b922a81fe.png)

**Comment by danvk** [comment]
@mattzeunert what monitoring tool is that? I'd like something similar for my site!

**Comment by mattzeunert** [comment]
@danvk  It's a Grafana dashboard running on [Hosted Metrics](https://hostedmetrics.com/). I think Grafana also has their own Cloud offering too.
