### ISSUE TITLE
There are 3 vulnerable dependencies according to nsp

### ISSUE THREAD

**Issue by THPubs** [googleapis/nodejs-storage#134]
Hi, this package has three vulnerable dependencies according to nsp. Namely, `mime`, `request` and `hawk` which come from the packages `@google-cloud/storage@1.5.2`.

**Comment by stephenplusplus** [comment]
Thanks for reporting, @THPubs. How can I check this myself to see which versions are the problematic ones? I ran `nsp check` in my local `@google-cloud/storage` directory, and it found no vulnerabilities.

**Comment by THPubs** [comment]
Hi @stephenplusplus You're correct. I also didn't find the issues when I run it on your source code. Anyway here's a screenshot of my nsp result in my app:

<img width="504" alt="screen shot 2018-02-13 at 5 45 55 am" src="https://user-images.githubusercontent.com/1212023/36127023-41a98424-1081-11e8-94ff-a115db146a8c.png">

**Comment by THPubs** [comment]
Great thanks for the quick update!
