### ISSUE TITLE
file.publicUrl() returns a Promise instead of the publicUrl

### ISSUE THREAD

**Issue by shaffeeullah** [googleapis/nodejs-storage#1344]
#### Steps to reproduce
    const bucket = storage.bucket(bucketName);
    const file = bucket.file(filename);
    const publicUrl = file.publicUrl();

**Comment by stephenplusplus** [comment]
There's actually a PR for this! https://github.com/googleapis/nodejs-storage/pull/1339

**Comment by soraxtend** [comment]
It still not working. I got undefined when I call file.publicUrl.

**Comment by shaffeeullah** [comment]
> It still not working. I got undefined when I call file.publicUrl.

@soraxtend is your file already public? It can be made public by calling `await storage.bucket(bucketName).file(filename).makePublic();`
