### ISSUE TITLE
I am getting error just after importing @google-cloud/storage : Module not found: Error can't resolve 'child_process', how to fix?

### ISSUE THREAD

**Issue by noukaza** [googleapis/nodejs-storage#1363]
**I am getting error just after importing @google-cloud/storage** 

#### Environment details

  - OS: macOS Big Sur
  - Node.js version: v12.18.4
  - npm version:6.14.6 
  - `@google-cloud/storage` version:^ 5.6.0
  - framework nuxt js version : Nuxt.js @ v2.14.7

#### Steps to reproduce

  1.  install @google-cloud/storage
`yarn add @google-cloud/storage`or `npm install @google-cloud/storage --save`
  2.  import it 
const {Storage} = require('@google-cloud/storage');
const storage = new Storage({
      keyFilename : path.join(__dirname, './file.json'),
      projectId: "xxx-xxx-xxx"
    });

just after that i got this error

`ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in '/Users/xxx/xxxx/node_modules/google-auth-library/build/src/auth'
ERROR in ./node_modules/@google-cloud/storage/build/src/file.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/@google-cloud/storage/build/src'
ERROR in ./node_modules/@google-cloud/storage/build/src/bucket.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/@google-cloud/storage/build/src'
ERROR in ./node_modules/configstore/node_modules/make-dir/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/configstore/node_modules/make-dir'
ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/google-auth-library/build/src/auth'
ERROR in ./node_modules/google-p12-pem/build/src/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/google-p12-pem/build/src'
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/graceful-fs'
ERROR in ./node_modules/gtoken/build/src/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/gtoken/build/src'
ERROR in ./node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/xxxx/node_modules/write-file-atomic'
ERROR in ./node_modules/http-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'net' in '/Users/xxx/xxxx/node_modules/http-proxy-agent/dist'
ERROR in ./node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'net' in '/Users/xxx/xxxx/node_modules/https-proxy-agent/dist'
ERROR in ./node_modules/http-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'tls' in '/Users/xxx/xxxx/node_modules/http-proxy-agent/dist'
ERROR in ./node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'tls' in '/Users/xxx/xxxx/node_modules/https-proxy-agent/dist'`
Thanks!

**Comment by Segrelove** [comment]
I'm having the same problem

**Comment by shaffeeullah** [comment]
Hi @noukaza and @Segrelove , 

I am struggling to reproduce this issue. How are you running this code? Also, can you paste your entire code snippet (including how you define `path`)?

**Comment by noukaza** [comment]
hi @shaffeeullah 

firstly you need to create a nuxt js project

`npx create-nuxt-app my-app`

```
✨  Generating Nuxt.js project in my-app
Project name: my-app
Programming language: JavaScript
Package manager: Yarn
UI framework: None
Testing framework: None
**Rendering mode: Universal (SSR / SSG)**
**Deployment target: Server (Node.js hosting)**
```

make sure to select **Rendering mode: Universal (SSR / SSG)** and **Deployment target: Server (Node.js hosting)**

if you start the project by typing `yarn dev ` everything will compile perfectly 
now if you install google-cloud/storage
```
yarn add @google-cloud/storage
```

and import it anywhere in the project

for example in` pages/index.vue `

```
<script>
const {Storage} = require('@google-cloud/storage');
// or import {Storage} from '@google-cloud/storage';
export default {}
</script>

```

**Comment by eagleeye** [comment]
The library is named 'nodejs-storage'. There is no chance, that you will make it work in the browser. child-process is the core node.js module. https://nodejs.org/api/child_process.html

**Comment by noukaza** [comment]
@eagleeye i already know that and that's why i'm using nuxtjs with SSR mode

**Comment by alexander-fenster** [comment]
This sounds like a fun thing with Nuxt that wants to use Webpack bundle even when running on the server side.  I found https://github.com/nuxt-community/dotenv-module/issues/11 which suggested that we could blocklist some Node modules for webpack, and they will magically start working on the Node side of the things. Try this in your `nuxt.config.js`:

```
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    extend (config, ctx) {
        config.node = {
            fs: "empty",
            child_process: "empty",
            net: "empty",
            tls: "empty"
        };
    }
  }
```

My `pages/index.vue` that worked:

```
<script>
const storage = require('@google-cloud/storage');
console.log(storage);
// exports and other stuff here
</script>
```

**Note:** we have never tested this library with Nuxt. Consider this to be a "warranty void if seal broken" situation - let us know if anything does not work but fixing stuff might be complicated.

**Comment by shaffeeullah** [comment]
Thanks @alexander-fenster for the solution! @noukaza please re-open this or leave a comment if this is still an issue.

**Comment by josiext** [comment]
oh so you can only use cloud storage in the backend. Nice to know.
