### ISSUE TITLE
Type definitions are missing a lot of the documentation that exist in the JS files

### ISSUE THREAD

**Issue by JamesYeoman** [googleapis/nodejs-storage#1384]
This has lead to me digging through `bucket.js` just to figure out if the pathString parameter is for specifying the local file or the cloud storage file.
#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 12.8.1
  - npm version: 6.10.2
  - `@google-cloud/storage` version: 5.7.2

#### Steps to reproduce

  1. View the upload function in `bucket.js` at line 2967
  2. View the upload function's type definition in `bucket.d.ts` at line 565

The upload function is just one example of documentation that isn't available in the type definitions. There will be cases where the documentation isn't as useful, but in this particular instance, I _needed_ the documentation to make sure I was passing the correct data to the function.

Maybe it's worth having a script that can identify functions and their corresponding locations in the type definitions (possibly by using a marker in a comment) and can copy the documentation from the functions into the type definition files. As it stands, there's no way to view that documentation without diving into the npm package and browsing the source code (can get time-consuming very quickly)

**Comment by stephenplusplus** [comment]
Thank you for taking the time to report this issue. I believe we are working towards merging these to overcome our current documentation strategy that requires duplication.

@bcoe do you know if this is currently being worked on?

**Comment by JamesYeoman** [comment]
It's been nearly 2 weeks without any activity. Is there any update on documentation plan?

**Comment by JustinBeckwith** [comment]
@JamesYeoman this is something we're actively working on, but we don't have a timetable for when it will be resolved.

**Comment by shaffeeullah** [comment]
@JamesYeoman does this page have the information you were looking for? https://googleapis.dev/nodejs/storage/latest/Bucket.html#upload

**Comment by shaffeeullah** [comment]
I believe the page linked above has the information requested by this issue. Please reopen if this is not the case.
