### ISSUE TITLE
Allow setting metadata when copying

### ISSUE THREAD

**Issue by leon** [googleapis/nodejs-storage#1398]
We store some metadata on images regarding which post a certain image belongs to.
We have some cloud functions that listen to new files being added and depending on the metadata we do some actions.

We now want to be able to copy a file to a new location.
But because our triggers fire of as soon as we use the copy command we would like to be able to specify what should happen with the metadata.

https://googleapis.dev/nodejs/storage/latest/File.html#copy
https://googleapis.dev/nodejs/storage/latest/global.html#CopyOptions

Either we should be able to say, skip copying the metadata.
```
const file = bucket.file('my-image.png');
file.copy('my-image-copy.png', {
  metadata: null
}
```
Or we should be able to set the metadata from the copy method.

```
const file = bucket.file('my-image.png');
file.copy('my-image-copy.png', {
  metadata: {
    thisIsACopy: true
  }
}
```

## What we have tried

- downloading the file and uploading again. (takes to long, and means extra costs)
- removing the metadata on the source before copying (not ideal because then we need to put the metadata back again)

Would this be possible?

**Comment by stephenplusplus** [comment]
Hi @leon, thanks for reporting. I've sent [a PR](#1406) that has an example of how to overwrite metadata. Apparently, nulling out the metadata during a copy, isn't possible.

**Comment by leon** [comment]
Thats great that it is possible.

What would happen if we send in an empty object?
would that mean that we can "null" out the metadata.

```
await originalFile.copy('new-file-name', {metadata: {}})
```

**Comment by stephenplusplus** [comment]
No, I tried that as well :\ The docs for the API method ([/rewriteTo](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite)) mention in the first line how you can optionally override the metadata. It doesn't seem to be warm to the idea of removing it, however.

@frankyn is it possible a rewrite operation can allow nullifying the origin file's `metadata` object from the destination file?

**Comment by frankyn** [comment]
Good question for @tritone who is on duty right now

**Comment by leon** [comment]
@tritone Any news on this?

**Comment by stephenplusplus** [comment]
I think we should be able to merge #1406 while we wait for an answer. I just need someone to approve the PR, so I can merge :)

**Comment by tritone** [comment]
Apologies for the belated response-- to clear custom metadata in a patch request, I believe you need to null out keys individually rather than sending an empty object.

```
// to delete "foo" send:
{
  "foo": null
}
```
So to clear all custom metadata, you'd need to do this for all keys you currently have in there.

**Comment by shaffeeullah** [comment]
To add to what @tritone mentioned, nulling out the metadata in the way described will retain the keys on the file, just with value null. Removing the keys entirely is not supported at this time.

**Comment by leon** [comment]
Thanks for this!
Now we can null out the metadata, which is a start :)
