### ISSUE TITLE
Google Cloud Vision API returns "Bad image data" when images is uploaded in Node

### ISSUE THREAD

**Issue by Uvindu96** [googleapis/nodejs-storage#1399]
Hi all,

I was trying to implement an image application using google cloud vision API. The initial step in the application allows users to upload images to the application. When I use the command "gsutil" Vision API works fine without any issues. To make the process easier for the users I have created a  node.js server to upload the images to the application, But when I upload my images through the node.js server it gives me the following error. (Note: application is deployed in Kubernetes cluster)

![Screenshot from 2021-02-06 13-40-00](https://user-images.githubusercontent.com/31029812/107113093-ab113180-6882-11eb-85f6-a505d187e26c.png)

This error occurs when I upload the images through the node.js server, If I use the gsutil command it works fine.!

This the Nodejs server that I have created 
Link to code:= https://github.com/Uvindu96/apollo-server-react-file-upload/blob/master/server/src/index.js

```
const nodejsBucket = gc.bucket('stone-semiotics-297911-images-input');

const resolvers = {
  Query: {
    files: () => files
  },
  Mutation: {
    uploadFile: async (_, { file }) => {
      const { createReadStream, filename } = await file;

      await new Promise(res =>
        createReadStream()
          .pipe(
            nodejsBucket.file(filename).createWriteStream({
              resumable: false,
              gzip: true
            })
          )
          .on("finish", res)
      );

      files.push(filename);

      return true;
    }
  }
};
```

#### Environment details

  - OS: Ubuntu 20.04
  - .NET version: mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
  - Package name and version: Google.Cloud.Vision.V1

I really appreciate your help, Thanks!

**Comment by Uvindu96** [comment]
@jskeet Thanks for the guidelines, I have updated the git issue. I checked the uploaded image by downloading it again, there was no issue with the image file it was fine.

**Comment by jskeet** [comment]
Okay, that's interesting that after downloading it the image was okay.

I'd suggest comparing the metadata for an image uploaded via gsutil and one uploaded via your node code, both from the same original file. Check that they have the same Content-Encoding, for example. You can check some of this in the Storage console - or you could use the API to get more details, including the hash of the data. Fundamentally the next step should be to work out the difference between uploading via gsutil and uploading via your Node code.

**Comment by Uvindu96** [comment]
@jskeet I was able to find out what causing this error, Its encoding that set from node server (gzip: true) when the value is true it set the gzip type encoding, after I set the value to false it worked fine. Thank you for all the support you gave me, appreciate it !

**Comment by jskeet** [comment]
Very glad it worked out :)
