### ISSUE TITLE
Can File#download include some HTTP-based metadata in the callback?

### ISSUE THREAD

**Issue by CapnSpellcheck** [googleapis/nodejs-storage#140]
When using File#download perhaps I would like to access some of the HTTP header-based metadata for this object, specifically Content Type. Since presumably this data was encountered in the response headers when File#download does the request, is it possible to expose this metadata in the callback?

**Comment by stephenplusplus** [comment]
You can actually check `file.metadata` for an updated representation of the remote object.

```js
file.download(function(err, contents) {
  if (!err) {
    console.log(file.metadata) // updated!
  }
})
```

**Comment by CapnSpellcheck** [comment]
sweet
