### ISSUE TITLE
Unable createNotification from client

### ISSUE THREAD

**Issue by yusef-ho** [googleapis/nodejs-storage#1402]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello, I'm trying to create notification from bucket in storage client
```ts
bucket.createNotification('topic_name')
```
but it always give me error
```
"code": 400,
  "errors": [
    {
      "message": "Cloud Pub/Sub topic '//pubsub.googleapis.com/projects/{{project_id}}/topics/{{topic_name}}' not found, or user 'service-{{number}}@gs-project-accounts.iam.gserviceaccount.com' does not have permission to it.'",
      "domain": "global",
      "reason": "invalid"
    }
  ],
```
How can i programmatically create notification for bucket by the service account create myself with enough permission?

thanks

**Comment by tritone** [comment]
It looks like you're calling the `createNotification` method correctly. Does your client work to authenticate for other kinds of requests? I would look at the docs here and make sure you have all the prerequisites met: https://cloud.google.com/storage/docs/reporting-changes#prereqs

**Comment by tritone** [comment]
Closing this, feel free to re-open if you have further questions that are specific to the client library.
