### ISSUE TITLE
How to upload data directly without a file?

### ISSUE THREAD

**Issue by damagicalcat** [googleapis/nodejs-storage#1430]
I want to upload data directly, with something like bucker.upload({"data":"data"}, {destination: "data.json"}), however currently I can only upload data from a file bucket.upload("/path/data.txt", {destination: "data.txt"})

I want to be able to upload directly, without having to use fs to create a file, upload it, and then delete it.

**Comment by stephenplusplus** [comment]
Hey @damagicalcat. [`file.save()`](https://googleapis.dev/nodejs/storage/latest/File.html#save) will work for this. As an example:

```js
const file = bucket.file('data.txt')
await file.save('new contents provided as string or buffer')
```

**Comment by romanlv** [comment]
Related: how to create a subfolder for such file, `file.save` fails with directory does not exist, returns ` Error: No such object....`

**Comment by stephenplusplus** [comment]
@romanlv could you please open a new issue with reproduction steps?

**Comment by romanlv** [comment]
> @romanlv could you please open a new issue with reproduction steps?

there was a problem somewhere else in my code, `file.save` creates subfolder as expected
