### ISSUE TITLE
Rename storage objects returns 404 Not Found

### ISSUE THREAD

**Issue by ds185359** [googleapis/nodejs-storage#1462]
Hi. This feature over [here](https://github.com/googleapis/nodejs-storage/blob/HEAD/samples/moveFile.js) for renaming GCS Objects is not working for me. Is this still active? I keep getting 404 Not found whereas I verified all my resources are present and I'm using correct paths and credentials. 

Also, found mistake in documentation - you are using a different variable name in comments guide [here]( https://github.com/googleapis/nodejs-storage/blob/67f2e16dc91f3544893a8e22960eb3943d8c62dd/samples/moveFile.js#L33) and different in actual code over [here](https://github.com/googleapis/nodejs-storage/blob/67f2e16dc91f3544893a8e22960eb3943d8c62dd/samples/moveFile.js#L49).

#### Environment details

  - Node.js version: v14
  - npm version: v6
  - `@google-cloud/storage` version: ^5.8.5

#### Steps to reproduce

  1. I used this template - [here](https://github.com/googleapis/nodejs-storage/blob/HEAD/samples/moveFile.js). I'm trying to rename an existing file in same bucket.

Thanks!

**Comment by cojenco** [comment]
Hi @ds185359, thanks for filing the issue and catching the typo in the code sample. We will fix the typo with a PR shortly. The renaming feature as in the [sample](https://github.com/googleapis/nodejs-storage/blob/HEAD/samples/moveFile.js) is still active. Could you share in the comments the code you are trying to run? Are you running into errors with other HTTP requests or only with move() in attempt to rename an object?

**Comment by ds185359** [comment]
@cojenco Sure. Adding details below. I'm trying to use the `move()` to rename a file. But I also tried using `copy()` and I get same error `404 Not Found`. 

Problem statement and code snippet: 

I'm trying to rename files in Cloud storage with a script that calls google api `move()`. This is sample template I wrote for initial test:

```
async function rename(){
    //GCS Data Source
    const bucketName = 'bucket-name';

// Import the Google Cloud client libraries
    const {Storage} = require('@google-cloud/storage');

// Instantiate BigQuery and Storage clients
    let projectId = require("../../credentials-file.json").project_id;
    const storage = new Storage({
        keyFilename: "../../credentials-file.json",
        projectId: projectId
    });

    let destFileName = `test.txt`;  //also tested with filename as just `test`
    await storage.bucket(bucketName).file('some-file').move(destFileName);
}

rename().catch(e => console.log(e));

```

Thank you for quick response.

**Comment by stephenplusplus** [comment]
The code worked for my test. I used a file named "testfile" that previously existed in the bucket. After running the code, the file was successfully renamed "testfile2":

```js
'use strict'

async function rename() {
  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage();
  await storage.bucket('my-bucket-name').file('testfile').move('testfile2');
}

rename().catch(e => console.log(e));
```

**Comment by ds185359** [comment]
Do you think this can be an issue with permissions? I'm using service account with Storage Admin permissions to create, update, delete storage objects, buckets etc.

**Comment by ds185359** [comment]
Yes it generated from same project I'm trying to access the bucket from.

**Comment by stephenplusplus** [comment]
`parent-bucket/child-bucket` is suspicious. GCS doesn't have bucket hierarchies like that, as far as I know. It should just be `/b/source-bucket/o/original-file-name/rewriteTo/b/source-bucket/o/new-file-name`

**Comment by stephenplusplus** [comment]
Could you paste the code you're using, including more realistic strings that match your actual paths provided to `storage.bucket()` and `file()` and `move()`? Feel free to jumble up the actual resource names, but keep in place the folder/file separators.

**Comment by stephenplusplus** [comment]
I tried with a directory structure, and this way worked:

```js
await storage.bucket('bucket-name').file('dir/testfile').move('dir/testfile2');
```

**Comment by ds185359** [comment]
Sure. Following is the code I'm using:

```

//Import all files
async function rename(){
    //GCS Data Source
    const bucketName = 'bucket-name/folder-name';   //folder-name is in format `TEST.FOLDER`

// Import the Google Cloud client libraries
    const {Storage} = require('@google-cloud/storage');

// Instantiate BigQuery and Storage clients
    let projectId = require("../../credential-file.json").project_id;
    const storage = new Storage({
        keyFilename: "../../credential-file.json",
        projectId: projectId
    });

    let destFileName = `test-2`;
    await storage.bucket(bucketName).file('test-env-data-000000000000').move(destFileName);
}

rename().catch(e => console.log(e));
```

**Comment by ds185359** [comment]
@stephenplusplus Yes what you suggested works for me. Using filename as `folder/file` but that renames and stores my file `some-bucket` instead of renaming and storing it `some-bucket/some-folder`.

**Comment by stephenplusplus** [comment]
Thank you for taking the time to do that. The issue is how `bucketName` is defined. To get the folder name, pass that into the `file()` and `move()` methods. Could you try it with these changes?

```diff
//Import all files
async function rename(){
    //GCS Data Source
-   const bucketName = 'bucket-name/folder-name';   //folder-name is in format `TEST.FOLDER`
+   const bucketName = 'bucket-name';   //folder-name is in format `TEST.FOLDER`

// Import the Google Cloud client libraries
    const {Storage} = require('@google-cloud/storage');

// Instantiate BigQuery and Storage clients
    let projectId = require("../../credential-file.json").project_id;
    const storage = new Storage({
        keyFilename: "../../credential-file.json",
        projectId: projectId
    });

-   let destFileName = `test-2`;
+   let destFileName = `folder-name/test-2`;
-    await storage.bucket(bucketName).file('test-env-data-000000000000').move(destFileName);
+    await storage.bucket(bucketName).file('folder-name/test-env-data-000000000000').move(destFileName);
}

rename().catch(e => console.log(e));
```

**Comment by stephenplusplus** [comment]
Woo! Glad we got it figured out. Sorry for the confusion!
