### ISSUE TITLE
failed to get default service account when using GAE (google app engine) 

### ISSUE THREAD

**Issue by levischechter** [googleapis/nodejs-storage#1465]
#### Environment details

  - OS: flexible version of app-engine using "launcher.gcr.io/google/nodejs" as base image in the Dockerfile 
  - Node.js version: 8.17
  - npm version: 6.13.4
  - `@google-cloud/storage` version: ^4.7.0

#### Steps to reproduce

  1. ? get an app-engine environment
  2. ? connect to google storage: 
      `const { Storage } = require('@google-cloud/storage');`
      `const storage = new Storage();`
  3. try to create a bucket: 
        `const [bucket] = await storage.createBucket("test", {`
            `location: "US",`
            `storageClass: "ARCHIVE"`
        `});`
  4. getting the error "The file at ./auth.json does not exist, or it is not a file."
  5. as I understand from reading the module: the npm trying only to look for GCE (google compute engine) service account and not for GAE. instead it's trying to look for a file (that in my case not exists).
  6. **workaround to solve it: create service account and use it instead of the GAE default service account.**

**Comment by cojenco** [comment]
Hi @levischechter, thanks for filing the issue. 

I followed the steps you outlined and was able to create a bucket via the App Engine default service account. By default, the app's environment contains credentials from the default App Engine service account and [calls from your App Engine app to services in the same project are authorized](https://cloud.google.com/appengine/docs/standard/python/access-control#apps). Could you help check if your App Engine default service account has the Editor role in the project, as shown [here](https://cloud.google.com/appengine/docs/standard/python/service-account)? 

Looking at the error message, is it possible that you have anything cached? Also, are you getting the same error if you use current versions libraries?

**Comment by cojenco** [comment]
Hi @levischechter, please reopen if this is still an issue.
