### ISSUE TITLE
How can i download .webm file(google storage file with url) and process without fs on google function on node.js

### ISSUE THREAD

**Issue by okeoke85** [googleapis/nodejs-storage#1468]
It is a question actually, I want to download a video with .webm format from google services and get frames on the fly from it, my application is a google function so i cant use fs, my videos on google storage  thanks in advance.

sample video url ;

https://firebasestorage.googleapis.com/v0/b/zetform-63ea7.appspot.com/o/organizations%2FuQbMQXCc2tOqjcG4NpEz%2Fmonitorings%2FRvNxY92jwm7FmqjjBSIA%2Ftestinstances%2FHSWGxyg1Tg8IMpCOoWk3%2Fvideos%2F2_2021-05-11%2014%3A51%3A52.webm?alt=media&token=c87ddb9c-f388-4ae7-a988-308dabec66b0

```
let videoUrl = "https://a"

let outputUmages : image[] = getVideoImagesBySeconds(1.sec, 10.sec, 20.sec)
```

i couldnt prepare getVideoImagesBySeconds functions is it possible?

**Comment by cojenco** [comment]
Hi @okeoke85! To download files from Cloud Storage for Firebase, please see [here](https://firebase.google.com/docs/storage/web/download-files).

**Comment by cojenco** [comment]
Feel free to reopen if you have more questions.
