### ISSUE TITLE
Possible to use with Firebase Storage Emulator?

### ISSUE THREAD

**Issue by steinroe** [googleapis/nodejs-storage#1473]
Hi,

is it possible to use this client lib with firebase storage emulator, which [was released last week](https://firebase.google.com/docs/emulator-suite/connect_storage)?

Thanks!

**Comment by BenWhitehead** [comment]
Hi @steinroe,

We do not currently have the Firebase Emulator integrated with the test suite of this library, however this library is used as part of the Firebase Admin Storage tools.

@abeisgoat Do you know if this is possible to try out?

**Comment by steinroe** [comment]
Yes, and I assumed that firebase uses this library as the core for their storage communication. It would be great to enable non-firebase storage customers to use the emulator, too. Thanks for checking! 👍

**Comment by jonstout** [comment]
I tried to get this working today via `firebase.storage()`; It did not go well for me. I got the emulator running and ended up setting both
```
STORAGE_EMULATOR_HOST=http://localhost:9199
FIRESTORE_STORAGE_EMULATOR_HOST=localhost:9199
```
to get the API looking away from the cloud instance, but I never could get any queries to work. I'd appreciate if someone could take a closer look.

**Comment by abeisgoat** [comment]
The Cloud Storage for Firebase emulator only supports a very small subset of the Cloud API and it is intended to only be used via the `firebase-admin` package, so really the answer is officially *no*. You may be able to connect directly and some things may work, but it's not an intended flow. It's a Firebase emulator intended for Cloud Storage for Firebase :)

**Comment by steinroe** [comment]
Thanks for clarifying! We can close the issue then. :)

**Comment by vajahath** [comment]
@jonstout
> I tried to get this working today via firebase.storage(); It did not go well for me.

Reason: https://github.com/firebase/firebase-tools/issues/3447
