### ISSUE TITLE
Object prototype may only be an Object or null: undefined at Function.setPrototypeOf appeared between 5.8.2 and 5.8.5

### ISSUE THREAD

**Issue by cnpatric** [googleapis/nodejs-storage#1492]
1) Is this a client library issue or a product issue?
This is the client library.

2) Did someone already solve this?
I was not able to find any other tickets regarding this error

#### Environment details

  - OS: macOS 11.3
  - Node.js version: 12.22.1
  - yarn version: 1.22.10
  - `@google-cloud/storage` version: 5.8.5

#### Steps to reproduce

  1. Update from 5.8.2 to 5.8.5 

Throws 

```
TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

      at node_modules/graceful-fs/polyfills.js:139:39
      at patch (node_modules/graceful-fs/polyfills.js:141:5)
      at patch (node_modules/graceful-fs/graceful-fs.js:104:3)
      at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:96:18)
      at Object.<anonymous> (node_modules/configstore/index.js:4:12)
```

**Comment by danielduhh** [comment]
Hi @cnpatric, thanks for submitting this issue. Do you mind providing details on when exactly this error occurs? It it during `npm install`?

**Comment by danielduhh** [comment]
Also.. what version of typescript are you using?

**Comment by cnpatric** [comment]
this happens when we run our tests when we try to test our storage implementations so with yarn test which runs `"test": "node_modules/.bin/jest --config jest.config.unit.js",` . I can't tell when exactly this appears though it looks like it crashes immediately since no tests in this file are run.

we use typescript 4.3.4

**Comment by danielduhh** [comment]
Interesting! This will be hard to reproduce unless I have access to your test files. Can you make sure you environment doesn't have any circular dependencies? [These are the changes to package.json](https://github.com/googleapis/nodejs-storage/compare/v5.8.2...v5.8.5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) between the two versions you mentioned.

**Comment by cnpatric** [comment]
Looks like we actually have circular dependencies that use firestore.

I'll fix them and report back if that solved the issue, thanks for your help so far!

**Comment by danielduhh** [comment]
No prob @cnpatric. I'll hold off on closing the ticket until I hear back.

**Comment by danielduhh** [comment]
Closing this out. Please re-open if issue persists. Thanks @cnpatric!

**Comment by cnpatric** [comment]
@danielduhh Sorry just had time for that now, we removed the circular dependency and don't have any other according to madge. So this doesn't seem to be a circular dependency issue.
