### ISSUE TITLE
Mention necessary rights/role

### ISSUE THREAD

**Issue by nikita-fuchs** [googleapis/nodejs-storage#1499]
If I havn't missed it, the documentation currently says nothing about necessary roles/rights, so one unavoidably runs into errors. Various places tell you it's necessary to add the role `iam.serviceAccountTokenCreator` to use URL signing, wouldn't it be worth mentioning it in the docs right away ?

Thanks and have an awesome day !

**Comment by ddelgrosso1** [comment]
Hi @nikita-fuchs,

Would you be able to point out where in the documentation you feel would benefit from the additional clarification (or where you feel is currently vague)? Thank you.

**Comment by nikita-fuchs** [comment]
_Personally_, as a developer, I would love to see it directly in the code example because that's generally what I jump to directly, skipping all other important information in the description before it 😁
_Generally_, as a quick solution, I would suggest putting that information in one of the "Important" or "Note" remarks. But inflationary usage of those also gets contraproductive.

A _good_ solution would be to have information on role requirements in the docs of **every** gcloud service - maybe as some accordeon UI element sticking at the top, called "Show/Hide Permission Requirements"

A _smart_ solution I would expect of _google_ would be a direct way to check for / grant necessary roles directly from the docs, maybe as a link inside the bespoke UI element (dropdown accordion bar). As the docs and the gcloud console are separated from each other it won't be possible to have a dropdown with available (service)accounts to check and set the roles, but I recall seing links for something related to OAuth, where you were pointed to a page for setting permissions with the permissions required already set by parameters in the link, and you had just had to accept the setting.

As of right now, the routine is always: Study the API, write code, debug it, get permission errors, head over to stackexchange et al and find the right IAM properties to set, wait minutes for them to be applied, retry and hope you did it all right.

Thanks for your consideration !

**Comment by ddelgrosso1** [comment]
Hi @nikita-fuchs,

I wanted to let you know that we are having discussions internally about how to best document this moving forward. In the meantime I wanted to link some [documentation](https://cloud.google.com/storage/docs/access-control/iam-reference) that might be helpful. I will circle back on this issue when I have more details or a solution. Thanks!

**Comment by shaffeeullah** [comment]
Most of our docs pages have a `prerequisites` section before the samples which explain permissions needed to perform the operations. Example here: https://cloud.google.com/storage/docs/listing-buckets#prereq-code-samples

Closing this out.
