### ISSUE TITLE
File is still available using the old URL after a copy()/move()

### ISSUE THREAD

**Issue by pkyeck** [googleapis/nodejs-storage#152]
Hi, this is more a question than a bug, but I was hoping someone around here can shed some light on this.

When I `file.move()` to basically make the file not publicly accessible (at least not under the same URL) anymore, the moved file is cached and can be accessed for quite some time. Even doing a `file.makePrivate()` before moving the file doesn't change that. What is the exact time-delay and is there a way around this? Thanks.

**Comment by stephenplusplus** [comment]
I put together a simple test, and I'm seeing that the expected results:

```js
var file = bucket.file('file-original');
var fileMoved = bucket.file('file-moved');

file.save('Test', function(err) {
  if (err) throw err

  file.move(fileMoved, function(err) {
    if (err) throw err

    file.exists(function(err, exists) {
      if (err) throw err

      console.log('Old file exists?', exists)

      fileMoved.exists(function(err, exists) {
        if (err) throw err

        console.log('New file exists?', exists)
      });
    });
  });
});
```
```
exists? false
exists? true
```

How long have you tried waiting before seeing that the old file was removed?

**Comment by pkyeck** [comment]
I waited up to 30min. But the file could still be viewed inside the browser using the old URL. That was on Friday before I left for the weekend. Today (Monday) I can't access them anymore. So I don't exactly know how long they were available after deletion.

I haven't tried `fileMoved.exists()` but checked the bucket and the file was actually deleted. I guess it's more a "GCS cache thing" than an API/lib thing. Do I have to purge any caches or set any options while saving/copying for those files to be gone "immediately"?

**Comment by stephenplusplus** [comment]
Interesting. I'm not sure, but check out the resources listed on the [Support page](https://cloud.google.com/storage/docs/support). StackOverflow might help; I've seen GCS team members answer questions there before. If you do make a post and/or find an answer, please link back! Sorry that I couldn't be more help.
