### ISSUE TITLE
Document how to use a CredentialAccessBoundary/DownscopedToken

### ISSUE THREAD

**Issue by apjoseph** [googleapis/nodejs-storage#1522]
There is currently no documentation or example anywhere obvious that describes how you are supposed to use a `CredentialAccessBoundary` or `DownscopedClient `with `Storage` either in this library or in `google-auth-library`. It would be very helpful to have this information for issuing onetime tokens for accessing specific resources within a bucket. 

This seems like a relatively common need for projects that deal with file uploads/downloads and so would be worth explicitly documenting since it's not remotely close to obvious.

**Comment by ddelgrosso1** [comment]
Hi @apjoseph ,

Thank you for reporting this issue. There is still some development work ongoing for `DownscopedClient`. Part of that work will include documentation and samples. I will update this issue when the documentation becomes available.
