### ISSUE TITLE
Should I use this library or v9?

### ISSUE THREAD

**Issue by Cosbgn** [googleapis/nodejs-storage#1528]
I have a node app which runs on aws lambda, so a smaller package is beneficial for me because it means directly a faster cold start.

I'm a bit confused about the new v9 https://firebase.google.com/docs/web/modular-upgrade - Is this only for the web? I did try to use it on node with aws lambda and it seems to work fine, will this library eventually be depriciated in favour of v9?

I just would like to know if it make sense to use V9 or if that's something completely different aimed for the web only and not node.

**Comment by ddelgrosso1** [comment]
Hi @Cosbgn,

It sounds like your question is more suited for the Firebase team to answer. That repo can be found [here](https://github.com/firebase/firebase-js-sdk). You can file an issue there. I am going to close this as a result. If I have misunderstood the question please feel free to reopen. Thank you!
