### ISSUE TITLE
signedUrl interface is wrong, functionality is incomplete

### ISSUE THREAD

**Issue by flockonus** [googleapis/nodejs-storage#1571]
#### Environment details

  - OS: mac
  - Node.js version: 14.16
  - npm version: 14.16
  - `@google-cloud/storage` version: 5.14.0

#### Steps to reproduce

signedUrl interface is incoherent with the examples / tests
https://github.com/googleapis/nodejs-storage/blob/653f4b488e8603e4008e51b45920fb7de7138eab/src/bucket.ts#L258
but it should also add remove, write, ... as per https://github.com/googleapis/nodejs-storage/blob/939856680d279dcd9587328d0cc58f789b022f5a/system-test/storage.ts#L3610

Also i need a request to be able to create a `getSignedUrl` + set to file to 'public' + set cache in the metadata, there is no example of how to do either.

Thanks!

**Comment by ddelgrosso1** [comment]
Hi @flockonus,

Thank you for raising this issue. Could you provide a bit more information about the first part of the issue. You mention that the example(s) are incoherent or incomplete but you are pointing at 2 different classes (bucket in the first link and file in the second). What do you feel is missing or incomplete?

**Comment by flockonus** [comment]
@ddelgrosso1 sure, and thanks for following up so quickly.

Right now App Engine has this limitation of requests need to be <32Mb, which leaves us to try and use `getSignedUrl` for all use cases like `upload` would be used.
In my case I need to setup the file for public access, but there is no docs on that, and even more generally there is no documentation on the headers that could be setup, and the typescript signature seems incomplete

**Comment by ddelgrosso1** [comment]
Hi @flockonus,

From what I understand you would like to:

1. Upload an object >= 32Mb
2. Make the object from the first step public
3. Set cacheControl in the metadata of the object

If so you could accomplish this by doing the following:

1. [file.save](https://googleapis.dev/nodejs/storage/latest/File.html#save) or [bucket.upload](https://googleapis.dev/nodejs/storage/latest/Bucket.html#upload). My understanding of the 32Mb limit is that it is on incoming requests to your application / app engine. 
2. [file.makePublic()](https://googleapis.dev/nodejs/storage/latest/File.html#makePublic)
3. Invoke [file.setMetadata()](https://cloud.google.com/storage/docs/samples/storage-set-metadata#storage_set_metadata-nodejs) with the appropriate `cacheControl` option.

Please let me know if I have misunderstood what you are trying to accomplish. Thanks!

**Comment by flockonus** [comment]
Hey @ddelgrosso1 i'm using App Engine and indeed i need to upload a file > 32Mb.

The setup I have is similar to what you mentioned, except they don't mention the 32Mb limit, which made my upload system useless over there. It works fine under 32Mb.

Btw you can also make steps 1 + 2 + 3 in one go, even tho documentation for that is not the most clear.

**Comment by ddelgrosso1** [comment]
Hi @flockonus,

A similar issue was brought up previously [here](https://github.com/googleapis/nodejs-storage/issues/1392). It offers a few ways to be able to upload items >= 32MB. Can you see if any of those suggestions will help you? Thank you.

**Comment by flockonus** [comment]
Thanks @ddelgrosso1 , I'm also looking into HTTP/2 on cloud run - which has no request limit it seems, and I can run the same Node.js code.
From the issue you linked, the example for `getSignedUrl` is may be useful as well for others attempting this. Feel free to make what you wish of this task since on my account i'm not pursuing this anymore.

**Comment by ddelgrosso1** [comment]
Thanks @flockonus going to close this issue out. Feel free to reopen if something else comes up.

**Comment by shaffeeullah** [comment]
For more information on bypassing the Cloud Run HTTP/1 32mb limit, please see this blog post: https://medium.com/google-cloud/bypass-the-cloud-run-32mb-limit-with-cloud-storage-65c24156189
