### ISSUE TITLE
Bucket.upload not returning api response.

### ISSUE THREAD

**Issue by scragg0x** [googleapis/nodejs-storage#159]
#### Environment details

  - OS: Linux
  - Node.js version: 8
  - `@google-cloud/storage` version: 1.6

#### Steps to reproduce

```javascript
const response = await bucket.upload('/tmp/myfile', { destination: '/some/path' });
```
response[0] is the file object
response[1] isn't defined, I was expecting an apiResponse object

Looks like it should return:
https://github.com/googleapis/nodejs-storage/blob/master/src/bucket.js#L2028
 https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/Bucket#upload

**Comment by stephenplusplus** [comment]
Thanks for pointing this out. It looks like we are falsely stating we'll return an API response argument, when we certainly don't. We should return the metadata as the `apiResponse` argument.

For a workaround in the meantime, you can read the returned File object's `metadata` property, which will be the same thing.

**Comment by scragg0x** [comment]
Thanks for the workaround!

**Comment by akashgangrade** [comment]
I am not getting any response and image is also not getting uploaded to bucket.
```
bucket.upload(localFilePath, {
            destination: 'images1/',
            uploadType: "media",
            metadata: {
              contentType: 'image/jpg',
            }
          })
          .then((data) => {
            console.log("Asdasdasdasdas");
              const file4 = data[0];})
```
