### ISSUE TITLE
Latest release is causing uploads to fail with "GaxiosError: Required"

### ISSUE THREAD

**Issue by BenSjoberg** [googleapis/nodejs-storage#1600]
Since upgrading @google-cloud/storage to 5.14.2, uploads created with `File.createWriteStream()` have started failing with the fairly cryptic error mentioned in the title. It seems like some value isn't being sent to the server, but there's no indication of what that is. No other aspect of the code, the environment, or the bucket configuration has changed.

Here's the full error output. Let me know if any other information would be helpful:

```
GaxiosError: Required
    at Gaxios._request (/image/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/image/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at async Upload.makeRequest (/image/node_modules/gcs-resumable-upload/build/src/index.js:348:21)
    at async Upload.createURIAsync (/image/node_modules/gcs-resumable-upload/build/src/index.js:171:22) {
  response: {
    config: {
      method: 'POST',
      url: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted)/o?name=sanitized%2Fg2planet-emax-master.pg&uploadType=resumable',
      params: [Object],
      data: [Object],
      headers: [Object],
      validateStatus: [Function (anonymous)],
      paramsSerializer: [Function: paramsSerializer],
      body: '{"storageClass":"multi_regional"}',
      responseType: 'json'
    },
    data: { error: [Object] },
    headers: {
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      connection: 'close',
      'content-length': '191',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Tue, 21 Sep 2021 13:52:55 GMT',
      expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
      pragma: 'no-cache',
      server: 'UploadServer',
      vary: 'Origin, X-Origin',
      'x-guploader-uploadid': 'ADPycduORZSKta7Z16dQ01vYRwJpaqOz9zWLYl_HUVvDr4S_RLAL34IMUywSH0gPFqaAb3-KE2HnesZAmhOnX8skfKI'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted)/o?name=sanitized%2Fg2planet-emax-master.pg&uploadType=resumable'
    }
  },
  config: {
    method: 'POST',
    url: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted)/o?name=sanitized%2Fg2planet-emax-master.pg&uploadType=resumable',
    params: {
      name: 'sanitized/g2planet-emax-master.pg',
      uploadType: 'resumable'
    },
    data: { storageClass: 'multi_regional' },
    headers: {
      Authorization: 'Bearer (redacted)',
      'User-Agent': 'google-api-nodejs-client/7.9.2',
      'x-goog-api-client': 'gl-node/16.9.1 auth/7.9.2',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    validateStatus: [Function (anonymous)],
    paramsSerializer: [Function: paramsSerializer],
    body: '{"storageClass":"multi_regional"}',
    responseType: 'json'
  },
  code: 400,
  errors: [ { message: 'Required', domain: 'global', reason: 'required' } ]
}
```

#### Environment details

  - OS: Debian 10 (Official Node.js Docker image)
  - Node.js version: 16.9.1
  - npm version: 7.21.1
  - `@google-cloud/storage` version:

#### Steps to reproduce

  1. Create an upload stream with File.createWriteStream() and attempt to write to it

**Comment by jeremydw** [comment]
Hi @BenSjoberg – I don't work on this client nor at Google but am impacted by the same issue out of the blue. Can you confirm if you've discovered a workaround (we'd like to use it if so). Are you able to pin any of the `@google-cloud` dependencies to older versions to fix the issue?

**Comment by BenSjoberg** [comment]
I figured it out by sifting through the package-lock.json diff. Turns out the issue isn't in @google-cloud/storage, it was in a sub-dependency - node-fetch! Version 2.6.3 had an issue which has been patched: https://github.com/node-fetch/node-fetch/issues/1302

Running `npm update node-fetch` resolved the issue. Sorry for the noise!

**Comment by astefer** [comment]
I've had exactly the same problem with 5.14.2 and I'm not using node-fetch. Updating to 5.14.3 seems to solve the problem but this might as well be related to something else. With previous versions I didn't have any problem. Maybe this should be reopened? @ddelgrosso1

**Comment by ddelgrosso1** [comment]
Hi @astefer, thank you for letting us know. Can you give me any further details about what you are seeing, i.e. the same error messages outlined above? What version were you on previous to `5.14.2`? Does it appear isolated to `5.14.2` for you?

**Comment by ddelgrosso1** [comment]
@astefer another piece of information that might be helpful is when did you update to 5.14.2?

**Comment by astefer** [comment]
It worked with 5.14.1, didn't work with 5.14.2, and now seems to work again with 5.14.3. But I can't say for sure since this function never ran in production and therefore does not have many executions.

I'm in a firebase cloud functions environment that runs node 14.

### Error message
```
GaxiosError: Required
    at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Compute.requestAsync (/workspace/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at async Upload.makeRequest (/workspace/node_modules/gcs-resumable-upload/build/src/index.js:348:21)
    at async Upload.createURIAsync (/workspace/node_modules/gcs-resumable-upload/build/src/index.js:171:22) {
  response: {
    config: {
      method: 'POST',
      url: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted).appspot.com/o?name=users%2F(redacted)%2Factivities%2F(redacted).json&uploadType=resumable',
      params: [Object],
      data: [Object],
      headers: [Object],
      validateStatus: [Function (anonymous)],
      paramsSerializer: [Function: paramsSerializer],
      body: '{"contentType":"application/json"}',
      responseType: 'json'
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      connection: 'close',
      'content-length': '191',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Thu, 23 Sep 2021 13:11:10 GMT',
      expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
      pragma: 'no-cache',
      server: 'UploadServer',
      vary: 'Origin, X-Origin',
      'x-guploader-uploadid': 'ADPycduQ1bRE5o4sxP2YjZaVEDf9clKtkdxJaLL0liei4zEEJg6p3Y50CaQ_KT5qOF9iWyMb_ihK4KMt-w-OPn8-sj8'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted).appspot.com/o?name=users%2F(redacted)%2Factivities%2F(redacted).json&uploadType=resumable'
    }
  },
  config: {
    method: 'POST',
    url: 'https://storage.googleapis.com/upload/storage/v1/b/(redacted).appspot.com/o?name=users%2F(redacted)%2Factivities%2F(redacted).json&uploadType=resumable',
    params: {
      name: 'users/(redacted)/activities/(redacted).json',
      uploadType: 'resumable'
    },
    data: { contentType: 'application/json' },
    headers: {
      'X-Upload-Content-Type': 'application/json',
      Authorization: '(redacted)',
      'User-Agent': 'google-api-nodejs-client/7.9.2',
      'x-goog-api-client': 'gl-node/14.17.3 auth/7.9.2',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    validateStatus: [Function (anonymous)],
    paramsSerializer: [Function: paramsSerializer],
    body: '{"contentType":"application/json"}',
    responseType: 'json'
  },
  code: 400,
  errors: [ { message: 'Required', domain: 'global', reason: 'required' } ]
}
```

**Comment by ddelgrosso1** [comment]
Thanks for the info @astefer. One other question, could you possibly drill into your `node_modules` folder for `5.14.2` and look for `node-fetch` and tell me what version it is using?

**Comment by astefer** [comment]
Okay I'm stupid. Thought that the node-fetch problem came by importing it separately (and therefore somehow having a different version) which I don't do. So 2.6.3 was causing the problem for me as well. But still, maybe you should fix it to ^2.6.4?

**Comment by ddelgrosso1** [comment]
Thanks for verifying @astefer. `node-fetch` is being imported by one of our downstream dependencies. I will raise a PR to that repo to set the version above `2.6.3`.

**Comment by ddelgrosso1** [comment]
I'm going to close this issue. A fix has been made to the gaxios library to pin the version of node-fetch above the bad version. If this doesn't resolve it for all, feel free to reopen or comment.

**Comment by jeremydw** [comment]
Hi @ddelgrosso1 - Thanks for chiming in here and I agree pinning `node-fetch` to a working version is a good solution for this issue. That said I do have a suggestion that can help similar issues in the future if they ever crop up –

The raised error was simply `GaxiosError: Required` -- which provides no useful information about what went wrong with the request. It's not super urgent but maybe the error could be changed to show what's missing from the request?

**Comment by ddelgrosso1** [comment]
@jeremydw I totally agree that the message could be improved / more details given. We have some upcoming initiatives to improve error messaging in the storage library as well as some of the dependencies. This will hopefully improve clarity in the future.

**Comment by BCJdevelopment** [comment]
I am having the exact same issue as the initial post by @BenSjoberg . Getting 400 "Required" error, my @google-cloud/storage version is 5.14.5. Any suggestions on how to fix?

**Comment by BCJdevelopment** [comment]
UPDATE: 
The node-fetch package was defaulting to version 2.6.3 for me, which was the source of the issue (as outlined by several of the references made in comments above). I was able to get it working by adding the following as "dependencies" under both gaxios and teeny-request in my package-lock.json:

```
"teeny-request": {
      ...,
      "dependencies": {
        "node-fetch": {
          "version": "2.6.5",
        }
      }
    },
```

```
"gaxios": {
      ...,
      "dependencies": {
        "node-fetch": {
          "version": "2.6.5",
        }
      }
    },
```

And then running `npm install` to update the packages accordingly.

**Comment by Abhishek-tellisim** [comment]
I am still facing this error even after updating the dependency node-fetch under tenny-request and gaxios.

**Comment by ddelgrosso1** [comment]
@Abhishek-tellisim if you are facing a similar or new issue please feel free to open a new issue. This issue is several years old and we have revised the library several times since.
