### ISSUE TITLE
Can't upload using custom apiEndpoint

### ISSUE THREAD

**Issue by jpambrun** [googleapis/nodejs-storage#1611]
#### Environment details

  - OS: Linux (node:16 docker image)
  - Node.js version: v16.10.0
  - npm version: 7.24.0
  - `@google-cloud/storage` version :5.14.3

#### Steps to reproduce

  1. setup an emulator (on a different machine or pod)
  2. run the following (this expects the emulator is reachable from google-cloud-storage.gcp-emu):
``` js
const { Storage } = require('@google-cloud/storage');

const storage = new Storage({ apiEndpoint: 'https://google-cloud-storage.gcp-emu', projectId: 'gcp-emu-prj' });

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

(async () => {
  console.log('CREATE BUCKET');
  await storage.createBucket('bucketname').catch(console.warn);
  const bucket = storage.bucket('bucketname');
  await sleep(2000);

  console.log('WRITE FILE');
  const blobWrite = bucket.file('test.txt');
  const blobWriteStream = blobWrite.createWriteStream();
  blobWriteStream.end(`test: ${Date.now()}`);
  await sleep(2000);
})();
``` 

  3. notice the following errors:
```
> NODE_TLS_REJECT_UNAUTHORIZED=0 node test.js
CREATE BUCKET
(node:116) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
WRITE FILE

node:events:368
      throw er; // Unhandled 'error' event
      ^
FetchError: request to http://[::]/upload/resumable/fd51c5c13d6966f8ec5a55b1b67c5f24 failed, reason: connect ECONNREFUSED :::80
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Pumpify instance at:
    at Pumpify.Duplexify._destroy (/app/node_modules/duplexify/index.js:195:15)
    at /app/node_modules/duplexify/index.js:185:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  config: {
    method: 'PUT',
    url: 'http://[::]:80/upload/resumable/fd51c5c13d6966f8ec5a55b1b67c5f24',
    headers: {
      'Content-Length': 0,
      'Content-Range': 'bytes */*',
      Accept: 'application/json'
    },
    validateStatus: [Function (anonymous)],
    paramsSerializer: [Function: paramsSerializer],
    responseType: 'json'
  }
}
```

The create bucket seems to works as expected (it POST to `https://google-cloud-storage.gcp-emu/storage/v1/b?project=gcp-emu-prj`), but the upload stream is attempted to `http://[::]:80/upload/resumable/fd51c5c13d6966f8ec5a55b1b67c5f24`. This appears to be the wrong url and wrong protocol.

**Comment by jpambrun** [comment]
To add some information,  I can list buckets with getBuckets() and the bucket create in the snipped above before the error appears. I can also download existing files with `storage.bucket('bucketname') .file('.keep').download();`. Only the create stream function doesn't work.

**Comment by jpambrun** [comment]
OK. wow. this is confusing.

The actual issue was with the fake gcs emulator I was using not returning valid upload url.. this is where the `[::]:80` came from.

One thing I would say made debugging this very challenging was the use of gcs-resumable-upload which use configStore to save a file to `~/.config/configstore/gcs-resumable-upload.json` with cached url. This is something _very unexpected_ and it means that tweaking apiEndpoints with same filename has no effect.

**Comment by BrennaEpp** [comment]
Hi @jpambrun, thanks for opening this issue. Glad you managed to resolve it!

Thanks for the feedback as well. Using configstore is a known pain point and we’re tracking removing it in https://github.com/googleapis/gcs-resumable-upload/issues/347 

Closing this issue for now. Feel free to leave more feedback or open another issue if you continue experiencing difficulties with the library.
