### ISSUE TITLE
Don't throw an error if contentType can't be determined in bucket.combine

### ISSUE THREAD

**Issue by zbjornson** [googleapis/nodejs-storage#166]
Currently an error is thrown if this library can't detect the content type from the filename with `bucket.combine(files, "destination")`. The GCS API doesn't require a content type though[1], so I don't think this library should throw.

https://github.com/googleapis/nodejs-storage/blob/31e4654497cb02ce8dd2111c64f0c7c739d0b19c/src/bucket.js#L338-L340

#### Environment details

  - `@google-cloud/storage` version: master

[1] As far as I can tell at least. I tried the API explorer on the [doc page](https://cloud.google.com/storage/docs/json_api/v1/objects/compose) and it didn't cause an error. GCS responded with an object without a content-type. From the other docs, it sounds like it serves the contents with `application/octet-stream` in this scenario.

**Comment by stephenplusplus** [comment]
Thanks for catching this. @frankyn -- it looks like the API doesn't require a contentType to be specified for an Objects: compose request, but we were intentionally throwing if the user didn't provide one to this library. Do you recall if this was old behavior, or ultimately, if it's safe for us to remove the throw, and let the API figure it out?

**Comment by zbjornson** [comment]
FWIW, this was the most useful part of the docs that I could find:

> If you do not specify a content type when you upload an object, the Cloud Storage system defaults to application/octet-stream when it serves the object.

https://cloud.google.com/storage/docs/xml-api/reference-headers#contenttype

**Comment by frankyn** [comment]
Checking on this with GCS team to make sure.  @zbjornson's quote can also be found in the [Discovery doc](https://www.googleapis.com/discovery/v1/apis/storage/v1/rest). 
The object metadata doesn't look to be required as it defaults to application/octet-stream.

**Comment by frankyn** [comment]
From GCS team: It turns out in the past Content-type was required. Now it's considered optional as it defaults to application/octet-stream when not provided.

**Comment by stephenplusplus** [comment]
Thank you!
