### ISSUE TITLE
Seem to be getting a 403 when using `getSignedUrl` with Workload Identity

### ISSUE THREAD

**Issue by mattmelgard** [googleapis/nodejs-storage#1672]
### Overview

I seem to be encountering a 403 when attempting to generate a signed URL for a GCS bucket object after switching to Workload Identity and my question is - is Workload Identity supported for that code path? If so, is there something else I need to be doing to configure credentials correctly? This was working just a little while ago for us and the only change that I can track down is that we've moved from a "physical" service account JSON key presented as a k8s secret to Workload Identity. Additionally, the PubSub role does seem to still be functional and publishing a message from our application does still appear to work with Workload Identity, just not generating a signed URL via this library.

Here are some more details if any of this helps -

Example of the error output:

```
{"level":"error","time":1634781291172,"pid":1,"hostname":"ovr-api-8698496c66-s7zwj","name":"ovr-api","name":"SigningError","stack":"Error: Unsuccessful response status code. Request failed with status code 403\n    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:129:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async metadataAccessor (/app/node_modules/gcp-metadata/build/src/index.js:68:21)\n    at async GoogleAuth.getCredentialsAsync (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:531:22)\n    at async GoogleAuth.sign (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:646:23)\n    at async sign (/app/node_modules/@google-cloud/storage/build/src/signer.js:97:35)","type":"Error","msg":"Unsuccessful response status code. Request failed with status code 403"}
```
```
Uncaught Error: Unsuccessful response status code. Request failed with status code 403
    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async metadataAccessor (/app/node_modules/gcp-metadata/build/src/index.js:68:21)
    at async GoogleAuth.getCredentialsAsync (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:531:22)
    at async GoogleAuth.sign (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:646:23)
    at async sign (/app/node_modules/@google-cloud/storage/build/src/signer.js:97:35) {
  name: 'SigningError'
}
```

Here's what the k8s service account looks like:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    iam.gke.io/gcp-service-account: api-dev@ovrnight-dev.iam.gserviceaccount.com
  creationTimestamp: "2021-10-16T16:49:46Z"
  labels:
    app.kubernetes.io/instance: ovr-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ovr-api
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: ovr-api-0.1.0
  name: ovr-api
  namespace: main
  resourceVersion: "225142306"
  selfLink: /api/v1/namespaces/main/serviceaccounts/ovr-api
  uid: ed20cf6e-f76b-44b8-afd8-4b1fce5edceb
secrets:
- name: ovr-api-token-4r4b4
```

Code snippet where signed URL is requested:

```
import { Storage } from '@google-cloud/storage';
import { DateTime } from 'luxon';

import { Image } from 'src/entity';
import { config } from 'src/lib/config';
import { guidPath } from 'src/lib/guidPath';

import { logger } from './logging';

const storage = new Storage();
const buckets = config.storage;

export const getSignedUrl = async (image: Image, mimeType: string): Promise<string> => {
    if (!buckets[image.constructor.name]) {
        throw new Error(`Invalid configuration. No storage bucket found for '${image.constructor.name}'`);
    }
    const file = storage.bucket(buckets[image.constructor.name]).file(guidPath(image.guid));
    const result = await file.getSignedUrl({
        expires: DateTime.local().toUTC().plus({ hours: 2 }).toString(),
        action: 'write',
        contentType: mimeType
    });
    return result[0];
};
```

And the IAM roles in GCP for that service account are as follows:

* `Pub/Sub Publisher`
* `Secret Manager Admin`
* `Storage Object Admin`

### Environment details

  - OS:
  - Node.js version: `16.11.1`
  - npm version: `8.0.0`
  - `@google-cloud/storage` version: `@google-cloud/storage@5.13.0`

### Steps to reproduce

1. Spin up a GKE cluster with Workload Identity enabled
2. Create a service account with the IAM roles of `roles/storage.objectAdmin`
3. Spin up an application that uses Workload Identity via a k8s service account
4. Create a storage bucket and place an object there
5. Assign the k8s service account `roles/iam.workloadIdentityUser` for the cluster/namespace where the application is deployed
6. Attempt to generate a signed URL using `file.getSignedUrl` on the object created above

**Comment by ddelgrosso1** [comment]
Hi @mattmelgard sorry for the delay in getting back to you on this. I am going to be investigating this issue but I just wanted to confirm that you are still seeing this problem? Thanks!

**Comment by mattmelgard** [comment]
@ddelgrosso1 no worries, and yeah, this still seems to be an issue from what I can tell

**Comment by ddelgrosso1** [comment]
Hi @mattmelgard I am still in the process of getting a local setup to test this out. However, have you tried the troubleshooting steps outlined [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#troubleshooting)?

**Comment by ddelgrosso1** [comment]
Hi again @mattmelgard I have been trying to reproduce this issue locally and so far I have not had any luck utilizing the steps you outlined above. Are there any other details you might be able to provide me with that might be helpful in recreating this issue?
