### ISSUE TITLE
`File.download` truncates output file on failure

### ISSUE THREAD

**Issue by wchargin** [googleapis/nodejs-storage#1713]
The following minimal example attempts to download an object that does not
exist. We expect it to do nothing, but instead it truncates the output file(!):

```javascript
async function main() {
  const gcs = require("@google-cloud/storage");
  const bucketName = "gcp-public-data-landsat";
  const f = new gcs.Storage().bucket(bucketName).file("enoent");
  try {
    await f.download({ destination: "/tmp/gcsoutput" });
  } catch (e) {
    console.error("Download failed:", e.message);
  }
}
main();
```

As expected, this fails because the object does not exist:

> Download failed: No such object: gcp-public-data-landsat/enoent

However, it also creates or truncates `/tmp/gcsoutput`, as if the object
actually had existed and been 0 bytes long.

This is surprising and violates atomicity guarantees: a download that fails to
start should have no side effects, and should certainly not truncate a file. In
my use case, creating an empty file is just as bad as truncating an existing
one.

By way of comparison, using `curl(1)` for the same task *does not* touch the
output file if download fails:

```
$ printf 'hey\n' >/tmp/curlout
$ curl -fsSL https://storage.googleapis.com/gcp-public-data-landsat/enoent -o /tmp/curlout
curl: (22) The requested URL returned error: 404 
$ cat /tmp/curlout
hey
```

Suggestion: in `File#download`, only call `fs.createWriteStream(destination)`
once OK response headers have been received from the server. (If the download
fails midway through, ending up with the truncated contents in the destination
makes sense.)

#### Environment details

  - OS: Debian (but shouldn't matter)
  - Node.js version: v16.8.0 (but shouldn't matter)
  - npm version: v7.21.0 (but shouldn't matter)
  - `@google-cloud/storage` version: v5.15.4

#### Steps to reproduce

 1. `printf 'hello\n' >/tmp/gcsoutput`
 2. Run the script listed above, which should fail to download and leave
    `/tmp/gcsoutput` unchanged.
 3. Note that `/tmp/gcsoutput` is now in fact empty.

**Comment by shaffeeullah** [comment]
@wchargin Making this change could break existing users who rely on this behavior. As a workaround, you can call `file.exists` before downloading the file from GCS. Documentation for the `file.exists` API is [here](https://googleapis.dev/nodejs/storage/latest/File.html#exists).

**Comment by wchargin** [comment]
> As a workaround, you can call `file.exists` before downloading the file from GCS

This is not sufficient, because it introduces a race condition.

(It also introduces another network roundtrip, which is unnecessary.)

> making this change could break existing users who rely on this behavior

Would you consider making this an option, while retaining the
flexibility to flip the default in a major version release?

**Comment by shaffeeullah** [comment]
Discussed with the team and we will consider this a bug and fix the default logic. Fixing this will bring the library in alignment with `gsutil rsync`, `/usr/bin/rsync`, & `/usr/bin/curl` in addition to be safer against accidentally removing a file
