### ISSUE TITLE
Support creating signed urls for Cloud CDN

### ISSUE THREAD

**Issue by TriPSs** [googleapis/nodejs-storage#1719]
**Is your feature request related to a problem? Please describe.**
We want to implement signed urls that go through the load balancer with Cloud CDN, this library does not yet expose a method that can be used to generate those urls.

 **Describe the solution you'd like**
An method that will generate these urls for us.

 **Describe alternatives you've considered**
Create the custom code inside the application itself.

 **Additional context**
Would be awesome if this could be integrated inside the library as now everyone who needs this needs to figure it out themselves (As the Google Cloud docs does not have an example for node) and create their own solution.

**Comment by shaffeeullah** [comment]
Hi @TriPSs ,
Can you please elaborate a bit further on your use case? What would be the difference between this function and [file.getSignedUrl()](https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl)? You mention that the google cloud docs page doesn't have an example for node. Are there examples in other languages? What docs page are you referencing?

**Comment by TriPSs** [comment]
I mean [this](https://cloud.google.com/cdn/docs/using-signed-urls#signing_urls), if  I understood it correctly you need to create a custom "URL signing key" for the load balancer and use that one when creating the signed url so Cloud CDN / Load Balancer can accept it. Or is this incorrect?

**Comment by shaffeeullah** [comment]
Hi @TriPSs , 
Thanks for calling out the missing sample! I filed an issue in the samples repo and will move this discussion there. This repo hosts Storage samples only.
