### ISSUE TITLE
check bug call to https://www.googleapis.com/oauth2/v4/token have proxy from google

### ISSUE THREAD

**Issue by dangtinh97** [googleapis/nodejs-storage#1722]
request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 173.194.194.95:443

**Comment by ddelgrosso1** [comment]
Hi @dangtinh97, thank you for opening an issue. Could you give me a little bit more information about the problem you saw? Has this been consistently happening or is it a sporadic issue? Could you provide me with a code snippet that might reproduce the issue you are seeing? Thank you!

**Comment by ddelgrosso1** [comment]
Hi @dangtinh97 I will be happy to further look into this if additional information is available. In doing some testing on my own I did not see any issues with timeouts. In the meantime I am going to close this issue but please feel free to reopen if this continues to be a problem for you.
