### ISSUE TITLE
Missing Uint8Array type for file.save parameters

### ISSUE THREAD

**Issue by kuk941025** [googleapis/nodejs-storage#1724]
#### Environment details

  - OS: Big Sur 11.6.1
  - Node.js version: 14.17.4
  - npm version: yarn v1.22.10
  - `@google-cloud/storage` version: 5.16.0

#### Steps to reproduce
  1. update @google-cloud/storage to 5.16.0 from 5.7.2 

In #1388, types for file.save data parameter changed from any to string | Buffer. This resulted an type error.

Heres code from my project.
I am using firebase-admin@9.12.0 and @google-cloud/text-to-speech. Ran `yarn upgrade-interactive` command to make updates.

```ts
 const client = new textToSpeech.TextToSpeechClient();

 ...
 const [response] = await client.synthesizeSpeech(request);
 const file = bucket.file(filePath);

 await file.save(audioBuffer.audioContent, {
    resumable: false,
    contentType: 'audio/mpeg',
 });
```
client.synthesizeSpeech returns an array of Uint8Array as a response, and above code works perfectly fine.
as a work around, im using as type assertion
```ts
await file.save(audioBuffer.audioContent as Buffer)
```

Shoudn't Uint8Array type be included for file.save data parameter?
Thanks! :)

**Comment by ddelgrosso1** [comment]
Hi @kuk941025 thank you for bringing this up. This behavior is actually correct. If you look at the node documentation for the [Buffer class here](https://nodejs.org/api/buffer.html#buffer). You will see that `UInt8Array` are accepted anywhere `Buffer` are.

**Comment by kuk941025** [comment]
> Hi @kuk941025 thank you for bringing this up. This behavior is actually correct. If you look at the node documentation for the [Buffer class here](https://nodejs.org/api/buffer.html#buffer). You will see that `UInt8Array` are accepted anywhere `Buffer` are.

got it! thank you 👍
