### ISSUE TITLE
Accessing the Node.js client library from browser

### ISSUE THREAD

**Issue by faraazmalak** [googleapis/nodejs-storage#1725]
Any chance we can access the Node.js client  library from browser?
I get the following error, when trying to do so: `Uncaught TypeError: The "original" argument must be of type Function`

**Comment by ddelgrosso1** [comment]
Hi @faraazmalak if I understand correctly you are trying to import the library into a browser side application is that correct? If so, that is not currently supported. However, if you are trying to perform an operation such as an upload, you can generate a signed URL server side and use that URL client side to perform the operation using a standard HTTP request.

**Comment by ddelgrosso1** [comment]
Hi @faraazmalak please let me know if you need any further assistance with this issue and I will be happy to help. In the meantime I am going to close it out. The documentation on signed URLs can be found [here](https://cloud.google.com/storage/docs/access-control/signed-urls).

**Comment by faraazmalak** [comment]
> Hi @faraazmalak if I understand correctly you are trying to import the library into a browser side application is that correct? If so, that is not currently supported. However, if you are trying to perform an operation such as an upload, you can generate a signed URL server side and use that URL client side to perform the operation using a standard HTTP request.

Hi @ddelgrosso1 
Thanks for your reply. Yes, I was trying to import the library into a browser side app.. Since it's not supported, I've created a server side Node.js app and used the GCP Storage library
