### ISSUE TITLE
NO_PROXY variable on file.download()

### ISSUE THREAD

**Issue by mjoffily** [googleapis/nodejs-storage#1729]
I'm trying to download a file from cloud storage using the code below. The google APIs are not behind my companies proxy, so I am setting NO_PROXY=*googleapis.com

Unfortunately this does not seem to work on file.download() as it seems to be opening a tcp stream to download the file and ignoring that env variable

```javascript
 async function getFile(fileName) {
    try {
      const myfile = myBucket.file(fileName);
      const data = await myfile.download() // Need NO_PROXY here
      return JSON.parse(data.toString())
    } catch (error) {
      console.log(`getFile Error\n${error}`)
      throw error
    }
  }
```
Is there a way to use the download function with NO_PROXY?
Thanks in advance.

**Comment by shaffeeullah** [comment]
Hi @mjoffily ,

Can you please share how you're setting `NO_PROXY`?

**Comment by shaffeeullah** [comment]
Please reopen with the requested information if you're still seeing this issue.
