### ISSUE TITLE
Eliminate constructor pattern

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#173]
We currently use a little code like this in the Storage constructor:

```js
if (!(this instanceof Storage)) {
  return new Storage(options);
}
```
The problem is, this isn't valid es6/TypeScript :(   If we're going to convert this library over to TypeScript, we need to make a breaking change to the API first.  Given the fact that the death of nodejs 4 is near...  could we bundle this change with that one?  Otherwise we may need to wait another 6-12 months to do TypeScript.

**Comment by JustinBeckwith** [comment]
cc @ofrobots @googleapis/node-team

**Comment by ofrobots** [comment]
I think this change needs to happen more pervasively across all the client libraries, and we should not be making a semver major change to drop Node 4 support without also bundling this change alongside.

So +1.

**Comment by jinwoo** [comment]
This style is invalid only when using `class` vs legacy "function-as-a-constructor" style.

If we don't want to break existing code, we can leave the function constructor as is, and only use `class`'s in the internal implementations.

**Comment by jmdobry** [comment]
The autogenerated libraries have already made this switch.

**Comment by JustinBeckwith** [comment]
Given the fact that this API is GA, I would super like to avoid breaking things here.  @kolodny came up with this sweet work around:

```js
// Allow creating a `Bigtable` instance without using the `new` keyword.	
Bigtable = new Proxy(Bigtable, {	
  apply(target, thisArg, argumentsList) {	
    return new target(...argumentsList);	
  },	
});
```

**Comment by kinwa91** [comment]
> The problem is, this isn't valid es6/TypeScript

Do we also want to convert the `Storage` constructor into ES6 `class`? Otherwise I don't see how using this workaround makes it valid typescript.

**Comment by JustinBeckwith** [comment]
@kinwa91 Yes!  That's exactly the goal.  We may need to do this and #228 at the same time :)
