### ISSUE TITLE
Clean-up for `gcs-resumable-upload`

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/nodejs-storage#1743]
Now that `gcs-resumable-upload` has been merged into this library (https://github.com/googleapis/nodejs-storage/pull/1736), we should consider a refactor:

- [x] Rename `src/gcs-resumable-media/index.ts` to `src/gcs-resumable-upload.ts`
- [ ] Remove unnecessary dependencies in favor of native dependencies:
  - [ ] `pumpify` -> [Stream](https://nodejs.org/api/stream.html)
  - [x] `is-stream` -> [Stream](https://nodejs.org/api/stream.html)
  - [ ] `streamEvents` (remove, unnecessary)
- [x] Tighten `gcs-resumable-upload` integration  with `File` (shared type definitions, removing things that are optional that File wouldn't use, etc.)

**Comment by danielduhh** [comment]
FYI @shaffeeullah @danielbankhead , I made this a checklist so we can track what we've done so far

**Comment by danielbankhead** [comment]
`AbortController` isn't native in Node.js pre-v15... removing from the list for now

**Comment by danielbankhead** [comment]
Related:
- https://github.com/googleapis/nodejs-storage/issues/1915
- https://github.com/googleapis/nodejs-storage/issues/1916
