### ISSUE TITLE
Drop support for node.js 4

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#175]
This will be a semver major breaking change.  With 4 going out of support at the end of April, lets go ahead and:
- [ ] remove it from the circleci config
- [ ] Update the supported version in package.json

**Comment by stephenplusplus** [comment]
cc @alexander-fenster @jmdobry -- this seems like something that should be done in the generator thing.

**Comment by jmdobry** [comment]
affirmative

**Comment by JustinBeckwith** [comment]
To be clear - I am in no hurry to ship this breaking change :)  More than anything I want to collect all the breaking changes we want in the next semver major release and keep them in this 2.0 milestone.

**Comment by alexander-fenster** [comment]
Re: circleci, I'll take care of that.
Re: generator, other than updating supported version in `package.json`, what other changes need to be done in the generator?

**Comment by JustinBeckwith** [comment]
For hand written libs - I would prefer that we don't script this change.  Reason - we have other breaking changes we want to bundle into the major release, and I'd rather do these one at a time.  Specifically I'm worried about #173 type issues across all the hand written libs.

**Comment by fhinkel** [comment]
I'm closing this, `package.json` is updated and 4 is not on CircleCI anymore. Please re-open if needed.
