### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#177]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2814

<a href="/ravirajdj"><img src="https://avatars2.githubusercontent.com/u/10830160?s=88&v=4" height=44 width=44 align=left></a>@ravirajdj<br>April 16, 2018 7:24 AM

When I access the signed url from browser it gives a message stating "SignatureDoesNotMatch"

I checked below link but no luck.

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1976

Below is my function code

`
     }).then(() => {

                 const thumbFile = bucket.file(thumbFilePath)
                 const config = {
                   action : 'write',
                   expires : '03-09-2400'
                   

                 }
                 return Promise.all([
                   thumbFile.getSignedUrl(config),
                   file.getSignedUrl(config)

                 ])
`

Error Message:

`[<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
</Message>
<StringToSign>
GET 13575340800 /mango-b715d.appspot.com/asART_Nikola-Tesla_Wallpaper_V03.png
</StringToSign>
</Error>](url)`

-

#### Environment details

  - OS: Trying on windows & professional
  - Node.js version:8.11.1
  - npm version:5.6.0
  - `@google-cloud/storage` version:

#### Steps to reproduce

 My goal is ..
 
 I  have an android app in which i want to download an image and video,post download i am having some different logic to play with thoose files.
 
 After much r&d came to know google cloud is teh best fit, So below is the function code in which signed url will be triggering to teh database when i upload the  image, and currently because of this problem i am not able to donwload the file from the sighned url like, which makes my project haulted very badly.
 
 I need the fix immediately, without this fix my business logic will ge effected very badly,Kindly respond as soon as possible and let me know if any information required.
 
 
 Below is my code..

```js
const functions = require('firebase-functions');
const gcs = require('@google-cloud/storage')({keyFilename:'xxxxx.json'})
const spawn = require('child-process-promise').spawn
const admin = require('firebase-admin')

admin.initializeApp(functions.config().firebase)

exports.generateThumbnail = functions.storage.object().onChange(event => {
  const object = event.data
  const filePath = object.name
  const fileName = filePath.split('/').pop()

  const fileBucket = object.bucket
  const bucket = gcs.bucket(fileBucket)
  const tmpFilePath = '/tmp/${fileName}'

  const ref = admin.database().ref()
  const file = bucket.file(filePath)
  const thumbFilePath = filePath.replace(/(\/)?([^\/]*)$/,'$1thumb_$2')

  if(fileName.startsWith('thumb_')){
    console.log("already a thumb")
    return
  }

  if(!object.contentType.startsWith('image/')){
    console.log("thsi sis not an image")
    return
  }

  if(object.resouceState == 'not_exists'){
    console.log("thsi is a deletion event ")
    return
  }

  return bucket.file(filePath).download({destination:tmpFilePath})
    .then(() => {
      console.log("file downloaded to thmp path",tmpFilePath)
      return spawn('convert',[tmpFilePath,'-thumbnail','300x300>',tmpFilePath])
    })
    .then(() => {
      console.log("thumbail created")
      //const thumbFilePath = filePath.replace(/(\/)?([^\/]*)$/,'$1thumb_$2')
      return bucket.upload(tmpFilePath,{
        destination:thumbFilePath
      })
   }).then(() => {
      const thumbFile = bucket.file(thumbFilePath)
      const config = {
        action : 'write',
        expires : '03-09-2400'             
      }
      return Promise.all([
        thumbFile.getSignedUrl(config),
        file.getSignedUrl(config)
      ])
    }).then(results => {
      const thumbResult = results[0]
      const originalResult = results[1]
      const thumbFileUrl = thumbResult[0]
      const fileUrl = originalResult[0]
      return ref.child('posts').push({path:fileUrl, thumbnail:thumbFileUrl})
    })
})
```

**Comment by stephenplusplus** [comment]
Thanks for reporting, @ravirajdj. Could you fill in our [issue template](https://github.com/googleapis/nodejs-storage/edit/master/.github/ISSUE_TEMPLATE.md)? In this case, reproduction code and steps will be very helpful. We have tests passing that do the same as what your code shows, so boiling your code down to the smallest reproduction case possible will help tell what differentiates our working code from yours. Thanks!

**Comment by ravirajdj** [comment]
Hi Stephen,As per your request I have updated issue template,and as you said you have a code which works without the error i am facing, So could you share me that code, So that i can try it out, and I need imemdiate assistance because my complete businees logic will ge effected very badly if this signedurl doesn't works.

My main motive is using this signedurl i want to donwload the image into my android aoo to external storage.

And could you tell me is there any way to get donwloadurl from the cloud functions sdk.

**Comment by stephenplusplus** [comment]
Thanks, I pasted your completed template in the first post in this issue. The way you are generating the URL seems correct-- can you show the details of the HTTP request you are making to the generated URLs?

**Comment by stephenplusplus** [comment]
You configured a URL that is meant to be `PUT` to. Can you provide the details of the HTTP request you're sending to the generated URL?

> 2. Is it possible to share the link or code, the way to download the image from signed url.

You can create a URL using the `READ` action. This is from our docs:

```js
var config = {
  action: 'read',
  expires: '03-17-2025'
};

file.getSignedUrl(config, function(err, url) {
  if (err) {
    console.error(err);
    return;
  }

  // The file is now available to read from this URL.
  request(url, function(err, resp) {
    // resp.statusCode = 200
  });
});
```

**Comment by stephenplusplus** [comment]
I'm going to close, as I believe this is a matter of making the correct HTTP request. Feel free to ask any additional questions.

**Comment by ravirajdj** [comment]
Sure, please close it , I was able to access after giving "read" in the
code.
