### ISSUE TITLE
Is there is way that we can compress entrire directory on GCS ?

### ISSUE THREAD

**Issue by JagdishElsner** [googleapis/nodejs-storage#1770]
Is there is way that we can compress and zip entire direcroty on google cloud storage ?

as of now we have to do below step, which take longer time and use high resourecs.

- User Archiver in node JS
- Download File 
- Append them in Archiver 
- Upload zip again back to firebase storage

so does any way that we directly can compress zip on firebase cloud storage ?

**Comment by ddelgrosso1** [comment]
Hi @JagdishElsner thank you for opening an issue. It seems that you are accessing storage through FIrebase, questions for that particular SDK should be opened at https://github.com/firebase/firebase-js-sdk/issues. I am going to close this issue. If I am incorrect and you are accessing storage without Firebase please feel free to reopen.
