### ISSUE TITLE
File upload to google cloud storage is slow

### ISSUE THREAD

**Issue by dev2k22** [googleapis/nodejs-storage#1795]
**What you're trying to do**
I am using google cloud storage for uploading videos via a separate server in Node.js. For multipart form data, I am using [busboy](https://www.npmjs.com/package/busboy), but for videos as small as 40 MB (1920x1080 resolution), the upload time is 19 minutes (1182652.762 ms) which is quite long. I am uploading file in chunks (as atm I do not intend to save it to temporary memory). I am looking for optimizations to my code that will ensure performance boost as even files of 1700 KB are taking too long to upload (7-8 seconds).

**What code you've already tried**
```
try {
    const busboy = Busboy({
      headers: req.headers,
    });

    const { title } = req.query;

    let newVideo;

    busboy.on('file', (name, file, info) => {
      const { filename, encoding, mimeType } = info;
      console.log(
        `File [${name}]: filename: %j, encoding: %j, mimeType: %j`,
        filename,
        encoding,
        mimeType
      );

      if (!isVideoValid(mimeType)) {
        return res.status(422).json({
          message: 'File type is not valid',
        });
      }

      const extension = mimeType.split('/').pop();

      newVideo = courseBucket.file(
        `${title}.${extension}`
      );

      file
        .pipe(newVideo.createWriteStream({ gzip: 'auto', resumable: true }))
        .on('error', (err) => {
          console.log(err);
        })
        .on('finish', () => {
          console.log(`File ${name} upload finished`);
          newVideo
            .getSignedUrl({ action: 'read', expires: '03-17-2024' })
            .then((url) => {
              res.status(201).json(url[0]);
            });
        });
    });

    busboy.on('close', () => {
      console.log('Done parsing form!');
    });

    req.pipe(busboy);
  } catch (err) {
    console.log(`Internal Server Error, ${err}`);
    res.status(500).json({ message: err.message, error: err });
  }
```
and here is the config for server middleware wrt urlencoded
```
app.use(
  express.urlencoded({
    limit: '50mb',
    extended: true,
  })
);
```

**Any error messages you're getting**
None, code is working fine apart from slow performance. And I am also using a separate Node.js server for video upload and streaming

**Comment by dev2k22** [comment]
Issue is with the way I am uploading files to GCP via streaming, as busboy is working fast when uploading files to disk. Any recommendations as I am using multi-part form data and busboy is the ideal library for such endeavor

**Comment by ddelgrosso1** [comment]
Hi @dev2k22 thank you for bringing this to our attention. A few questions for you, what version of the library are you currently using? Instead of using `busboy` have you tried simply uploading a static file to see if you still get the same results, i.e. the upload of a static file takes 19 minutes? What about trying without the gzip option set in the `createWriteStream`?

**Comment by dev2k22** [comment]
Hi @ddelgrosso1 it was a nationwide issue with internet connectivity for a few days that gave me the impression that the code was not working as intended. Its all working fine now as 40 MB file is uploaded within 5 minutes. I also checked by uploading the file via GCP storage console and it took the same amount of time.
Thank-you for taking your time, btw is my approach correct wrt streaming upload from source to destination?

**Comment by dev2k22** [comment]
@ddelgrosso1 thanks for your suggestion on a signed URL, for uploaded files URLs in the database, should I set the bucket to public?
Because some file URLs might have a shelf life of a year

**Comment by dev2k22** [comment]
@ddelgrosso1 Thanks for the heads-up, I will definitely change the signed URL according to application's use case. Thanks again
