### ISSUE TITLE
Getting content of object

### ISSUE THREAD

**Issue by darweshsinghcgi** [googleapis/nodejs-storage#180]
How do I get the content of a file in a bucket, to say, print to console?

Something similar to `curl -H "Authorization: Bearer {token}" https://www.googlapis.com/storage/v1/b/{bucket}/o/(object}?alt=media`, which returns the actual object body and not metadata/a promise.

#### Environment details

  - OS: macOS, Ubuntu
  - Node.js version: 9.10.1
  - npm version: 5.8.0
  - `@google-cloud/storage` version: 1.6.0

**Comment by stephenplusplus** [comment]
I believe the closest we have is [`file.download()`](https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/File#download):

```js
file.download(function(err, contents) {
  console.log(contents)
})
```
