### ISSUE TITLE
File randomly not available right after upload via signed URL

### ISSUE THREAD

**Issue by PierBover** [googleapis/nodejs-storage#1801]
We're uploading files from the browser using a signed URL. The files are not very big. Less than 20MB.

Once the upload has completed from the client, a request is made to our server to notify the upload has been completed. The server then checks if the file exists in the storage.

The problem we're having is that the [exists()](https://googleapis.dev/nodejs/storage/latest/File.html#exists) function returns `[false]` randomly even though we know the upload has completed 100% and we can actually see the file in the bucket a bit later.

This is the function we're using in the server to verify if the file exists in the bucket:

```js
async function checkFileExistsInStorage ({storageKey, bucketName}) {
	const bucket = storageClient.bucket(bucketName);
	const file = bucket.file(storageKey);
	const result = await file.exists();
	return result[0];
}
```

It would appear there is some random lag/latency between the completion of the upload and [exists()](https://googleapis.dev/nodejs/storage/latest/File.html#exists) returning `[true]`.

To test this hypothesis, we've modified our function to retry for up to 5 times:

```js
export async function checkFileExistsInStorage ({storageKey, bucketName}) {
	const bucket = storageClient.bucket(bucketName);
	const file = bucket.file(storageKey);

	let retries = 0;
	let exists = false;

	do {
		console.log(retries);
		const result = await file.exists();
		console.log(result);
		exists = result[0];
		retries ++;
	} while (exists === false && retries < 5);

	return exists;
}
```

Typically we can see this in the logs:

```
0
[ true ]
```

This indicates the file was available on the first check. But maybe 30% of the times we see this instead:

```
0
[ false ]
1
[ false ]
2
[ true ]
```

Which confirms the uploaded files are not immediately available after the upload has completed.

This behavior seems extremely weird. One would assume the file should be immediately available after a successful upload response considering Google Cloud Storage is supposedly [strongly consistent](https://cloud.google.com/storage/docs/consistency).

Is this expected behavior?

If yes, how can we handle this behavior?

The Google Cloud docs don't seem to mention any of this.

**Comment by ddelgrosso1** [comment]
Thanks for raising this issue @PierBover. On the browser side how are you verifying the upload has completed? What are you getting as the response? Also, what is delay between success on the browser and the query on the server?

**Comment by PierBover** [comment]
Hey @ddelgrosso1 

I'm uploading via XHR to be able to monitor the progress. The upload is assumed as completed when the browser fires the `loadend` event.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event

After the `loadend` event is fired, an empty `200` response is received, and the client makes a request to the server.

Before checking if the file exists, the server does some stuff with the database. I'm guessing maybe 500ms or so have passed after the upload has completed.

**Comment by PierBover** [comment]
I think I've found the problem.

There seems to be a small delay between the `loadend` and the last `readystatechange` events.

If I wait for the last `readystatechange` to be triggered in the client, the issue seems to disappear.

I'll close this issue for now and reopen if this doesn't solve it.
