### ISSUE TITLE
What is the proper way to download everything from a bucket?

### ISSUE THREAD

**Issue by kruncher** [googleapis/nodejs-storage#1819]
We have a CMS in GCP which has images uploaded to a bucket and we have a website that is being generated and deployed by Netlify. When Netlify generates the static website we want it to copy the contents of the bucket into the generated website.

From the documentation it seems that the only way to do this is:
1. Get a listing of the contents of the bucket.
2. Download each file individually.

Is there a better way? perhaps a way to download the entire thing as a .zip file?

**Comment by kruncher** [comment]
Thank you for your reply @ddelgrosso1; in that case I will proceed with the above since the CMS does not have such a feature.

Are you able to suggest a reasonable maximum number of async/parallel downloads at a time?

**Comment by ddelgrosso1** [comment]
I would generally recommend starting with a smaller number of concurrent downloads, i.e. 5 - 10 and scale up from there. In some informal testing I have found this to be a good starting point. How far you scale will of course depend on the size of the instances and network configuration you are utilizing on GCP.

**Comment by kruncher** [comment]
Perfect, thank you!
