### ISSUE TITLE
File.publicUrl() returns an incorrect URL if the file key contains URL query parameters

### ISSUE THREAD

**Issue by jbrowning** [googleapis/nodejs-storage#1824]
#### Environment details

  - OS: Google Cloud Function (1st gen)
  - Node.js version: 14.19.1
  - npm version: 
  - `@google-cloud/storage` version: 5.8.5

#### Steps to reproduce

  1. Upload a file to Cloud Storage containing query parameters in the key -- example: `somefile.jpg?state=thumbnail`
  2. Make the file public via `File.makePublic()`
  3. Retrieve the file's public URL with `File.publicUrl()`

The returned URL looks like `https://storage.googleapis.com/bucket/somefile?state=thumbnail` but any attempt to download the file at that URL results in the following error:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

**HOWEVER** Viewing the file in the Google Cloud Platform Cloud Storage web console *does* give the correctly-encoded URL which looks like `https://storage.googleapis.com/bucket/somefile.jpg%3Fstate%3Dthumbnail`

I've reviewed the Changelog for subsequent releases but there is no mention of a fix for this.

**Comment by ddelgrosso1** [comment]
@jbrowning what I believe to be the fix for this has been released in version `5.18.3`.

**Comment by jbrowning** [comment]
@ddelgrosso1 Perfect. Thanks for the quick fix.

**Comment by sseppola** [comment]
@ddelgrosso1 was it intentional that filenames with paths now turn from `upload/video/test.mp4` to `upload%2Fvideo%2Ftest.mp4`?
It still works, and the GCS UI shows the directories as expected, but the public urls I store in my DB are less readable.

**Comment by ddelgrosso1** [comment]
@sseppola I should have realized this before but the reason it was done this way is due to the [object naming guidelines](https://cloud.google.com/storage/docs/naming-objects) in GCS. In the above snippet `this.name` represents the object name, which can support characters such as spaces, ampersands, etc. In order to return a properly working public url the entire name will need to be encoded to account for these cases.

**Comment by sseppola** [comment]
Makes sense, thanks for resolving it so quickly 👍
