### ISSUE TITLE
Unable to upload file with content-type image/jpeg

### ISSUE THREAD

**Issue by ry-propeller** [googleapis/nodejs-storage#1836]
#### Environment details

  - OS: Mac
  - Node.js version: v14.18.2
  - npm version: 6.14.15
  - `@google-cloud/storage` version: 5.18.3

#### Steps to reproduce

  1. Get a URL Serverside:
 ```
const response = await storage
    .bucket(bucket)
    .file(key)
    .getSignedUrl({
      action: 'write',
      expires: new Date().getTime() + MINUTE_IN_MILLISECONDS * 50,
      version: 'v4',
    });
return response[0]
```

  2. Make a PUT request client side with the URL from the above step `signedUploadURL`
 
This successfully uploads, but it is the wrong file type.
```
// get file from file input (Testing with a JPEG file)
const file = event.target.files[0];
fetch(signedUploadURL, {
            method: 'PUT',
            body: file,
            mode: 'cors',
            headers: {
              'Content-Type': `text/plain`,
            },
            cache: 'no-cache',
            credentials: 'same-origin',
            redirect: 'follow',
          });
```

When I change the file type (`image/jpeg`) this does not work. I get a 400 status with no error message.
```
fetch(signedUploadURL, {
            method: 'PUT',
            body: file,
            mode: 'cors',
            headers: {
              'Content-Type': file.type,  // image/jpeg
            },
            cache: 'no-cache',
            credentials: 'same-origin',
            redirect: 'follow',
          });
```

I have also tried matching the server call with contentType like this, but it does not work either.
 ```
const response = await storage
    .bucket(bucket)
    .file(key)
    .getSignedUrl({
      action: 'write',
      expires: new Date().getTime() + MINUTE_IN_MILLISECONDS * 50,
      version: 'v4',
      contentType: `image/jpeg`,
    });
return response[0]
```

**Comment by ddelgrosso1** [comment]
Hi @ry-propeller thank you for raising this issue. According to the documentation for [`getSignedUrl`](https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl) if you provide (or don't provide) a value for `contentType` the following request must utilize the same value. I have successfully uploaded an image that displays the expected content type utilizing the following code:

```
const url = await file.getSignedUrl({
      contentType: "image/jpeg",
      action: "write",
      expires: tomorrow,
      version: 'v4',
    });

const result = await axios.put(url[0], imageData, {
      headers: {
        "Content-Type": 'image/jpeg'
      }
});

**Comment by ry-propeller** [comment]
Thanks! Turns out it had to do with CORS caching
