### ISSUE TITLE
"Cannot insert legacy ACL for an object when uniform bucket-level access"  only for large file

### ISSUE THREAD

**Issue by lucascognamiglio1** [googleapis/nodejs-storage#1842]
#### Environment details

  - OS: MacOs Monterey
  - Node.js version: 16
  - npm version: 8.5.1
  - `@google-cloud/storage` version:

Hi everyone, I'm having a problem uploading a 920Mb file.

When I try to upload the file via google storage's "upload" function, I get this error message:

`"User-Agent":"google-api-nodejs-client/7.14.0","x-goog-api-client":"gl-node/16.13.0 auth/7.14.0","Accept":"application/json"},"responseType":"json"},"code":400,"errors":[{"message":"Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access","domain":"global","reason":"invalid"}],"errorMessage":"Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access","errorStack":"Error: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access\n    at Gaxios._request (/Users/lucascognamiglio/Desktop/CherryProjects/epona-ape/node_modules/gaxios/build/src/gaxios.js:129:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async JWT.requestAsync (/Users/lucascognamiglio/Desktop/CherryProjects/epona-ape/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)\n    at async Upload.makeRequest (/Users/lucascognamiglio/Desktop/CherryProjects/epona-ape/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:605:21)\n    at async Upload.getAndSetOffset (/Users/lucascognamiglio/Desktop/CherryProjects/epona-ape/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:552:26)\n    at async Upload.continueUploading (/Users/lucascognamiglio/Desktop/CherryProjects/epona-ape/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:350:9)"}
`

This only happens to me when I try to upload a file of this size, while if I try to upload an image, I don't have any kind of problem.

![Screenshot 2022-04-05 at 17 51 28](https://user-images.githubusercontent.com/88660458/161794717-1b6b6f24-7b82-4f1b-8ee7-db5f1b00a66a.png)

For greater clarity I am attaching the part of the code:

https://pastebin.com/xmwtjPa0

**Comment by ddelgrosso1** [comment]
Hi @lucascognamiglio1 thank you for bringing this issue to our attention. We are in the process of determining how to best fix this. However, I can offer some workarounds in the meantime. 

The issue you are seeing seems related to this [one](https://github.com/googleapis/nodejs-storage/issues/1230) and one of the users offered a possible fix [here](https://github.com/googleapis/nodejs-storage/issues/1230#issuecomment-750493684). Another possibility would be to call `deleteResumableCache` in the event that you get this error. This is the library friendly way of accomplishing the same suggestion offered in the issue. Documentation for this function is [here](https://googleapis.dev/nodejs/storage/latest/File.html#deleteResumableCache).

**Comment by ddelgrosso1** [comment]
In the next major version revision we will be attempting to remove the resumable upload cache to prevent this issue in the future. Being as there is currently a workaround solution I am going to close this issue. If you feel that this did not resolve your issue please feel free to reopen.
