### ISSUE TITLE
Why is my uploaded file blank?

### ISSUE THREAD

**Issue by enahsor** [googleapis/nodejs-storage#1852]
I'm attempting to copy files in a google drive folder to a google cloud storage bucket. This is the code I have so far:

```js
async function addData(bucketName, data) {
  const storage = new Storage();
  const bucket = await storage.bucket(bucketName);

  const readable = new Readable();
  readable._read = () => {};
  readable.push(data.content);
  readable.push(null);

  const file = bucket.file(data.name);
  readable
    .pipe(file.createWriteStream({ gzip: true }))
    .on("error", (err) => {
      console.log(err);
    })
    .on("finish", () => {
      console.log("Upload complete");
    });

async function getData(authClient, fileId) {
  const version = "v3";

  const drive = google.drive({
    version,
    client: authClient,
  });
  const json = await drive.files.get({
    alt: "json",
    fileId: fileId,
    auth: authClient,
  });

  const media = await drive.files.get({
    alt: "media",
    fileId: fileId,
    auth: authClient,
  });

  const data = {
    name: json.data.name,
    content: media.data,
  };

  return data;
}

exports.copy = async (req, res) => {
  const auth = new google.auth.GoogleAuth();

  const client = await auth.getClient();

  const containingFolder = "folder-name";

  const bucketName = "bucket-name";
  const fileId = "file-id"
  try {
       
    const content = await getData(client, fileId);

    await addData(bucketName, content);
    res.send("Done");
  } catch (err) {
    res.send(err.message);
  }
}
```

Now, this seems to work - the file is added to the bucket but when I open it, it's either corrupted or it has the correct number of pages but all of them are blank. Quite strange. Might I be missing something here?

Let me know if you need any additional information to help me with this.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by shaffeeullah** [comment]
Hi @enahsor ,

It looks like there are two options of where the file could get corrupted:
1. When retrieved from Google Drive
2. When uploaded to Storage

Have you verified that after (1) is complete, the file looks correct?

**Comment by shaffeeullah** [comment]
Hi @enahsor ,

Please re-open with the requested information if youre still seeing this issue
