### ISSUE TITLE
Drop support for Node 10 and make Node 12 the minimal version.

### ISSUE THREAD

**Issue by ddelgrosso1** [googleapis/nodejs-storage#1856]
As a result of Node 10 having gone end of life in April 2021 the decision has been made to move to Node 12 as the minimum supported version. See also: https://cloud.google.com/blog/products/application-development/google-cloud-sdk-moves-nodejs-10-to-maintenance-mode

**Comment by rayfoss** [comment]
https://nodejs.org/en/about/releases/ 12 is EOL as of today as well.
