### ISSUE TITLE
publicUrl method is uri-encoding slashes inside the name

### ISSUE THREAD

**Issue by miguepintor** [googleapis/nodejs-storage#1869]
When the name of a file contains / the publicUrl method returns url which contains some / and some %2F inconsistently

#### Environment details

  - OS: Ubuntu 20.04.3 LTS
  - Node.js version: v16.14.1
  - npm version: 8.5.0
  - `@google-cloud/storage` version: 5.19.1

#### Steps to reproduce

  1. call bucket.file('resources/2022/04/229bcc42b7ab45f4a0c467fe4d8af277.res').publicUrl() with a name containing slashes
  2. the publicUrl method returns url which contains some / and some %2F inconsistently=> https://storage.googleapis.com/a-bucket-name/resources%2F2022%2F04%2F229bcc42b7ab45f4a0c467fe4d8af277.res

Thanks for all your support!

**Comment by shaffeeullah** [comment]
Hi @miguepintor , this is happening on purpose. Only the file name is being encoded. https://github.com/googleapis/nodejs-storage/blob/5f78907a75883cec3fe67204281fb1f9f5a1a03a/src/file.ts#L3309-L3330

The rules surrounding bucket names allow us to safely assume that they will never need to be encoded. Is this causing issues for you in some way?
