### ISSUE TITLE
"ReferenceError: process is not defined" When running in Browser/Deno/WebContainers/Vite

### ISSUE THREAD

**Issue by rayfoss** [googleapis/nodejs-storage#1882]
Thanks for stopping by to let us know something could be better!

1) Is this a client library issue or a product issue? Yes.

2) Did someone already solve this? No.

#### Environment details

  - Node.js version: 16
  - npm version: 7.17
  - `@google-cloud/storage` version: 5.19.2

#### Steps to reproduce

1. Attempt to run the upload from memory example on the browser.

## Expected

Running from the browser should work as long as the user has a service account key.

## Actual

A mysterious dependency on process arises... Why would you need to access the process to write from a JavaScript string.

![image](https://user-images.githubusercontent.com/876076/164278824-c37a7568-9258-42fc-808a-26a52aeeceb7.png)

## Example Code:

Runnable in https://vite.new/vite-ts

```typescript
import { getSecrets } from './secrets'
import { Storage } from '@google-cloud/storage'
import './style.css'

const bucketName = 'my-bucket'
const contents = 'these are my file contents'
const destFileName = `file-${Date.now}.txt`

class UI {
  promise: Promise<void>
  appEl: HTMLDivElement
  storage!: Storage
  gscKey: any
  secrets: any

  constructor() {
    this.appEl = document.querySelector<HTMLDivElement>('#app')!
    this.promise = this.main()
    this.appEl.innerHTML = `<h1>Hello Vite!</h1>`
  }

  async main() {
    this.secrets = getSecrets()
    this.gscKey = this.secrets.GCS_KEY
    this.storage = new Storage({
      projectId: this.gscKey.project_id,
      credentials: this.gscKey
    })
    await this.uploadFromMemory()
  }

  async uploadFromMemory() {
    await this.storage.bucket(bucketName).file(destFileName).save(contents)

    console.log(
      `${destFileName} with contents ${contents} uploaded to ${bucketName}.`
    )
  }
}

new UI()
```

## Related:

- https://github.com/googleapis/gaxios/issues/337
- https://github.com/googleapis/gcs-resumable-upload/issues/347
- https://github.com/googleapis/nodejs-storage/pull/1871

**Comment by shaffeeullah** [comment]
Hi @rayfoss ,

This client library is not currently supported in the browser. We are working toward getting this supported in the future.

**Comment by shaffeeullah** [comment]
I've created a feature request to track this https://github.com/googleapis/nodejs-storage/issues/1883

**Comment by shaffeeullah** [comment]
Hi @rayfoss ,
Have you considered using signed URLs to perform this upload? https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#storage-signed-url-object-nodejs This would allow you to perform this upload using a PUT request.

**Comment by rayfoss** [comment]
> 



> Hi @rayfoss , Have you considered using signed URLs to perform this upload? [cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#storage-signed-url-object-nodejs](https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#storage-signed-url-object-nodejs) This would allow you to perform this upload using a PUT request without needing the client library in the the browser

Thanks for the suggestion, unfortunately this will not work. I built a tool used by employees that's built in and runs on StackBlitz's Node.js [WebContainers](https://github.com/stackblitz/webcontainer-core). It clones git repositories, manipulates them and publishes to APIs... the last thing I need to do is automate the static asset upload process, which apparently can't be done with Google Cloud Storage at the moment.
