### ISSUE TITLE
Reduce the number of transitive dependencies

### ISSUE THREAD

**Issue by IchordeDionysos** [googleapis/nodejs-storage#1888]
The package still includes 78 direct/transitive dependencies, it would be nice if this number could be reduced even further!

I do appreciate the efforts you did and plan to do in #207 and #1743.

But especially when integrated into bigger projects this still adds quite a bit of baggage to the project and more risk for security vulnerabilities (like longer chains to update vulnerable dependency versions).

http://npm.anvaka.com/#/view/2d/%2540google-cloud%252Fstorage
https://bundlephobia.com/package/@google-cloud/storage

**Comment by ddelgrosso1** [comment]
Thank you for opening this issue @IchordeDionysos. As you noted we have taken steps previously to reduce the number of dependencies. Please know that this is also an ongoing effort. I will update this issue accordingly as we move forward.

**Comment by shaffeeullah** [comment]
We have scoped out some dependencies that are reasonable to drop:
- https://github.com/googleapis/nodejs-storage/issues/1916
- https://github.com/googleapis/nodejs-storage/issues/1915
- https://github.com/googleapis/nodejs-storage/issues/1908
- https://github.com/googleapis/nodejs-storage/issues/1907
- https://github.com/googleapis/nodejs-storage/issues/1909
- https://github.com/googleapis/nodejs-storage/issues/1910
- https://github.com/googleapis/nodejs-storage/issues/1911
- https://github.com/googleapis/nodejs-storage/issues/1906

Closing this issue in favor of tracking this work there.
