### ISSUE TITLE
Proposal: Instantiate a File using Public URL

### ISSUE THREAD

**Issue by GabrielBB** [googleapis/nodejs-storage#1898]
**Is your feature request related to a problem? Please describe.**

Right now [File](https://googleapis.dev/nodejs/storage/latest/Bucket.html#file) can only be instantiated using the file name. However, is common for systems to save the entire file url in databases, in these cases, to later delete the file from the bucket you would need to extract the file name (including parent directories) from the public url. Which means that you would have to spend some time thinking how to properly do this and write unit tests for it. I would prefer if the library handles this for me.

 **Describe the solution you'd like**

1 - Switch from `file(name: string, options?: FileOptions): File` to just `file(options: FileOptions): File`

2 - Extend [FileOptions](https://cloud.google.com/nodejs/docs/reference/storage/latest/storage/fileoptions) like:

```typescript
interface FileOptions {
    name?: string,
    publicUrl?: string,
    ...
}
```

3- Extract the name from the public url:

If `name` is not filled, we can proceed and check `publicUrl` -> From `https://storage.googleapis.com/${firebase-project}.appspot.com/images%2Ftest.jpeg` extract just `images%2Ftest.jpeg`, decode it as `images/test.jpeg` and use it as `name`. This would require doing a [split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split): We already know the host is a static `https://storage.googleapis.com` and the bucket name (`${firebase-project}.appspot.com`) we already have it from [here](https://googleapis.dev/nodejs/storage/latest/Storage.html#bucket).

**Example of usage of proposed API**

`file({ name: "images/test.jpeg" })` and `file({ publicUrl: "https://storage.googleapis.com/${firebase-project}.appspot.com/images%2Ftest.jpeg" })`

 **Describe alternatives you've considered**

A backwards compatible way to achieve this would be to leave the API as it is but automatically recognise if `name` is a public url, in this case you would apply the same extraction logic mentioned before.

I can offer myself to open the PR if you guys agree with one solution

**Comment by danielbankhead** [comment]
Implementation idea if we decide to adopt this - this could be a static method on `File`, say `File.from`:
```ts
class File {
  static from (publicUrl: string | URL, options: FileOptions): File {
    // ...
  }
}
```

This way:
- the parent `Bucket` object can be determined and passed to `File#constructor`
- the existing `File#constructor` remains the same
- matches other JS `static from` conventions (e.g. https://nodejs.org/api/buffer.html#static-method-bufferfromarray)

**Comment by GabrielBB** [comment]
> Implementation idea if we decide to adopt this - this could be a static method on `File`, say `File.from`:
> ```ts
> class File {
>   static from (publicUrl: string | URL, options: FileOptions): File {
>     // ...
>   }
> }
> ```
> 
> This way:
> - the parent `Bucket` object can be determined and passed to `File#constructor`
> - the existing `File#constructor` remains the same
> - matches other JS `static from` conventions (e.g. https://nodejs.org/api/buffer.html#static-method-bufferfromarray)

Sounds good

**Comment by danielbankhead** [comment]
Additional implementation note: should support `gs:` URIs as well to satisfy this feature request:
- https://github.com/googleapis/nodejs-storage/issues/2057

**Comment by IchordeDionysos** [comment]
@shaffeeullah 
This is so much needed, we have to many times parts gs:// URLs and everywhere we do it a bit differently (maybe not 100% considering all edge-cases).

Having an easy way to create a File instance would be so helpful to just be able to do:

`storage.file('gs://...')`
or:
`File.from('gs://...')`

**Comment by IchordeDionysos** [comment]
The Python SDK already has a similar function
