### ISSUE TITLE
refactor(deps): Remove `extend` dependency

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/nodejs-storage#1908]
Remove `extend` & `@types/extend` dependencies in favor of native, standardized dependencies.

**Comment by ddelgrosso1** [comment]
There are several places in the code that we utilize the deep option to extend (example [here](https://github.com/googleapis/nodejs-storage/blob/main/src/bucket.ts#L3292). While the shallow cases could be replaced by `Object.assign` the deep cases would require us to either roll our own recursive option, leave extend in place, or remove in favor or something like lodash.

**Comment by danielbankhead** [comment]
Here are a few options worth exploring:
- https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy
- https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
