### ISSUE TITLE
Stream createWriteStream seems to hang since 5.20.0

### ISSUE THREAD

**Issue by loopingz** [googleapis/nodejs-storage#1946]
#### Environment details

  - OS:
  - Node.js version: 14,16,18
  - npm version:
  - `@google-cloud/storage` version: >= 5.20.0

#### Steps to reproduce

This code works with `5.19.x` and breaks with `5.20.x`
```
async test() {
  const file = new Storage().bucket("webda-dev").file("tsconfig.json");
  const stream = fs.createReadStream("./myfile.txt");
  await new Promise((resolve, reject) => {
      stream
        .pipe(
          file.createWriteStream({
            contentType,
          })
        )
        .on("error", reject)
        .on("finish", resolve);
    });
}
```

**Comment by danielbankhead** [comment]
Thanks for filing @loopingz - I'm able to reproduce for an empty file. Would `myfile.txt` be empty in your example?

**Comment by danielbankhead** [comment]
If so, this PR will resolve this issue: https://github.com/googleapis/nodejs-storage/pull/1949

**Comment by danielbankhead** [comment]
Update: let me know if v5.20.4 resolves this for you https://github.com/googleapis/nodejs-storage/pull/1948

**Comment by loopingz** [comment]
I will check but yes my framework creates empty marker files so might be the reason

**Comment by loopingz** [comment]
My local test are successful, now checking with the CI: https://github.com/loopingz/webda.io/pull/220

Thank you for the quick reaction, should I close the issue?

**Comment by danielbankhead** [comment]
Excellent! Good to hear. I'll close for now
