### ISSUE TITLE
v6.0.0 throws exceptions off main thread during upload

### ISSUE THREAD

**Issue by sethvargo** [googleapis/nodejs-storage#1968]
1) Is this a client library issue or a product issue?

This is a bug in @google-cloud/storage client library at v6.0.0.

2) Did someone already solve this?

I could not find an instance.

3) Do you have a support contract?

I'm a Googler.

#### Environment details

  - OS: Reproduces all on OSes
  - Node.js version: v16.14.0
  - npm version: 8.10.0
  - `@google-cloud/storage` version: 6.0.0

#### Steps to reproduce

When uploading an object at a non-existent filepath:

```node
await storage.bucket('bucket').upload('non-existent-file', { destination: 'foo', resumable: true, gzip: true })
```

The error/rejection occurs off the main thread. In the 5.20.5, this issue does not exist.

The easiest way to reproduce this is with a test in mocha (which is how we found it when tests started failing):

```node
try {
  await storage.bucket('bucket').upload('non-existent-file', { destination: 'foo', resumable: true, gzip: true })
} catch(err: unknown) {
  expect(err).to.match('ENOENT')
}
```

Mocha will complain about an exception even though the exception is clearly caught. If you follow the stacktrace, the error is coming from a background stream:

```text
Error: ENOENT: no such file or directory, open 'non-existent-file'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'non-existent-file'
}
```

The exact same tests with v5.20.5 succeeds without modification.

**Comment by danielbankhead** [comment]
Apologies @sethvargo - opened #1969 to resolve this
