### ISSUE TITLE
Multiple errors occurred during the request. Please see the `errors` array for complete details

### ISSUE THREAD

**Issue by himanshuteotia** [googleapis/nodejs-storage#1971]
Error details :

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/10083136/170484129-e23eca6d-1378-4202-9efc-f3403e88f227.png">

Code trowing an error :

<img width="705" alt="image" src="https://user-images.githubusercontent.com/10083136/170484471-fe809475-1ca6-40a6-aba1-97a1d64c11ae.png">

Headers getting in above route 

![image](https://user-images.githubusercontent.com/10083136/170484575-e553ef69-ef92-4bfd-b5ce-2366b300eb28.png)

#### Environment details

  - OS: M1 Mac OS 
  - Node.js version: 10.20.1
  - npm version: 6.14.4
  - `@google-cloud/storage` version: 5.19.0

**Comment by ddelgrosso1** [comment]
Hi @himanshuteotia thank you for opening this issue. A few followup questions, is the data you are streaming always the same size as in the picture? Are you doing multiple uploads concurrently? Are there any conditions under which you successfully upload the data? If you have tried retrying, does it succeed?

**Comment by himanshuteotia** [comment]
1. is the data you are always streaming the same size as in the picture?
No, it depends on the file. 
2.  Are you doing multiple uploads concurrently? 
No, its only one file 
3. Are there any conditions under which you successfully upload the data?
No conditions, As I always get the file on this route, and I have to upload it to gs bucket.
4. If you have tried retrying, does it succeed?
I am not sure what do yo mean but yeah I have tried multiple options like **resumable : false** or the code mentioned here https://gist.github.com/frankyn/58e6715b68a742ca59183c1c6c9619b0 but it didn't work
5. Also, are you using anything like bodyParser on this endpoint?
Yes I am using **bodyParser**

Also want to mention that It works when both the server on the same machine(like on my local computer) but it didn't work whenever I use different machines for both servers.

**Comment by ddelgrosso1** [comment]
Could you try disabling `bodyParser` and see if that works? If I remember correctly, `bodyParser` will already have consumed the stream which would not allow you to then pipe it as in your example code.

**Comment by himanshuteotia** [comment]
Hi, I removed the bodyParser but still getting the same error.

**Comment by ddelgrosso1** [comment]
If it works when both ends are on a local machine, is it possible that you have some networking (proxies, security policies, CORS) in place that might prevent this when going from different machines? I just tested a few versions of the library with the code you provided and did not see any issues myself.

**Comment by ddelgrosso1** [comment]
Do you have a rough idea of what the size range is for these files? Also to double check, have you tried setting `resumable = true` and does the problem persist in that situation?

**Comment by himanshuteotia** [comment]
All files are between 19MB to 25MB, and just now, I have also tried `resumable = true` still no luck :(

**Comment by himanshuteotia** [comment]
I am not sure if this can be helpful, but if you see in this picture the above headers when I am using a different machine, and it doesn't work, and down the headers, it works when I run on the local machine.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/10083136/170538163-878f9a4b-638b-4e50-a1e1-0fd827678da3.png">

**Comment by ddelgrosso1** [comment]
I have been unsuccessful in recreating this issue without further information. As a result, I am going to close this. If there is additional information that might help in recreating please feel free to comment and reopen.
