### ISSUE TITLE
`RequestError: The uploaded data did not match the data from the server.` after updating to v6 when using Firebase Storage Emulator

### ISSUE THREAD

**Issue by sceee** [googleapis/nodejs-storage#1975]
After updating `@google-cloud/storage` to v6.0.1, tests used in combination with Firebase Storage emulator start to fail that passed before.
After updating, the following error is thrown for uploaded files:
`RequestError: The uploaded data did not match the data from the server.`

#### Environment details

  - OS: Windows & Ubuntu
  - Node.js version: 16.14.2
  - npm version: 8.10.0
  - `@google-cloud/storage` version: 6.0.1

#### Steps to reproduce

Precondition:
Use Firebase Storage emulator (`firebase-tools v10.9.2`).

  1. Have a test that saves a file to storage like
```typescript
await myStorageBucket.file(somefilename).save(dataBuffer)
```
and afterwards, checks that the file exists via
```typescript
const fileRef = getStorage().bucket(myStorageBucket).file(somefilename)
const fileExists = await fileRef.exists()
expect(fileExists[0]).to.equal(true)
```
  2. Execute this test with `@google-cloud/storage` v5.20.5 -> Test passes
  3. Update `@google-cloud/storage` to v6.0.1 and execute test again -> Test fails with
```
RequestError: The uploaded data did not match the data from the server.
    As a precaution, the file has been deleted.
    To be sure the content is the same, you should try uploading the file again.
    at C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\build\\src\\file.js:1402:35
    at C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\build\\src\\nodejs-common\\service-object.js:139:13
    at C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\build\\src\\nodejs-common\\util.js:398:25
    at Util.handleResp (C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\build\\src\\nodejs-common\\util.js:164:9)
    at C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\build\\src\\nodejs-common\\util.js:493:22
    at onResponse (C:\\proj\\functions\\node_modules\\@google-cloud\\storage\\node_modules\\retry-request\\index.js:235:7)
    at C:\\proj\\functions\\node_modules\\teeny-request\\src\\index.ts:333:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'FILE_NO_UPLOAD',
  errors: [ null ]
}"}
```

It doesn't matter if I add `{ resumable: false }` to the `save` method when uploading the file. Even with `resumable: false`, the same error occurs.
The uploaded data is pretty small, it's only small JSONs.

**Comment by danielbankhead** [comment]
This is actually an issue within the Firebase storage emulator - opened a PR on your behalf: https://github.com/firebase/firebase-tools/pull/4609

**Comment by sceee** [comment]
Thank you @danielbankhead !

**Comment by danielbankhead** [comment]
Hey @sceee, this fix has been merged in `firebase-tools` and will be available in its next release. Thanks for your patience!
