### ISSUE TITLE
Download method hangs on zero byte files

### ISSUE THREAD

**Issue by peteredhead** [googleapis/nodejs-storage#1991]
#### Environment details

  - OS: Mac OS 12.4
  - Node.js version: 14.18.2
  - npm version: 6.14.15
  - `@google-cloud/storage` version: 6.1.0

#### Steps to reproduce

  1.  Create an empty file (e.g. `touch emptyfile.txt`) and upload it to cloud storage.
  2. Download the file using the code below

```
const storage = new Storage({ retryOptions: { autoRetry: false } });
storage
  .bucket(BUCKET_NAME)
  .file(emptyfile)
  .download({ destination: destFilename })
  .then(() => console.log("Success"))
  .catch(() => console.error("Error"));
```

When the target file has a size of zero bytes, the promise gets stuck in the pending state. It never resolves or throws an error. If using the method as async rather than a promise then the next line will never get called.

From what I can tell, changing the `autoRetry` options don't seem to make any difference.

Thanks,

Pete

**Comment by tritone** [comment]
Thanks for reporting. Zero-byte files are definitely supported so this seems like a bug. @ddelgrosso1 will work on a fix this  week.

**Comment by ddelgrosso1** [comment]
Thank you @peteredhead I have found the source of the issue and should be releasing a fix in the next day or two.
