### ISSUE TITLE
How to use CRC32CValidator in v6

### ISSUE THREAD

**Issue by rhodgkins** [googleapis/nodejs-storage#2003]
Previously this library used external dependencies for the file validation, and in v6 this was changed - how do we use the new validation? 

I see that the (optional) need for `fast-crc32c` has gone now, or can this still be used for quicker validation?

(Also [the docs](https://googleapis.dev/nodejs/storage/latest/global.html#StorageOptions) don't mention `CRC32CValidator` at all).

**Comment by danielbankhead** [comment]
Hey @rhodgkins, by default we provide and utilize a built-in [`CRC32C`](https://googleapis.dev/nodejs/storage/latest/CRC32C.html) instance whenever CRC32C validation is enabled.

This can be overwritten by providing a function that returns an object implementing `CRC32CValidator` (an object with `toString`, `validate`, and `update` methods). Here's some documentation on those methods:

https://github.com/googleapis/nodejs-storage/blob/cb627213adc698c349cd99a0d1205872d6cf7a1b/src/crc32c.ts#L66-L112

Here's an example for using with `Storage`:

```ts
import {CRC32C, Storage} from '@google-cloud/storage';

// A function returning a `CRC32C` instance (a `CRC32CValidator`)
const crc32cGenerator = () => new CRC32C();

const storage = new Storage({crc32cGenerator});
```

Additionally, the `crc32cGenerator` option can be overwritten on the `Bucket` and `File` levels as well:
```ts
import {CRC32C, Storage} from '@google-cloud/storage';
const storage = new Storage();

const myBucket = storage.bucket('my-bucket');
const myFile = myBucket.file('my-file');

// Affecting `myBucket` and new `File` objects generated using `myBucket`
myBucket.crc32cGenerator = () => new CRC32C();

// Only affecting `myFile`
myFile.crc32cGenerator = () => new CRC32C();
```

> I see that the (optional) need for `fast-crc32c` has gone now, or can this still be used for quicker validation?

It can be used when wrapped as a `CRC32CValidator`. In our tests we've seen similar performance between the two - are you experiencing a performance degradation in v6?

> (Also [the docs](https://googleapis.dev/nodejs/storage/latest/global.html#StorageOptions) don't mention CRC32CValidator at all).

I'll create a PR to document this functionality.

**Comment by rhodgkins** [comment]
@danielbankhead This is great, thanks for the explanation 👍

> are you experiencing a performance degradation in v6?

Not at all, my question was more around if it would still be needed / how much code changes would be required from a package update perspective.
I was hoping more so this would be the case (similar performance) so can bin off the extra dependency.
