### ISSUE TITLE
exception thrown outside of main thread when upload fails

### ISSUE THREAD

**Issue by modosc** [googleapis/nodejs-storage#2007]
1) Is this a client library issue or a product issue?

client issue - `@google-cloud/storage@6.2.3`

2) Did someone already solve this?
no but it's _very_ similar to https://github.com/googleapis/nodejs-storage/issues/1968, perhaps the same solution can be applied here?

3) Do you have a support contract?
no

#### Environment details

  - OS: linux
  - Node.js version: 16.x
  - npm version: 8.5.5
  - `@google-cloud/storage` version: 6.2.3

#### Steps to reproduce
unfortunately i can't reliably reproduce it but sometimes we get errors that can't be caught. 

our code:
```js
try {
  await storage.bucket(bucket).file(file).save(data, { resumable: false })
} catch(error) {
 // do something here
}
```

the stack trace
```
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in new ApiError at line 79:15
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in Util.parseHttpRespBody at line 214:38
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in Util.handleResp at line 155:117
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in <anonymous> at line 535:22
/usr/src/app/node_modules/retry-request/index.js in onResponse at line 240:7
/usr/src/app/node_modules/teeny-request/build/src/index.js in <anonymous> at line 157:17
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in runMicrotasks
node:internal/process/task_queues in processTicksAndRejections at line 96:5
```

and the associated network request:
```
POST https://storage.googleapis.com/upload/storage/v1/b/BUCKET/o?uploadType=multipart&name=FILENAME [503]
```

we've seen this ~20 times today

**Comment by ddelgrosso1** [comment]
Thank you for reporting this @modosc. I know you said you are not reliable able to reproduce this but is there any other information you could provide, i.e., does this happen more often on data of a certain size threshold? Any particular time of day when it happens more frequently? How many operations are you performing at a time?

**Comment by modosc** [comment]
this mostly seems to happen in a single endpoint call where we are uploading ~20 different files - each one is around 200kb. 

beyond that there's no pattern to when this occurs.

**Comment by modosc** [comment]
we also get a slightly different version of the stack trace sometimes:
```
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in new ApiError at line 79:15
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in Util.parseHttpRespBody at line 214:38
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in Util.handleResp at line 155:117
/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in <anonymous> at line 535:22
/usr/src/app/node_modules/retry-request/index.js in onResponse at line 240:7
/usr/src/app/node_modules/teeny-request/build/src/index.js in <anonymous> at line 157:17
node:internal/process/task_queues in processTicksAndRejections at line 96:5
```

note this one is missing the `/usr/src/app/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js in runMicrotasks` line

**Comment by modosc** [comment]
@ddelgrosso1 thanks for the suggestion, we're adding that option now.

**Comment by modosc** [comment]
it turns out this wasn't occurring outside of the main thread after all and was just a bug in how we handled error reporting. sorry for the noise!

**Comment by ddelgrosso1** [comment]
Thank you for the update @modosc.
