### ISSUE TITLE
samples: update bucketMetadata

### ISSUE THREAD

**Issue by thaaaarun** [googleapis/nodejs-storage#2033]
Thanks!

The bucketMetadata.js sample incorrectly prints bucket metadata because it does not account for nested Objects. In particular, the `cors`, `iamConfiguration` and `lifecycleRules` properties have their values printed as `Array` or `Object` rather than the contents of the Array/Object. 
I updated to print the metadata as a JSON string instead.

**Comment by shaffeeullah** [comment]
fixed by https://github.com/googleapis/nodejs-storage/pull/2031
