### ISSUE TITLE
 File not showing when used express-fileupload

### ISSUE THREAD

**Issue by melitus** [googleapis/nodejs-storage#2054]
- I am trying to upload files to google cloud storage using express-fileupload. I set the config for the express-fileupload as shown below
```
app.use(fileUpload({
    useTempFiles : true,
    tempFileDir : '/tmp/'
}));
```

- This is the code I have used for the upload operation
```
const uploadToGCS = async (
  file: Buffer,
  fileName: string,
  mimeType: string,
): Promise<string> => {
  const storage = new Storage({
    keyFilename: config.googleBucket.serviceKeyPath,
  });
  const bucket = storage.bucket(config.googleBucket.publicBucket);
  const gcsFileName = `${Date.now()}-${fileName}`;
  // Create a new blob in the bucket and upload the file data.
  const fileToUpload = bucket.file(gcsFileName);
  const fileStream = fileToUpload.createWriteStream({
    metadata: {
      contentType: mimeType,
    },
    resumable: false,
  });
  return new Promise((resolve, reject) => {
    fileStream.on('finish', () => {
      const publicUrl = getPublicUrl(encodeURIComponent(fileToUpload.name));
      fileToUpload
        .makePublic()
        .then(() => resolve(publicUrl))
        .catch(reject);
    });
    fileStream.on('error', (ex) => {
      Logger.log(ex, 'GCS');
      return reject;
    });
    fileStream.end(file);
  });
};
```
- On pdf upload, I got this error- https://storage.googleapis.com/temp-hold-eu/1661769692085-impatient-js-preview-book.pdf. On image upload, I got this error -  https://storage.googleapis.com/temp-hold-eu/Z0cuwDoD6-Screenshot%25202022-08-05%2520at%252017.21.28.png

**Comment by shaffeeullah** [comment]
@melitus I'm not able to view the links you sent. Can you re-send the errors?

**Comment by shaffeeullah** [comment]
Hi @melitus ,

Thanks for reaching out! I'm unable to reproduce this issue. I've tried running this code on the latest version of the library with both an image and a pdf passed in under the `file` parameter. Is this code failing for you for all files? Or just some files? What version of the library are you on? Are you sure that your file path is correct for creating your `file` buffer? If I try to upload an image with a file path that's incorrect, I get the result that you get on your `png` link. I'd also appreciate any other information you can give me that might be useful in reproducing this issue.

**Comment by melitus** [comment]
@shaffeeullah Because the express-fileupload configuration above, this is the incoming file structure below

```
files: {
    'attachment-1': {
      name: 'Screenshot 2022-08-04 at 20.43.08.png',
      data: <Buffer >,
      size: 358128,
      encoding: '7bit',
      tempFilePath: '/tmp/tmp-1-1661525832015',
      truncated: false,
      mimetype: 'image/png',
      md5: '7f9578f42b7467b42437ddbfc5245e2d',
      mv: [Function: mv]
    },
    'attachment-2': {
      name: 'Screenshot 2022-08-03 at 14.10.25.png',
      data: <Buffer >,
      size: 124444,
      encoding: '7bit',
      tempFilePath: '/tmp/tmp-2-1661525832022',
      truncated: false,
      mimetype: 'image/png',
      md5: '9e86e5c450f58a6985b49e32d3a89ebc',
      mv: [Function: mv]
    }
  }
}
```

What I passed as a file is the value of the `tempFilePath` which is the representation of the file. Do I need to pass another thing along with that

**Comment by shaffeeullah** [comment]
Hi @melitus ,

It looks like you're using the wrong API. It seems like you're passing the path to [createWriteStream](https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream), but it takes the data itself. [bucket.upload](https://googleapis.dev/nodejs/storage/latest/Bucket.html#upload) takes a file path.

**Comment by shaffeeullah** [comment]
Awesome!

**Comment by shaffeeullah** [comment]
It looks like you're trying to access an object that it cannot find. I noticed the message has two `//` in it. Is that path correct? 
```
 "message": "No such object: temp-hold-eu//tmp/tmp-18-1662127588163"
```

**Comment by melitus** [comment]
This is the file I passed to the `bucket.upload `function ` /tmp-18-1662127588163`.  It is the tempFilePath which is the path to the temporary file in case` useTempFiles` option of express-fileupload was set to true. I tested it on Cloudinary to confirm whether the temp file exists, and it works well.

**Comment by melitus** [comment]
I have been able to get it work but getting this error`.https://storage.googleapis.com/temp-hold-eu/96d5a3b7-7e0c-425e-9380-e0174fe1ac9c-Screenshot%202022-08-03%20at%2014.10.25.png`

How do I make it public via the code
