### ISSUE TITLE
Memory leak observed in Jest tests when calling bucket.exists()

### ISSUE THREAD

**Issue by wimagguc** [googleapis/nodejs-storage#2059]
#### Environment details

  - OS: macOS, Linux
  - Node.js version: 16.17.0
  - npm version: 8.15.0
  - `@google-cloud/storage` version: 6.4.1

#### Steps to reproduce

  1. Provide credentials for the sample script below
  2. Run the provided tests using jest: `node ./node_modules/.bin/jest --detectLeaks sample.ts`
  3. Observe Jest's complaint

#### Description

`NOTE` using a real `Storage` or the GCS simulator makes no difference
`NOTE` run jest with `--watch` flag and rerun the suite to observe the heap increase
`NOTE` any call on Bucket objects (`exists()`, `.delete()` will cause the heap increase, not only exists())

A minimal script to reproduce the `--detectLeaks` crash. Notice that the two test in this suite are the same apart from the two "leaky" lines — the heap will start rising as soon as the second test runs, and the suite will crash with `--detectLeaks`.

```
import { Storage } from "@google-cloud/storage";

const storage = new Storage(...);

describe("Leaky Bucket", () => {
  it("everything works just fine", async () => {
    const bucket = storage.bucket("bucketName");
    const bucketFile = bucket.file("objectName");
    expect(bucketFile).not.toEqual(undefined);
  });

  it("crashes when --detectLeaks is used", async () => {
    const bucket = storage.bucket("bucketName");
    const bucketFile = bucket.file("objectName");
    expect(bucketFile).not.toEqual(undefined);

    // The Leak
    const [objectExists] = await bucketFile.exists();
    expect(objectExists).not.toEqual(undefined);
  });
});
```

**Comment by danielbankhead** [comment]
Thanks for filing @wimagguc, while I'm able to reproduce the `jest` bug, I'm not seeing if there's an actual memory leak. I've spent an hour or so looking into this, but haven't spotted anything that looked out of place.

Could you point to any particular parts of the code base to narrow the scope? Or, do you see any particular objects not being cleaned up after?

Also, I see `jest` still has `--detectLeaks` as experimental feature.

**Comment by wimagguc** [comment]
Thanks for jumping on this super quickly @danielbankhead, really appreciate the help!

First things first, it's worth running `jest` with `--watch` and looking at the heap size. That gives a little extra insight into how much data is retained, while `--detectLeaks` is admittedly experimental and a little flaky (it made it easier to explain the issue though :))

As for running it outside `jest`, I have this tiny piece of code that keeps running forever:

```
import { Storage } from "@google-cloud/storage";

const functionToTest = () => {
  const storage = new Storage(...);

  const bucket = storage.bucket("bucketName");
  const bucketFile = bucket.file("objectName");

  bucketFile.exists().then((response) => {
    const [objectExists] = response;
    console.log(objectExists);
  });
};

setInterval(functionToTest, 1000);
```

Taking snapshots every minute or so, I can see the allocations keep ever increasing:

<img width="968" alt="between-snapshots-2" src="https://user-images.githubusercontent.com/349687/188744272-fda2d167-8c11-4e8c-8a42-121ea7c3c9b6.png">

The extra allocations don't tell me much, but they are all under `compiled` code (with `@google-cloud/storage` being the only import in the file) and they all look pretty consistent:

<img width="967" alt="between-snapshots-3" src="https://user-images.githubusercontent.com/349687/188744870-7f0e97d0-4aa3-453c-82cb-336ba0e9d3b4.png">

Digging into allocations further I can see this, but it might be a red herring:

<img width="964" alt="api-errors" src="https://user-images.githubusercontent.com/349687/188746386-5a581b5e-3816-4d67-b6c3-75e76cdc25b6.png">

**Comment by danielbankhead** [comment]
Isolating this down to the following (to reduce noise from `Storage`, `Bucket`, & `File` creation):
```ts
import {Storage} from '@google-cloud/storage';

const storage = new Storage();
const bucket = storage.bucket('...');
const file = bucket.file('test-file');

async function functionToTest() {
  const results = await file.exists();
  console.dir({results});
}

setInterval(functionToTest, 1000);
```

I'm seeing a slight, non-alarming buildup (in the order of bytes/second in Chrome DevTools) and it's unclear if it's this library directly.

> Digging into allocations further I can see this, but it might be a red herring:

I agree, the `ApiError` in this screenshot & context would occur if a file doesn't exist.

Let me know if you see something in particular that is leaking; `(compiled code)` could be the library or any dependency.

**Comment by defunctzombie** [comment]
> Isolating this down to the following (to reduce noise from `Storage`, `Bucket`, & `File` creation):

Are these removed because they are certain not to be any source of leaked memory?

Is it only the exists check that we believe is at fault? @wimagguc in your interval example, if you remove the exists check but keep the newly created objects is memory stable?

**Comment by danielbankhead** [comment]
> > Isolating this down to the following (to reduce noise from `Storage`, `Bucket`, & `File` creation):
> 
> Are these removed because they are certain not to be any source of leaked memory?

Yes, referencing the "everything works just fine" test from the first example.

> 
> Is it only the exists check that we believe is at fault? @wimagguc in your interval example, if you remove the exists check but keep the newly created objects is memory stable?

Other API calls, such as `save` and `delete`, produce the same behavior.

**Comment by danielbankhead** [comment]
Circling back; it's unclear if this is directly library related and after investigating it doesn't appear to be a significant amount of data (possibly some request caching somewhere that gets cleaned up on subsequent requests).

Thanks for filing this issue - we will continue to monitor for leaks in the future.
