### ISSUE TITLE
File not readable(no content appended)

### ISSUE THREAD

**Issue by deepakgupta-unthinkable** [googleapis/nodejs-storage#2064]
File is uploading but not readable

Followed below step with latest download
cd samples
npm install
cd ..
node samples/streamFileUpload.js mybucket myfile

Thanks
Deepak
[TestDeepak.pdf](https://github.com/googleapis/nodejs-storage/files/9538510/TestDeepak.pdf)

**Comment by danielbankhead** [comment]
Hey @deepakgupta-unthinkable, I'm unable to replicate this issue.

Please answer more details from the bug report template:
```
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-storage/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/storage` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

```

**Comment by deepakgupta-unthinkable** [comment]
Hi @danielbankhead 

Here is what I followed
Download the latest code

Now follow the below steps to test the sample code provided

cd samples
npm install
cd ..
node samples/streamFileUpload.js [mybucket] [myfilename]

The file is getting uploaded but it is not having any content on the pdf generated. When I download the file it is showing file cannot be opened.

Sample file attached 

Thanks
Deepak
[TestDeepak.pdf](https://github.com/googleapis/nodejs-storage/files/9572304/TestDeepak.pdf)

**Comment by danielbankhead** [comment]
@deepakgupta-unthinkable again, please answer the following:

```
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-storage/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/storage` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

```

**Comment by deepakgupta-unthinkable** [comment]
@danielbankhead 

1) Is this a client library issue or a product issue?
Library issue.

2) Did someone already solve this?
  - Search the issues already opened:  yes but it is closed
  - Search the issues on our "catch-all" repository: here is similar link https://github.com/googleapis/nodejs-storage/issues/1712
  - Search or ask on StackOverflow (engineers monitor these tags):Not found

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: v14.10.0
  - npm version:6.14.8
  - `@google-cloud/storage` version: 6.4.2

#### Steps to reproduce

  1. Download the latest code 
  2.  cd samples
 3.   npm install
 4.   cd ..
 5.   node samples/streamFileUpload.js [mybucket] [myfilename]
It generates the PDF but no content inside the pdf and also it shows an error when you open the pdf file. Try opening the one attached here.

[TestDeepak.pdf](https://github.com/googleapis/nodejs-storage/files/9576555/TestDeepak.pdf)

Hope this is enough to reproduce.

Thanks
Deepak

**Comment by danielbankhead** [comment]
Thanks @deepakgupta-unthinkable, you will want to use this sample to upload a file: https://github.com/googleapis/nodejs-storage/blob/main/samples/uploadFile.js

We will make some modifications so that this sample is clearer while remaining uniform with the other language implementations:
- https://cloud.google.com/storage/docs/streaming#stream_an_upload
