### ISSUE TITLE
Node's server (integrated with firebase) keep crashing because error "A bucket name is needed to use Cloud Storage"

### ISSUE THREAD

**Issue by tphduy** [googleapis/nodejs-storage#208]
I am using a Firebase admin in Node.js and I am not going to use Cloud Storage in my own server, firebase app initialization working well before but it crash today because of error "A bucket name is needed to use Cloud Storage".
So I tried to integrate cloud storage to fix it but it did not work.
      const admin = require('firebase-admin')
      const serviceAccount = require('./letseat-dd347-firebase-adminsdk-op4zs-3ad050a59d.json')
      admin.initializeApp({
       credential: admin.credential.cert(serviceAccount),
            storageBucket: 'letseat-dd347.appspot.com'
     })

#### Environment details

  - OS: MacOS High Sierra
  - Node.js version: 10.2.1
  - npm version: 5.6.0
  - Firebase version: 5.12.1
  - `@google-cloud/storage` version:  lasted

#### Steps to reproduce

  1. npm install
  2. nodemon or node app.js or nom start.

=> Crashing because of error: A bucket name is needed to use Cloud Storage.
<img width="689" alt="screen shot 2018-05-29 at 6 43 42 pm" src="https://user-images.githubusercontent.com/16264018/40656923-3e7984ce-6370-11e8-9e77-9b4b223af249.png">

**Comment by stephenplusplus** [comment]
Hey @tphduy, this sounds like an issue for `firebase-admin`. Please try over here: https://github.com/firebase/firebase-admin-node/issues/new.
