### ISSUE TITLE
Sensitive information attached to exception for ENOTFOUND/ECONNRESET errors

### ISSUE THREAD

**Issue by zachary-povey** [googleapis/nodejs-storage#2080]
1) Is this a client library issue or a product issue?

Client Lib

2) Did someone already solve this?

Not as far as I can see

#### Environment details

  - OS: MacOS Monterey 12.5.1
  - Node.js version: v16.13.0
  - npm version: 8.1.0
  - `@google-cloud/storage` version: 6.5.2

#### Steps to reproduce

  1. Ensure GCP application default creds set up
  2. Disconnect internet
  3. Run:
 ```
import { Storage } from "@google-cloud/storage"

async function main() {
  // Creates a client using Application Default Credentials
  const storage = new Storage()
  const allBuckets = await storage.getBuckets()
  console.log(allBuckets)
}

main().catch((e) => console.log(JSON.stringify(e, null, 4)))

```
You will see an exception, presumably from a lower level http lib which details everything about the request including the client secret. 

The actual error I saw in the wild was an ECONNRESET which similarly dumped the whole request info on to the exception, which in that case meant the authorization header. This presumably is the case for other TCP / connection errors also, it does not occur for http requests which complete but have a 4xx/5xx response code (here an exception is raised, but it contains no request information).

Labelling this as a bug may be a bit strong, but for us what this ended up meaning was that we exported the exception as a log record into elastic and displayed it in kibana for anyone with access to see the authorization token which isn't great. It will be a common pattern for people to log out these kinds of exceptions so on balance it feels like the GCS lib should obfuscate sensitive info when raising such errors.

**Comment by ddelgrosso1** [comment]
Thank you for the report @zachary-povey. I will do some investigation and get back to you.

**Comment by ddelgrosso1** [comment]
@zachary-povey I did some investigation into this. As you noted the details of the error are bubbling up from the HTTP libraries used when making the API calls. Currently the storage library does not do any additional processing / manipulation on the error details. 

I don't believe that trying to obfuscate these at the library level is something we want to do as it will add complexity with additional flags / fields to try and allow for flexibility to handle all use cases. I think that this is better handled in application space before ingesting into logging / data collection systems.

However, if there is strong support from users it is definitely something we would reconsider in the future.

**Comment by ddelgrosso1** [comment]
I am going to close this issue for the time being. If there is strong support from the community to have this as a feature please feel free to reopen and we will reconsider doing this at the library level.
