### ISSUE TITLE
ERR_MULTIPLE_CALLBACK on file.download()

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [googleapis/nodejs-storage#2082]
1) Is this a client library issue or a product issue?
yes

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-storage/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
no

3) Do you have a support contract?
no

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Win10 21H2
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `@google-cloud/storage` version: 6.5.2

#### Steps to reproduce

  Try to download a file:
```
  try {
    await file.download({
      destination: destination
    })
  } catch(e) {
    console.log(e);
  }
```

As the result catching error ERR_MULTIPLE_CALLBACK

**Comment by ddelgrosso1** [comment]
Hi @Aliaksandr-Kasko-JazzTeam thank you for opening an issue. Can you provide us with a bit more information, how often are you seeing this error? Was the code you provided previously working in a different version of the library? Do other operations (i.e. upload) work correctly?

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
Hi, @ddelgrosso1.
1. I see this error every time with this mentioned version of library.
2. The code was working with previous versions of library (now I tried with 6.5.0).
3. I can't try other operations like upload because our project is very complex (first we download a file, then we make computations, at last we upload another computed file).

**Comment by ddelgrosso1** [comment]
I also tested this in a Windows 10 environment but did not see the issue. @Aliaksandr-Kasko-JazzTeam if you can provide the information from my previous comment I will investigate further.

**Comment by ddelgrosso1** [comment]
Thanks @amerej we believe we have found the cause of this issue and we will be releasing a fix shortly.

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@ddelgrosso1 sorry for my long response and big thanks for fix. Now it works for me

**Comment by ddelgrosso1** [comment]
Thanks for letting me know @Aliaksandr-Kasko-JazzTeam. Glad this resolved your issue.
