### ISSUE TITLE
Posting object to Google Cloud Storage doesn't replace ${filename} variable

### ISSUE THREAD

**Issue by husain-b** [googleapis/nodejs-storage#2084]
npm package name : @google-cloud/storage
version : 6.5.2

I'm trying to create a signed policy for users to upload their files on Google Cloud Storage.

The Issue i'm facing here is with the filename, i want the user to provide the filename at the time of the upload, as mentioned in the official GCS documentation that you can provide filename as ${filename} if you want it from the user, this doesn't work as i m getting the following error :

```
<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>InvalidPolicyDocument</Code>
    <Message>The content of the form does not meet the conditions specified in the policy document.</Message>
    <Details>Failed condition: {"key":"${filename}"}</Details>
</Error>
```
Request i'm trying to make : 

```
curl --location --request POST 'https://storage.googleapis.com/some-bucket/' \
--form 'key="test.pdf"' \
--form 'x-goog-date="20221015T212358Z"' \
--form 'x-goog-credential="credential"' \
--form 'x-goog-algorithm="GOOG4-RSA-SHA256"' \
--form 'policy="policy"' \
--form 'x-goog-signature="signature"' \
--form 'file=test.pdf"'

```

My Node.js Code for generating policy from GCS :

```
const { Storage } = require('@google-cloud/storage');
const storage = new Storage();

generateSignedPolicy = () => {

        const bucket = 'some-bucket';
        const file = storage.bucket(bucket).file("${filename}");

        const options = {
          expires: Date.now() + (1000 * 300),
          conditions : [
            { bucket : bucket },
          ]
        };

        return new Promise((resolve, reject) => {
            file.generateSignedPostPolicyV4(options)
            .then(([res]) => resolve(res))
            .catch(error => reject(error))
        })
    } 

```

Policy generated from above code : 

`
{
  "url": "https://storage.googleapis.com/some-bucket/",
  "fields": {
    "key": "${filename}",
    "x-goog-date": "20221015T212358Z",
    "x-goog-credential": "credential",
    "x-goog-algorithm": "GOOG4-RSA-SHA256",
    "policy": "policy",
    "x-goog-signature": "signature"
  }
}
`

**Comment by husain4598** [comment]
@ddelgrosso1 is anyone looking into this?

**Comment by ddelgrosso1** [comment]
Hi @husain4598 thank you for opening this issue. I will run a few tests in my environment to attempt to recreate this and let you know what I find.

**Comment by husain4598** [comment]
ok @ddelgrosso1 , thanks.

**Comment by ddelgrosso1** [comment]
Hi @husain-b I tested this out today. In your `curl` command try replacing `--form 'key="test.pdf"'` with `--form 'key="${filename}"'. With this change I was successful in making the request.

**Comment by husain-b** [comment]
hi @ddelgrosso1 it works with ${filename} but i'm using ${filename} as a placeholder for filenames that i want to use while uploading, it should replace ${filename} with the key that i'm providing, in my example 'test.pdf', you can read about this feature from this doc : https://cloud.google.com/storage/docs/xml-api/post-object-forms 
Check the key in the form fields section. 
"The [name of the object](https://cloud.google.com/storage/docs/objects#object-names) that you are uploading. You can also use the ${filename} variable if a user is providing a file name"

**Comment by ddelgrosso1** [comment]
@husain-b server side is where the replacement will occur. It will replace `${filename}` with the value you provide in the file argument. However, you need to still provide `key=${filename}` as it is part of the policy. 

So in your example the server will do a replacement with 'test.pdf' which was provided in `file=test.pdf`.

**Comment by husain-b** [comment]
okay, so name of the file that we are uploading gets replaced. Actually in S3 we provide the filename in the key itself, so was expecting same behaviour here, anyway thanks @ddelgrosso1 for clearing this out for me.
