### ISSUE TITLE
Improvements to SignedURL Function has broken CNAME compatability

### ISSUE THREAD

**Issue by AJCStriker** [googleapis/nodejs-storage#210]
#### Environment details

  - OS: Alpine Linux
  - Node.js version: 
  - npm version: 9.4.0
  - `@google-cloud/storage` version: 1.7.0

#### Steps to reproduce

  1. Attempt to use File.getSignedURL with a CNAME'd bucket
  2. Visit the URL and receive and error with code: "SignatureDoesNotMatch"

This is distinct from previously reported errors that are similar in name in that the URL worked prior to the change shipped in 1.7.0 (https://github.com/googleapis/nodejs-storage/pull/169). It appears superficially that the bucket name should not be included in the URL, that is to say:

**Correct Value**:
 https://cname.mygcloudproject.google/myfileuuid?GoogleAccessId=etc

**Erroneous value generated by 1.7.0 release**: https://cname.mygcloudproject.google/cname.mygcloudproject.google/myfileuuid?GoogleAccessId=etc

I'm happy to submit a PR if the maintenance team would prefer but the original author may have better insight into how to repair this functionality.

Thanks!

**Comment by stephenplusplus** [comment]
Yes, that does indeed look like an accident. Thank you for catching it. A PR would be awesome :)
