### ISSUE TITLE
feat: `Bucket#getFiles` Filtering

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/nodejs-storage#2119]
It would be cool if `Bucket#getFiles` offered a `filter` option to offer client-side filtering.

Here's what that interface could look like:
```ts
import {GetFilesOptions, File} from '@google-cloud/storage';

// Modify `GetFilesOptions` to look like this
interface GetFilesOptionsWithFilter extends GetFilesOptions {
  filter?: (file: File) => boolean
}
```

This way customers can pass a filter, like this:
```ts
const [images] = await storage.bucket(config.bucket).getFiles({
  prefix: 'media/', // storing mixed media using this prefix
  filter: f => /^image\//.test(f.metadata.contentType) // only retrieve images
});
```

We could also rename this to `clientFilter`/`clientSideFilter`/`localFilter` to clarify this is client-side filtering and to not conflict with the backend if the service offered a `filter` option.

**Comment by danielduhh** [comment]
Creating an internal request to add advanced filtering to ListObject. Closing this out
