### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': member signal is not of type AbortSignal

### ISSUE THREAD

**Issue by Prat1143** [googleapis/nodejs-storage#2125]
#### Environment details

  - OS: Windows 10
  - Node.js version: v14.17.0
  - npm version: 6.14.13
  - `@google-cloud/storage` version: 6.8.0

#### Steps to reproduce
I am trying to upload images to the google cloud storage bucket from my electron app.

Case 1
`
const { Storage } = Cloud
const GCP_BUCKET_NAME = storage.bucket("bucket-name")

const uploadFile = (filePath, fileName) => {
 GCP_BUCKET_NAME.upload(`${fileName}.jpg`, function (err, data) {
    if (err) {
      console.log("IMAGE ERRRO => ", err)
      throw err;
    }
    console.log(`File uploaded successfully. ${data.Location}`);
  })
}

uploadFile(imgPath, imgName);
`

Case 2
`
  const file = GCP_BUCKET_NAME.file(fileName);

  fs.createReadStream(filePath)
  .pipe(file.createWriteStream({ gzip: true }))
  .on('error', function(err) {
    console.log("onerr=========",err)
  })
  .on('finish', function() {
    console.log("onfinish=========")
    // The file upload is complete.
  });
`

On calling the uploadFile function get the error - "TypeError: Failed to execute 'fetch' on 'Window': member signal is not of type AbortSignal" for both cases.

**Comment by ddelgrosso1** [comment]
Hi @Prat1143 thank you for opening this issue. I'm not all that familiar with Electron apps but my understanding is that they run in a browser on the desktop is that accurate? If so, unfortunately we do not currently support browser based usage of the storage client. However, if you have a server side component I can offer a few alternatives that might be useable in this scenario.

**Comment by ddelgrosso1** [comment]
Hi @Prat1143 I wanted to circle back on this issue. If you are attempting to utilize the above code in a browser context (Chromium) direct usage of the library is not currently supported. If you have a node backend I would suggest generating a [signed url](https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers) and utilizing the resultant URL on the client side to upload the files. I am going to close this issue. If I have misunderstood and this error is occurring in a node environment please feel free to reopen.
