### ISSUE TITLE
`service-object.d.ts: export declare type Metadata = any;`

### ISSUE THREAD

**Issue by iiian** [googleapis/nodejs-storage#2127]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

`Metadata` has no type information. This is slightly unsettling, because if I want to get the `generation` number after creating a file, I have to type-coerce an `any`.

For example:

```typescript
// node_modules/@google-cloud/common/build/src/service-object.d.ts (L16):  export declare type Metadata = any;
// node_modules/@google-cloud/common/build/src/service-object.d.ts (L17):  export declare type MetadataResponse = [Metadata, r.Response];
// node_modules/@google-cloud/common/build/src/service-object.d.ts (L168): File.getMetadata(options?: GetMetadataOptions): Promise<MetadataResponse>; 
const [metadata] = await my_file.getMetadata();
// metadata is typed as `any`
```

 **Describe the solution you'd like**

Better type information on metadata

**Comment by ddelgrosso1** [comment]
Hi @iiian thank you for opening this issue. We have plans to work on this in the future and it is currently being tracked by #1817. I am going to close this issue as a duplicate.
