### ISSUE TITLE
not able to store metadata when calling file.save

### ISSUE THREAD

**Issue by vadimMv** [googleapis/nodejs-storage#2134]
Hi ,

#### Environment details

  - OS: Cloud Foundry
  - Node.js version: ^14.0.0
  - npm version: 6.14.8
  - `@google-cloud/storage` version: 6.9.0

#### Steps to reproduce
  we are  trying to  add metadata when calling file.save , but metadata is not available when calling fetch

```js
async function insert(record) {
    const file = client.file (record.key);
    const options = {
        metadata:{dtserviceinstanceid:'777'},
        resumable: false
    };
    await file.save(record.value,options);
}


async function fetch(fileName) {
    let file = await client.file(fileName).download();
    const [metadata]  = await client.file(fileName).getMetadata();
    console.log(metadata.dtserviceinstanceid); // this is  undefined
}
```
Thanks!

**Comment by shaffeeullah** [comment]
Have you confirmed that the `file.save` call is succeeding?

**Comment by vadimMv** [comment]
Hi @shaffeeullah ,

It is already resolved thanks !!
I have another question if possible to get file metadata and file content in a single request like the old SDK version 

const file = client.file(key);
 file.download()
      .then((result) => {
        const fileMetadata = file.metadata.metadata; // here metadata exist
});

In new version 6.9.0 I should do 2 request to object store
 
  const file = await client.file(fileName).download();
 const [metadata]  = await client.file(fileName).getMetadata();

thanks!

**Comment by vadimMv** [comment]
Hi @shaffeeullah 

We want to upgrade sdk version in our project from 3.0.2 to 6.9.0

It looks like required making two requests to the object store to get file content and metadata =>

const file = await client.file(fileName).download();  // get content
const [metadata] = await client.file(fileName).getMetadata();  // get metadat 

In 3.0.2 one request was enough 

Is it possible to do this in 6.9.0 per a single request?
I didn't find examples, two request looks expensive for our runtime.

Thank you

**Comment by shaffeeullah** [comment]
Hi @vadimMv ,

In the latest version of the library, you will have to make the call to `getMetadata` explicitly. It shouldn't be any more expensive, as [3.0.2 used to call `getMetadata` under the hood](https://github.com/googleapis/nodejs-storage/blob/74332da5ddb2d42a0447f6f5ba9c2ae9cd6f103c/src/file.ts#L1345
). It'll work out to be the same.

Just curious, what motivated the upgrade from 3.0.2 to 6.9.0? Is there a certain feature or reliability improvement that you're particularly interested in?

**Comment by vadimMv** [comment]
Hi @shaffeeullah 

We have requirement to update of all dependencies in the project.
Thank you for help
