### ISSUE TITLE
Trivial question: were you build each language specific GCS SDK from scratch?

### ISSUE THREAD

**Issue by MadhuPolu** [googleapis/nodejs-storage#2148]
Hi,

if you don't mind, I'm curious to know how you built the language specific GCS SDKS, were you build each language SDK from the scratch or are you using any tool to transform a common code base into a language specific SDKs?

Thanks,
Madhu

**Comment by ddelgrosso1** [comment]
Hi @MadhuPolu it is a mixture of both. For example, this library (storage), is handwritten for all the languages we support. Other SDKs, for example https://github.com/googleapis/google-cloud-node, are mostly autogenerated based on API documentation (discovery docs, protos, etc...). One of the tools we utilize to accomplish this can be seen [here](https://github.com/googleapis/gapic-generator-typescript).

**Comment by MadhuPolu** [comment]
Got it @ddelgrosso1, thank you so much!
