### ISSUE TITLE
Unable to understand the error message

### ISSUE THREAD

**Issue by vr001** [googleapis/nodejs-storage#215]
I am using firebase cloud functions to copy files from one bucket to another and ran into the below error.

`Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read'`

I did search for it and i couldn't get any lead on it. Will be great, if any of you can give some hint. Thanks.

**Comment by stephenplusplus** [comment]
I believe this means we lost our connection to the server, such as when a network connection is lost. I believe we automatically retry these types of errors, but to be sure, can you share the version of the library you're using as well as the code that resulted in the error?

**Comment by Alappin** [comment]
I have been experiencing the same issue with a cloud function triggered from pubsub that tries to delete a file in cloud storage. Error message:

`Error: read ECONNRESET\n at exports._errnoException (util.js:1020:11)\n at TLSWrap.onread (net.js:580:26)`

**Comment by fhinkel** [comment]
@Alappin, is it possible to stage a small reproduction codebase?

**Comment by stephenplusplus** [comment]
Thanks for the update. I think that means that it's a matter the user can resolve, should they run into this, by making sure the GCF callback isn't called until after a long-running operation has resolved.
