### ISSUE TITLE
`file.acl.get` malformed request if `entity` is not provided

### ISSUE THREAD

**Issue by theGOTOguy** [googleapis/nodejs-storage#2159]
#### Environment details

  - OS:  Alpine
  - Node.js version:  18.12.0
  - npm version:  8.19.2
  - `@google-cloud/storage` version:  6.9.0

#### Steps to reproduce

1.  Create a file in a bucket.
2.  Run 
```
let fileAcls = [];
await file.acl.get().then((data) => {fileAcls = data[0]});
console.log(fileAcls);
```
3.  Note that, while entity ([a required option!](https://github.com/googleapis/nodejs-storage/blob/9741a7a2acb2d4b75020d79e34a7d661ab866c63/src/acl.ts#L42)) was not provided, we listed all ACLs for the file.
4.  Change your bucket to requester pays.
5.  Run
```
let fileAcls = [];
await file.acl.get({userProject: "YOUR_PROJECT_HERE"}).then((data) => {fileAcls = data[0]});
```
6.  Note malformed request error.

The reason for this is [here](https://github.com/googleapis/nodejs-storage/blob/main/src/acl.ts#L719).  If `entity` is not provided but any other option is, then our path is `/undefined`.  On the other hand, if no options at all are provided, `entity` effectively defaults to `''`.  The issue can straightforwardly be worked around by providing the option `{entity: ''}`.

I propose one of two solutions:
1.  If entity is not provided, default `entity` to empty string.  This effectively makes `entity` not a required field.
2.  Enforce `entity` as a required field.  Fail `file.acl.get(...)` if `entity` is not provided.  Document that users wishing to retrieve all ACLs should pass  `{entity: ''}`.

**Comment by ddelgrosso1** [comment]
Thank you for opening an issue @theGOTOguy. I am assuming you are attempting this from a JavaScript application and not TypeScript? When I attempt this in a TypeScript I'm not even able to compile due to the following:

```Overload 1 of 3, '(options?: GetAclOptions | undefined): Promise<GetAclResponse>', gave the following error.
    Argument of type '{ userProject: string; }' is not assignable to parameter of type 'GetAclOptions'.
      Property 'entity' is missing in type '{ userProject: string; }' but required in type 'GetAclOptions'.```
      
 Additionally in looking at the [JSON API docs](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/get) this is a documented required field. We generally shy away from adding additional error checking on top of what the API returns. 
 
 However, it does appear that the docs for ACL are missing from the [client docs](https://googleapis.dev/nodejs/storage/6.9.4/index.html) and I will look into the reason behind that.

**Comment by theGOTOguy** [comment]
Yes, I am using JavaScript and not Typescript.

I agree with you that the client is not the right place to do error checking for the API.  In vanilla JavaScript, the client defaults a different value for entity depending on whether other options are included or not which is certainly less desirable than either setting it to a consistent default or failing the request entirely for missing a default field.

**Comment by ddelgrosso1** [comment]
Correcting what I said above, I did find the [client docs](https://googleapis.dev/nodejs/storage/6.9.4/Acl.html#get), however they appear incorrectly labeling `entity` as optional. I will correct this.

**Comment by ddelgrosso1** [comment]
Do you have the stack trace of the error? I assumed this was something bubbling up from the API side, if not I can look at correcting it in the client.

**Comment by theGOTOguy** [comment]
I agree that to make entity required would be an acceptable fix, but I wanted to add a few concerns you might want to consider before considering this closed.

1.  [Other existing Google documentation](https://cloud.google.com/storage/docs/samples/storage-print-file-acl#storage_print_file_acl-nodejs) shows (correctly) that `file.acl.get()` will work even if entity is not provided in Node.JS, so you will want to update that as well.
2.  Clearly, this change is documentation-only.  It will not be enforced in code and will not break existing code.  This leaves open the possibility that other users will, like me, find themselves confused when they pass non-entity options and the default value for entity changes.  Without going through the trouble of setting up a bucket, creating a file, getting a key to connect and running the code through a `node` console, it's easy to see, [tracing through the code](https://github.com/googleapis/nodejs-storage/blob/main/src/acl.ts#L708), how this happens.

```bash
ben@anteater:~$ node
Welcome to Node.js v17.2.0.
Type ".help" for more information.
> '/' + encodeURIComponent(undefined)
'/undefined'
```

What's happening is that when entity is not provided, if any other option is provided, then we [hit this line](https://github.com/googleapis/nodejs-storage/blob/main/src/acl.ts#L720) and the default value of entity provided by your client becomes `'undefined'` instead of `''`, [as it is if no other option is provided](https://github.com/googleapis/nodejs-storage/blob/main/src/acl.ts#L716).  I would suggest that the lowest-friction path forward would be to simply check for the `entity` option in the client and keep the current default, `''`, if it's `undefined`.  That way you have no breaking changes and you keep the existing, sensible default.
3.  It may be worth documenting somewhere that `entity: ''` will retrieve all ACLs.

**Comment by ddelgrosso1** [comment]
To clarify a bit further `file.acl.get()` with no arguments is a [list operation](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/list) while `file.acl.get({arguments})` is a [get operation](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/get). 

Under the current code if a user does not supply the entity argument or supplies it incorrectly the server returns a `400 Bad Request`. By defaulting `entity = ''` it is essentially converting the `get` back into a `list` which I'm not convinced is appropriate as the user may not be intending this.

The documentation does say that supplying no arguments retrieves all acls but stops short of saying that it is essentially 2 different API calls without parameters vs with parameters. This `get` / `list` pattern is pretty consistent throughout the library so I'm not sure changing it in one place makes sense. That said, if helpful we could look at more explicitly calling this out in the documentation.
