### ISSUE TITLE
Downloading file during it's streaming upload

### ISSUE THREAD

**Issue by mprudnik** [googleapis/nodejs-storage#2165]
Hi, is it possible to download a file during its upload?
We have a case when we need to stream files to storage since their content is gathered "on the fly". We are using `createWriteStream`.
From another server, we sometimes need to get the already streamed part of that file. Currently, we're receiving `Error: No such object` - I've checked that both file and bucket names are correct. We use `bucket.file(fileName).download()` for download.

**Comment by ddelgrosso1** [comment]
Hi @mprudnik I do not think this is possible. If you are uploading and have not yet received a success response the object would not yet be available for download ([documentation on consistency](https://cloud.google.com/storage/docs/consistency#strongly_consistent_operations)).

**Comment by mprudnik** [comment]
Hi @ddelgrosso1, thank you for your answer! Is this the same when the resumable upload is used?
If I understand the docs correctly, the file is uploaded in multiple chunks (we're using 8 MB chunk size) in multiple requests.
Will the file be available to download after the first chunk is successfully uploaded, or only after the stream will be closed?
To get stream we use `bucket.file(fileName).createWriteStream({ gzip: true, timeout: 0, chunkSize: 8 * 1024 * 1024 })`.

**Comment by ddelgrosso1** [comment]
I need to do some further checking but I believe even with a chunked resumable upload this would not be possible. During a chunked resumable upload each chunk before the last will receive a `308 - Resume Incomplete` response ([docs here](https://cloud.google.com/storage/docs/performing-resumable-uploads#chunked-upload)). It is not until the last chunk is uploaded that a `200 or 201` is received. 

However, I have not tried this myself so let me try / talk to some other team members and I will circle back.

**Comment by ddelgrosso1** [comment]
Hi @mprudnik I spoke with some other people on the team and they confirmed what I was saying above. From the server perspective, an object isn't available until it is finalized. This means that you would not be able to download it until you have received a success response. This would also include resumable uploads where an object is not complete until the final chunk has been sent.

**Comment by mprudnik** [comment]
Hi @ddelgrosso1, thank you for clarifying this!
