### ISSUE TITLE
TypeError: err.message.indexOf is not a function

### ISSUE THREAD

**Issue by austinpray-mixpanel** [googleapis/nodejs-storage#2171]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: v18.12.0
  - npm version: 8.19.2
  - `@google-cloud/storage` version: 6.9.3

#### Steps to reproduce

When GitHub Actions has issues (https://www.githubstatus.com/incidents/chnz8v3m9dqm) and you use https://github.com/google-github-actions/auth, sometimes GitHub will give back 503 errors when trying to refresh your token.

This library does not handle that situation gracefully

```
/home/runner/work/analytics/analytics/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:360
                    err.message.indexOf('Could not load the default credentials') > -1;
                                ^

TypeError: err.message.indexOf is not a function
    at onAuthenticated (/home/runner/work/analytics/analytics/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:360:33)
    at prepareRequest (/home/runner/work/analytics/analytics/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:457:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ddelgrosso1** [comment]
Thanks for letting us know @austinpray-mixpanel I will raise a fix for this.

**Comment by ddelgrosso1** [comment]
@austinpray-mixpanel no problem, this fix went out in `v6.9.5`. I think `upload-cloud-storage` likely uses a bot which should hopefully open a PR to update the storage dependency. If not, I will raise one tomorrow to that repo.

**Comment by ddelgrosso1** [comment]
Looks like they are already on it: https://github.com/google-github-actions/upload-cloud-storage/pull/318

**Comment by austinpray-mixpanel** [comment]
Sweet! Y'all are on top of things! 👍 Thank you!
