### ISSUE TITLE
Error while trying to use @google-cloud/storage npm package in Angular application

### ISSUE THREAD

**Issue by vinodhreddygs** [googleapis/nodejs-storage#2176]
Hello,

I have installed the latest version of @google-cloud/storage npm package in my Angular application. My **Angular version is 7.3.4** and **Typescript version is 3.2.4**. After successfully installing the npm package, I tried to import the model in my component using `import { Storage } from '@google-cloud/storage';.`

However, when I tried to compile my Angular application, it threw a lot of errors that look like the following
```
ERROR in node_modules/@google-cloud/storage/build/src/crc32c.d.ts(7,45): error TS1005: ']' expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(7,47): error TS1134: Variable declaration expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(7,3042): error TS1005: ';' expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(68,5): error TS1127: Invalid character.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(116,51): error TS1005: ']' expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(116,63): error TS1005: ';' expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(116,75): error TS1005: ';' expected.
node_modules/@google-cloud/storage/build/src/crc32c.d.ts(116,86): error TS1005: ';' expected.
```

I have successfully used the same npm package in a node.js server to upload and delete files, but it is not working in my Angular application. I want to know if it is possible to use this package with Angular and how to do it.

Thank you in advance.

**Comment by ddelgrosso1** [comment]
Hi @vinodhreddygs, unfortunately at this time we do not officially support using `@google-cloud/storage` from browser / client side environments. It is something we are looking into but no official timeline. 

If you are trying to simply upload / download a file from the browser and you have a Node based server API it is possible to generate a signed URL on the server and return it to the client side. Once you have the URL client side you can use an HTTP library of your choice to make the request.

**Comment by vinodhreddygs** [comment]
Hi @ddelgrosso1,
Okay, Can you please suggest the best possible approach for me to upload larger files from the client-side environment (Angular, in my case) through the Node server API using `@google-cloud/storage `in the Node server? The Node API should emit the progress of file upload events to the Angular application to display for the user, for a better UI experience.

It would be greatly appreciated if you could provide documentation for this in addition to your suggestion.

**Comment by ddelgrosso1** [comment]
There are several ways to accomplish this. For example you could stream your data from the client side to the Node API and utilize [createWriteStream](https://googleapis.dev/nodejs/storage/6.9.5/global.html#CreateWriteStreamOptions) to send the data to GCS. Since this function returns a stream you could subscribe to the `data` event to report status to the UI. Samples for [streaming](https://cloud.google.com/storage/docs/samples/storage-stream-file-upload)
