### ISSUE TITLE
TypeError: mime.getType is not a function

### ISSUE THREAD

**Issue by xonaman** [googleapis/nodejs-storage#2180]
#### Environment details

  - OS: AWS Lambda
  - Node.js version: 14.x
  - npm version: 9.6.4
  - `@google-cloud/storage` version: 6.8.0

#### Steps to reproduce

  1. ```npm i firebase-admin@^11.4.0 --save```
  2. ```const firebase = require('firebase-admin');```
  3. ```await firebase.storage().bucket().file('/some/path.txt').save(/* some data */);```

Producing the following response:
```html
<pre>TypeError: mime.getType is not a function<br> 
  at File.createWriteStream (/opt/nodejs/node_modules/@google-cloud/storage/build/src/file.js:1398:46)<br> 
  at /opt/nodejs/node_modules/@google-cloud/storage/build/src/file.js:2877:39<br> 
  at new Promise (&lt;anonymous&gt;)<br> 
  at retry.retries (/opt/nodejs/node_modules/@google-cloud/storage/build/src/file.js:2873:19)<br> 
  at RetryOperation.runAttempt [as _fn] (/opt/nodejs/node_modules/async-retry/lib/index.js:42:15)<br> 
  at RetryOperation.attempt (/opt/nodejs/node_modules/retry/lib/retry_operation.js:116:8)<br> 
  at run (/opt/nodejs/node_modules/async-retry/lib/index.js:55:8)<br> 
  at new Promise (&lt;anonymous&gt;)<br> 
  at retry (/opt/nodejs/node_modules/async-retry/lib/index.js:58:10)<br> 
  at File.save (/opt/nodejs/node_modules/@google-cloud/storage/build/src/file.js:2872:29)</pre>
```

It seems that ```mime.getType``` should be replaced with ```mime.lookup```. I know that this would work, but editing the file in my node_modules folder cannot be the solution. What am I missing?

**Comment by ddelgrosso1** [comment]
Hi @xonaman can you do an `npm ls mime` and let me know what version comes back? `mime.lookup` was renamed `mime.getType` [in v2.0.0](https://github.com/broofa/mime/releases/tag/v2.0.0)

**Comment by xonaman** [comment]
This is my output:
```
nodejs@1.0.0 /[...]/amplify/backend/function/remononappAdminLayer/lib/nodejs
└─┬ firebase-admin@11.4.1 overridden
  └─┬ @google-cloud/storage@6.8.0
    └── mime@3.0.0 overridden
```
Note: it says "overridden", because I tried to fix this issue by overriding the mime dependency. This is my package.json:
```json
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^11.4.0"
  },
  "overrides": {
    "firebase-admin": {
      "mime": "3.0.0"
    }
  }
}
```

**Comment by ddelgrosso1** [comment]
@xonaman if you can provide a list of other packages that would be helpful. I will try to recreate this issue by pulling in `firebase-admin` to a test project. Are you seeing this in a pure JavaScript environment or are you using TypeScript?

**Comment by xonaman** [comment]
My lambda function uses two layers, the first one is the one I pasted above. Here is the ```package.json``` is the second one:
```json
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@aws-crypto/sha256-js": "^3.0.0",
    "@aws-sdk/credential-provider-node": "^3.267.0",
    "@aws-sdk/protocol-http": "^3.267.0",
    "@aws-sdk/signature-v4": "^3.267.0",
    "aws-serverless-express": "^3.4.0",
    "axios": "^0.27.2",
    "body-parser": "^1.20.0",
    "dayjs": "^1.11.6",
    "express": "^4.18.1",
    "form-data": "^4.0.0",
    "node-fetch": "2.6.9",
    "xml-js": "^1.6.11"
  }
}
```
And the ```package.json``` of my actual lambda function:
```json
{
  "name": "userqueries",
  "version": "1.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0",
  "dependencies": {
    "path": "^0.12.7"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.92"
  }
}
```
And yes, I am seeing the issue in pure JavaScript, I am not using TypeScript.

**Comment by ddelgrosso1** [comment]
Hi @xonaman I did a few tests today. First I created a very simple firebase test from your first example. When I ran it I did not have any issues. I then added the packages from your second app and did an `npm ls mime`. I see the following:

```
firebase-admin-test@1.0.0 /usr/local/google/home/ddelgrosso/source/firebase-admin-test
├─┬ express@4.18.2
│ └─┬ send@0.18.0
│   └── mime@1.6.0
└─┬ firebase-admin@11.6.0
  └─┬ @google-cloud/storage@6.9.5
    └── mime@3.0.0
  ```
  
 While I didn't have any errors I do wonder if this could be causing an issue in your environment?

**Comment by ddelgrosso1** [comment]
@xonaman were you able to get this resolved?

**Comment by xonaman** [comment]
Yes, I did. All this time I overlooked an additional layer with mime 1.6 installed. Sorry for the false alarm and thanks for your help!
