### ISSUE TITLE
file.delete returns a wrong value when the files doesn't exist

### ISSUE THREAD

**Issue by vicb** [googleapis/nodejs-storage#2182]
#### Environment details

  - OS: MacOs
  - Node.js version: v18.10.0
  - npm version: 8.19.2
  - `@google-cloud/storage` version: 6.9.5

#### Steps to reproduce

 Try to delete a file that doesn't exists:

```
const response = await bucket.file('path/to/no/file').delete({ ignoreNotFound: true });
```

The response is:

```
[
  {
    error: {
      code: 404,
      message: 'No such object: airsp/tiles/10/100/601.pbf',
      errors: [Array]
    }
  },
  PassThrough {
    //...
  }
]
```

The first element of the array should not be here as the response is supposed to be a `[r.Response]` 

https://github.com/googleapis/nodejs-storage/blob/b122e1811c558f1f4eefda30c78b93f61f60a6b9/src/file.ts#L1983

**Comment by ddelgrosso1** [comment]
Released with 7.0
