### ISSUE TITLE
Is it possible to get prefixes too when listing bucket content

### ISSUE THREAD

**Issue by cristiboariu** [googleapis/nodejs-storage#219]
- OS: 
  - Node.js version: 8.9.4
  - npm version: 6.0.1
  - `@google-cloud/storage` version: latest

#### Steps to reproduce

 When listing bucket files with `delimiter:'/'` I want to be able to also see `prefixes` returned (like here: https://cloud.google.com/storage/docs/json_api/v1/objects/list#try-it which returns:
```
{
 "kind": "storage#objects",
 "prefixes": [
  "sports/",
  "test/"
 ],
 "items": [
  {
   "kind": "storage#object",
   "id": "nextpro_assets/0041f496-7746-4330-bce1-29320892f550.jpg/1527088009331794",
   "self
....}]
}
```

Right now this lib only returns files but this is not enough because using the delimiter from above I can't view directories from my bucket (but only files). I know I can view ALL files inside my bucket but I only want to view files and dirs from first level and the only solution I saw it like I described already...

I see in [source code](https://github.com/googleapis/nodejs-storage/blob/master/src/bucket.js#L1286) that only `resp.items` are taken in consideration. Can this be improved to also return `prefixes`?

**Comment by stephenplusplus** [comment]
Thanks for the question! Please see this response from a similar issue: https://github.com/googleapis/nodejs-storage/issues/26#issuecomment-364993784
