### ISSUE TITLE
Can't upload from inside Cloud Function

### ISSUE THREAD

**Issue by savager** [googleapis/nodejs-storage#2191]
```
"Error: TypeError: Expected signal to be an instanceof AbortSignal
    at /workspace/index.js:2:1801556
    at /workspace/index.js:2:1799686
    at Object.throw (/workspace/index.js:2:1799791)
    at s (/workspace/index.js:2:1798559)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
```
    
#### Environment details

  - OS: Cloud function
  - Node.js version: 14
  - npm version: using pnpm
  - `@google-cloud/storage` version: 	"^6.10.0",

#### Steps to reproduce

Can't produce locally. But when I push the compiled JS file to the cloud function I get this error

I believe it has to do with bundling the code with webpack. If I don't install request manually, I get this error:

```
WARNING in ../../node_modules/.pnpm/retry-request@5.0.2/node_modules/retry-request/index.js 76:21-39
Module not found: Error: Can't resolve 'request' in '/Users/*****/Projects/project/node_modules/.pnpm/retry-request@5.0.2/node_modules/retry-request'
```

If i add request as a dep, then I get the AbortSignal error. 

the package request is deprecated, and I think it should be removed as a dep.

**Comment by savager** [comment]
Disabling Webpack 5 minification solves this issue.

**Comment by mbrevda** [comment]
Just noticed the same when using `esbuild`. Is there a way to fix?

**Comment by mbrevda** [comment]
Look like this is coming from the [teeny-request](https://github.com/googleapis/teeny-request) dependency, an issue is outstanding here: https://github.com/googleapis/teeny-request/issues/260
