### ISSUE TITLE
CRC32C validation for File.getSignedURL

### ISSUE THREAD

**Issue by christhegrand** [googleapis/nodejs-storage#2198]
File.getSignedURL has an optional contentMd5 parameter that I can include. Is there a way to use a CRC32C checksum instead of an MD5 value with this getSignedURL method, and if so, how would I do that? I don't see anything relevant in the GetSignedUrlConfig type.

**Comment by ddelgrosso1** [comment]
Hi @christhegrand there is currently no way to utilize a CRC32C checksum. The intention of `contentMd5` was to align with setting the `Content-MD5` when sending a request to the generated signed URL. 

In looking into your question it now appears that `Content-MD5` [has been obsoleted](https://www.rfc-editor.org/rfc/rfc9110.html#section-18.4-10). So I might urge caution with utilizing it.

**Comment by christhegrand** [comment]
Oh, I didn't know that. So what should I do to verify the integrity of a file after an upload with a signed URL?

**Comment by ddelgrosso1** [comment]
After looking at the [docs](https://cloud.google.com/storage/docs/access-control/signed-urls) I believe this is currently the only way I see to verify integrity when utilizing a signed URL.

**Comment by ddelgrosso1** [comment]
I believe this is working as documented / intended and I am going to close this issue. If you have any other issues please feel free to reopen.
