### ISSUE TITLE
Return values instead of arrays of values.

### ISSUE THREAD

**Issue by gauntface** [googleapis/nodejs-storage#221]
I couldn't see a justification for why the API returns promises that resolves to arrays instead of values, but this is what I expected to write:

```
const exists = await this.bucket.exists();
if (!exists) {
  ...
}
```

instead of:

```
const data = await this.bucket.exists();
if (!data[0]) {
  ...
}
```

**Comment by JustinBeckwith** [comment]
Greetings!  We're aware this is less than ideal :(  This is going to be a fairly broad change that we'd like to make across all of our libraries, so it's going to take some coordination.

**Comment by gauntface** [comment]
Glad to hear it's at least being discussed - feel free to close as a duplicate if there is a master issue on a more generic repo for cloud node modules.

**Comment by stephenplusplus** [comment]
The duplicate: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2556
