### ISSUE TITLE
storage.bucket().file().save(content) returns undefined - content is uploaded as it should

### ISSUE THREAD

**Issue by SinanGabel** [googleapis/nodejs-storage#2222]
#### Environment details

  - OS: Ubuntu 22.04.2 LTS
  - Node.js version: 18.16.0
  - npm version: 9.6.7
  - `@google-cloud/storage` version: 6.11.0

#### Steps to reproduce

I am running the below within a cloud function using the functions framework: the upload of the contents is fulfilled without any problem but `undefined` is returned as the result.

  1. `const result = await storage.bucket(bucketName).file(destFileName).save(contents);`

**Comment by ddelgrosso1** [comment]
Hi @SinanGabel this is the expected behavior. `File.save`[ returns `Promise<void>`](https://github.com/googleapis/nodejs-storage/blob/37ce0a67748b66d3d7f4f94a12d416b725a3f30a/src/file.ts#L3530). Also documented [here](https://googleapis.dev/nodejs/storage/6.11.0/File.html#save).
