### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#224]
~~Currently blocked on #202~~

**Comment by JustinBeckwith** [comment]
The only steps that should be in this PR are:
- renaming all the *.js files to *.ts files (except for samples)
- Run `npx gts init` to get gts set up
- `npm install --save-dev` all the missing @type/<packages>
- Switch all `require` statements to `import` statements
- Get the compiler running
- Get the unit tests passing

I know it sounds silly but the trick is to change *as little* as possible.

**Comment by fhinkel** [comment]
Never mind, this happened.
