### ISSUE TITLE
Error "You must specify an object name." when uploading file to bucket

### ISSUE THREAD

**Issue by stx-chris** [googleapis/nodejs-storage#2248]
#### Environment details

  - OS: Mac OS 13.5
  - Node.js version: 18.16.0
  - npm version: 9.5.1
  - `@google-cloud/storage` version: 6.12.0

#### Issue
See code snippet below. We have a lot of legacy code using `stream1` method below (basic non-resumable stream). But as of recently, an error is thrown by the `storage` library. Only `stream2` (providing metadata) and `stream3` (resumable stream) work, but I don't know why suddenly the basic method fails.

#### Error

```
request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://storage.googleapis.com/upload/storage/v1/b/<mybucket>/o?uploadType=multipart&name=myfile.txt'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 400,\n' +
      '    "message": "You must specify an object name.",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "You must specify an object name.",\n' +
      '        "domain": "global",\n' +
      '        "reason": "required"\n' +
      '      }\n' +
      '    ]\n' +
      '  }\n' +
      '}\n',
```
#### Steps to reproduce
Example with a basic text file `myfile.txt`:
 
```
const { Storage } = require("@google-cloud/storage");
const fs = require("fs");

// Initialize storage
const storage = new Storage({
  keyFilename: `./<mykeyfile.json>`,
});

const bucketName = "<mybucket>";
const bucket = storage.bucket(bucketName);

const file = bucket.file("myfile.txt");

// crashes
const stream1 = file.createWriteStream({ resumable: false });

// works with provided metadata
const stream2 = file.createWriteStream({ metadata: {name: "myfolder/myfile.txt"}, resumable: false });

// works with resumable = true
const stream3 = file.createWriteStream({ resumable: true });


fs.createReadStream("./myfile.txt")
  .pipe(stream1)  // works only with stream2 or stream3
  .on("error", function (err) {
    console.log("error", err);
  })
  .on("finish", function () {
    console.log("success");
  });
```

**Comment by stx-chris** [comment]
all of a sudden `stream1` works again. We've had issues with this for the last couple of hours. Was there anything wrong with the storage service today?

**Comment by ddelgrosso1** [comment]
@stx-chris I'll check if there was anything strange going on with the service side. We haven't made changes recently in the SDK that might have caused this.

**Comment by ddelgrosso1** [comment]
Checked around and there didn't appear to be anything unusual going on. Have you seen this issue at all since?

**Comment by stx-chris** [comment]
Hi @ddelgrosso1 no, fortunately not. Maybe it had to do with Node module caching. Glad that it works now and thanks for your fast response
