### ISSUE TITLE
Missing Some Types

### ISSUE THREAD

**Issue by hspak** [googleapis/nodejs-storage#2257]
#### Environment details

  - OS: macOS 13.5.
  - Node.js version: 18.16.0
  - npm version: 9.5.1
  - `@google-cloud/storage` version: 6.10.1 / 7.0.0

#### Steps to reproduce

  1. Try to use any of the lifecycle related types from bucket.ts, e.g `LifecycleRule` or `LifecycleAction`.
  2. Get type error saying it doesn't exist.

It appears we're not exporting these in the index file: https://github.com/googleapis/nodejs-storage/blob/main/src/index.ts

**Comment by ddelgrosso1** [comment]
Thanks @hspak raising a PR to fix this.
