### ISSUE TITLE
Undocumented breaking change in v7

### ISSUE THREAD

**Issue by runeh** [googleapis/nodejs-storage#2285]
Typings was added for file metadata in https://github.com/googleapis/nodejs-storage/pull/2234 which was seemingly was released with 7.0.0.

This is a breaking change, code no longer compiles if the assumptions about the previously typed `any` are different from the ones in the new `FileMetaData`.

Really appreciate getting proper typings for these objects! But would be great with a heads up. Might we worth updating the release notes.

**Comment by tritone** [comment]
Thanks for the issue; you're correct and we can update the release notes as you suggest.

**Comment by ddelgrosso1** [comment]
Looks like there was a problem with some merges and the release notes not updating automatically / correctly. I will see about getting them corrected.

**Comment by duncannz** [comment]
The additional breaking changes are still missing from the [Github release notes](https://github.com/googleapis/nodejs-storage/releases/tag/v7.0.0). Is it possible to also fix these?

**Comment by ddelgrosso1** [comment]
@duncannz let me see about regenerating the Github side of things.
