### ISSUE TITLE
"Failure from metadata server" when using GKE and Workload Identity

### ISSUE THREAD

**Issue by bradam12** [googleapis/nodejs-storage#2346]
We were getting the "Failure from metadata server" when trying to create a signed URL in our existing application. This is an app already running in prod. We're adding an additional feature that requires signed URLs.

I created a barebones test.js file and also used the included sample at https://github.com/googleapis/nodejs-storage/blob/main/samples/generateV4ReadSignedUrl.js as reproducible cases. Versions 2.x, 3.x, 4.x all work properly, and 5.0.0 and up exhibit the error.

#### Environment details

  - OS: buster
  - Node.js version: 16.20.2
  - npm version: 8.19.4
  - `@google-cloud/storage` version: 5.0.0 and up

#### Steps to reproduce

  1. Run node:16 pod in GKE (we're currently on v1.24.15-gke.1700), with established workload identity, KSA and GSA linked. GSA has Storage Object Admin and Service Account Token Creator.
  2. Exec into pod
  3. Write the sample file from https://github.com/googleapis/nodejs-storage/blob/main/samples/generateV4ReadSignedUrl.js
  4. Install @google-cloud/storage@5
  5. Run `node test.js bucketname filename`
  6. Receive error: `Failure from metadata server.`
  7. Repeat for @google-cloud/storage@6 and @google-cloud/storage@7, receive same error

**Comment by ddelgrosso1** [comment]
Hi @bradam12 is this only happening within GKE? Has it been successful in other environments for you?

**Comment by ddelgrosso1** [comment]
@bradam12 came across this documentation: https://cloud.google.com/knowledge/kb/unable-to-reach-gke-metadata-server-on-workload-identity-enabled-cluster-000004705 is this inline with your problem?
