### ISSUE TITLE
SetMetadata is throwing not found error

### ISSUE THREAD

**Issue by vkclogituit** [googleapis/nodejs-storage#2361]
Following block of code is given in the samples of this project. 

And, I have create a object in the google cloud bucket and then I am trying to set the custom metadata for the same. 

But this code block is throwing same error. ( Not Found )

`
 const options = {
        ifMetagenerationMatch: 0,
    };
`
 `  
storage.bucket(bucketName)
        .file(filename)
        .setMetadata(
`
 `           {
                contentType: 'video/mp4',
                metadata: {
                    description: 'file description...',
                    modified: '1900-01-01',
                },
            },
            options
`
 `       ).then((data) => {
            console.log('COMPLETED)
        }).catch((error) => {
            console.log(error)
        });
`

Environment Details:
  - OS: Windows 11
  - Node.js version: 16.14.2
  - npm version: 8.5.0
  - `@google-cloud/storage` version: 7.5.0

#### Steps to reproduce
  1. initialize storage object with serviceAccount 
  2. run the given code and it will throw the not found error

![Screenshot 2023-11-10 1035330000](https://github.com/googleapis/nodejs-storage/assets/106573979/4950c727-a658-4c7b-90f4-ca4ecaf2ff5e)

**Comment by ddelgrosso1** [comment]
Hi @vkclogituit I just tried the snippet you provided and I did not see any errors. Are you sure the object you are attempting to `setMetadata` on exists? Have you verified with a `.exists()` call to check?

**Comment by vkclogituit** [comment]
![image](https://github.com/googleapis/nodejs-storage/assets/106573979/2a996e22-a7a6-4fea-ad8a-f29a897c51ff)

exists() returns two and but still this code fails and saying not found.

**Comment by ddelgrosso1** [comment]
Looking at the above code `file.exists` needs to either be provided a callback or `await`ed for the promise form. The documentation is [here](https://googleapis.dev/nodejs/storage/7.6.0/File.html#exists).

**Comment by vkclogituit** [comment]
I encountered an odd situation. 

I uploaded video files ( mp4 ) to google bucket using preSigned Url and I have mentioned the same content type as video/mp4.

I can see the files on the bucket but those are not playing and showing the message as too large to view.

For those uploaded through preSigned url I could not able to set the metadata as file.exists returning false. 

![image](https://github.com/googleapis/nodejs-storage/assets/106573979/f083e74a-7551-4fd1-8ad7-3d4b3ab31405)

**Comment by ddelgrosso1** [comment]
Would it be possible to see the code / an example of how you are uploading using a signed url?

**Comment by vkclogituit** [comment]
![image](https://github.com/googleapis/nodejs-storage/assets/106573979/12329955-f7f2-4440-a14a-1f5925d977f2)

Here is my upload code

And I can see the upload going well from network logs
![image](https://github.com/googleapis/nodejs-storage/assets/106573979/a4fa71d1-b147-42f0-854f-9309e7940c3e)

**Comment by vkclogituit** [comment]
There were two issues, due to which I could not able to see the video playing and also not able to set the metadata. 
reason 1: treating folders also as bucket. 
 instead of getting the bucket object  by simply mention the bucket name, I was using the full path as bucket name ( except filename ) . 
Due to this file able to get placed correctly in right path but while setting the setMetada it was throwing the error. 

Reason 2: from angular, I was uploading video file and setting the type as file instead of 'video'- due to that I could not able to play it back when I render the object . 

So it is my mistake, 

Thank you @ddelgrosso1 for guiding on this.
