### ISSUE TITLE
 state.buffer[0].length  Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by gal-checksum** [googleapis/nodejs-storage#2368]
#### Environment details

  - OS: Mac 13.5 (22G74)
  - Node.js version: 21.2.0
  - npm version: 10.2.3
  - `@google-cloud/storage` version: 7.6.0

Getting the following error when trying to download a file:
```
source-map-support.js:496 node_modules/stream-shift/index.js:16
    return state.buffer[0].length
  source-map-support.js:499 TypeError: Cannot read properties of null (reading 'length')
    at getStateLength (node_modules/stream-shift/index.js:16:28)
    at shift (node_modules/stream-shift/index.js:6:99)
    at Duplexify._forward (node_modules/duplexify/index.js:170:35)
    at PassThrough.onreadable (node_modules/duplexify/index.js:136:10)
    at PassThrough.emit (node:events:519:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

```

This only happens when I download the file from a certain project. If I copy the exact same config and code but initiate it within a script, it works

**Comment by unifractal** [comment]
I am seeing the same problem. But for me it seems to be an issue with most versions, not just 7.6.0. I have tested all the way back to 6.12 and it is broken for me

**Comment by gal-checksum** [comment]
Has to do with this:
https://github.com/mafintosh/stream-shift/issues/6

Downgrade your node.js version to below 21.2

**Comment by jontybrook** [comment]
Ditto this. Downgrading to node v20.10 resolved fixed it.

**Comment by drichardson** [comment]
FYI I ran into this with current LTS of node (20.11.0). I worked around it by removing the `{destination: my_output}` option from the `download` function and writing it to a file myself.

**Comment by mpalmerlee** [comment]
I experienced the same issue with Node 20 although my error message was slightly different:
```
TypeError: Cannot read properties of null (reading 'length')
    at getStateLength (/prod/api/node_modules/.pnpm/stream-shift@1.0.1/node_modules/stream-shift/index.js:16:28)
    at shift (/prod/api/node_modules/.pnpm/stream-shift@1.0.1/node_modules/stream-shift/index.js:6:99)
    at Duplexify._forward (/prod/api/node_modules/.pnpm/duplexify@4.1.2/node_modules/duplexify/index.js:170:35)
    at PassThrough.onreadable (/prod/api/node_modules/.pnpm/duplexify@4.1.2/node_modules/duplexify/index.js:136:10)
    at PassThrough.emit (node:events:518:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

To work around I changed my code from:
`await this.storage.bucket(config.gcp.storageBucket).file(gcsPath).download(options);`

To:
`await this.transferManager.downloadFileInChunks(gcsPath, options);`

Like in this example [downloadFileInChunksWithTransferManager.js](https://github.com/googleapis/nodejs-storage/blob/main/samples/downloadFileInChunksWithTransferManager.js#L59)

**Comment by russell-liu-splyt** [comment]
stream-shift 1.0.2 works fine with node 20.11.0

**Comment by mksony** [comment]
> stream-shift 1.0.2 works fine with node 20.11.0

Can confirm that 💯

**Comment by MilosLukicBM** [comment]
Can also confirm that setting stream-shift 1.0.2 for all dependencies (used the [overrides](https://stackoverflow.com/a/70396201) method) works with node 20.11.0 :tada:

**Comment by MattBidewell** [comment]
Those who might end up here whilst running a Google Cloud Function, theres a chance the underlying image of your cloud function has been updated and this bug has manifested itself!

For the time being, you can add the following to your package.json to get around the issue the storage API is updated:

JSON
```
  "overrides": {
    "stream-shift": "1.0.2"
  }
```

**Comment by majikandy** [comment]
Can also confirm this works in the package json to override to 1.0.2 using the overrides block above.

Using the functions-framework to run the function locally doesn't cause the `stream-shift TypeError: Cannot read properties of null (reading 'length')`, it only seems to happen when it runs in the cloud so we only became aware on a rebuild.

**Comment by undesicimo** [comment]
downgrading to 20.10 seems to work for now
