### ISSUE TITLE
I can't download files larger than 70KB to my Google Cloud Storage bucket

### ISSUE THREAD

**Issue by PatricioPoncini** [googleapis/nodejs-storage#2370]
I'm having an issue with GCS and Bun. It turns out that I want to download an image from my bucket, and I'm encountering an error. I'm using the `.download()` method from the GCS library, but it gives me an error for files larger than a certain size in KB.

This worked fine in Express, but when doing it in Bun, it doesn't, and I don't know why. What I'm trying to do is pass an array of public URLs that I have in my bucket, download them, and send them by email. However, for files larger than approximately 70KB, it doesn't work because the code stops, and nothing gets sent. I'm getting the following errors:

```
262 | 'ECONNREFUSED',
263 | ].includes(err.code))) {
264 | let code = 'UNKNOWN';
265 | if (err.code)
266 | code = err.code;
267 | process.emitWarning(`received unexpected error = ${err.message} code = ${code}`, 'MetadataLookupWarning');
^
warn: received unexpected error = Was there a typo in the URL or port? code = FailedToOpenSocket
at /mnt/c/Users/user/Desktop/proyect/node_modules/gcp-metadata/build/src/index.js:267:16
at processTicksAndRejections (:61:76)

11 | // Since node 6.3.0 state.buffer is a BufferList not an array
12 | if (state.buffer.head) {
13 | return state.buffer.head.data.length
14 | }
15 |
16 | return state.buffer[0].length
               ^
TypeError: undefined is not an object (evaluating 'state.buffer[0].length')
at getStateLength (/mnt/c/Users/user/Desktop/proyect/node_modules/stream-shift/index.js:16:11)
at shift (/mnt/c/Users/user/Desktop/proyect/node_modules/stream-shift/index.js:6:98)
at /mnt/c/Users/user/Desktop/proyect/node_modules/duplexify/index.js:170:34
at onreadable (/mnt/c/Users/user/Desktop/proyect/node_modules/duplexify/index.js:136:4)
at processTicksAndRejections (:61:76)
```

I'm not sure what these errors refer to. I've tried updating the library, dependencies, etc., but nothing seems to work. The error seems to have occurred when I switched from Express to Bun because it used to work perfectly fine before.

This is the line, with files larger than approximately 70KB, it doesn't go beyond this line, meaning it doesn't download them: const `downloadResponse = await findFile.download();`

**Comment by ddelgrosso1** [comment]
Hi @PatricioPoncini unfortunately at this time we do not have official support for Bun. This library was written / intended for Node environments. We are currently investigating the possibility of expanding support to other runtimes but there is no time frame for when / if this will happen.

**Comment by ddelgrosso1** [comment]
@PatricioPoncini unfortunately my testing with Bun has been fairly limited at this point. I've actually spent more time investigating Deno. So I'm not sure how to get this working with Bun. 

Just looking at the stack trace you provided the problem seems to be coming from Duplexify which is one of our dependencies. It might be worth opening an issue with that repository. I noted this on another similar issue, we are planning to move away from Duplexify in the next major revision to storage but I wouldn't expect that to happen until sometime next year.

**Comment by PatricioPoncini** [comment]
@ddelgrosso1 No problem, thanks anyway. Cheers!

**Comment by charlesbodman** [comment]
Same error occurs on node 20

**Comment by ddelgrosso1** [comment]
@charlesbodman if you are seeing this issue on a supported Node version can you please open a new issue with additional details?

**Comment by ddelgrosso1** [comment]
Going to close this as I believe this has been resolved (at least for Node). At this time we do not support environments other than Node. If this is still an issue for Node, please feel free to open a new issue with additional details.
