### ISSUE TITLE
error TS2305: Module '"stream"' has no exported member 'PipelineSource'.

### ISSUE THREAD

**Issue by eggsys** [googleapis/nodejs-storage#2382]
```
node_modules/@google-cloud/storage/build/cjs/src/file.d.ts:7:30 - error TS2305: Module '"stream"' has no exported member 'PipelineSource'.

7 import { Writable, Readable, PipelineSource } from 'stream';

```
#### Environment details

  - OS: macOS
  - Node.js version: 16.20.1
  - npm version: 8.19.4
  - `@google-cloud/storage` version:
  - typescript: 4.7.4

#### Steps to reproduce

  1. `npm install `
  2. `tsc`
  3. error above shows up

**Comment by ddelgrosso1** [comment]
Hi @eggsys please update your `@types/node` I believe this will resolve the issue.

**Comment by eggsys** [comment]
@ddelgrosso1 after update `@types/node` its work perfectly 
thank you very much

**Comment by yatzeck** [comment]
> @ddelgrosso1 after update `@types/node` its work perfectly thank you very much

May i know how did you resolved exact steps. I tried updating the npm update and still facing the same error

**Comment by eggsys** [comment]
@yatzeck  which version of @types/node, node version in your package.json ?
