### ISSUE TITLE
How to Add custom value for the header `x-goog-api`  using the module google cloud storage?

### ISSUE THREAD

**Issue by armandocomellas1** [googleapis/nodejs-storage#2399]
Hey l have a question regarding cloud-storage:

To service patgh is src/nodejs-common/service.ts and what l am trying to do is to add for example to the header 
![image](https://github.com/googleapis/nodejs-storage/assets/70304755/14aec974-3fcb-42db-9b87-6f271d83fe8d)
`X-Google-Api` the value of a lets say backstage/cloudstorage/version

l tried so set parameters from the script GoogleGcsUrlReader.ts
![image](https://github.com/googleapis/nodejs-storage/assets/70304755/efb08adf-0891-4c08-8939-6d446918b9d6)
but it doesnt allow me to invoke some other paramters, so can you create a condition and a constructor keys and parameters to accept libName and libVersio just like you have with the script packages/google-container/src/v1/cluster_manager_client.ts

Thank you for taking the time to understand and reply to my question.
Regards,

@ddelgrosso1

**Comment by ddelgrosso1** [comment]
Hi @armandocomellas1 if I understand correctly you are looking for a way to set `x-goog-api-client` from the client. Unfortunately, we don't allow users to manipulate this particular header as it is used by internal systems. As you can see from your first snippet, even if you were to set it, the library will override it.

**Comment by armandocomellas1** [comment]
> Hi @armandocomellas1 if I understand correctly you are looking for a way to set `x-goog-api-client` from the client. Unfortunately, we don't allow users to manipulate this particular header as it is used by internal systems. As you can see from your first snippet, even if you were to set it, the library will override it.

Thank you for quick answer @ddelgrosso1
