### ISSUE TITLE
How to list the subdirectories/subfolders in a folder

### ISSUE THREAD

**Issue by convers39** [googleapis/nodejs-storage#2423]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do

For example, I have a folder structure like below, the root `folder` contains subfolders and files.

```
folder
 - sub1
   - file1.ext
 - sub2
   - nest1
     - file2.ext
 - file3.ext
```

I want to list all directories including or excluding nested ones.

```
folder/sub1/
folder/sub2/

# or with nested folders
folder/sub1/
folder/sub2/
folder/sub2/nest1/
``` 

- What code you've already tried

I have tried with the code below:

```ts
      const [folders] = await client.getFiles({
        prefix: 'active/',
        delimiter: '/',
        autoPaginate: false,
      });
      console.log(
        'folders',
        folders.map((f) => f.name),
      );
```

which gives me

```
folder/
folder/file3.ext
```

↓gives me an empty array
```ts
      const [folders] = await client.getFiles({
        prefix: 'active',
        delimiter: '/',
        autoPaginate: false,
      });
      console.log(
        'folders',
        folders.map((f) => f.name),
      );
```

- Any error messages you're getting

No

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by ddelgrosso1** [comment]
Hi @convers39 I think using `matchGlob` here is the better choice. For example using your structure to retrieve everything you can use `bucket.getFiles({matchGlob: '**');`

See the documentation [here](https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters) and [here](https://cloud.google.com/storage/docs/json_api/v1/objects/list#list-object-glob).

**Comment by ddelgrosso1** [comment]
@convers39 were you able to implement a working solution?

**Comment by ddelgrosso1** [comment]
Going to close this out as I think the above docs should help resolve the issue. If there are other questions or this doesn't fully answer the question, please feel free to reopen.
