### ISSUE TITLE
Support Storage Control quickstart

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/nodejs-storage#2433]
1. Please update Library Install Section to include install instructions for storage control, if applicable.
2. Please create sample with region tag storage_control_quickstart_sample that shows an example of initializing a storage control client and performing an call.
3. Please include me on reviews for tracking.

See [internal doc](http://goto.google.com/storage-control-quickstart) for further information.

**Comment by ddelgrosso1** [comment]
@sydney-munro we want to add these to the storage client? The PR for storage control contains samples, etc... https://github.com/googleapis/google-cloud-node/pull/5154. Seems confusing to add instructions on using a different library in this library, no?

**Comment by sydney-munro** [comment]
Where do you keep the installation instructions? the idea was to keep them in the same place so they can be pulled in together to the docs.

**Comment by ddelgrosso1** [comment]
The installation instructions for this library live in the `README.md`: https://github.com/googleapis/nodejs-storage?tab=readme-ov-file#installing-the-client-library. 

Perhaps we could add a new section in the `README.md` that says something along the lines that if a user needs control plane operations please see storage control with a link to that repo / those docs?

**Comment by frankyn** [comment]
Let's keep the consolidated guidance for each language here: https://cloud.google.com/storage/docs/reference/libraries

For node, we will want the quickstart in the main google-cloud-node repo; It might help to add a call out in storage README.md as a supplemental client but can keep it in our public docs for now.

**Comment by ddelgrosso1** [comment]
When you say consolidated guidance you mean you want to add additional instructions for installing storage control to that page?

**Comment by frankyn** [comment]
That's correct, that's the plan that we have for storage control.

**Comment by ddelgrosso1** [comment]
The relevant changes have been made / merged / released in google-cloud-node. Is there anything further to be done or can this issue be closed?

1. https://github.com/googleapis/google-cloud-node/pull/5154/files#diff-52e419208627877e68c42243488440500ccfef048b9130fc8bd13c6552e87e00R53
2. https://github.com/googleapis/google-cloud-node/pull/5154/files#diff-00d6964ecf2c290edc4386f2badcd6288597462ba15576be112fe0317b090c29R22

**Comment by ddelgrosso1** [comment]
Spoke with Sydney offline. Closing this as completed.
