### ISSUE TITLE
File.from picks up incorrect bucket name from passed URL

### ISSUE THREAD

**Issue by IchordeDionysos** [googleapis/nodejs-storage#2448]
I'm going crazy here, as I'm exactly replicating the test case: https://github.com/googleapis/nodejs-storage/pull/2432/files#diff-84c67ae7b647502a4aa36d73e488640768b074793ad0b8c940a22af156e96f0b
And there it worked.

The test also did run: https://github.com/googleapis/nodejs-storage/actions/runs/8440365167/job/23117068589?pr=2432#step:8:689
![image](https://github.com/googleapis/nodejs-storage/assets/10195482/94a88941-0546-44f6-95ec-99639325823c)

Though for me the bucket name is always `gs` ...

When running the regex in the browser it is clear why the issue exists:
![image](https://github.com/googleapis/nodejs-storage/assets/10195482/d96df5da-19fa-4161-8873-4c3e20c30af8)
The bucket name is at index `[0][2]` but [here](https://github.com/googleapis/nodejs-storage/pull/2432/files#diff-bc9705d0f7a567399044dfc66ccc82d4d9aa1cff116842a0094d54e463c9ecbcR2381) it's accessed by index `[0][1]`

(though I don't understand why the test wouldn't have caught it)

#### Environment details

  - OS: macOS
  - Node.js version: `v20.11.0`
  - npm version: `10.2.4`
  - `@google-cloud/storage` version: `7.10.1`

#### Steps to reproduce

  1. Run `npx gts init` (use defaults)
  2. Run `npm i @google-cloud/storage`
  3. Run `npm i ts-node`
  4. Add the following script: `"start": "ts-node ./src/index.ts",`
  5. Change the `src/index.ts` to:
```ts
import {Storage, File} from '@google-cloud/storage';

const file = File.from(
  'gs://mybucket/myfile',
  new Storage({
    projectId: 'simpleclub',
  })
);
console.log(file.bucket.name); // 'gs'
````
6. Run using `npm run start`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ddelgrosso1** [comment]
Hi @IchordeDionysos I just want to confirm something, are you running this from a browser based application or from a node environment (you mentioned Node 20.11.0)?
