### ISSUE TITLE
Calling signed URL generated from Cloud Function by web app gives Access-Control-Allow-Origin header errors on preflight OPTIONS call

### ISSUE THREAD

**Issue by nathanclemente** [googleapis/nodejs-storage#245]
#### Environment details

  - OS: macOS High Sierra 10.13.4
  - Node.js version: 8.9.4
  - npm version: 6.0.1
  - `@google-cloud/storage` version: ^1.7.0

#### Steps to reproduce

I have a cloud function that gets a write signed URL for a Storage object. It follows the tutorial here: https://cloud.google.com/functions/docs/writing/http#file_uploads_using_cloud_storage

```
// Get a reference to the destination file in GCS
    const file = storage.bucket(bucketName).file(req.body.filename);

    // Create a temporary upload URL
    const expiresAtMs = Date.now() + 300000; // Link expires in 5 minutes
    const config = {
      action: 'write',
      expires: expiresAtMs,
      contentType: req.body.contentType,
    };

    file.getSignedUrl(config, function (err, url) {
      if (err) {
        console.error(err);
        res.status(500).end();
        return;
      }
      res.send({"signedUrl": url});
    });
```
 It returns the URL back to the app client and the client calls the PUT method on the URL with the file. However, we are getting the following from Chrome:

**Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.**

There are no CORS responses headers coming back from the signed URL - is there something I need to configure during URL generation to get my origin to pass?

Let me know if you need more info. Thank you!!

**Comment by nathanclemente** [comment]
Just as additional information, the bucket that we are posting to has the following CORS configuration, but we're not sure if it actually affects the signed URL response headers:
`[{"maxAgeSeconds": 3600, "method": ["*"], "origin": ["*"], "responseHeader": ["*"]}]`

**Comment by nathanclemente** [comment]
Any thoughts on this @JustinBeckwith (or know anyone who can look at it for us)? We're hoping to use this flow but may have to switch to the storage JSON API instead if we can't get past this. Thanks!

**Comment by nathanclemente** [comment]
We realized we had a typo in the way we were sending contentType... closing for now. Sorry for the trouble!

**Comment by dakom** [comment]
I'm hitting this as well - do you mind sharing more details about the typo?

**Comment by nathanclemente** [comment]
I wish I had more info to help @dakom, I believe on the request side we accidentally had "Content-Type" as the body parameter instead of "contentType", which the code was expecting. We were using "image/jpeg" but I don't think that matters to you. Do you have any code I can look at to help you out?
