### ISSUE TITLE
File.save() with a Uint8Array fails

### ISSUE THREAD

**Issue by aiden-jeffrey** [googleapis/nodejs-storage#2478]
When saving a UintArray8, we see the error `The "chunk" argument must be of type string or an instance of Buffer or Uint8Array.`. This bug is only present in 7.0.0 onwards. I have to cast it to a buffer for the save to succeed, which wasn't necessary on 6.x.x.

#### Environment details

  - OS: Ubuntu 23.04
  - Node.js version: v18.13.0
  - npm version: 8.19.3
  - `@google-cloud/storage` version: 7.11.1

#### Steps to reproduce

  1. Bucket.file("some-file.bin").save(new Uint8Array([1,2,3,4,5]))
  2. See error:
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. 
  Received type number (20)
  at new NodeError (node:internal/errors:400:5)
  at _write (node:internal/streams/writable:315:13)
  at Writable.write (node:internal/streams/writable:337:10)
  at pump (node:internal/streams/pipeline:130:21)
  at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ERR_INVALID_ARG_TYPE'
  }
  error Command failed with exit code 1.
  ```

**Comment by ddelgrosso1** [comment]
@aiden-jeffrey did you also update node versions as part of the move from 6.x to 7.x? Looking at the signature for `file.save` in `6.9.3` [it was defined](https://github.com/googleapis/nodejs-storage/blob/7054e4318a4c45b89db9c3c2236efeaab8b1dc37/src/file.ts#L3646) as only accepting `string | Buffer`. We added `PipelineSource` in 7.x as another option. 

If you updated Node versions perhaps there used to be an automatic conversion that was changed.

**Comment by aiden-jeffrey** [comment]
No. I didn't change node version. We upgraded to `7.11.1` (following direction here https://github.com/googleapis/nodejs-storage/issues/2476), and saw the bug. Then I bisected to work out which was the first release to exhibit - 7.0.0.

**Comment by sidsethupathi** [comment]
If it isn't clear, Aiden and I work together. 

I also don't think 7.0.0 is the first bad commit. I checked out this repo, bisected the commits, and landed on https://github.com/googleapis/nodejs-storage/commit/c0d9d58b56a9a3485b6c0e5eb92411bb094f7bcb to be the commit that starts failing when passing in a `Uint8Array`, always using Node `v18.13.0` during the bisect.

**Comment by ddelgrosso1** [comment]
@sidsethupathi beat me to it. I was just looking at those lines. It looks like Uint8Array worked previously because despite the TypeScript signature saying `string | Buffer` we never actually verified that data was actually one of those. Let me take a look at extending the signature and checks to accept further types.

**Comment by sidsethupathi** [comment]
The interesting thing is that we are using TypeScript so we'll look into why TS didn't yell at us for trying to pass in a `Uint8Array` into the `File.save` method.

**Comment by ddelgrosso1** [comment]
When I tried in TypeScript just now, it wouldn't accept a `UInt8Array.` 

`typescript: 5.3.3`
`@types/node: 20.11.20`

**Comment by sidsethupathi** [comment]
Yes, we have some abstract classes on top of our GCS invocations so I think something got messed up there.

In short, we have an abstract class
```typescript
abstract class Writer {
  saveBinary(data: Buffer | Uint8Array);
}
```
and then a GCS specific implementation
```typescript
class GCSWriter extends Writer {
  saveBinary(data: Buffer) {
    // call File.save(data) here
  }
}
```

I think since `Buffer` extends `Uint8Array`, TS allows `GCSWriter.saveBinary(data: Buffer)` to satisfy `Writer.saveBinary(data: Buffer | Uint8Array)` because all `Buffer`s will be `Uint8Array`s, but then that borks the actual implementation because `File.save` doesn't want to take a `Uint8Array`.

**Comment by ddelgrosso1** [comment]
@sidsethupathi thank you for your investigation. I've opened a PR to add support for Uint8Array.

**Comment by aiden-jeffrey** [comment]
> @sidsethupathi thank you for your investigation. I've opened a PR to add support for Uint8Array.

Thank you! I'd sure I'd checked the type definition in `SaveData`, but apparently I didn't.
