### ISSUE TITLE
Samples system test failing: files › should download a file

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-storage#249]
Observed the test failing in `samples/system-test/files.test.js` in `master` since dad87eba3, then re-run tests on earlier commits `7e81936d` and the test went from green to red.

![screen shot 2018-06-21 at 4 36 01 pm](https://user-images.githubusercontent.com/4001432/41750506-3da0fff6-7571-11e8-8913-e83888fac58d.png)

**Comment by kinwa91** [comment]
Can I get confirmation it is a duplicate of #53 and it's a known issue?

**Comment by JustinBeckwith** [comment]
@kinwa91 please add the appropriate labels to this :)

**Comment by JustinBeckwith** [comment]
summoning @stephenplusplus :)

**Comment by stephenplusplus** [comment]
I'm not sure about this one. It passed locally for me, as well as recent nightly builds (2, 3, 4, 5 nights ago). But, it did fail before that, and it's possible it will fail again.

The test structure makes sense:

1. upload file
2. download file
3. check that there weren't errors
4. check that file exists on disk

The step that fails is 4, which means `fs.writeFileStream('{{file path}}')` succeeded. And if that worked, then how is it that the file doesn't exist?

I'm a wee bit lost here.

**Comment by stephenplusplus** [comment]
Seems fine in recent CI. If it pops back, we can look again.

**Comment by vernk** [comment]
Yes, still failing with downloading a file
