### ISSUE TITLE
Cannot import  RETRYABLE_ERR_FN_DEFAULT

### ISSUE THREAD

**Issue by Cynocracy** [googleapis/nodejs-storage#2516]
**Is your feature request related to a problem? Please describe.**
I want to import RETRYABLE_ERR_FN_DEFAULT to be able to customize it
 **Describe the solution you'd like**
export RETRYABLE_ERR_FN_DEFAULT
 **Describe alternatives you've considered**
Copying the code into my repo is my current option, but this will drift from upstream over time, and hurts Google's ability to provide good service through GCS to nodejs consumers, imo.
 **Additional context**

**Comment by ddelgrosso1** [comment]
Hi @Cynocracy 

The function is already customizable by passing a function here:

https://github.com/googleapis/nodejs-storage/blob/main/src/storage.ts#L76-#L84

Which can be passed to the `Storage` constructor here:

https://github.com/googleapis/nodejs-storage/blob/57b28f1123db414c545bc0c1b0a760cf57aa2cb0/src/storage.ts#L100

Is there another reason you want to have the default exported?

**Comment by Cynocracy** [comment]
@ddelgrosso1 I want to customize the default with

```
retryableErrorFn: (error) => {
    const default = RETRYABLE_ERR_FN_DEFAULT(error);
    // log the error
    return default;      
}
```

if the default is not exported, I would have to reimplement it
