### ISSUE TITLE
How to delete an empty folder?

### ISSUE THREAD

**Issue by jezaman** [googleapis/nodejs-storage#2520]
Hello,

I have a setup where inside my bucket, i organise files based on project
So files are stored as {projectUUID}/{filename}

How do i delete the actual empty folder?
I found that i can use deleteFiles to delete the files inside the folder
await bucket.deleteFiles({
     prefix: `${project}/`,
});

But this doesn't delete the folder. I tried doing a manual delete of the folder path afterwards but that doesn't seem to work.
I tried removing the trailing '/' but that didn't have an effect either.

I really think this repo could use some basic examples. There is so many super complex examples already there, but there is not a basic example of  "Delete multiple files" or a "Delete a folder".

And yes i know technically there are no folders inside the bucket.

**Comment by ddelgrosso1** [comment]
Hello @jezaman, it sounds like you are referring to `simulated folders`. If so, there is nothing in particular you need to do to delete the folder because it doesn't actually exist. See the docs [here](https://cloud.google.com/storage/docs/objects#removing_simulated_folders)

**Comment by jezaman** [comment]
Yes i know that, but the empty non-existent folder does remain in my Google Cloud Storage overview in Google Cloud Console. I was expecting that if all the files would be removed, the path would also be removed from the Console.

**Comment by ddelgrosso1** [comment]
@jezaman I would try performing a `getFiles()` to see if the folder / files still exist. It might be some weirdness with the console. I can also check if having a softDeletePolicy has any impact.

**Comment by vuduong97** [comment]
Hello @jezaman , i encountering an issue with the `deleteFolder` method from the `@google-cloud/storage-control` library, with Hierarchical namespace enabled. When I try to delete a folder, I encounter the error: "The folder you tried to delete is not empty." Below is the code snippet I am using:

```
async deleteFolder() {
    const res = await this.controlClient.deleteFolder({
      name: `projects/_/buckets/${this.bucketName}/folders/Content/test/`,
    });
    return "Delete folder successfully";
}
```
![image](https://github.com/user-attachments/assets/b4fc0151-2f22-4bcf-811a-3dc42cc21668)

Could you please provide some guidance on whether this method is designed exclusively for empty folders, or if there is a recommended approach for handling non-empty folders? Any assistance would be greatly appreciated.
Thank you for your support.

**Comment by ddelgrosso1** [comment]
Closing as I don't think there is anything else to be done. Please feel free to reopen if a question still remains.
