### ISSUE TITLE
Ship a new release

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#259]
This release has a lot of changes :) Can we cut a new release?

**Comment by stephenplusplus** [comment]
I sent an email called "Major breaking stuff" about this!

**Comment by frankyn** [comment]
What's major breaking?

**Comment by kinwa91** [comment]
rewritten in es6 class #246, thus no longer support node<6.

**Comment by frankyn** [comment]
Thanks for the context.

**Comment by AVVS** [comment]
I'd say thats still needed - Lots of deps are outdated in the released version at this point, at least an RC under @next would be great

**Comment by fhinkel** [comment]
Fixed by https://github.com/googleapis/nodejs-storage/pull/343
