### ISSUE TITLE
TypeScript conversion roadmap, discussion, timeline?

### ISSUE THREAD

**Issue by lukewlms** [googleapis/nodejs-storage#264]
I see check-ins for TypeScript conversion which are very exciting.  We plan to adopt Google Storage mainly b/c of dev productivity (only one of the Big Three to support promises now).  TS is another major draw.

Can we see a roadmap and discussion anywhere?  I'm looking around and I see fragmented convos but not a specific plan or timeline.

Thank you!

**Comment by stephenplusplus** [comment]
Hey @lukewlms! I don't believe we have a public roadmap anywhere. You can subscribe to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/952 and https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2821.

cc @JustinBeckwith in case he wants to provide any more information.
