### ISSUE TITLE
Delete Non empty bucket folder

### ISSUE THREAD

**Issue by ranjitnadar** [googleapis/nodejs-storage#278]
Code snippet

 ```
 storage.bucket(bucketName)
  .file(fileName)
  .delete()
  .then(res =>{
   cb(null,res);
  }).catch(e =>{
    console.log('bucket error ====>',e)
    cb(e, null)
  })
```

empty folder get delete, folder with files failed to delete.  Is there any option to force delete or any suggestion welcome

**Comment by stephenplusplus** [comment]
We have [`bucket.deleteFiles()`](https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/Bucket#deleteFiles), then you can call `bucket.delete()`. Let me know if this works!
