### ISSUE TITLE
createWriteStream({resumable:false}) causes error to be swallowed and program to hang

### ISSUE THREAD

**Issue by giltayar** [googleapis/nodejs-storage#312]
#### Environment details

  - OS: MacOS and Linux
  - Node.js version: 10.6.0
  - npm version: 6.1.0
  - `@google-cloud/storage` version: 1.7.0

#### Steps to reproduce

  1. Run the code below (before, change projectId and bucket in the code, and run `npm install @google-cloud/storage @rauschma/stringio`)
  2. It should fail with error code 429 (`rateLimitExceeded`), but instead the code never finishes. This is the problem. The program _should_ fail, because we're putting the same content in the same path too many times. (If you always put the text in random paths then everything works without a 429.)
  3. Comment out `resumable: false` and run it again
  4. It will fail with error code 429, as expected.

Code:

```js
'use strict'
const Storage = require('@google-cloud/storage')
const {StringStream} = require('@rauschma/stringio')

const projectId = 'rendering-grid'
const bucket = 'test-storage-problem-can-delete'

async function main() {
  const storage = new Storage({
    projectId,
  })

  const put = async () => {
    await new Promise((resolve, reject) => {
      const writeStream = storage
        .bucket(bucket)
        .file('foo/bar')
        .createWriteStream({
          resumable: false,
          metadata: {
            contentType: 'text/plain',
          },
        })

      writeStream.on('finish', resolve).on('error', reject)

      const readStream = new StringStream('some debugging text')

      readStream.on('error', reject)
      readStream.pipe(writeStream)
    })
  }

  for (let i = 0; i < 10; ++i) {
    console.log('#### Run #', i + 1)
    await Promise.all([...Array(10)].map(() => put().then(() => process.stdout.write('.'))))
    console.log('')
  }
}

main().catch(console.error)
```

So `{resumable: false}` is causing the program to hang, I'm guessing because it's not reporting the error on the stream.

**Comment by andreban** [comment]
I took a look at [file.js](https://github.com/googleapis/nodejs-storage/blob/master/src/file.js#L990-L998) and I think there's a possible fix. 

I think the issue seems to be tat that the stream to which the error is being emitted to is different from the one exposed to the user (eg: where stream.on('error', ...) is being called.

```javascript
const fileWriteStream = duplexify();
```

But the stream that is being returned to the user is 

```javascript
const stream = streamEvents(
      pumpify([
        gzip ? zlib.createGzip() : through(),
        validateStream,
        fileWriteStream,
      ])
    );
```
I noticed that a little below the code, event emitted to `fileWriteStream` and being replicated to `stream`. Example:

```javascript
fileWriteStream.on('response', stream.emit.bind(stream, 'response'));
```

I tested out doing the same thing for the error event, and it helps in my case (the code posted previously works):

```javascript
fileWriteStream.on('error', stream.emit.bind(stream, 'error'));
```
Are there other clean-ups that should be done instead of simply forwarding the event?

**Comment by stephenplusplus** [comment]
@andreban thank you for that investigation. It didn't resolve @giltayar's issue for me, unfortunately, and it seems unnecessary as pumpify will destroy the whole "pumpified" stream if any of them emit an error.

What I see when I run the original script is:

```sh
$ node .
#### Run # 1
..........
#### Run # 2
{ Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/stephen/dev/play/gissue-312/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:661:40)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5) code: 'ESOCKETTIMEDOUT', connect: false }
```

A long time goes by before the timeout (2 or 3 minutes), but the error that is coming from the request library *is* being reported.

So, I'm not sure why there is no error, but also no success. I'll keep looking. I just thought I'd share where I'm at so far.

**Comment by stephenplusplus** [comment]
Awesome, thank you for this research! 🙏

> Accept that streams can't be retried, and remove the retry attempts for non-resumable uploads.

Yes, sadly. Here's a related issue in the retry-request library about retrying POST requests: https://github.com/stephenplusplus/retry-request/issues/3#issuecomment-120428333.

I'm working on making this a single, untried request. I'll link you when I have a PR for review 👍

**Comment by stephenplusplus** [comment]
PR sent! https://github.com/googleapis/nodejs-common/pull/268

**Comment by zbjornson** [comment]
Looks good to me!

Since that changes the default though, does the number of retries need to be changed anywhere else?

**Comment by zbjornson** [comment]
@JustinBeckwith @stephenplusplus just want to make sure my question above doesn't get lost -- it looks like that PR *changed the  default* number of retries, so do non-zero retry values need to be set in this and other modules (for non-streaming requests obviously)?

**Comment by stephenplusplus** [comment]
The PR didn't change the default for all methods, only `util.makeWritableStream`, where we set the number of retries to 0, since retrying a POST is never possible.
