### ISSUE TITLE
Can't Override Content-Disposition to 'inline' in Firebase Storage with Admin SDK

### ISSUE THREAD

**Issue by ilyaigpetrov** [googleapis/nodejs-storage#321]
#### Environment details

  - OS: Lubuntu 18.04 (18.04.1 LTS)
  - Node.js version: v10.7.0
  - npm version: 6.1.0
  - `@google-cloud/storage` version: 1.7.0
  - `firebase-admin`: 5.13.1

#### Steps to reproduce

1. Upload an image with this code:
```js
'use strict';

const Admin = require('firebase-admin');
// How to get a key: https://firebase.google.com/docs/admin/setup#add_firebase_to_your_app
const serviceAccount = require('./path-to-your-key-file.json'); // Edit here!

Admin.initializeApp({
  credential: Admin.credential.cert(serviceAccount),
  storageBucket: 'PROJECT_NAME.appspot.com', // Edit here!
});

const bucket = Admin.storage().bucket();

const destination = 'images/test';
const photoUrl = 'https://some-site.com/some-path.jpg'; // Edit here!

const match = photoUrl.match(/^.+(\.[^.]+)$/);
const ext = match ? match[1] : '';
let contentType = 'application/octet-stream';
if (ext) {
  console.log('EXT', ext);
  contentType = {
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    png: 'image/png',
    gif: 'image/gif',
  }[ext.substr(1)] || contentType;
}
console.log('TYPE', contentType);
bucket.upload(photoUrl, {
  destination: `${destination}${ext}`,
  public: true,
  metadata: {
    contentType, // You may comment this line out, result is the same.
    contentDisposition: 'inline',
  },
}).then((data) =>
  console.log(data[1].mediaLink),
);
```
2. Open Chrome with devtools Network tab.
3. Paste the link from the script output into the address bar, open.
4. See headers like this:
```
content-disposition: attachment
content-type: image/jpeg
```
__Expected__: The image must be opened for viewing in browser, not downloaded.
__Actual__: The image is downloaded (because of wrong headers setup).

**Comment by stephenplusplus** [comment]
I believe you'll need to use a signed URL for this behavior. The `mediaLink` address appears to be meant for downloading, and also requires authorization to access (unless you made your bucket/file public).

A signed URL will create a unique URL for users to access, unrelated to the privacy of the Object in GCS. It will also inherit the metadata you set. To get a signed URL that opens in the browser, modifying the code above:

```js
const file = bucket.file(`${destination}${ext}`);

bucket.upload(photoUrl, {
  destination: file,
  metadata: {
    contentType, // You may comment this line out, result is the same.
  },
}).then(() =>
  file.getSignedUrl({
    action: 'read',
    expires: '12-31-2118',
  })
).then((data) =>
  console.log(data[0]),
);
```

Let me know if you have any issues with this approach!
