### ISSUE TITLE
Library not released yet and developers hitting new constructor issues.

### ISSUE THREAD

**Issue by frankyn** [googleapis/nodejs-storage#345]
Hi,
I'm following the new instructions while the v2.0.0 is not on [npmjs](https://www.npmjs.com/package/@google-cloud/storage) and hitting the following error. I received external dev feedback that they're hitting this as well.

#### Error
```javascript
TypeError: Storage is not a constructor
```

#### Environment details

  - OS: MacOS
  - Node.js version: v8.9.4
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 1.7.0

#### Steps to reproduce
Attempt to run the following quickstart.
```javascript
// Imports the Google Cloud client library
const {Storage} = require('@google-cloud/storage');

// Your Google Cloud Platform project ID
const projectId = 'YOUR_PROJECT_ID';

// Creates a client
const storage = new Storage({
  projectId: projectId,
});

// The name for the new bucket
const bucketName = 'my-new-bucket';

// Creates the new bucket
storage
  .createBucket(bucketName)
  .then(() => {
    console.log(`Bucket ${bucketName} created.`);
  })
  .catch(err => {
    console.error('ERROR:', err);
  });
```

**Comment by frankyn** [comment]
Looks like this is WIP in PR #344.

**Comment by fhinkel** [comment]
2.0.0 was released. So our Quick Start is correct again. Please re-open if closed in error.

**Comment by frankyn** [comment]
Forgot to close this, thanks @fhinkel!
