### ISSUE TITLE
"Cannot sign data without `client_email`" for getSignedUrl

### ISSUE THREAD

**Issue by pikelnys** [googleapis/nodejs-storage#360]
I'm trying to get a signed url from a storage bucket, but am getting a signing error. I have permission to read from the bucket, and have been able to stream its contents fine. 

Code:
```
  ...

  const expires = new Date()
  expires.setSeconds(expires.getSeconds() + 30)

  const storage = new Storage({ projectId });

  storage
    .bucket(bucketName)
    .file(`${directory}/${packageName}`)
    .getSignedUrl({
      expires,
      action: 'read',
    })
    .then(url => {
      res.send(url)
      console.log(url)
    })
    .catch(console.log)
```

Error:
```
{ SigningError: Cannot sign data without `client_email`.
    at /Users/pikelnys/Desktop/code/gcs-project/api/node_modules/@google-cloud/storage/src/file.js:1784:16
    at Auth._signWithApi (/Users/pikelnys/Desktop/code/gcs-project/api/node_modules/google-auto-auth/index.js:331:7)
    at getCredentials (/Users/pikelnys/Desktop/code/gcs-project/api/node_modules/google-auto-auth/index.js:316:14)
    at googleAuthClient.getCredentials (/Users/pikelnys/Desktop/code/gcs-project/api/node_modules/google-auto-auth/index.js:194:9)
    at /Users/pikelnys/Desktop/code/gcs-project/api/node_modules/google-auth-library/build/src/auth/googleauth.js:602:67
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) message: 'Cannot sign data without `client_email`.' }
```

#### Environment details

  - OS: macOS 10.13.4
  - Node.js version: 8.11.2
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 1.7.0

Edit: I'm getting this in both a local environment (where I authenticate with `gcloud auth application-default login`) and while the code is deployed to cloud functions.

**Comment by fhinkel** [comment]
I think `gcloud auth application-default login` doesn't support `client_email` and you need to get a [service account](https://cloud.google.com/storage/docs/authentication#service_accounts) instead. 

Here's a related issue: https://github.com/googleapis/nodejs-storage/issues/116.

**Comment by pikelnys** [comment]
I'm getting it on Cloud Functions, though, which I believe is a service account.

**Comment by kinwa91** [comment]
I tried to reproduce it on Cloud Functions, but was able to generate signed URL from the code provided.

Default service account in Cloud Functions should have a client_email `{{project_id}}@appspot.gserviceaccount.com`. The only thing I had to do was to add `Service Account Token Creator` role to the service account from IAM.

**Comment by kinwa91** [comment]
Can you provide the error you got when running the code under Functions?

**Comment by pikelnys** [comment]
I did something soon after my original post to get it working on Functions. But I'm still getting this error locally.

**Comment by ujwalkagrawal** [comment]
Hi @pikelnys.

You will have to specify **keyFilename** while creating the **Storage** object if you are deploying locally.

**keyFilename** is not required if you have deployed your code under the same project your Google Cloud Bucket was created. You just have to ensure you have the right access by having a look at your service-account-key.

[This is well explained here](https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-nodejs)



**Steps to Follow.**

Download the service account key in JSON format and specify its path inside keyFilename. Default service-account-key provided by Google has read-only access. So make sure if you want to write to your bucket you would have to change the permissions inside the service-account.

[Here is the 
Google Codelab link for reference](https://codelabs.developers.google.com/codelabs/cloud-nodejs/index.html?index=..%2F..%2Findex#7)

```
var storage = new Storage({
  projectId: "your project id",
  keyFilename:"your-service-account-key.json"
});
```

Hope this resolves your issue.

**Comment by kinwa91** [comment]
@ujwalkagrawal, thanks for posting such detailed explanation on service account credentials!

@pikelnys we hope this resolves your issue, please re-open if you run into anymore issues :)

**Comment by barocsi** [comment]
Is this possible to authenticate without a keyfile?

**Comment by christiangenco** [comment]
I was getting "Cannot sign data without `client_email`" error when running `firebase emulators:start`.

I fixed it by [setting up a service account and downloading the service account .json credentials file](https://cloud.google.com/storage/docs/reference/libraries#setting_up_authentication) as `service_account.json`, then running `GOOGLE_APPLICATION_CREDENTIALS="service_account.json" firebase emulators:start`

**Comment by ollydixon** [comment]
Service account isn't good for multi-stage environments and security. This should be reopened.

**Comment by deimantasa** [comment]
BUMP as there isn't seem to be a way to deal with it via `emulator` without exposing `dev`/`prod` configs.

**Comment by dwanderton** [comment]
Bump. Firebase emulator should emulate the environment, this appears to be a failure state

**Comment by ddelgrosso1** [comment]
Hi @dwanderton thank you for bumping this. In reading your comment and the last few, it appears the feeling is that there is incorrect behavior in the Firebase emulator. If so, I would encourage you to open an issue with the Firebase CLI repository. That repository is at: https://github.com/firebase/firebase-tools

**Comment by timbuckiii** [comment]
For anyone else that comes across this issue, here is a bit more info for posterity.

The [GCP client libraries docs](https://cloud.google.com/docs/authentication/client-libraries) use the Storage libary _as the example_ when leveraging ADC locally. The same docs also call out the fact that using service accounts locally is bad practice (see the Note in [this section](https://cloud.google.com/docs/authentication/provide-credentials-adc#local-key)).

However, for some reason Google contradicts itself with the implementation of the `getSignedUrl` method and its corresponding endpoint. After a couple hours of debugging and re-reading the disparate and disconnected docs scattered all over the place, I found the source of the issue as documented [here](https://cloud.google.com/storage/docs/access-control/signed-urls#types). V4 (and the legacy V2) signing **requires** usage of a service account.

It would be nice if Google would have bothered to call this out in the ADC docs where they use Storage as an example, or better yet, return the relevant instructions in the SigningError message, especially because they contract themselves within the different docs on related topics. 

Hope this helps someone!

**Comment by ollyde** [comment]
Indeed many of the google services use the less secure credentials initialization; you think they’d be on top of this with some simple version updates; but I’m seeing nothing being update for years and incorrect documentation everywhere.

**Comment by tritone** [comment]
Hey @timbuckiii and @ollyde , just wanted to note a couple things:

1. GCS does in fact support signing without having a local service account key file by using a GCE workload identity or service account impersonation to call [signBlob](https://cloud.google.com/storage/docs/access-control/signed-urls#signing-iam). I definitely see that this could be clearer in the GCS docs and will file an internal issue to improve this.
1. The nodejs-storage library in particular does not yet have support for signing via service account impersonation. However, there is an open issue for this in the node auth library. Comment or follow along at googleapis/google-auth-library-nodejs#1443

Also, in the future, if you could open a new issue for any problems rather than commenting on a closed one, that would help us respond faster. Thanks!

**Comment by timbuckiii** [comment]
Thanks @tritone, appreciate the response!

**Comment by jtrenton21** [comment]
I recently wrote a Medium article describing a workaround I created for local development. There is also a git repo with my solution. [Article](https://medium.com/@trentonliebman/generating-local-auth-tokens-for-service-accounts-with-node-js-gcp-3e61811fc6e0) | [Repo](https://github.com/jtrenton21/sa-local-token-generation)
I use IAM Credentials API coupled with a cloud function. Hope this helps someone.

**Comment by ollyde** [comment]
@tritone indeed many of the libraries are suppose to refer to the internal meta-services APIs first but they don't and they are not being updated. 
Right now GCP has a huge issue with almost nothing being updated, we have over 100 tickets over 4 years and not one of them has been addressed, simple things like "Enabling PNG for trans-coder service, which is an easy task, nadda"

**Comment by gbersac** [comment]
Got the issue and solved it thanks to this solution firebase-adminsdk-ov3eh@staging-louve.iam.gserviceaccount.com
thanks @christiangenco

**Comment by howlettga** [comment]
I don't think you should switch to a json keyfile. I just added an npm command to add the `client_email` to the application default credentials after login using the json lib.

```sh
npm install --save-dev json
```

```package.json
"scripts": {
  ...
  "login": "gcloud auth application-default login {EXTRA_ARGUMENTS}",
  "update-client-email": json -I -f ~/.config/gcloud/application_default_credentials.json -e 'this.client_email=\"{MY_EMAIL}\"'"
}
```

**Comment by boarush** [comment]
@howlettga I have tried using the solution you suggest by adding in a `client_email` field to the existing ADC, but that doesn't seem to work now. Were you able to get it to work?

The only way I can get it working currently is by passing in a service account key when using locally to generate a Signed URL.

**Comment by howlettga** [comment]
@boarush yes it works for me. I am using a service account intentionally when logging in the application default credentials (using the `--impersonate-service-account` argument). But I don't think using a service account is dependent on this error.

This error is specific to the missing `client_email`. In my case, I am relying on `application_default_credentials.json` for authentication so this is where it needs to be defined. My understanding is that `gcloud auth application-default login` does not set `client_email` and in fact removes it from the json file. Most authenticated tasks do not require this field and I believe that it is guaranteed to be set when running on an actual google cloud environment. However, SignedURL activities require the field which then would not be set simply by using the login command locally.

So whatever authentication method you already use should work. If you can do things like Decode Id Tokens and stuff, but not sign urls because of this error, you simply need to ensure the `client_email` field is populated to the source of the credentials each time you authenticate.

Ultimately, I don't believe this library is the proper place for this error. It really has to do with the gcloud cli initialization. It might not even be an error, but a missing configuration command. I haven't played around with the `gcloud config configurations create` or `gcloud auth activate-service-account` commands or read thoroughly through all that documentation.

**Comment by AlvesJorge** [comment]
bump. this should be re-opened.

**Comment by adamsiwiec1** [comment]
Double bump.  There's not a great firebase-admin solution for this when running in the emulator without using a service account json. It's messy, insecure, and inconvenient for testing... 

 It's really easy on the frontend with Firebase Auth. Ex:
```
  const imageListRef = ref(storage, `${currentUser?.uid}/story_images/${story.id}.png`);
  try {
      story.imageBlobUri = await getDownloadURL(imageListRef);
  } catch (error) {
      story.imageBlobUri = undefined;
  }
  readyStories.push(story);
```

**Comment by ddelgrosso1** [comment]
I see a few bumps on this old issue so wanted to leave a comment. It seems that the issue most are bumping about is trying to sign using ADC which does not include the `client_email` field. Unfortunately, this library does not own the JSON file produced during login nor the signing process. Signing with impersonation should now work and might be one alternative to explore.

If there is a different issue, I would ask that you open a new issue so that I can investigate / resolve as appropriate.

**Comment by nidegen** [comment]
For me it is while using firebase emulator, I just want to be able to sign local storage URLs. Nothing cloud side. Everything just local!

**Comment by DanielFrageri** [comment]
Any workaround?

**Comment by dinkel-katilyst** [comment]
> I see a few bumps on this old issue so wanted to leave a comment. It seems that the issue most are bumping about is trying to sign using ADC which does not include the `client_email` field. Unfortunately, this library does not own the JSON file produced during login nor the signing process. Signing with impersonation should now work and might be one alternative to explore.
> 
> If there is a different issue, I would ask that you open a new issue so that I can investigate / resolve as appropriate.

@ddelgrosso1 So are you saying this library doesn't work with ADC?

**Comment by ddelgrosso1** [comment]
> > I see a few bumps on this old issue so wanted to leave a comment. It seems that the issue most are bumping about is trying to sign using ADC which does not include the `client_email` field. Unfortunately, this library does not own the JSON file produced during login nor the signing process. Signing with impersonation should now work and might be one alternative to explore.
> > If there is a different issue, I would ask that you open a new issue so that I can investigate / resolve as appropriate.
> 
> @ddelgrosso1 So are you saying this library doesn't work with ADC?

That is not what I was saying. ADC works fine outside of signing. 

This library doesn't own or produce the ADC credentials. If the ADC credentials do not contain the `client_email` field necessary for signing there isn't anything from the library perspective to be fixed. Additionally, this library hands off the actual signing to https://github.com/googleapis/google-auth-library-nodejs. So both the credentials and the auth library would need to support this in order for storage to utilize it.

**Comment by howlettga** [comment]
> Adding my "client_email" to the ADC file didn't work for me either. That gives me the error: `Gaia id not found for email XXXXX`. 

Yeah I can see that logging in with my admin user doesn't seem to configure the ADC to properly pull the Gaia id. May as well just impersonate a service account that is properly configured `--impersonate-service-account=<service.account@email>`

**Comment by pikelnys** [comment]
I can't believe it's been six years since I ran into this issue and it's still not resolved. Since then, I found a work around for the issue, the project died, I quit that job, and the company went out of business.

**Comment by dinkel-katilyst** [comment]
I think impersonating the service account is the answer for local development. It doesn't have the security concerns that using a service account key does. It also has the benefit of using the actual deployed account, so you are confirming it is set up correctly. Was a breeze to do.

See:
https://cloud.google.com/docs/authentication/use-service-account-impersonation#adc

**Comment by dinkel-katilyst** [comment]
Nevermind. 

I thought it wasn't erroring, but that's because it's now no longer getting to the signing code. For me, account impersonation is failing even earlier, when I call `bucket(x).file(y).exists()` - something that doesn't happen in the deployed environment using that service account. 

I'm getting:  `The incoming JSON object does not contain a client_email field.` 

If I skip the exists() check, `.getSignedUrl()` give me the same error.

Checking the `application_default_credentials.json` file, it still doesn't have a `client_email` value in it.

My hunt for a working solution continues. 🤕 

> > > I see a few bumps on this old issue so wanted to leave a comment. It seems that the issue most are bumping about is trying to sign using ADC which does not include the `client_email` field. Unfortunately, this library does not own the JSON file produced during login nor the signing process. Signing with impersonation should now work and might be one alternative to explore.
> > > If there is a different issue, I would ask that you open a new issue so that I can investigate / resolve as appropriate.
> > 
> > 
> > @ddelgrosso1 So are you saying this library doesn't work with ADC?
> 
> That is not what I was saying. ADC works fine outside of signing.
> 
> This library doesn't own or produce the ADC credentials. If the ADC credentials do not contain the `client_email` field necessary for signing there isn't anything from the library perspective to be fixed. Additionally, this library hands off the actual signing to https://github.com/googleapis/google-auth-library-nodejs. So both the credentials and the auth library would need to support this in order for storage to utilize it.

That makes total sense. Have any issues been submitted to anyone else for this? I'd love to take this discussion to someone else's repo instead who could actually fix it. I think you're in the best position to write up what needs to be fixed in which repo and also influence the rest of the googleapis team.

In the meantime, you've got a known broken use case and the errors that are bubbling up out of your library don't make sense in the context of your library. Is that a valid bug worth having an open issue for?

**Comment by ddelgrosso1** [comment]
> That makes total sense. Have any issues been submitted to anyone else for this? I'd love to take this discussion to someone else's repo instead who could actually fix it. I think you're in the best position to write up what needs to be fixed in which repo and also influence the rest of the googleapis team.
> 
> In the meantime, you've got a known broken use case and the errors that are bubbling up out of your library don't make sense in the context of your library. Is that a valid bug worth having an open issue for?

@dinkel-katilyst I found [this public issue](https://b.corp.google.com/issues/262700869) that was filed against `gcloud cli`. For yourself and anyone else, I would suggest making additional noise on that issue to try and get it visible again. In the meantime I found the same issue internally and I will reach out to the team and link them to this issue. Can't promise anything, but I'll try what I can to get this either fixed or rationale why it was never done.

**Comment by howlettga** [comment]
> Checking the `application_default_credentials.json` file, it still doesn't have a `client_email` value in it.
> 
> My hunt for a working solution continues. 🤕

@dinkel-katilyst if you just add `client_email` of the impersonated service account after signing in (which will clear the client_email), this is the quickest workaround. I automated it as a single npm command in my previous solution

**Comment by dinkzilla** [comment]
@ddelgrosso1 The link you shared doesn't appear to be public.

@howlettga adding the `client_email` manually to the `application_default_credentials.json` file changes the error to `The incoming JSON object does not contain a private_key field`.

Something else I just stumbled upon: it appears that the python version of this library was able to fix what looks like the same issue themselves. I've tried to read it and figure out how, but I don't think my python skills are good enough. Or maybe it's not quite the same issue. Might be worth a look tho. 

https://stackoverflow.com/a/74116712/4839461
https://github.com/googleapis/python-storage/issues/355

**Comment by ddelgrosso1** [comment]
> @ddelgrosso1 The link you shared doesn't appear to be public.

Try this [link](https://issuetracker.google.com/262700869). Please let me know if this does not work. Also updated in my previous comment.

**Comment by dinkzilla** [comment]
That one worked!

**Comment by howlettga** [comment]
@dinkzilla so then you are resolving the error in this thread... And sounds like you have a separate error initializing the `Storage` library in a way where it is expecting a private key. You shouldn't initialize the client library with a `keyFilename` parameter if you are using ADC. The README of this repo shows initialization options. Or provide your code.

**Comment by howlettga** [comment]
Just realized the [previously linked issue](https://github.com/googleapis/google-auth-library-nodejs/pull/1694) was merged in last year and the `client_email` issue was resolved (no longer required) for impersonated service accounts. I just updated my library version and can confirm no workaround is necessary anymore. Adding my version info for posterity:

```
Google Cloud SDK 495.0.0
bq 2.1.8
core 2024.09.27
gcloud-crc32c 1.0.0
gsutil 5.30
Node.js v20.11.0

"@google-cloud/storage": "^7.13.0"
```

**Comment by dinkel-katilyst** [comment]
Thank you so much @howlettga ! an upgrade made it work for me too! 🕺 Many thanks!

**Comment by ddelgrosso1** [comment]
Circling back. I spoke with the teams who own the login / writing of the ADC JSON file. This isn't just a matter of adding a `client_email` to the JSON as this alone would not allow for signing. It would require involvement of HMAC keys and from what I was told this is beyond the scope of ADC. 

The best course of action is to utilize SA impersonation for signing in these situations.

**Comment by superjose** [comment]
Jeez. Enabling OIDC has been a massive challenge with the garbage documentation out there. 

Anyhow, after **hours** of fighting, here's how I could sign the URL using service account impersonation:


1st. Create the service account:

```bash
gcloud iam service-accounts create "local-dev-account" \
    --description="Local Development Account" \
    --project="${YOUR_PROJECT_ID}" \
    --display-name="Local Development Account"
```

2nd. Create the `local_dev_role` that will be attached to the service account:

```bash
gcloud iam roles create "local_dev_role" \
 --project="${YOUR_PROJECT_ID}" \
 --file="./roles-local.gcp.yml"
````

roles-local.gcp.yml:
```
# gcloud iam roles update local_dev_role --project=alertdown-staging --file=./roles-local.gcp.yml
# https://stackoverflow.com/a/68901952/1057052
# We are currently using Workload Identity Federation to authenticate. This means that there are no service keys passed
# around.
# Therefore, we need another mechanism to authenticate when developing locally.
# In Production, services are authenticated via IAM directly.
# This files contains only the minimum set of permissions required to access the development environment.
# We will generate a local JSON file that will serve as an impersonation to a service account.
# Required roles:

title: Local Development Roles
description: |
  This policy is for local development as Google discourages the usage of service account keys. This will work for impersonation
stage: GA
# https://cloud.google.com/iam/docs/permissions-reference
includedPermissions:
  # Permissions for GCR
  - storage.objects.create
  - storage.objects.delete # Optional: only include if you need to delete images
  - storage.objects.get
  - storage.objects.list
  - storage.objects.update
  - storage.objects.getIamPolicy
  - storage.objects.setIamPolicy
  # Add these permissions for token management
  - iam.serviceAccounts.getAccessToken
  - iam.serviceAccounts.signBlob # Required for signed URLs
  # Add more permissions as needed
```

3rd. Attach the service account at the **project level**

```bash
gcloud projects add-iam-policy-binding ${YOUR_PROJECT_ID} \
 --member="serviceAccount:local-dev-account@${YOUR_PROJECT_ID}.iam.gserviceaccount.com" \
 --role="projects/${YOUR_PROJECT_ID}/roles/local_dev_role" \
 --project="${YOUR_PROJECT_ID}"
```

Note: There's a similar command called `gcloud iam service-accounts add-iam-policy-binding`.... Don't! This will not work.

4th. Impersonate the service account:
```bash
gcloud auth application-default login --impersonate-service-account=local-dev-account@alertdown-staging.iam.gserviceaccount.com
```

If that didn't work, and you're getting errors about the account not getting impersonated:

Attach the `roles/iam.serviceAccountTokenCreator` to YOUR email address:

```bash
gcloud iam service-accounts add-iam-policy-binding \
    local-dev-account@${YOUR_PROJECT_ID}.iam.gserviceaccount.com \
    --member="user:your-logged-in-user@email.com" \
    --role="roles/iam.serviceAccountTokenCreator" \
    --project="${YOUR_PROJECT_ID}"

gcloud iam service-accounts add-iam-policy-binding \
    local-dev-account@${YOUR_PROJECT_ID}.iam.gserviceaccount.com \
    --member="user:your-logged-in-user@email.com" \
    --role="roles/iam.serviceAccountUser" \
    --project="${YOUR_PROJECT_ID}"
```

And just for the sake of completeness: Here's the full Storage class wrapper I've created in Node:

```ts
import {
  InternalServerException,
  PromiseExceptionResult,
} from '@alertdown/core';
import { Storage as GoogleCloudStorage } from '@google-cloud/storage';
import { Err, Ok } from 'oxide.ts';

const getFileUrl = (bucket: string, filename: string) => {
  return `https://storage.googleapis.com/${bucket}/${filename}`;
};

type ConstructorInput = {
  bucket: string;
  /**
   * Development only
   */
  projectId?: string;
};

export class Storage {
  #client: GoogleCloudStorage;
  #bucket: string;

  constructor(input: ConstructorInput) {
    this.#client = new GoogleCloudStorage({
      projectId: input.projectId,
    });
    this.#bucket = input.bucket;
  }

  async upload(file: Buffer, filename: string): PromiseExceptionResult<string> {
    try {
      const bucket = this.#client.bucket(this.#bucket);
      const blob = bucket.file(filename);

      await blob.save(file, {
        metadata: {
          contentType: 'image/png',
        },
      });
      return Ok(getFileUrl(this.#bucket, filename));
    } catch (error) {
      return Err(new InternalServerException(error as Error));
    }
  }

  async resolveUrl(url: string): PromiseExceptionResult<string> {
    try {
      const parsedUrl = new URL(url);
      const filename = parsedUrl.pathname.split('/').pop();
      console.log((await this.#client.authClient.getClient()).credentials);

      if (!filename) {
        return Err(new InternalServerException('Invalid URL format'));
      }

      const bucket = this.#client.bucket(this.#bucket);
      const file = bucket.file(filename);
      const [signedUrl] = await file.getSignedUrl({
        version: 'v4',
        action: 'read',
        expires: Date.now() + 15 * 60 * 1000, // 15 minutes
      });
      return Ok(signedUrl);
    } catch (error) {
      console.error(`Error resolving URL: ${url}`, error);
      return Err(new InternalServerException(error as Error));
    }
  }
}
```

Note:
See that I only pass the `projectId` (YOUR_PROJECT_ID) and the bucket name.

## Additional Notes:

* [List of Permissions - Google Cloud](https://cloud.google.com/iam/docs/permissions-reference)
* [View Roles Permissionshttps://console.cloud.google.com/iam-admin/roles) (You can view the individual roles permissions here. Then you can add it to your yam file as needed)
* Every time you update a permission, if it doesn't work for any reason, try reauthenticating. 

## Helpful Commands For Debugging:
1. Check if the role exists and its permissions
```bash
gcloud iam roles describe local_dev_role \
    --project=${YOUR_PROJECT_ID}
```
2. Verify if the role is attached to the service account:
```bash
gcloud projects get-iam-policy ${YOUR_PROJECT_ID} \
    --filter="bindings.members:local-dev-account@${YOUR_PROJECT_ID}.iam.gserviceaccount.com" \
    --format="table(bindings.role)"
```
3. Command to update the role from the yaml (roles-local-gcp.yml)
```bash
gcloud iam roles update local_dev_role \
    --project=${YOUR_PROJECT_ID} \
    --file=./roles-local.gcp.yml
```

**Comment by michalmokros** [comment]
@superjose thank you so much, it works, btw I think in step 4. you used the actual PROJECT_ID: `alertdown-staging` instead of the variable ${PROJECT_ID}
