### ISSUE TITLE
Included TypeScript declaration files not working

### ISSUE THREAD

**Issue by welkie** [googleapis/nodejs-storage#372]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 8.11.4
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 2.0.0

#### Steps to reproduce

  1. Create a new TypeScript Node.js project (with `npm init` and `npm i -D typescript`)
  2. Install the library with `npm i @google-cloud/storage`..
  3. Import the library in a source code file with `import Storage from '@google-cloud/storage'`.

I notice that the library is now coded in TypeScript and that the declaration files are included in the published NPM package. However, when I try to use the library in a TypeScript project without installing the `@types` package, which should now be deemed deprecated, I get an error message from the TypeScript compiler saying that it can't access the declaration files:

```
[ts]
Could not find a declaration file for module '@google-cloud/storage'. '/home/matt/cloud-storage-ts-test/node_modules/@google-cloud/storage/build/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/google-cloud__storage` if it exists or add a new declaration (.d.ts) file containing `declare module 'google-cloud__storage';`
```
Is the work to port the library over to TypeScript still a work in progress? If it's considered complete, there is likely an issue with the configuration for the type definition file generation.

Here's an [example repo](https://github.com/welkie/issue-example-ts-google-cloud-storage) that reproduces the problem. It will not compile with the project TypeScript compiler. The command `npm run build` will fail.

**Comment by kinwa91** [comment]
The release #375 should fix this.

**Comment by sal-g** [comment]
@jkwlui  I have the same issue with using @google-cloud/vision

**Comment by welkie** [comment]
@sal-g Looks like they have a repo for the Vision NPM package: https://github.com/googleapis/nodejs-vision

I'd suggest raising an issue there.
