### ISSUE TITLE
Support crypto without a key file

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#39]
*From https://github.com/GoogleCloudPlatform/google-cloud-common/issues/180*

Calls requiring crypto, such as `file.getSignedUrl()` currently do not work automatically-authenticated environments, because values of a service account's JSON key file are required. However, [it's possible to query the metadata server for those values](https://github.com/GoogleCloudPlatform/google-cloud-common/issues/180#issuecomment-327884883):

```
curl -H 'Metadata-Flavor: Google' -vs 'http://metadata/computeMetadata/v1/instance/service-accounts/default/' 2>&1
```
Which will give you something like:
```
aliases
email
scopes
token
```
Implying
```
http://metadata/computeMetadata/v1/instance/service-accounts/default/aliases
http://metadata/computeMetadata/v1/instance/service-accounts/default/email
http://metadata/computeMetadata/v1/instance/service-accounts/default/scopes
http://metadata/computeMetadata/v1/instance/service-accounts/default/token
```

**Comment by keplersj** [comment]
What would it take to get this fixed? I'd love to use this functionality in my GCF endpoint

**Comment by aaronkchsu** [comment]
I'd love to see this get fixed too! I want to use it in my GCF endpoint as well! Can we get someone on this?

**Comment by stephenplusplus** [comment]
Opened an issue on google-auth-library: https://github.com/google/google-auth-library-nodejs/issues/169

**Comment by rendaw** [comment]
Hello, is there any more documentation on this?  I'm running in a function and getting the inspecific error "Failure from metadata server."  Digging into the code, the metadata for the function doesn't have the defaults `key` (or `email`).

All my googling failed to indicate any information on that key, or a way to change the service account in case one configured differently is needed (it's using the default service account).  I couldn't find any general cloud documentation on usage of scopes either, but I enabled the IAM api for the project.
