### ISSUE TITLE
Un-skip system-test

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-storage#393]
Saw that we're skipping this `system test`: https://github.com/googleapis/nodejs-storage/blob/8b73cfc1c60a128b2a1ed6425eefa8b76e0cb336/system-test/storage.js#L1387

```
// @TODO: There may be a backend bug here.
// Reference: https://github.com/googleapis/nodejs-storage/pull/190#issuecomment-388475406
it.skip(...)
```
    
Looking at the issue, it should be fine to run the test again.

**Comment by stephenplusplus** [comment]
It's not safe to run just yet: https://github.com/googleapis/nodejs-storage/pull/251#issuecomment-419625053

**Comment by frankyn** [comment]
I'm working on resolving this with the GCS team. Pending fix being released to prod at the moment.

Bug=79524739
