### ISSUE TITLE
Use EcmaScript Object.assign instead of extend

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-storage#394]
If possible, we should use `Object.assign` instead of relying in `extend`. 

So, instead of
```JavaScript
options = extend({metadata: {}}, options);
```
let's use standard ES6:
```JS
options = Object.assign({metadata: {}}, options);
```

**Comment by JustinBeckwith** [comment]
It sorta depends.  `Object.assign` only clones properties that are 1 level deep.  `extend` does a deep clone by default (I believe).  We have to be selective/careful about where we do this 🤷‍♂️

**Comment by fhinkel** [comment]
Yes, why I didn't do it and instead opened an issue  😆.

**Comment by fhinkel** [comment]
`Object.assign` is shallow. But most of the time our `options` are strings and not objects, so it should be fine. And we have tests, right?

**Comment by JustinBeckwith** [comment]
sounds good to me :) Was always too scared to try doing this 😆

**Comment by stephenplusplus** [comment]
I believe we accept options for things like `metadata`. Our tests try to cover that we don't modify a user's object, but I can't guarantee it's in every method. This would be a good time to seal those gaps, though!

**Comment by JustinBeckwith** [comment]
This happened in all of the places where it was feasible in #469!
