### ISSUE TITLE
Migration from v1 to v2 Unclear

### ISSUE THREAD

**Issue by MarkHerhold** [googleapis/nodejs-storage#395]
I'm trying to upgrade this module from v1.6.0 to v2.0.3 and have read the [CHANGELOG](https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md#bucketupload-method-removed) on how to migrate from `bucket.upload()` to using a file stream.

I'm not sure how to set the metadata and public options on the new file with the new API.

#### Old code:
```js
await bucket.upload(myFilePath, {
    destination: `some/deeply/nested/file.png`,
    public: true,
    metadata: {
        cacheControl: 'public, max-age=7776000',
        contentType: 'image/png',
        metadata: {
            'arbitraryData': '123abc'
        }
    }
})
```

Any guidance would be appreciated. Thanks!

#### Environment details
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 2.0.3

**Comment by stephenplusplus** [comment]
Hello! Here's a conversion that should work:

```js
const fs = require('fs')

function upload(filePath, options) {
    return new Promise((reject, resolve) => {
        const file = bucket.file(options.destination)

        fs.createReadStream(filePath)
            .on('error', reject)
            .pipe(file.createWriteStream(options))
            .on('error', reject)
            .on('finish', resolve)
    })
}

await upload(myFilePath, {
    // Full list of options:
    // https://cloud.google.com/nodejs/docs/reference/storage/latest/File#createWriteStream
    destination: `some/deeply/nested/file.png`,
    public: true,
    metadata: {
        cacheControl: 'public, max-age=7776000',
        contentType: 'image/png',
        metadata: {
            'arbitraryData': '123abc'
        }
    }
})
```

Let me know if there are any issues!

**Comment by MarkHerhold** [comment]
@stephenplusplus Brilliant, thank you!

One minor issue for future readers - the code above has the `new Promise()` signature args swapped. Should be `(resolve, reject)`.

**Comment by stephenplusplus** [comment]
Oops, thank you! I'll update that 👍
