### ISSUE TITLE
Docs on cloud.google.com are out of date

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-storage#405]
After 2.0 shipped, we didn't update the reference docs on cloud.google.com:
https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/

**Comment by JustinBeckwith** [comment]
@crwilcox just checking in - did this happen?

**Comment by crwilcox** [comment]
@JustinBeckwith the docs rollout happened yesterday. I haven't closed this yet as 
1) there are outstanding updates for a few libraries.
2) A report came in via Slack that some content isn't included in the latest generation of 2.0.x docs for storage.

**Comment by crwilcox** [comment]
https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/File and other storage docs are now up to date.
