### ISSUE TITLE
High latency on first readStream of a series.

### ISSUE THREAD

**Issue by JAciv** [googleapis/nodejs-storage#414]
#### Environment details

- OS: Windows 7
- Node.js version: 10.11.0
- yarn version: v1.9.4
- `@google-cloud/storage` version: 2.0.3

#### Steps to reproduce

1. Define storage and bucket when node starts:

    ```ts
    const storage = new Storage({
        projectId: projectID,
    });

    // See: https://github.com/googleapis/nodejs-storage/issues/101
    storage.interceptors.push({
        request: reqOpts => {
            reqOpts.forever = true
            return reqOpts
        }
    });

    const hotBucketName = 'sampleName';
    const hotBucket = storage.bucket(hotBucketName);

    function getHotBucket() {
        return hotBucket;
    }
    ```

2. At a later time (when petitions are handled) use the bucket, get the File, create a readStream and read:

    ```ts
    const bucket = getHotBucket();

    let name: string = "sampleFile"; // Existing file.

    const file = bucket.file(name);

    const rdStrm = file.createReadStream({ validation: "crc32c" });

    let once = true;
    console.log("start");
    rdStrm.on('data', (chunk) => {
        if (once) {
            console.log("First on('data')");
            once = false;
        }
        // Do stuff, like passing the data to the client, saving a file, etc...
    });
    reader.on('end', () => {
        console.log("End");
        // Do other stuff
    })
    ```

So, I usually do this in sequence for multiple files as requests come in (the code shown is a simplified version). And the first of a series takes unusually long to fire the first *.on('data')*. Even up to 10 seconds. After that the next files that are requested take only a few ms.

**Comment by stephenplusplus** [comment]
Hey @JAciv, I just ran a quick test to see if I could reproduce, and I'm not seeing the same speed delays you are. Here is the script I am using:

```js
'use strict'

const {Storage} = require('@google-cloud/storage')
const storage = new Storage()

storage.interceptors.push({
  request: reqOpts => {
    reqOpts.forever = true
    return reqOpts
  }
})

const bucket = storage.bucket('stephen-has-a-new-bucket')
const file = bucket.file('daw.jpg')

const rdStrm = file.createReadStream({ validation: 'crc32c' })

console.time('First data event')

rdStrm
  .once('data', () => console.timeEnd('First data event'))
  .on('end', () => console.log('End'))
```

I'm on a slow, public wifi connection, and seeing between 800ms and 1600ms.

I wonder if the slowdown has to do with the environment your code is running in, and/or the authentication token fetching step that is performed at the time of the first API request. For the first request, one of our dependencies tries to resolve where your credentials will come from, starting with an environment variable pointing to a file. It could be worth trying to provide a service account JSON key file directly to see if it improves the speed:

```diff
- const storage = new Storage()
+ const storage = new Storage({
+   keyFilename: '/path/to/keyfile.json'
+ })
```

**Comment by JAciv** [comment]
Thanks for the swift response @stephenplusplus 

It seems that passing building the storage with the JSON key file does improve the response time. Up until now I've been using the environment variable to handle the authentication.  Any ideas on how to debug this?

**Comment by stephenplusplus** [comment]
I believe the library that would need the most debugging is [google-auth-library](https://github.com/googleapis/google-auth-library). Maybe an easier way forward is to see if you can produce the slow speeds when using only that library. Something like:

```js
const {auth} = require('google-auth-library')

// @TODO: replace with a path to your key file
const KEY_FILENAME = '/Users/stephen/dev/key.json'

function getAutoClient() {
  return auth.getClient({
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  })
}

function getKeyFileClient() {
  return auth.getClient({
    KEY_FILENAME,
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  })
}

async function getTimeDifference() {
  const run1StartTime = Date.now()
  await getAutoClient()
  const autoClientRunTime = Date.now() - run1StartTime

  const run2StartTime = Date.now()
  await getKeyFileClient()
  const keyFileClientRunTime = Date.now() - run2StartTime

  if (keyFileClientRunTime > autoClientRunTime) {
    console.log(`Fetching the key file client took ${keyFileClientRunTime - autoClientRunTime}ms longer`)
  } else {
    console.log(`Fetching the auto client took ${autoClientRunTime - keyFileClientRunTime}ms longer`)
  }
}

getTimeDifference().catch(console.error)
```

For me, the auto client always take 5-7ms longer. It would be interesting if something about Windows 7 could be causing a larger time difference here.

Let me know what you find!

**Comment by JAciv** [comment]
Welp, after running your code snippet on two machines (local and server) I get the same results you get.

5-6ms on average, sometimes a 30+ms spike but nothing notable.
