### ISSUE TITLE
Invalid credentials results in empty list rather than error

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-storage#415]
In 1.7, you would get an error if the credentials are invalid. Now the `getBuckets()` promise is resolved and it looks like you have no buckets. Is that behavior intended? I can't find it anywhere in the docs. 

```
const Storage = require('@google-cloud/storage');

  // Invalid credentials
  const storage = new Storage({
    keyFilename: '/Users/foo.json'
  });

  // Makes an authenticated API request.
  storage
    .getBuckets()
    .then((results) => {
      const buckets = results[0];

      console.log('Buckets:');
      buckets.forEach((bucket) => {
        console.log(bucket.name);
      });
    })
    .catch((err) => {
      console.error('ERROR:', err);
      console.log('such error');
    });
```

**Comment by stephenplusplus** [comment]
In 2.0.3, if these aren't set:

- keyFilename
- env var `GOOGLE_APPLICATION_CREDENTIALS`

I get an error:

```
Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

What is invalid about the `/Users/foo.json` file?

**Comment by fhinkel** [comment]
The file doesn't exist. I'm passing in the `keyfilename`, it shouldn't look for default credentials.

**Comment by fhinkel** [comment]
I think it depends on the application default credentials that we fall back to for auth. The system tests that's checking that credentials are wrong is failing for me after the update because it's printing the empty list instead of the expected error.

**Comment by fhinkel** [comment]
Edit: I'm assuming it's falling back to a different account locally, which doesn't have a bucket with the specified name - so it's not 403 or no result. Never mind.

**Comment by barocsi** [comment]
Can you only provide a keyfilename? Or a credentials objects according to this: https://github.com/googleapis/google-cloud-node/blob/master/docs/authentication.md,
