### ISSUE TITLE
CHANGELOG.md issue

### ISSUE THREAD

**Issue by ncruces** [googleapis/nodejs-storage#420]
Documentation in [CHANGELOG](https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md#bucketupload-method-removed) about breaking changes has me scratching my head.

Has [bucket.upload](https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md#bucketupload-method-removed) really been removed?

Documentation is still [there](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/Bucket#upload), #337 implies just the upload remote URLs using `request` has been dropped, and uploading files seems to be work.

Hopefully this is just a documentation issue. Removing this method for file uploads seems silly.

**Comment by stephenplusplus** [comment]
That's wrong! We still have `bucket.upload()`. It just doesn't take URLs anymore. I sent a PR to clear up the CHANGELOG: #421

**Comment by ncruces** [comment]
OK, thanks! Feel free to close.
