### ISSUE TITLE
Example instantiations don't use `new`

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#43]
@jmdobry -- do we want to put `new`s in front of these instantiations? This is from the README.

```js
// Imports the Google Cloud client library
const Storage = require('@google-cloud/storage');

// Your Google Cloud Platform project ID
const projectId = 'YOUR_PROJECT_ID';

// Instantiates a client
const storage = Storage({
  projectId: projectId,
});
```

**Comment by jmdobry** [comment]
After recently working with one of our newer clients that contains auto-generated code and uses ES2015 classes, I'm thinking yes, we should use `new` for consistency with our ES2015 classes.

**Comment by lukesneeringer** [comment]
Agreed.
