### ISSUE TITLE
could not authenticate request

### ISSUE THREAD

**Issue by ils-sapnaj** [googleapis/nodejs-storage#432]
I am still getting the issue and error "Error: Could not authenticate request". Here is the system configuration : 

OS: Windows 10
Node.js version: 8.11.4
npm version: 5.6.0
@google-cloud/storage version: 2.0.3

It was working fine with node version 6.11.2 and npm version 3.10.10.

Please help me out, I can't work with node 6, I need to upgrade but google storage package is not working.

_Originally posted by @ils-sapnaj in https://github.com/googleapis/nodejs-storage/issues/365#issuecomment-427732963_

**Comment by JustinBeckwith** [comment]
Greetings!  Could you please share a small code snippet that produces the error?  Also, can you please share your package.json?

**Comment by ils-sapnaj** [comment]
Package.json : 
"dependencies": {
    "@google-cloud/storage": "^1.5.2",
    "adm-zip": "0.4.7",
    "apn": "^1.7.8",
    "assert-plus": "0.2.0",
    "async": "0.2.9",
    "asynckit": "0.4.0",
    "aws-sdk": "2.122.0",
    "aws-sign2": "0.6.0",
    "aws4": "1.6.0",
    "babel-core": "*",
    "babel-istanbul": "*",
    "base64url": "2.0.0",
    "bluebird": "^3.5.1",
    "body-parser": "~1.15.1",
    "connect-flash": "~0.1.1",
    "cookie-parser": "~1.4.3",
    "dateformat": "3.0.2",
    "debug": "~2.2.0",
    "ejs": "~2.5.7",
    "end-of-stream": "1.4.0",
    "express": "~4.13.4",
    "express-session": "~1.14.2",
    "extend": "3.0.0",
    "extract-zip": "^1.6.5",
    "extsprintf": "1.0.2",
    "fcm-node": "1.2.1",
    "fiber": "1.0.4",
    "fibers": "2.0.0",
    "forever-agent": "0.6.1",
    "form-data": "2.1.4",
    "gcloud": "^0.37.2",
    "gcp-metadata": "0.3.1",
    "group-array": "0.3.1",
    "http-signature": "1.1.1",
    "jenkins-mocha": "^4.1.2",
    "json-schema": "0.2.3",
    "json-stable-stringify": "1.0.1",
    "json-stringify-safe": "5.0.1",
    "log-driver": "1.2.5",
    "mailchimp-api-v3": "1.7.0",
    "make-dir": "1.1.0",
    "md5": "~2.2.1",
    "methmeth": "1.1.0",
    "mime": "1.4.1",
    "mime-db": "1.27.0",
    "mime-types": "2.1.15",
    "mocha": "1.14.0",
    "mocha-logger": "^1.0.5",
    "modelo": "4.2.0",
    "moment": "^2.20.1",
    "morgan": "~1.7.0",
    "multer": "1.3.0",
    "mysql": "~2.11.1",
    "newrelic": "^2.7.0",
    "node-datetime": "1.0.0",
    "node-forge": "0.6.49",
    "node-gyp": "^3.8.0",
    "node-pre-gyp": "^0.11.0",
    "node-stream-zip": "^1.3.7",
    "nodemailer": "~2.6.4",
    "npm": "^3.10.10",
    "nyc": "^11.2.1",
    "paypal-rest-sdk": "1.8.1",
    "readable-stream": "2.3.3",
    "request": "2.81.0",
    "retry-request": "3.1.0",
    "rimraf": "2.6.2",
    "rmdir-sync": "1.0.1",
    "safe-buffer": "5.0.1",
    "safe-json-stringify": "^1.0.4",
    "serve-favicon": "~2.3.2",
    "slashes": "~1.0.5",
    "sort-by": "1.2.0",
    "sql.js": "0.4.0",
    "stubs": "3.0.0",
    "typedarray": "0.0.6",
    "unique-string": "1.0.0",
    "util-deprecate": "1.0.2",
    "uuid": "3.0.1",
    "wait.for": "0.6.6",
    "babel-core": "*",
    "babel-istanbul": "*",
    "nyc": "^11.2.1",
    "rimraf": "2.6.2"
  },

and it is a simple code of uploading file on google bucket :

        var fs = require("fs");
	var mime = require('mime-types')
        var GoogleCloudStorage = require('@google-cloud/storage');
	var mimetyp = mime.lookup(image_look_up_path);
	
	if (fs.existsSync(image_look_up_path))
	{
		var storage = GoogleCloudStorage
		({
		  projectId: project_id,
		  keyFilename: './GCP_credential.json'
		})
		
		var bucket = storage.bucket(CLOUD_BUCKET);
		var files = bucket.file(space+'/'+user_email+'/'+image_file_name);
		fs.createReadStream(image_look_up_path)
		.pipe(files.createWriteStream
		({
			metadata:
			{
			  contentType: mimetyp
			},
			predefinedAcl: "publicRead"
		}))
		.on("error", (err) =>
		{
			console.log("err : "+err);
		})
		.on('finish', () =>
		{
			console.log("Done");
		});
		return callback(null, "done");

**Comment by ils-sapnaj** [comment]
Any update ???

**Comment by JustinBeckwith** [comment]
Yes! It looks like you're using an old version of the library.  Can you upgrade to 2.0?

**Comment by ils-sapnaj** [comment]
I have upgraded to 2.0.3 but still it not running with node 8. Now I am getting "Could not refresh access token" error.

**Comment by JustinBeckwith** [comment]
Would it be possible for you to create a small GitHub repository with a simple repo of the problem?  That would make debugging this a lot easier :) You have *a lot* of stuff installed in your package.json. Do you need all of that?

**Comment by ils-sapnaj** [comment]
Hey, When I have kept the code separate for image upload (simple repo), it is working fine but it is giving "Could not refresh access token" error in the above code for which I have raised the issue. COuld you tell me what can cause this error? If you can tell me the code condition which is triggerring this error in google package, I can proceed.

**Comment by JustinBeckwith** [comment]
This happens when you get a 403 or 404 back from the token service:
```js
const e = err as AxiosError;
if (e.response && (e.response.status === 403 || e.response.status === 404)) {
  e.message = 'Could not refresh access token.';
}
throw e;
```

This can happen if you're passing an invalid key or invalid parameters to the constructor of the storage class.  One thing I noticed looking at your code:

```js
 var GoogleCloudStorage = require('@google-cloud/storage');
var storage = GoogleCloudStorage
		({
		  projectId: project_id,
		  keyFilename: './GCP_credential.json'
		})
```

With the the 2.1 version of the storage npm module....  that shouldn't work.  It should look like:

```js
const {Storage} = require('@google-cloud/storage');
const storage = new Storage({
  projectId: project_id,
  keyFilename: './GCP_credential.json'
});
```

I'm a little surprised the `keyFilename` you're using is working without doing something like `path.join(__dirname, './GCP_credential.json')` or something of the like.

**Comment by ils-sapnaj** [comment]
The changes related to package 2.0.3 I already did and it is running fine. The same code is working when I am executing as a sample but I am using it in real project it is giving again and again "Could not refresh access token".  I initially thought that the issue is maybe with my credential file but it is working fine in sample code. Any idea ???

**Comment by JustinBeckwith** [comment]
Apologies.  Unless we have code that can reproduce the issue, there's really not a lot I can do :( If you can show us how to make it fail, I'd be happy to help.  But right now, I just don't have enough information to go on.

**Comment by ils-sapnaj** [comment]
Hey, I found that due to my project library file which has sql queries written and I am including that file in my app.js, the error is coming. If I comment out that file, the code is working. Giving you an example for that sql function which is causing issue.  Logically there should be no connection but don't know how the code is working without this DB lib file.

Object.prototype.delete_class_shared_record = function (connection, cc_shared_to_user_id, cc_shared_by_user_id, cc_shared_class_id, callback)
{
    var sql='delete from cc_shared_student_details where cc_shared_by_user_id = "'+cc_shared_by_user_id+'" and cc_shared_to_user_id = "'+cc_shared_to_user_id+'" and cc_shared_class_id = "'+cc_shared_class_id+'" ';
    
    connection.query(sql,function(err,rows)
    {
        if(err) throw err;
        
		return callback(err,{rows:rows});      			
	});	
}

Any hint how this relates to google cloud ???
