### ISSUE TITLE
System tests that don't require credentials fails under Kokoro

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-storage#437]
I think I'm starting to get a sense of why system tests are failing under Kokoro while they're passing on CircleCI.

Here's snapshot of the currently failing system tests on [Kokoro](https://source.cloud.google.com/results/invocations/21fd7c92-0da0-4bfc-90e6-f73100358e7f/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fgoogleapis%2Fnodejs-storage%2Fcontinuous%2Fnode8%2Fsystem-test/log):
<img width="935" alt="screen shot 2018-10-08 at 3 15 57 pm" src="https://user-images.githubusercontent.com/4001432/46636499-15780280-cb0d-11e8-950c-8fd9b0248c49.png">

These tests explicitly unset the `GOOGLE_APPLICATION_CREDENTIALS` to test that we're still able to access files in Storage that doesn't require auth.

The error message points to an auth issue - I believe what's happening here that's different in Kokoro vs CircleCI is that Kokoro runs on a Compute instance, so when it doesn't find the application credentials, it [fallbacks](https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L662) to the application credential from the metadata server.

I'm hoping for suggestions on how to modify the tests so that it will run on Kokoro.

**Comment by JustinBeckwith** [comment]
Pretty sure we got this in #438
