### ISSUE TITLE
Can't import Storage from @google-cloud/storage

### ISSUE THREAD

**Issue by Steven4294** [googleapis/nodejs-storage#456]
#### Environment details

  - Node.js version: 8.9.0
  - npm version: 5.5.1
  - `@google-cloud/storage` version: ^2.1.0

#### Steps to reproduce

I am just trying to setup GCS in a cloud code function. I am using typescript. However when I try to `import { Storage } from '@google-cloud/storage';` i get an error that `node_modules/@types/google-cloud__storage/index"' has no exported member 'Storage'.`

If i try, `import * as Storage from '@google-cloud/storage';` I get an error `TypeError: Storage is not a constructor`. Here is my dependency file and then my `index.js`.

```
   // in package.json
  "dependencies": {
    "@google-cloud/storage": "^2.1.0",
    "@types/google-cloud__storage": "^1.7.2",
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.3",
    "fs-extra": "^7.0.0",
    "sharp": "^0.21.0"
  }

  // index.ts

import * as functions from 'firebase-functions';
import * as Storage from '@google-cloud/storage';

const projectId = 'xxxx';

const storage = new Storage({
 projectId: projectId,
});


```

**Comment by Steven4294** [comment]
It seems that the correct way to import it is ```
import * as Storage from '@google-cloud/storage'
```
However, i'm getting the error that Storage is not a constructor. Am i missing something very obvious here?

**Comment by kinwa91** [comment]
Hi 👋 Thanks for filing an issue with us.

We've temporarily [disabled types](https://github.com/googleapis/nodejs-storage/pull/392) on nodejs-storage because we currently have some incomplete types and it was causing issues to people that uses TypeScript. That's why the `import { Storage } from '@google-cloud/storage';` doesn't work currently.

For now, please use

```typescript
import * as storage from '@google-cloud/storage';

const client = new storage.Storage();
```

**Comment by Steven4294** [comment]
thanks!

**Comment by mpmckenz** [comment]
import * as storage from "@google-cloud/storage";
Gets an error as well:
SyntaxError: Unexpected token *

Looks like google cloud storage doesn't work at all right now. That's not very reliable.. :/

**Comment by JustinBeckwith** [comment]
@mpmckenz are you writing TypeScript or JavaScript?  For TypeScript that makes sense, for plain ol' JavaScript it would still just be `const {Storage} = require('@google-cloud/storage');`.  Hope this helps!

**Comment by reduardo7** [comment]
```ts
import { Storage } from '@google-cloud/storage';
```
or
```js
const { Storage } = require('@google-cloud/storage');
```

**Comment by mahsanamin** [comment]
Unfortunately, In Node 12 the above snippets did not work in the module approach, so use below!

```
import storagePackage from '@google-cloud/storage';
const { Storage } = storagePackage;
const storage = new Storage();
```

**Comment by JuanjoFR** [comment]
In my case (Node 14) I needed something like this:

```
import * as storageModule from "@google-cloud/storage";
const { Storage } = storageModule;
const storage = new Storage();
```
