### ISSUE TITLE
Save function doesn't exist

### ISSUE THREAD

**Issue by adic26** [googleapis/nodejs-storage#46]
I am creating a firebase function where I need to call Google cloud storage library to store some contents using the save method: https://cloud.google.com/nodejs/docs/reference/storage/1.3.x/File#save

My code:

```
const Storage = require('@google-cloud/storage')({
    projectId: 'izotti-api',
    keyFilename: 'keyfile.json'
});
```

```
var myBucket = Storage.bucket('gs://izotti-api.appspot.com');

  const options = {
    action: 'read',
    expires: '12-31-2025'
  };

  //Front image storage task
  event.data.ref.parent.child('front_image').once('value').then((snapshot) => {
    const front_image = snapshot.val();
    console.log(front_image);

    //Store the file here by saving its content
    const file = myBucket.file(`${event.params.clientId}/front_image.png`);
    console.log(file);

    file.save(front_image, function(err) {
      if (!err) {
        console.log("Finished uploading front image");
      } else {
        console.log(err);
      }
    });
```
However, everytime at `file.save` it generates an error - 

> Error: Not Found
>     at Request._callback (/user_code/node_modules/@google-cloud/storage/node_modules/gcs-resumable-upload/index.js:283:25)
>     at Request.self.callback (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:186:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:1163:10)
>     at emitOne (events.js:96:13)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/request/request.js:1085:12)
>     at IncomingMessage.g (events.js:292:16)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Why doesnt the save function work ? Or am I calling it incorrectly?

#### Environment details

  - OS: Darwin Kernel Version 15.4.0
  - Node.js version: v6.9.4
  - npm version: 3.10.10
  - @google-cloud/storage version:   "^1.3.1"

#### Steps to reproduce

  1. New Instance of google cloud storage
  2. Create brand new content and save it using File.save as mentioned in https://cloud.google.com/nodejs/docs/reference/storage/1.3.x/File#save

Thanks!

**Comment by stephenplusplus** [comment]
Hey @adic26! The problem is likely how you're identifying the bucket. Try:

```diff
- Storage.bucket('gs://izotti-api.appspot.com');
+ Storage.bucket('izotti-api.appspot.com');
```

**Comment by adic26** [comment]
Thanks! That works. Can't believe i missed that!
