### ISSUE TITLE
OOM issue when writing to nodejs-storage writeStream

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-storage#489]
cc-ed from internal ticket.

```javascript
const {Storage} = require("@google-cloud/storage");
const gcs = new Storage({projectId: "test-1"});
const crypto = require("crypto");
const file = gcs.bucket("test-bucket").file("test");
const ws = file.createWriteStream({resumable: false}); // must be false

ws.on("error", console.error);
ws.on("finish", () => console.log("finish"));
ws.end(crypto.randomBytes(28e6));
```

### Steps to Reproduce
For latest version:
1. Create a .js file containing the command above
2. Run the command `node [FILENAME].js`

### Error
```
ivanlindoubeda@cloudshell:~ (hcl-ivanlindoubeda)$ node repro.js
<--- Last few GCs --->
 
[1277:0x3c0ea30]     8479 ms: Mark-sweep 333.3 (353.3) -> 333.3 (353.8) MB, 150.7 / 0.0 ms  (+ 35.8 ms in 1 steps since start of marking, biggest step 35.8 ms, walltime since start of marking 4972 ms) allocation failure GC in old space requested
 
 
<--- JS stacktrace --->
 
==== JS stack trace =========================================
 
Security context: 0x1bcbac825ee1 <JSObject>
    2: replaceProjectIdToken(aka replaceProjectIdToken) [/home/ivanlindoubeda/node_modules/@google-cloud/projectify/build/src/index.js:44] [bytecode=0x193e392eaa9 offset=72](this=0x2d02d8a02311 <undefined>,value=0x25688ced7ee1 <Uint8Array map = 0x15d55936bdf1>,projectId=0x2841cf0ccf21 <String[18]: hcl-ivanlindoubeda>)
    4: replaceProjectIdToken(aka replaceProjectIdToken) [/home/ivanlindoubeda/...
 
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x121a2cc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Rehash(v8::internal::Handle<v8::internal::OrderedHashSet>, int) [node]
 7: v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::EnsureGrowable(v8::internal::Handle<v8::internal::OrderedHashSet>) [node]
 8: v8::internal::OrderedHashSet::Add(v8::internal::Handle<v8::internal::OrderedHashSet>, v8::internal::Handle<v8::internal::Object>) [node]
 9: v8::internal::KeyAccumulator::AddKey(v8::internal::Handle<v8::internal::Object>, v8::internal::AddKeyConversion) [node]
10: 0xe11e57 [node]
11: v8::internal::KeyAccumulator::CollectOwnElementIndices(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [node]
12: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [node]
13: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [node]
14: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [node]
15: 0x10bf8b4 [node]
16: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [node]
17: 0x39fed190e6a5
Aborted (core dumped)
```

**Comment by zbjornson** [comment]
(Customer == me 🙂)

It looks like this might actually be another manifestation of #390. Above @kinwa91 notes "this reproduction fails on v1.6.0 as well", but in #390, @adriaanmeuris reported that 1.7.0 works.

**Comment by kinwa91** [comment]
Hi @zbjornson,

We made a patch release on `@google-cloud/common` (which was the dependency causing the bug) and I've verified that re-installing `@google-cloud/storage` resolved the OOM error on the reproduction. Please check if it also works on your side.

Note that you might have to remove `node_modules` and `package-lock.json` for `npm` to pick up the latest dependency.

**Comment by zbjornson** [comment]
Hi @kinwa91, thanks for that. I'm not sure if that's the best fix: why is the request body sent to that function in the first place? The projectId doesn't occur in any GCS API request body as far as I know. (I think the only three GCS API endpoints that use `projectId` are `list buckets`, `insert bucket` and `get projects.serviceAccount`, where it occurs in the path or query.)

Note that with the current code, objects that happen to have `{{projectId}}` in their name will get uploaded incorrectly:

```js
bucket.file("myobj{{projectId}}").createWriteStream().end("hello!")
// gets uploaded as "myobjmyproj"
```

Alternatively, maybe `nodejs-common/util/decorateRequest` or `makeAuthenticatedRequest` should be modified to (optionally?) not call `replaceProjectId` on the body?

**Comment by kinwa91** [comment]
I agree there's definitely something wrong with replacing `{{projectId}}` everywhere, I'm going to open an issue and make a reference to your recommendation, and thank you for that 👍 

My fix merely patched a bug that was introduced when converting `replaceProjectIdToken` into typescript (and dropping `is`) - I believe what you're describing always existed as an issue even before that.

If the fix successfully resolved the OOM issue, I'd like to close this issue and continue discussion on the new one. What do you think?

**Comment by zbjornson** [comment]
Sounds good! Yes, what I described was pre-existing. Thanks :)

**Comment by hden** [comment]
Just ran into similar issues on GKE. The pod exited with status `OOMKilled with exit code 137`.

<img width="1140" alt="screen shot 2018-11-14 at 16 59 19" src="https://user-images.githubusercontent.com/1910549/48468244-ad64bc80-e82e-11e8-824d-600ffdf9edd3.png">

What's inside was a very simple script dumping data from MySQL to Cloud Storage.

```js
const mysql = require('mysql')
const { Storage } = require('@google-cloud/storage')
const JSONStream = require('JSONStream')

const storage = new Storage({
  projectId: process.env.GCLOUD_PROJECT
})
const file = storage.bucket('bucket').file('filename')
const conn = mysql.createConnection(options)


conn.query('select * from large_table')
  .stream({ highWaterMark: 1000 })
  .pipe(JSONStream.stringify(false))
  .pipe(file.createWriteStream({ contentType: 'application/json', resumable: true }))
```

**Comment by kinwa91** [comment]
Hi @hden, we believe to have fixed your issue. See the related issue here - https://github.com/googleapis/nodejs-storage/issues/390#issuecomment-439054989

Please try again with the latest release of @google-cloud/storage v2.3.1. Thanks!
