### ISSUE TITLE
How to upload an image from an external link to google cloud storage ?

### ISSUE THREAD

**Issue by jackmatrix** [googleapis/nodejs-storage#506]
I am using `google-cloud-storage` on Node.js . Trying to find a solution to programmatically download an image from an external url then upload to my default GCS bucket. 

I'm using fetch API to get the image and turn it into a blob 
```javascript
 fetch('image.jpg').then( res => {
        var blob = res.blob()
    }) 
```

I've also tried this, without success

```javascript
bucket.upload(urlImage, function(err, file){
            const blobStream = file.createWriteStream();
            blobStream.on('error', (err) => {
              console.log('error',err)
            });

            blobStream.on('finish', () => {
              console.log('finished with success')
            
              });

              blobStream.end(file);
          })
```
All tutorials I've found on the web deal with form upload using multer. But nothing about my case. 

Now what's the right solution to upload this blob on my GCS bucket ?

**Comment by kinwa91** [comment]
```javascript
const fetch = require('node-fetch');
const {Storage} = require('@google-cloud/storage');

const storage = new Storage();
const bucket = storage.bucket('my-bucket');

// Create a WritableStream from the File
const file = bucket.file('my-image.jpg');
const writeStream = file.createWriteStream();

fetch('image.jpg')
  .then(res => {
    res.body.pipe(writeStream);
  });
```

**Comment by kinwa91** [comment]
Closing for now - please re-open if there's anymore questions :)

**Comment by rabble** [comment]
I'm sorry, but the original person didn't want to upload a local file, they've got the buffer and want to directly upload that. Did you even read the post?

**Comment by JustinBeckwith** [comment]
@rabble greetings!  We're sorry you're having trouble - if you're still running into issues, please open a new bug!

Independent of the issue here - we decided to remove this post because it violates our code of conduct:
https://github.com/googleapis/nodejs-storage/blob/master/CODE_OF_CONDUCT.md

**Comment by dcts** [comment]
Trying to achieve the same thing with axios here. Im geting the blob data of an image retrieved from an external url like this:
```js
async getBlob(url) {
  const response = await axios.get(url, { responseType: "blob" })
  return response.data;
}
```
@jkwlui how would i apply the write tream in this case? I don't understand what the `res.body.pipe(writeStream)` is doing in your example.

**Comment by gterras** [comment]
Hi @dcts I know this is old but if someone else is interested the `responseType: 'stream'` is needed : 

```js
	const writeStream = file.createWriteStream();
	const stream = await axios({ url, method: 'GET', responseType: 'stream'})
	stream.data.pipe(writeStream)
```
