### ISSUE TITLE
Random error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by tangkhaiphuong** [googleapis/nodejs-storage#508]
This library random show error below: 

```
Client network socket disconnected before secure TLS connection was established
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Show how we workaround by using non-SSL or any way?

**Comment by fueltank34** [comment]
I am getting this issue behind a proxy. I'm not sure if it is because of the proxy issue with axio so am waiting for 0.19 to release and then test again.

**Comment by kinwa91** [comment]
Can you provide the version of (1) nodejs-storage and (2) your OS. Also, @tangkhaiphuong, are you running behind a proxy like @fueltank34?

This would help us narrow down the problem, thanks!

**Comment by JustinBeckwith** [comment]
Greetings @fueltank34!  If you're still running into issues here - please do let us know!  We're going to close this out for now.

**Comment by jgresham** [comment]
I'm getting this error intermittently running on a GCE with docker deploy config which is running Google's Container-Optimized OS. My docker container is running OS node:11.13.0-stretch-slim and with Node v11.13.0. I am using "@google-cloud/storage": "^2.5.0".

**Comment by jgresham** [comment]
Relevant GCE with container docs: https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#publishing_container_ports

**Comment by jgresham** [comment]
It looks related to this: "There is some overhead when using a resumable upload that can cause noticeable performance degradation while uploading a series of small files. When uploading files less than 10MB, it is recommended that the resumable feature is disabled."

I've set resumable to false and I'm not having this issue.

**Comment by AVaksman** [comment]
@jgresham since it seems to work fine now I will close this issue.
Please comment if you still experiencing the issue.
