### ISSUE TITLE
`npm test` should include sample tests

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#51]
@lukesneeringer @jmdobry -- does it seem correct that `npm test` should run the sample tests as well?

**Comment by stephenplusplus** [comment]
Alternatively, it could be set up as a separate step of the CircleCI workflow.

**Comment by jmdobry** [comment]
`npm test` only runs unit tests right? If there are unit tests for the samples, then yes those should be included. Otherwise the samples' system tests should be executed on every PR and push to GitHub, using something like: https://github.com/googleapis/nodejs-storage/pull/38#issuecomment-335262727

**Comment by stephenplusplus** [comment]
What is the right way to only run sample unit tests from the npm test command? And will this change belong in the generator?

**Comment by jmdobry** [comment]
We typically do it as follows:

* `npm run unit-test` - Runs the unit tests
* `npm run system-test` - Runs the system tests
* `npm test` - Runs both the unit tests and the system tests

If there is no `unit-test` script in the samples' package.json, then there are no unit tests.

**Comment by stephenplusplus** [comment]
Thanks. And the generator stays out of rootDir/package.json and we should write these ourselves? I know we call through to repo-tools in some places. Is there room to integrate with it cor this task?

Additionally, I think unit-test should always exist, so we can run it without npm errors. Seeing "0/0 tests passed" is acceptable.

**Comment by jmdobry** [comment]
These scripts would be defined in `samples/package.json`, which is mostly copied over from `nodejs-docs-samples`. If there aren't unit tests, we could have: `"unit-test": "node -e \"console.log('No tests')\""`, which is cross platform.

**Comment by stephenplusplus** [comment]
It seems that whatever we have now is working.
