### ISSUE TITLE
createReadStream() on 'response' event doesn't contain status and headers information

### ISSUE THREAD

**Issue by ramesh-dev** [googleapis/nodejs-storage#526]
Hi, 
Earlier i was using `v2.0.3` and were able to access response headers & status code using `response` event from `createReadStream()`. But with the latest version `v2.3.1` i was not able to access the response status & headers when reading a file. 
 
    const storage = new Storage({projectId: 'projectId'});
    let readStream = file.createReadStream({validation: false })

    readStream.on('error', (e) => {
	log.error('error in gcs read stream: %O', e)
	res.status(500).send('error serving this file')
    })

    readStream.on('response', (streamResponse) => {
	
        var code = streamResponse.statusCode
        var headers = streamResponse.headers 
        //rest omitted
    })

but now was unable to access , i believe it returns stream object in the  `on response` event callback, not sure if that is the new behaviour, i have check the offical doc [createReadStream](https://cloud.google.com/nodejs/docs/reference/storage/2.0.x/File#createReadStream) even these it specified as 
` .on('response', function(response) {
        // Server connected and responded with the specified status and headers.
   })`

Can you please help me to understand or point me to the revelant doc to know how to access the response headers & status code for `createReadStream()` call, we are performing custom actions based on those values

Thank you in advance

#### Environment details

  - OS: OS X 10.14.1 (18B75)
  - Node.js version: v9.11.1
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 2.3.1

**Comment by ramesh-dev** [comment]
FYI, I have checked other version after `v2.0.3` and can confirm starting from `v2.2.0` headers are not returned instead it returns steam object (i believe)

**Comment by tcf909** [comment]
Running in to the same breaking behavior. 

Devs please clarify.

**Comment by JustinBeckwith** [comment]
This is almost certainly due to the request - teeny-request migration.

**Comment by JustinBeckwith** [comment]
@kinwa91 this should be fixed now, right?

**Comment by kinwa91** [comment]
Yup, it should be fixed in newer versions of @google-cloud/storage.
