### ISSUE TITLE
can't built functions for Firebase functions with this lib

### ISSUE THREAD

**Issue by lenanex** [googleapis/nodejs-storage#562]
#### Environment details

  - OS: mac 10.12.6
  - Node.js version: v8.11.3
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 2.3.4

#### Steps to reproduce

  1. npm i @google-cloud/storage
  2. firebase deploy --only functions

Following erros

> node_modules/@google-cloud/common/build/src/service-object.d.ts(72,45): error TS8020: JSDoc types can only be used inside documentation comments.

> node_modules/@google-cloud/common/build/src/service-object.d.ts(72,45): error TS8028: JSDoc '...' may only appear in the last parameter of a signature.

> node_modules/@google-cloud/common/node_modules/google-auth-library/build/src/auth/oauth2client.d.ts(291,55): error TS1039: Initializers are not allowedin ambient contexts.

>

**Comment by kinwa91** [comment]
The types declaration file in `@google-cloud/storage` is only compatible with newer versions of TypeScript (3+).

Upgrade the typescript compiler version in the functions project:
```shell
$   npm install --save-dev typescript@latest
```
