### ISSUE TITLE
CONTENT_DOWNLOAD_MISMATCH exception

### ISSUE THREAD

**Issue by atlanteh** [googleapis/nodejs-storage#566]
#### Environment details

  - OS: Windows (firebase functions emulator)
  - Node.js version: v8.12.07s
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 1.7.0 & 2.3.4

#### Steps to reproduce

  1. Upload an image file using: `file.save(mediaBuffer, {metadata: {contentType}, gzip: true})`
  2. Try downloading the img file using: `storage.bucket(fromBucket).file(f.name).createReadStream()`
  3. Exception is thrown: `code=CONTENT_DOWNLOAD_MISMATCH message=The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again., stack=Error: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.`

First I tried it using firebase-admin, and when I saw that they use an old version(1.7), I tried taking latest `@google-cloud` and run it again, but still nothing works.

The only solution I could find was to set storage.bucket(fromBucket).file(f.name).createReadStream({validation: false});
but this is just a quick hack, there should not be any reason the validation should fail

**Comment by atlanteh** [comment]
I see that this issue might be a very long due.
I'm trying to use google vision api on GCS gzipped image and it failed.
I tried looking it up and found this answer from 2016:
https://stackoverflow.com/a/36684248/1861047

> Turns out, there is a bug in Google's implementation of gzip compression on the request... I'm not sure if the API only applies gzip compression when the request size hits a certain threshold, or if the implementation bugs works for small requests, but not for large ones.

**Comment by kinwa91** [comment]
Hi @atlanteh, I tried to reproduce your issue with the following code:

```javascript
const {Storage} = require('@google-cloud/storage');
const storage = new Storage({projectId: PROJECT_ID});

const fs = require('fs');
const image = fs.readFileSync(LOCAL_FILE_NAME);

const bucket = storage.bucket(BUCKET_NAME);
const file = bucket.file('test.png');
const contentType = 'image/png';

file.save(image, {metadata: {contentType, gzip: true}})
  .then(() => {
    const stream = bucket.file('test.png').createReadStream();
    stream.pipe(fs.createWriteStream('downloaded.png'));
  });
```

But wasn't able to reproduce the error. How big was your file?

**Comment by atlanteh** [comment]
Not big at all. Around 2-5mb. Please note that in your example the gzip option is placed in the metadata instead of on the options object.

**Comment by kinwa91** [comment]
There was no issue if `{metadata: {contentType}}` wasn't supplied.

**Comment by atlanteh** [comment]
I'm glad that this is reproducible for you too. Is the problem in the nodejs module? or a problem with the backend?

**Comment by atlanteh** [comment]
So I tested it and as you said, when setting gzip "auto" it works. No need for validations anymore.

Anyways, I think that there's still a problem. When removing the gzip metadata from the image, it becomes unviewable so there's more to that than just the encoding. Now I have many photos on my storage that are "corrupt" this way so I can't download them without the "validation: false" flag. How can I fix it?

BTW, please note that gzip option is nowhere to be found other than in the code itself. I did try to look for it in the official docs, but couldn't find it. I looked at [file.createWriteStream](https://cloud.google.com/nodejs/docs/reference/storage/2.3.x/File.html#createWriteStream) and in the links for the options object there, but no gzip option was provided. It does talk about contentEncoding, but not on the gzip flag itself

**Comment by jkwlui** [comment]
> Now I have many photos on my storage that are "corrupt" this way so I can't download them without the "validation: false" flag. How can I fix it?

For those files, you should be able to fix existing objects by unsetting (stripping) the `Content-Encoding: gzip` metadata:

```javascript
await file.setMetadata({
  contentEncoding: null // this unsets the 'gzip' encoding causing the issue
});
```

**Comment by jheeffer** [comment]
We're getting this error without any content-encoding or gzip settings:

Running the below code once works (creating the file), the second time gives the `CONTENT_DOWNLOAD_MISMATCH` error (when updating the file).

```js
const storage = new Storage();
const bucket = storage.bucket(GCP_STORAGE_BUCKET_NAME);
const remoteFile = bucket.file('test.csv');

let fileContents = ''+ Date.now();

remoteFile.save(fileContents).then(
	() => remoteFile.download().then(console.log).catch(console.warn)
).catch(console.warn);
```

**Comment by danielsetreus** [comment]
@jheeffer - I'm having the exact same problem. Have tried with different ways of getting the file, through .createReadStream or simply .download(), but with same results. Disabling the validation returns old data. It just as if, on upload, the file data is not changed - but the hashes are.

This is really starting to annoy me. And I'm simply trying to write to a JSON-file.

**Comment by stephenplusplus** [comment]
@jheeffer I tested with this script, and it didn't have any issues matching. Could you give it a run to see if you still get errors? If you can make any modifications to demonstrate the error, that would be helpful as well. Thanks!

```js
'use strict'

const {Storage} = require('@google-cloud/storage')
const storage = new Storage()

const bucket = storage.bucket(GCP_STORAGE_BUCKET_NAME)
const file = bucket.file('test.csv')

async function test() {
  let fileContents = `${Date.now()}`
  console.log('saving: ', fileContents)
  await file.save(fileContents)
  const [contents] = await file.download({validation: false})
  console.log('downloaded:', contents.toString())
}

(async () => {
  await test()
  await test()
  await test()
  await test()
  await test()
})()
```

@danielsetreus do you have a script I can try?

**Comment by danielsetreus** [comment]
@stephenplusplus I ran you rest and can confirm there is something strange...

```
exports.test = () => {
  (async () => {
    await test()
    await test()
    await test()
    await test()
    await test()
  })()

};

const test = async () => {
  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage()
  const bucket = storage.bucket('spring-internals');
  const file = bucket.file('test.csv');

  let fileContents = `${Date.now()}`;
  console.log('saving: ', fileContents);
  await file.save(fileContents);
  const [contents] = await file.download({validation: false});
  console.log('downloaded:', contents.toString());
}
```

Results:
```
node -e 'require("./index.js").test()'
saving:  1553513666636
saving:  1553513666652
downloaded: 1553513666636
saving:  1553513668010
downloaded: 1553513666636
saving:  1553513668028
downloaded: 1553513668028
saving:  1553513669196
downloaded: 1553513668028
saving:  1553513669206
downloaded: 1553513669196
saving:  1553513670404
downloaded: 1553513669196
saving:  1553513670415
downloaded: 1553513670404
saving:  1553513672022
downloaded: 1553513670404
saving:  1553513672047
downloaded: 1553513672047
downloaded: 1553513672047
```
But the script also seems to not wait for itself properly... 

The original script I had is pretty long, but in concept it's the same as above. Download the file to a local copy, write to that, and upload the result. But it fails already in the download with CONTENT_DOWNLOAD_MISSMATCH. So, either the hash is badly created on upload, or the hash calculation is wrong on download.

Have any of you tried setting a specific hash algoritm?

**Comment by danielsetreus** [comment]
Got this working by really simplifying the script. Could it be that the local download changes some metadata about the file? 

```javascript
exports.writeEntry = async (message, attributes) => {
  const entry = constructEntry(message, attributes);
  let current = await getEventFile();
  console.log('Current: ', current);
  if(current.length === 0)
    current = '[]';

  current = JSON.parse(current);
  current.push(entry);

  console.log('Write', current);
  await writeEventFile(JSON.stringify(current));
};

const constructEntry = (message, attributes) => {
  return {
    message: message,
    severity: attributes.severity,
    timestamp: attributes.timestamp,
    readableTimestamp: Date(attributes.timestamp*1000).toString(),
    origin: attributes.origin
  };
};

const getEventFile = async () => {
  const content = await file.download();
  return content.toString();
};

const writeEventFile = async (data) => {
  await file.save(data, {
    contentType: 'application/json;',
    resumable: false,
  });
};
```

**Comment by stephenplusplus** [comment]
Thanks for that! It sent me down a few different tracks that ended up with this PR: #643. Feel free to chime in over there if you have any ideas about a solution.

**Comment by lvl99** [comment]
If it helps anyone doing a search online, I had this error code and wasn't sure what was going wrong.

What I realised was happening was that I had my rate limiter doing 2 concurrent read/write operations on the same file.
