### ISSUE TITLE
Error: Could not authenticate request unable to verify the first certificate - @@google-cloud/storage

### ISSUE THREAD

**Issue by Siddharthosatwal** [googleapis/nodejs-storage#569]
#### Environment details

  - OS: windows 7 64-bit
  - Node.js version: v8.11.3
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 1.5.2

I have implemented an object upload functionality which is providing an error "err : Error: Could not authenticate request unable to verify the first certificate"shown in the screenshot.
But when I run the same code on a Windows 10 OS with same Node.js and npm version the functionality works fine.

![errorscreenshot](https://user-images.githubusercontent.com/29251024/50588861-fe497680-0ea9-11e9-866e-01c51986dd06.PNG)

**Comment by JustinBeckwith** [comment]
Greetings!  I'm sorry, but we can't try to support Windows 7.  I would suggest sticking with a modern version of Windows :) Apologies!
