### ISSUE TITLE
Storage.createBucket signature

### ISSUE THREAD

**Issue by vlapo** [googleapis/nodejs-storage#578]
I think there is small bug with `Storage.createBucket`. There is no signature with `name`, `metadata` as arguments and returning promise. So this is no possible:

```typescript
const response = await storage.createBucket('just-a-test', {
    coldline: false
});
```

Thanks!

**Comment by kinwa91** [comment]
Sorry that was our bad - The typescript declarations should be fixed in v2.4.1.
