### ISSUE TITLE
Feature Request: Upload files to a bucket by passing url in place of a local path.

### ISSUE THREAD

**Issue by Kiricon** [googleapis/nodejs-storage#58]
Create a new method for the `Bucket` class called `uploadFromURL`. Said method would work the same way as the `upload` method, but in place of a local path would take a url (`http://exapmle.com/img.jpg`). 

This eliminates the need for a user to download the file, upload it, then delete it him or her self. 

If approved I would build the feature my self and submit a pull request.

**Comment by stephenplusplus** [comment]
A PR would be awesome!

**Comment by Kiricon** [comment]
Awesome, I'll get started on an implementation.
