### ISSUE TITLE
Installation fails via npm

### ISSUE THREAD

**Issue by edo386** [googleapis/nodejs-storage#6]
Install fails using `npm install --save @google-cloud/storage`

Error log:
` npm install --save @google-cloud/storage
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'google-cloud/storage' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
`

Cloning via git:
` git clone git@github.com:google-cloud/storage storage
Cloning into storage...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
`

**Comment by stephenplusplus** [comment]
We have this issue going on https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2582

Can you fill out:

- OS:
- Node.js version:
- npm version:
- @google-cloud/storage version:

**Comment by stephenplusplus** [comment]
Regarding the git error, try:

```
git clone git@github.com:GoogleCloudPlatform/google-cloud-node-storage
```

**Comment by lukesneeringer** [comment]
Hi @edo386,
Did this work for you? We have not heard from you in awhile. :-)

Going to close this for now, but let us know if you are still having issues.

**Comment by edo386** [comment]
My bad, I was using an old version of node.js followed the proper instructions to update it and worked. Thanks.
