### ISSUE TITLE
Why we always pick first entry from array?

### ISSUE THREAD

**Issue by Krizzu** [googleapis/nodejs-storage#60]
Hey,

Sorry if title is bit misleading, but I've been getting my hands dirty in Cloud functions today, and notice a pattern of [extracting first argument from result array](https://github.com/googleapis/nodejs-storage/blob/master/samples/files.js#L230). Did I missed something in docs?

Sorry if this was brought up already, I searched SO and issues here, but could not find any answer.

Thanks a lot!

**Comment by jmdobry** [comment]
It's because API responses sometimes have more than one result but you can
only resolve a promise with a single value, so we decided to be consistent
and always make the promise resolve with an array, even if sometimes the
array only has one item.

**Comment by Krizzu** [comment]
Fair enough, thanks!
