### ISSUE TITLE
Uncaught exception in Zlib when reading part of compressed file via File.createReadStream

### ISSUE THREAD

**Issue by imathews** [googleapis/nodejs-storage#602]
In my application, I'm trying to read part of a file in GCS — e.g., read the header from a large CSV. To do this, I create readStream with the `end` property specified — `file.createReadStream({ end: 1e6 })` — and then listen on the `data`, `error`, and `end` events. 

However, this causes Zlib to [throw an uncaught error](https://stackoverflow.com/questions/33926969/how-can-i-avoid-zlib-unexpected-end-of-file-when-gunzipping-partial-files), crashing the node process — even though I am listening on the `error` event of the readStream. Ideally, this error would either be handled internally or emit to the error event on the readStream.

#### Environment details
  - Node.js version: 10.14
  - `@google-cloud/storage` version: 2.4.2

#### Steps to reproduce

  1. Pipe `file.createReadStream({ end: # })` where `end < file.metadata.size`

Thank you!

**Comment by davidbielik** [comment]
I'm seeing this error, too, when using:
```
const file = bucket.file(filename);
await file.download().catch(error => {
    // the error is not caught here, as expected
});

**Comment by stephenplusplus** [comment]
I've put a PR together: #615. Would you mind testing?:

```sh
$ npm install stephenplusplus/nodejs-storage#spp--602
```

**Comment by imathews** [comment]
@stephenplusplus I just tested the PR; it works perfectly, thank you!! When possible, it'd be great to fold this into a release so that we can incorporate the fixes.

As an aside, I had a bit of a hard time testing the PR — `npm install` didn't work, it only copied package.json and README to `node_modules/@google-cloud/storage`. I had to clone the repo and run `npm run-script compile`. I may have missed something, but documentation / best practices (there must be a better way) for quickly testing forks from this repo would be very helpful.

**Comment by zjgreen** [comment]
Does someone have an estimate for when this fix will be released to `npm`?
