### ISSUE TITLE
Unhandled Rejection (TypeError): Expected `input` to be a `Function` or `Object`, got `undefined`

### ISSUE THREAD

**Issue by michaeldino27** [googleapis/nodejs-storage#617]
Hi,

I'm new to reactjs and not entirely sure if this is a bug or not, I've tried searching through the internet for possible fix for for 2days now and did not have any luck, i even tried below attempts on fixing the issue in 2 different computers and always get the same issue so i decided to report this issue here hoping somebody could shed some light to this problem. 
I've been trying to setup my create-react-app to be able to retrieve files from gcs(Hosted in app engine).
1st problem was when i installed the "@google-cloud/storage" and tried running the app, it gave this compilation warning: "**Module not found: Can't resolve 'worker_threads'** " so i went to node_modules/write-file-atomic and changed the code from require('**worker_threads**') to require('**worker-threads**') and installed the worker-threads then this issue went away, now I'm stuck with this error(Unhandled Rejection (TypeError): Expected `input` to be a `Function` or `Object`, got `undefined`) just by importing the @google-cloud/storage like below.

1. `import { Storage } from "@google-cloud/storage"`
2. `import Storage from "@google-cloud/storage"`
3. `require("@google-cloud/storage")`
4. `const config = { `
`projectId: "my-project-id",`
`keyFilename: "path/to/my/keyfile.json"`
// tried changing this to require("path/to/my/keyfile.json"), 
// tried changing the path from local drive(i.e. D:/Documents/keyfile.json) to code level path(i.e. /keyfile.json)
`
}
const Storage = require("@google-cloud/storage")(config);
`
5. `const Storage = require("@google-cloud/storage")({`
`projectId: "my-project-id",`
`keyFilename: "path/to/my/keyfile.json"` // tried changing this to require("path/to/my/keyfile.json"), 
// tried changing the path from local drive(i.e. D:/Documents/keyfile.json) to code level path(i.e. ./keyfile.json)
`});`

6. `const Storage = require("@google-cloud/storage");`
`const storage = new Storage({`
`projectId: "my-project-id",`
keyFilename: "path/to/my/keyfile.json" // tried changing this to require("path/to/my/keyfile.json"), 
// tried changing the path from local drive(i.e. D:/Documents/keyfile.json) to code level path(i.e. /keyfile.json)
`})`

All the possible combination that i can think if I've already tried and all of them failed.
I tried explicit setting up of the credentials like above, as well as the implicit one, all of them did not work, did not even change the error(hoping to make a baby steps in solving the issue).

I also tried downgrading from @google-cloud/storage@2.4.2 to 2.0.0 and got the same error.
At this point i'm out of clue, so any help will be much appreciated.

#### Environment details

  - OS: Windows
  - Node.js version: v10.15.0
  - npm version: 6.4.1
  - `@google-cloud/storage` version: 2.4.2

#### Steps to reproduce

  1. npm i @google-cloud/storage
  2.  import like the examples above on how i did the import
  3. npm start

**Comment by callmehiphop** [comment]
I'm pretty sure most of the snippets you've posted won't actually work, the correct way to create the client is as follows

```js
import {Storage} from '@google-cloud/storage';
// or if no import
const {Storage} = require('@google-cloud/storage');

const storage = new Storage({
  projectId: 'my-project-id',
  keyFilename: 'path/to/my/keyfile.json'
});
```

**Comment by jkwlui** [comment]
^ should be the correct way to initialize the library. It's also shown in the library's [README.md](https://github.com/googleapis/nodejs-storage). `keyFilename` expects a string which is the path to the file.

Please let us know if there're anymore issues getting it to work.

**Comment by michaeldino27** [comment]
Hi,
I've tried both approach just now and got the same error.
I have placed my json file at the same location of the js where i am trying to import.

**Comment by callmehiphop** [comment]
@michaeldino27 Is this code meant to run in the browser? I'm trying to figure out why you would want to manually change `worker_threads` to `worker-threads`?

**Comment by michaeldino27** [comment]
@callmehiphop Yeah i think i know already why it is not working, in my project setup it will really not work as the project is csr and not a reactjs ssr. thank you for you quick response. appreciate it.
