### ISSUE TITLE
Feature Request in getFiles: order and filter result

### ISSUE THREAD

**Issue by ivanandrianto** [googleapis/nodejs-storage#62]
I'm sure it will be useful if we can order result by certain criteria, such as  by date, name, or file type either ascending or descending.
In addition, it would be better if we can filter files by name. Therefore only matching files will be returned, not all files in the bucket

Is it possible with the current API provided by Google Cloud Storage? Unfortunately it's not easy to find the API documentation.

**Comment by callmehiphop** [comment]
The API documentation for the Storage module has moved recently, so let me apologize for the inconvenience. You can find it [here](https://cloud.google.com/nodejs/docs/reference/storage/1.4.x/Bucket#getFiles). 

As for your request, the API itself supports prefixes and delimiters (as mentioned [here](https://cloud.google.com/storage/docs/json_api/v1/objects/list)), however it does not appear that they support any sort of ordering.
