### ISSUE TITLE
SigningError when deployed to GCP

### ISSUE THREAD

**Issue by fedemar** [googleapis/nodejs-storage#622]
Hi all, 

I have a web site that needs to access private images on GCP storage, for that I'm calling getSignedUrl on the backend for each file before returning. 
Works fine when running locally but when deployed to GCP App Engine it throws SigningError exception each time getSignedUrl is called.
I've assigned the Owner role to the App Engine default service account with no avail.

@google-cloud/storage version: 2.4.2

Here's the code that signs the url

```
var config = {
            action: 'read',
            expires: new Date().getTime() + (1000 * 60 * 5)
        };

const response = await file.getSignedUrl(config);
```

Any idea what the problem could be?

**Comment by fedemar** [comment]
The issue went away by deploying the solution along with the json credentials for a service account with Owner role and setting the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to it.

I would assume this is not the intended use for the credentials, so I guess there should be an alternative solution. 

Not sure why the App Engine default credentials with Owner role doesn't work...

**Comment by jkwlui** [comment]
Hi @fedemar - I've tested this on App Engine on node10 but was able to generate a signed URL for a bucket file with no problems, using default credentials on app engine.

There should be an error message attached to the `SigningError` - does it indicate why the signing failed?
