### ISSUE TITLE
Is autoRetry working?

### ISSUE THREAD

**Issue by Maxpain177** [googleapis/nodejs-storage#661]

**Comment by JustinBeckwith** [comment]
Greetings!  We'd love to help, but we're going to need more information than that :) Please share:
- What code you're using
- What version of the module you're using
- Any errors you're getting, or expected behaviors

After that - we can try to take a look!

**Comment by Maxpain177** [comment]
Can you answer to my question please?

**Comment by Maxpain177** [comment]
Srsly?

**Comment by JustinBeckwith** [comment]
@Maxpain177 we would love to help - but we really need you to answer the questions above, an just for good measure - make sure to read our [Code of Conduct](https://github.com/googleapis/nodejs-storage/blob/master/CODE_OF_CONDUCT.md) :)
