### ISSUE TITLE
Why do we have 2 system-test scripts?

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/nodejs-storage#668]
https://github.com/googleapis/nodejs-storage/blob/master/package.json#L35-L38

And which one do we want?

**Comment by bcoe** [comment]
@JustinBeckwith @jkwlui I don't know enough to have an opinion about this yet, but curious about the answer; feels like probably it should be CI/CD that decides which tests to run, rather than running two types of tests in one script? (just my gut shot).

**Comment by jkwlui** [comment]
Yeah I wanted to run both tests as part of Kokoro's `System-test` build. I didn't realize I hadn't actually done this 😛, sorry!

Having to add another test build to our existing CI is not the easiest - so I think for now I'll just make it run after system-tests in the same build.
