### ISSUE TITLE
Tuple type '[File[]]' with length '1' cannot be assigned to tuple with length '3'.

### ISSUE THREAD

**Issue by n-for-all** [googleapis/nodejs-storage#672]
`bucket
				.getFiles({
					prefix: dir,
					delimiter: '/',
					autoPaginate: false,
				})
				.then(function([files, _nextQuery, apiResponse]) {`

Tuple type '[File[]]' with length '1' cannot be assigned to tuple with length '3'.
How can i fix this error in typesript?

**Comment by jkwlui** [comment]
It appears this function doesn't return `_nextQuery` and `apiResponse`:

```
  getFiles(query?: GetFilesOptions): Promise<[File[]]>;
```

**Comment by n-for-all** [comment]
```
export interface GetFilesCallback {
  (err: Error|null, files?: File[], nextQuery?: {},
   apiResponse?: Metadata): void;
}
```

GetFilesCallback returns apiResponse and so does the promise, infact apiResponse['prefixes'] will return all the prefixes for the files, it is just an error in the definition

**Comment by jkwlui** [comment]
Ah I see. Thanks for clarifying it for me. It looks like you'll get the `apiResponse` if you had set `autoPaginate: false`.
