### ISSUE TITLE
Google upload video createWritestream()  memory leak 

### ISSUE THREAD

**Issue by jaman99** [googleapis/nodejs-storage#673]
**I use   Multer** 

try{

  if(req.video_size_check){

   var myvideo=req.files.myvideo[0].originalname;
  
   var ext = path.extname(''+myvideo+'');
    const gcsname =Date.now()+ext;
      
		  const file = bucket.file(gcsname);
   
		  const stream = file.createWriteStream({
		    metadata: {
		      contentType: req.files.myvideo[0].mimetype
		    },
		    resumable: false
		  });

		  stream.on('error', (err) => {
		    req.files.myvideo.cloudStorageError = err;
		    req.videocheck=false;
		      mystreamendfun();
		    next(err);
		  });

		  stream.on('finish', () => {
		    req.files.myvideo.cloudStorageObjectimg = gcsname;
		    file.makePublic().then(() => {
		      req.files.myvideo.cloudStoragePublicUrlimg =getPublicUrl(gcsname);
		      req.videocheck=true;

		      next();
		    });
		  });

 	 stream.end(req.files.myvideo[0].buffer);

  }else{
  
  req.videocheck=false;
  next();
  }

 }catch(e){
 
req.videocheck=false;
 next()

 }

**Comment by jkwlui** [comment]
Hi there! thanks for the report. What was the message you received to suggest there was a memory leak?

**Comment by rangolisharan** [comment]
@jaman99 were you able to resolve this? I'm running into a similar issue trying to pipe a few 10s of Gigs to GCS.
