### ISSUE TITLE
ApiError with no reason. Cloud function, upload API

### ISSUE THREAD

**Issue by Kshitij-Banerjee** [googleapis/nodejs-storage#674]
In my firebase cloud function, I get the following error: Cannot parse JSON response (which is not very helpful).  

My cloud function is generating multiple csv files and trying to upload them to GCS bucket. 
The weird part is that some of the files do get uploaded, and some of them fail. It seems to be random. 

I tried 2.4.2, 2.4.3, 2.5.0 , all are giving the same error.  Earlier version 1.x was giving ESOCKETTIMEDOUT errors. 

When i run the function locally, I never get this error. It always finishes success. 

Could you please help to understand how to debug the same?  

```
Error: Cannot parse JSON response
    at ApiError (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:43:9)
    at Util.parseHttpRespBody (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:185:42)
    at Util.handleResp (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:422:22)
    at onResponse (/user_code/node_modules/@google-cloud/storage/node_modules/retry-request/index.js:200:7)
    at /user_code/node_modules/@google-cloud/storage/node_modules/teeny-request/build/src/index.js:158:17
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) message: 'Cannot parse JSON response'
```

#### Environment details

  - OS: mac
  - Node.js version: v8.9.4
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 2.5.0, 2.4.3, 2.4.2, 1.3

```
promises.push(Promise.all([

                filesysRef
                .outputFile(tmpFilePath, values.join('\n'))
                .then(() =>
                  gcs.bucket(bucketName).upload(tmpFilePath, { destination: filePath } )),

                filesysRef
                .outputFile(tmpItemFilePath, items.join('\n'))
                .then(() => gcs.bucket(bucketName)
                .upload(tmpItemFilePath, { destination: itemFilePath }
                )),

              ])
              .then(() => {
                gcs.bucket(bucketName).file(itemFilePath).exists()
                .then(() => { hour.ref.remove().then(() => console.log('done removeal'));
              }, err => console.log(err))
              .catch(error => {
                console.log(error)
              })
              .then(() => filesysRef.unlinkSync(tmpItemFilePath))
              .then(() => filesysRef.unlinkSync(tmpOrderFilePath))
            );


```
Function returns a Promise.all(promises) eventually. T. 

There is possibly a correlation on the memory size allocated to the function and the number of failures, but again I am not getting any useful error message to debug what the exact cause of the ApiError is. 

Would appreciate help in understanding how I can find the real reason of failure.

**Comment by Kshitij-Banerjee** [comment]
The way I've worked around this bug right now is the following.

1. Created two functions to do the processing, a parent and child.
2. parent function looks at the datasets and creates publishes multiple messages to a topic. 
3. The child function then subscribes to individual messages, in each instance it works on individual buckets and hence generates one csv per data bucket.  

This way the amount of memory being used per function call is limited and so far i'm not getting the error anymore (because individual buckets are small, compared to the sum of all). 


But again, my data is not that huge. its 200 or so jsons. divided in around 10 or so buckets, and I have 256 mb allocated to the functions.

**Comment by stephenplusplus** [comment]
@Kshitij-Banerjee sorry for the trouble. We have seen this "Cannot parse JSON response" error before, and it is either when the Storage JSON API doesn't return JSON for some reason, or when we somehow ping the XML API.

I filled in some blanks in your reproduction code: https://gist.github.com/stephenplusplus/82ad8615b7a7461c2426b7f33f9ae164 -- does this still look correct?

Any other details about the environment would be helpful as well (the more the better).

**Comment by stephenplusplus** [comment]
@Kshitij-Banerjee It seems like there is a lot of moving parts to your scenario, and any of them could be the culprit. In general, Pub/Sub has been working on some memory issues, and on top of that GCF is a unique environment. I'm going to close, but if you can provide more information about how to reproduce, we can start digging in. Sorry for the trouble.
