### ISSUE TITLE
@google-cloud/storage no longer works with Node.js 6

### ISSUE THREAD

**Issue by swalkowski** [googleapis/nodejs-storage#677]
#### Environment details

  - OS: Debian
  - Node.js version: 6.17.1
  - npm version: 3.10.10
  - `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce

  1. `npm install @google-cloud/storage@2.5.0` # latest version
  2. `cat > index.js`
```
require('@google-cloud/storage');
```
  3. `node index.js`
```
/home/swalkowski/node/storage/node_modules/gaxios/build/src/index.js:28
async function request(opts) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/swalkowski/node/storage/node_modules/gcp-metadata/build/src/index.js:17:18)
```

This is clearly caused by the update to the `gaxios` module 2 hours ago, which is a dependency of `gcs-resumable-upload`, which is a dependency of `@google-cloud/storage`. That update included https://github.com/JustinBeckwith/gaxios/pull/84 'build: drop support for node.js 6'. It was released as a patch version update so `gcs-resumable-upload` pulls it in.

I understand that Node.js 6 is going end of life but `@google-cloud/storage@2.5.0` should still support it, according to its package.json.

cc @JustinBeckwith

**Comment by thilinatnt** [comment]
I’m also facing this issue with a function hosted in firebase, I’m using this module in firebase function to download storage file content. It failed to deploy firebase functions after npm install, since firebase function support node 6.
Please let me know how to fix it, can I set an older version? If so what?

Really appreciate the help on this matter

**Comment by swalkowski** [comment]
You can switch to Node.js 8, see https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version. This should resolve the function deployment problem.

**Comment by thilinatnt** [comment]
Ok sure will try it, Thanks a lot! 🙇

**Comment by JustinBeckwith** [comment]
Greetings folks!  Apologies.  A downstream module released a patch release that accidentally dropped support for 6.x.  The `latest` tag on `gaxios` has been reverted to `1.8.4`.  You should be able to:
1. delete your `package-lock.json`
2. run `npm install`

And you should be fine.  Would folks mind trying this and ensuring everything works?

**Comment by JustinBeckwith** [comment]
Greetings folks - we're pretty sure this is resolved.  If this is still a problem - please do let us know!
