### ISSUE TITLE
getSignedUrl fails for v4 when including promptSaveAs OR responseDisposition

### ISSUE THREAD

**Issue by kaleidosim** [googleapis/nodejs-storage#682]
Setting promptSaveAs OR responseDisposition for v4 always results in SignatureDoesNotMatch error. Do note that both work fine for v2 though.

        async function getSignedUrl() {

            const { Storage } = require('@google-cloud/storage');

            const storage = new Storage({
                keyFilename: './gitignore/gcp.json'
            });

            const options = {
                version: 'v4',
                action: 'read',
                expires: Date.now() + 1000 * 60 * 60, // one hour
                // promptSaveAs: 'rajchaudhary.txt', // does not work for v4
                // responseDisposition: 'attachment; filename="rajchaudhary.txt"' // does not work for v4
            };

            const [ url ] = await storage.bucket('kaleido').file('raj.txt').getSignedUrl(options);

            console.log(url);        

        }

OS: Windows 8.1
Node.js: 10.15.1
npm: 6.4.1
@google-cloud/storage: 2.5.0

**Comment by vishald123** [comment]
Hi @kaleidosim, You can set the `Content-Disposition` parameter [here](https://console.cloud.google.com/storage/browser/powerful-decker-219612.appspot.com?project=powerful-decker-219612).  You need to add metadata to your object. ex. `Content-Disposition` : `Attachment; filename = "example.txt`.
![metadata](https://user-images.githubusercontent.com/44579906/57617403-b8cf4100-754e-11e9-9d94-24282253c091.PNG)

You can try the following changes
```js
async function getSignedUrl() {

    const { Storage } = require('@google-cloud/storage');
    const storage = new Storage({
        projectId : "['PROJECT_ID']",
        keyFilename : "['PATH_TO_KEY_FILE.json']"
    });

    const options = {
        version: "v4",
        action: "read",
        expires: Date.now() + 1000 * 60 * 60, // one hour
        contentDisposition : " attachment; filename= example.txt",
    };

    await storage.bucket('['BUCKET_NAME']')
                    .file('['FILENAME]')
                    .getSignedUrl(options
                        , function (error,url) {
                        if(error){
                            console.error(error);
                            return;
                        }
                        console.log(url) ;
                    });
}

getSignedUrl().catch(console.error);
```
Let me know if this works for you.

**Comment by vishald123** [comment]
@kaleidosim you can try the following way. It worked for me.

```js
// Imports the Google Cloud client library
        const {Storage} = require('@google-cloud/storage');

        // Creates a client
        const storage = new Storage({
            projectId : "[PROJECT_ID]",
            keyFilename : "[KEY_FILE.json]"
        });

        const bucketName = '[GOOGLE_CLOUD_BUCKET_NAME]';
        const filename = '[FILE_NAME]';

        const meta = await storage
        .bucket(bucketName)
        .file(filename).setMetadata({
             contentDisposition: 'attachment; filename*=utf-8\'\'second-file.txt',
        });

        // These options will allow temporary read access to the file
        const options = {
        version: 'v4', // defaults to 'v2' if missing.
        action: 'read',
        expires: Date.now() + 15 * 60 * 1000, // 15 minutes,
        };

        // Get a signed URL for the file
        const url = await storage
        .bucket(bucketName)
        .file(filename)
        .getSignedUrl(options);

        console.log('Generated GET signed URL:');
        console.log(url);
        console.log('You can use this URL with any user agent, for example:');
        console.log(`curl '${url}'`);

```

**Comment by AVaksman** [comment]
@kaleidosim please see documentation [link](https://cloud.google.com/storage/docs/access-control/signed-urls#considerations)

**Comment by AVaksman** [comment]
@kaleidosim 
I am closing this issue as the feature you are asking for is not currently supported by back-end.
To report a back-end issue or feature request please refer [here](https://cloud.google.com/storage/docs/getting-support#file_bugs_or_feature_requests) .
