### ISSUE TITLE
How to get subdirectory size without having to compute response of getFiles()

### ISSUE THREAD

**Issue by avin3sh** [googleapis/nodejs-storage#686]
Passing the subdirectory `prefix` to getFiles() will return entire hierarchy but this doesn't seem like an efficient method to compute the size of a subdirectory in a bucket. Is there are any known workaround this ?

**Comment by AVaksman** [comment]
@avin3sh Currently there seems no other way to do it. However, `getFiles()` returns only the file objects with its metadata, so it is quite fast. Also it is a paged response, stream version is available as well.
```ts
async function getSubdirectorySize() {
  const [files] = await bucket.getFiles({directory: 'my/directory/path'});
  let size = 0;
  files.forEach(file => {
    size += Number(file.metadata.size);
  });
  console.log(`subdirectory size is ${size}`);
}
```

**Comment by frankyn** [comment]
A solution to this problem would be to use [Cloud Storage Access Logs storage logs]( https://cloud.google.com/storage/docs/access-logs) and massage the data available using BigQuery to get a prefix data size.
