### ISSUE TITLE
No error is given using getFiles or getBuckets

### ISSUE THREAD

**Issue by barocsi** [googleapis/nodejs-storage#707]
Using the example .getFiles or .getBuckets return undefined data or empty arrays with no errors to catch in the promise when providing invalid credentials, why?

**Comment by AVaksman** [comment]
Thank you @barocsi for reporting it.

Please give some more information. 
In particular what version of the library are you using and what scenario of the invalid credentials you are experiencing you issue with.

I have tested 
1. valid keyfile with no permissions to `GET` the object/file.
2. a valid keyfile (local) that does not exist on the server.
3. keyfile with modified property (no existing email)

All above cases returned exceptions.

**Comment by AVaksman** [comment]
@barocsi Are you still experiencing this? I will close this issue for now, but if you still notice the same behavior please reopen the issue.
