### ISSUE TITLE
Error while uploading streams

### ISSUE THREAD

**Issue by Turniii** [googleapis/nodejs-storage#711]
#### Environment details

  - OS: Debian GNU/Linux 9
  - Node.js version: 9.11.2
  - npm version: 5.6.0
  - `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce

  1. Prepare a bucket to store files (which are private)
 
```javascript
const cluster = require('cluster');
const { Storage } = require('@google-cloud/storage');
const gcs = new Storage();
const bucket = gcs.bucket('myBucket');

const getData =  async(index) => {
  return; // Data to store, fetched with the use of the index [array]
}

const promisedWrite = (stream, data) =>
  new Promise((resolve) => {
    stream.write(data, 'utf-8', resolve);
  });

if (cluster.isMaster) {
  for (let i = 0; i < 64; i++) {
    cluster.fork({ index: i });
  }
} else if (cluster.isWorker) {
  const index = process.env.index;
  const writeStream = bucket.file(`tmp/${index}.txt`).createWriteStream();
  getData(index).then(async data => {
    for (let i = 0; i < data.length; i++) {
      await promisedWrite(writeStream, data[i]);
    }
    writeStream.end();
  });
}
```

I am using clusters to split the data in several file and uploading them to google storage. The problem is that I get the following error for some streams.
The errored streams are completly random in quantity and it's not the same index each time.

>Error: Upload failed
>    at Upload.on (/myproject/node_modules/gcs-resumable-upload/build/src/index.js:173:34)
>    at Upload.emit (events.js:185:15)
>    at Upload.onResponse (/myproject/node_modules/gcs-resumable-upload/build/src/index.js:376:14)
>    at Upload.<anonymous> (/myproject/node_modules/gcs-resumable-upload/build/src/index.js:324:18)
>    at Generator.next (<anonymous>)
>    at fulfilled (/myproject/node_modules/gcs-resumable-upload/build/src/index.js:10:58)
>    at <anonymous>
>    at process._tickCallback (internal/process/next_tick.js:182:7)

Thank you for your help

**Comment by jkwlui** [comment]
Thanks for the report, @Turniii.
My first hunch to why you're getting is we're hitting some request limit to the API - particularly noticed that you tries to write data to the Writable stream byte-by-byte. However it's hard to tell because `gcs-resumable-upload` swallowed the error message. 

@stephenplusplus Can we make `gcs-resumable-upload` emit the error message?

**Comment by Turniii** [comment]
I changed my destination bucket and now it's working.
I don't know the reason why.
