### ISSUE TITLE
file.download() takes too long if file does not exist

### ISSUE THREAD

**Issue by sokolandia** [googleapis/nodejs-storage#720]
## Blocked
- [x] https://github.com/fhinkel/teeny-request/issues/39
- [x] Release teeny-request
- [x] [Update nodejs-common dependency](https://github.com/googleapis/nodejs-common/pull/435)
- [x] Release nodejs-common

---

#### Environment details

  - OS: Ubuntu 16.04.5 LTS
  - Node.js version: 9.5.0
  - npm version: 5.7.0
  - `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce
```
const {Storage} = require('@google-cloud/storage');
const process = require('process');
const storage = new Storage({autoRetry: false});
const hrstart = process.hrtime();
const bucketName = 'my-app.appspot.com';
const bucket = storage.bucket(bucketName);
bucket.file('does_not_exist')
  .download()
  .catch(() => {
    const hrend = process.hrtime(hrstart);
    console.info('Execution time (hr): %ds %dms', hrend[0], hrend[1] / 1000000);
  });
```
The result I get locally is `Execution time (hr): 9s 79.380959ms`. I thing there might be an issue with dependencies `teeny-request` or `node-fetch`.

**Comment by stephenplusplus** [comment]
Thank you for the report. And your hunch is correct-- it is due to some logic inside of teeny-request. I have opened an issue here: https://github.com/fhinkel/teeny-request/issues/39

**Comment by stephenplusplus** [comment]
@sokolandia this should be good to go now! The update was made upstream, so a fresh install of @google-cloud/storage will pick up the changes. Thank you again for catching this issue!

**Comment by stephenplusplus** [comment]
Sorry-- this issue is resolved on master, but we need a release to put it out: #719
