### ISSUE TITLE
Timeout should be configurable as StorageOption

### ISSUE THREAD

**Issue by ildella** [googleapis/nodejs-storage#733]
There is no way to configure the timeout for a storage call. 
In 2.5 the [StorageOptions](https://cloud.google.com/nodejs/docs/reference/storage/2.5.x/global#StorageOptions) object that is passed as parameter on a new Storage() does not have any field for that. 

In the [python documentation](https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/retryparams_class) there is `urlfetch_timeout` for this. 

It would be great to have the same option in the nodejs library as well.

**Comment by stephenplusplus** [comment]
@AVaksman this appears to have been addressed in https://github.com/googleapis/nodejs-common/pull/455. Is more work required, or is this feature live for new Storage downloads?

**Comment by stephenplusplus** [comment]
Ping @AVaksman for clarity!

**Comment by AVaksman** [comment]
Work in progress to expose timeouts to user on a high level.

**Comment by moshekrup** [comment]
Any updates for this issue?
Does any way to define the timeout for the storage request?
Thanks
