### ISSUE TITLE
refactor: remove dependency on async module

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-storage#746]
we still rely on `async` in a few places, which broke a recent release of the module (as it was a devDependency only).

**Comment by AVaksman** [comment]
@bcoe is devDependency on `async` is OK or rather remove that as well?

**Comment by bcoe** [comment]
@AVaksman @callmehiphop I think if it simplifies our refactor, keeping `async` as a dev dependency for the time being is reasonable.

Will leave it to you and @callmehiphop to decide.
