### ISSUE TITLE
save reports 403 after upgrading from 2.5.0 to 3.0.1

### ISSUE THREAD

**Issue by jcjones1515** [googleapis/nodejs-storage#748]
## Blocked

- [ ] https://github.com/googleapis/google-auth-library-nodejs/pull/735

---

#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: 8
  - npm version:
  - `@google-cloud/storage` version: 3.0.1

#### Steps to reproduce

  1. Upgrade to 3.0.1
  2. Code makes a `save` call on a GCS file object
  3. Fails with this message:

```{ errors: [ { domain: 'global', reason: 'insufficientPermissions', message: 'Insufficient Permission' } ], code: 403, message: 'Insufficient Permission' }```

After upgrading to 3.0.1 my Google Cloud Function started getting this on trying to save a file via `File.save`.  I am providing a content type and a few metadata fields in the call.  Seems to work just fine with 2.5.0, but upon upgrading to 3.0.1 it starting giving me a 403.  If I revert back to 2.5.0 it starts working again.

Sorry I don't have more detail than that.

**Comment by bcoe** [comment]
@jcjones1515 to help us isolate a reproduction, mind sharing the extension of the file, and the metadata fields as well if possible?

**Comment by jcjones1515** [comment]
content type is `application/pdf` (extension is .pdf) and the metadata is 4 keys with very simple string and one key with stringified JSON.

**Comment by stephenplusplus** [comment]
@jcjones1515 sorry for the trouble. The team has removed 3.0.1 from npm and rolled back the `latest` tag, so that new installs of @google-cloud/storage will not use the broken version.

I've found the issue and have sent a PR with a proposal for a fix: https://github.com/googleapis/google-auth-library-nodejs/pull/735
