### ISSUE TITLE
Bucket#upload() options don't show up in documentation

### ISSUE THREAD

**Issue by jmdobry** [googleapis/nodejs-storage#75]
The options are documented in the [source code](https://github.com/googleapis/nodejs-storage/blob/master/src/bucket.js#L2053), but for some reason don't show up on [cloud.google.com](https://cloud.google.com/nodejs/docs/reference/storage/1.4.x/Bucket#upload)

**Comment by stephenplusplus** [comment]
That seems to be the case for all methods on Bucket. I don't know the spec on this, but maybe marking `options` as optional is enough, and it would be implied that `options.*` is optional. In diff:

```diff
 * @param {object} [options] Configuration options.
- * @param {string|File} [options.destination] The place to save
+ * @param {string|File} options.destination The place to save
```

**Comment by jmdobry** [comment]
I don't think that's the problem. When you run `npm run docs` locally and it uses the docstrap template, these options all show up fine in the generated docs. But when we generate the docs using our custom template on cloud.google.com, the options are missing. It must be a problem with the template we use on cloud.google.com.

**Comment by stephenplusplus** [comment]
Does another team need to take a look into why these aren't showing up?

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783.
