### ISSUE TITLE
Update Existing File in Google Cloud Storage

### ISSUE THREAD

**Issue by ankurgpt6719** [googleapis/nodejs-storage#755]
Does the nodejs-storage library has the support to update the existing file present in the bucket ?

**Comment by ankurgpt6719** [comment]
Do the nodejs-storage library has the support to update the existing file present in the bucket ?

**Comment by AVaksman** [comment]
@ankurgpt6719 to clarify, are you looking to overwrite content of an existing file on a bucket?

**Comment by ankurgpt6719** [comment]
@AVaksman yeah

**Comment by AVaksman** [comment]
Objects in Google Cloud Storage are immutable, once successfully uploaded it can't be changed. It can only be overwritten by a new upload. Supporting documentation is [here](https://cloud.google.com/storage/docs/key-terms#immutability).

What you could do is to upload the data to be appended in a separate temp file and then [combine](https://googleapis.dev/nodejs/storage/latest/Bucket.html#combine) to existing files into one overriding the original file.

```ts
async function uploadCombineDelete(originaFile, data) {
  const [file] = await bucket.file('tempFile').save(config);
  console.log(`${file.name} uploaded`);
  const [newFile] = await bucket.combine([originalFile, 'tempFile'], originalFile);
  console.log(`appended to ${newFile.name}`);
  await bucket.file('tempFile').delete();
}
```

**Comment by AVaksman** [comment]
I am closing this issue. If there are more questions please feel free to reopen it.

**Comment by Joe-bookdepot** [comment]
How can we replace/overwrite the uploaded file with a new file?
