### ISSUE TITLE
getSignedUrl does not check if file exists

### ISSUE THREAD

**Issue by JensMadsen** [googleapis/nodejs-storage#762]
I acidentally used a wrong bucket name when using `getSignedUrl`. function returns url to non-existing file (wrong bucket....)

see https://github.com/googleapis/nodejs-storage/blob/99e3b17f0b12ea66ed46060ca291124b10772111/src/file.ts#L2420

**Comment by AVaksman** [comment]
The resource (bucket of file) doesn't need to exist at the time of creation of signedURL.

Possible scenarios:
* Get signed URL to upload a new file (`write` or `resumable` action).
* Even if file existed at the moment of getting signed URL, the file can be deleted afterwards and you will also end up with the signed URL to a non existing file.
* The file (and the bucket) can be created after creation of signed URL and that signed URL can be used to get,  upload or delete the file.

**Comment by JensMadsen** [comment]
I still do not consider this behaviour intuitive in the standard use case. I would expect that when I ask for a signed url i get one I can use; but thats mayby just me :-) In any case perhaps consider a warning or smiilar? Best Jens

**Comment by stephenplusplus** [comment]
If there's a chance of a non-existing file in your app, maybe you could use `file.exists()` to help. It will return true/false if the file exists, and if so, you can proceed with creating the resumable URL.

**Comment by JensMadsen** [comment]
@stephenplusplus Thanks. I have already fixed the problem. Not difficult at all. Just a comment about what I as a naive user would expect from `getSignedUrl`. I develop clients and api's myself so sometimes this kind of user feedback can be useful :-) Best Jens
