### ISSUE TITLE
file.save and file.download of zipped content

### ISSUE THREAD

**Issue by rutanika** [googleapis/nodejs-storage#763]
Hello, 

We use file.save and file.download in order to upload and to download files.
We have the following issue with .zip files:

1. file.save content of .zip file --> succeded.
2. file.download the same .zip file --> succeded.

However, there’s a binary difference between the uploaded and downloaded zip file and the downloaded zip does not open.
When trying to unzip it we get "Unexpected end of file error".
It happens with very simple zip file that contains just very small text file.

Do we miss something?
Could you please assist?

Thanks, 
Talia

**Comment by stephenplusplus** [comment]
Hi Talia, sorry for the trouble. I put together a small reproduction gist, and it seems to succeed for me. Would you mind testing this or providing a reproduction script of your own?

https://gist.github.com/stephenplusplus/a79fe4032c014124cf4a97e00d8e6ab7

**Comment by rutanika** [comment]
Hi Stephen, 

I will try to explain the difference.

The zip we want to upload to GCP object store is a zip inside the complete zipped application (**body**). 
We use jszip npm to extract it:
jszip.loadAsync(**body**).then((**zipContent**)

Then we loop on the files inside **zipContent**:
async.eachSeries(**zipContent**.files, (**zipEntry**, callback)

And for each file (**zipEntry**) we extract the data 
**zipEntry.async('nodebuffer').then((**data**)**

and this is (**data**) what we upload to GCP object store using file.save:
file.save(**data**, meta).then…

We had a look into file.save and it looks similar to your example. 
So the main difference between your example and our code is that we use async('nodebuffer')

But I have to mention that the same works fine in AWS S3.

Should we pass some more parameter to the file.save in order to make it work?

Thank you in advance, 
Talia
