### ISSUE TITLE
Support readable[Symbol.asyncIterator]() Readble returned by createReadStream()

### ISSUE THREAD

**Issue by bag-man** [googleapis/nodejs-storage#765]
`createReadStream()` is typed as creating a `Readable`, however it doesn't fulfill the interface as of  node 10.16, as there is no `readable[Symbol.asyncIterator]()`. 

https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_readable_symbol_asynciterator

**Comment by JustinBeckwith** [comment]
Thanks for the issue!  Are you running into some kind of error?  Or something that doesn't work right?  Could you share:
- Any error / exception you're getting
- What code you're using to get it

Thanks!

**Comment by bag-man** [comment]
Here is a non running example (for brevity), but you can get it running super easily. It shows that if you try to do `for await (const chunk of stream)` like you should be able to do on `Readable` streams in node >= 10.16, you get a `TypeError: o[Symbol.iterator] is not a function`. 

```typescript
import { Storage } from '@google-cloud/storage';
import { createReadStream } from 'fs';

const storage = new Storage();
const bucket = storage.bucket('bucket-name');
const file = bucket.file('file/path.txt');
const stream = file.createReadStream();
const chunks: Buffer[] = [];

// This causes:
// (node:16953) UnhandledPromiseRejectionWarning: TypeError: o[Symbol.iterator] is not a function
for await (const chunk of stream) {
  chunks.push(chunk);
}
const file2: string = Buffer.concat(chunks).toString();
console.log(file2);

// So you have to do this:
stream.on('data', (data: Buffer) => {
  chunks.push(data);
});

stream.on('end', async () => {
  const contents = Buffer.concat(chunks).toString();
  console.log(contents);
});

stream.on('error', () => {
  throw new Error('Failed to get file');
});

// A real Readable stream can do this in node >10.16
const fileChunks: Buffer[] = [];
const testData = __dirname + 'filename.txt';
const fileStream = createReadStream(testData);

for await (const chunk of fileStream) {
  fileChunks.push(chunk);
}

const file2: string = Buffer.concat(fileChunks).toString();
```

**Comment by jkwlui** [comment]
Looking through our dependency chain, we're using the [`readable-stream`](https://github.com/nodejs/readable-stream) module in our transformation logic, and it's fixed to use `readable-stream@2.x`, which doesn't implement `[Symbol.iterator]` just yet.

Given that Node.js 12 [made](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator) this stable, we should look into bringing this in. @stephenplusplus you're the expert here - thought?

**Comment by arjunyel** [comment]
This is my first time using Nodejs streams but I believe I am coming across this too while using the firebase admin sdk

`const fileStream = admin.storage().bucket().file(filepath).createReadStream();
  for await (const chunk of fileStream) {
    console.log('>>> '+chunk);
}`

And the error is Invalid 'for-await-of' of a non-AsyncIterable value. (await-promise) tslint(1)

**Comment by AVaksman** [comment]
You may want to try a workaround for now. 
Set an environment variable `READABLE-STREAM` to 'disable'.
Please let me know if it worked for you.

**Comment by JustinBeckwith** [comment]
@stephenplusplus this appears to be due to an old version of `readable-stream`.  Following the chain I'm seeing this all boil down to this:
https://github.com/googleapis/gcs-resumable-upload/pull/237

The outdated version of pumpify is pulling in an old version of duplexify which is pulling in an old version of through2 which is pulling in an old version of readable-stream.  

Can you chase this down?

**Comment by stephenplusplus** [comment]
@JustinBeckwith gcs-resumable-upload@2.2.3 was released a week ago. Does that fix this issue?

**Comment by JustinBeckwith** [comment]
Should 🤷‍♂ Could I trouble you to try adding a system test that uses async iterators over a stream?

**Comment by AVaksman** [comment]
> @JustinBeckwith gcs-resumable-upload@2.2.3 was released a week ago. Does that fix this issue?

It should fix the issue once gcs-resumable-upload dependency is updated here on the storage.
was proposed in #773 (when it still was @2.2.2)
