### ISSUE TITLE
storage: add port option

### ISSUE THREAD

**Issue by jadekler** [googleapis/nodejs-storage#775]
Currently storage supports [apiEndpoint](https://github.com/googleapis/nodejs-storage/blob/master/src/storage.ts#L57). However, it should also support port, so that we can use this client against emulators.

**Comment by AVaksman** [comment]
It is possible to set port via `apiEndpoint`.
```ts
const storageClient = new Storage({
    apiEndpoint: 'localhost:' + customPort,
})
```
Do we need a separate optional `port` parameter that will be appended to or will override (if provided by user) `port` value of the `apiEndpoint`?

Or perhaps providing a sample and mentioning it in documentation will suffice?

**Comment by jadekler** [comment]
Yep, you're right. Closing.
