### ISSUE TITLE
HTTP_PROXY/http_proxy env variable name 

### ISSUE THREAD

**Issue by Rantoledo** [googleapis/nodejs-storage#776]
Hey,

I've been trying to access google APIs (storage API mainly) using a proxy. 
The documentation says you can set environment variables HTTP_PROXY/http_proxy with no further explanation (https://www.npmjs.com/package/googleapis#using-a-proxy).
So I set http_proxy, and it didn't work for me. Only HTTP_PROXY worked for me.
I think it's best to clarify the documentation, or just fix it - I dug down a little bit in your code and found out requests are made using 'teeny-request', and in this package code, they only consider HTTP_PROXY, and not http_proxy.

**Comment by JustinBeckwith** [comment]
Thanks for digging here!  We have a fix queued up over in https://github.com/googleapis/teeny-request/pull/56 for the underlying issue.

**Comment by stephenplusplus** [comment]
The fix was released, so we should be good to go! Let me know if there are still any issues.
