### ISSUE TITLE
Bucket open to specific website

### ISSUE THREAD

**Issue by ckhzb** [googleapis/nodejs-storage#794]
I use reactjs to create a website and host it on firebase, and set `serviceAccount.json` with `firebase-admin` and `@google-cloud/storage` on cloud functions to handle functions. Website has a `<iframe>` element, it will load `aaa.html` link url from bucket in google cloud storage.

><iframe src="https://storage.googleapis.com/bucket/aaa.html" />

And `aaa.html` will also load other files (`.js` files and `.png` files) stored in the same bucket. Users can login with `firebaseui-web-react`. `<iframe>` will load `aaa.thml` whether the user has logged in or not.

When I use `gsutil iam ch allUsers:objectViewer gs://bucket` to set bucket public and all files public, users can see that `aaa.html` is loaded. But I do not want that users could link `aaa.html` without going through my website. Set bucket and files public is seems to be incorrect. So I changed bucket and files back to private. `<iframe>` gets access denied with anonymous caller after change. 

My questions is how to load `aaa.html` successfully, where bucket is private and users is login or not?

Function `.getSignedUrl` is not for me, because user can link url without going through my website.

**Comment by stephenplusplus** [comment]
In this bug tracker, we're primarily focused on issues or feature requests for the Node.js @google-cloud/storage library. I think your question could be a good one for the community of GCS developers, in a place like StackOverflow. The official Storage [Support page](https://cloud.google.com/storage/docs/getting-support) links there as well as other places which could help. Please link back if you find an answer, as it may help other developers in the future. Thanks!
