### ISSUE TITLE
Resumable upload not possible with cloud functions

### ISSUE THREAD

**Issue by hixus** [googleapis/nodejs-storage#807]
## Blocked

- [x] gcs-resumable-upload needs a new release which includes https://github.com/googleapis/gcs-resumable-upload/pull/260

---

Should be possible to set resumable upload dir from config. Currently fails with node10 cloud function as only /tmp is writable 

#### Environment details

  - OS:
  - Node.js version: node10 cloud-function
  - npm version:
  - `@google-cloud/storage` version: 3.0.3

#### Steps to reproduce

  1. deploy nodejs cloud function
  2. try to upload large file from /tmp
  3. A resumable upload could not be performed. The directory, /root/.config, is not writable. You may try another upload, this time setting `options.resumable` to `false`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
You should be able to set an option, `configPath`, which will override where that file gets written to. Can you give that a shot and let me know how it goes?

**Comment by jiren** [comment]
Issue is related to gcs-resumable  https://github.com/googleapis/gcs-resumable-upload/issues/259

**Comment by stephenplusplus** [comment]
This issue has been resolve upstream in gcs-resumable-upload. New installations of @google-cloud/storage will pick this up. Let us know if there are still any issues!

**Comment by SinanGabel** [comment]
Hi, just to let you know that I have this issue using @google-cloud/storage 4.0.0 and google cloud functions nodejs version 8. 

Upload works if upload from `/tmp/big_file` has `options: {resumable: false}` but not with `options: {resumable: true}`.

My full options list is:

`let options = {resumable: false, metadata: {gzip: true, cacheControl: "public, max-age=31536000"}};`

**Comment by stephenplusplus** [comment]
@SinanGabel you should set an option, `configPath` that points to a writable directory:

```js
let options = {
  configPath: '/path/to/writable/directory',
  metadata: {
    gzip: true,
    cacheControl: "public, max-age=31536000"
  }
};
```

**Comment by reco** [comment]
> Hi, just to let you know that I have this issue using @google-cloud/storage 4.0.0 and google cloud functions nodejs version 8.
> 
> Upload works if upload from `/tmp/big_file` has `options: {resumable: false}` but not with `options: {resumable: true}`.
> 
> My full options list is:
> 
> `let options = {resumable: false, metadata: {gzip: true, cacheControl: "public, max-age=31536000"}};`

same here. tried to point configPath: '/tmp/'
still getting errors

**Comment by sgoertzen** [comment]
It appears this issue still exists.  I am seeing the same issue with:
- `@google-cloud/storage: 4.3.0`
- `node: 10`

Adding `resumable: false` to my config did fix the problem.

**Comment by jacksontong** [comment]
I have same issue
@stephenplusplus why can't it write to /tmp? as I'm able to write my file to /tmp, I don't know other writeable directory on cloud function.

**Comment by aponski** [comment]
I'm also having this problem. What other directory than /temp can be set in configPath?

**Comment by malimccalla** [comment]
I'm having this issue with `4.7.0` also. The error im getting is

```err
ResumableUploadError: A resumable upload could not be performed. The directory, /root/.config,
is not writable. You may try another upload, this time setting `options.resumable` to `false`.
``` 

I am able to write files to this location when I download them

**Comment by airowe** [comment]
Yeah, I'm having this issue all the time as well.

**Comment by nvtin** [comment]
I am facing this issue.

**Comment by wdelhagen** [comment]
I'm having this issue as well. Tried the configPath option with /tmp but that didn't help. The only way I can find to get my uploads to not fail is to set resumable = false.

**Comment by stephenplusplus** [comment]
Could you create a new issue with code and full environment and error details? Thanks!

**Comment by khu834** [comment]
Setting the `configPath` works, but you need to make sure that it points to a file, not a directory.
This works for me.
```
const options = {
  configPath: `${writableDirectory}/.config`,
  resumable: true
}
```

**Comment by dhamaletrupti7** [comment]
> Setting the `configPath` works, but you need to make sure that it points to a file, not a directory.
> This works for me.
> 
> ```
> const options = {
>   configPath: `${writableDirectory}/.config`,
>   resumable: true
> }
> ```

Please send me details. I have some error to change the path

**Comment by mhidalgo** [comment]
I am still having issues here and I get this in my error logs

{
  "textPayload": "Error: Required\n    at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:129:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Compute.requestAsync (/workspace/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)\n    at async Upload.makeRequest (/workspace/node_modules/gcs-resumable-upload/build/src/index.js:348:21)\n    at async Upload.createURIAsync (/workspace/node_modules/gcs-resumable-upload/build/src/index.js:171:22)",
  "insertId": "000000-2bff227d-079d-4acf-a8ed-81d04c922e07",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "uploadNewVideo",
      "region": "us-central1",
      "project_id": "dojo-app-9812e"
    }
  },
  "timestamp": "2021-09-22T16:01:15.449Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "mlasrjcluju3"
  },
  "logName": "projects/dojo-app-9812e/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/dojo-app-9812e/traces/b209d8e3b637a4795860c1119c856743",
  "receiveTimestamp": "2021-09-22T16:01:23.677416136Z"
}

I am using cloud functions and I am trying to create a url for resumable upload.  The simple function I created is below:


```
const functions = require("firebase-functions");
const admin = require('firebase-admin');
admin.initializeApp();

exports.uploadNewVideo = functions.firestore
    .document('videos/{videoId}')
    .onCreate(async (snap, context) => {
         const bucket = admin.storage().bucket();
         const fileName = `${context.params.videoId}.mp4`;
         const videoFile = bucket.file(fileName);
         const resumableUpload = await videoFile.createResumableUpload();
         const uploadUrl = resumableUpload[0];

         console.log(uploadUrl);

       await admin.firestore().collection("videos").doc(context.params.videoId).set({ uploadUrl}, { merge: true });
    });

```

**Comment by shaffeeullah** [comment]
Hi @mhidalgo , this seems like a different issue from the original issue that was reported. Can you please open a new issue with full environment details (including cloud storage version) and repro steps?
