### ISSUE TITLE
How to do auth for public buckets

### ISSUE THREAD

**Issue by ritikrishu** [googleapis/nodejs-storage#828]
#### Environment details

  - OS: OSx 10.13.6
  - Node.js version: 12.2.0
  - npm version: 6.9.0
  - `gcp-metadata` version: 1.0.0

#### Steps to reproduce
We are using google cloud storage SDK to fetch object keys from any public bucket in an electron-based app. The code snippet that we have is-
```
const gcs = new Storage({
    projectId
  });
  const objects = await gcs.bucket(bucketName).getFiles();
  return objects[0];
```
Private buckets work fine where we also pass the services.json. Public buckets work with same code as above in dev mode but in prod builds we get the following error-
```
GET http://metadata.google.internal./computeMetadata/v1/instance net::ERR_NAME_NOT_RESOLVED
Error: Unexpected error determining execution environment: Failed to fetch
    at GoogleAuth.<anonymous> (/Users/ritikrishu/Documents/Projects/sixgill/hl-opencv/dist/mas-dev/HyperLabel.app/Contents/Resources/app.asar/node_modules/google-auth-library/build/src/auth/googleauth.js:164)
    at Generator.throw (<anonymous>)
    at rejected (/Users/ritikrishu/Documents/Projects/sixgill/hl-opencv/dist/mas-dev/HyperLabel.app/Contents/Resources/app.asar/node_modules/google-auth-library/build/src/auth/googleauth.js:20)
```
Also, I wonder if the host name here is correct, https://github.com/googleapis/gcp-metadata/blob/aa708dd9788cf12e084be1a9bdfe8594288710ae/src/index.ts#L12. `http://metadata.google.internal` does not look right.
Thanks!

**Comment by ritikrishu** [comment]
it works for me as well, in dev env. But in prod builds, it doesn't.
I'll try to give you a debuggable sample soon.

**Comment by jkwlui** [comment]
@ritikrishu is your prod environment running under a proxy? This caused problems in another issue [here](https://github.com/googleapis/google-auth-library-nodejs/issues/711)

**Comment by stephenplusplus** [comment]
@ritikrishu is this still an issue? I'm going to close since I couldn't reproduce, but I'm happy to re-open if we can get more information. Thanks!
