### ISSUE TITLE
Install older google-storage/cloud version

### ISSUE THREAD

**Issue by TomokoOG** [googleapis/nodejs-storage#844]
I'm approaching from this issue on meteor-files (https://github.com/VeliovGroup/Meteor-Files/issues/709), where I was recommended to use an older version of google cloud storage to make it work, since I had errors I couldn't explain myself. However, installing older versions like suggested didn't work. This error occurs, where I tried to install version 2.1.0:

```
C:\Users\NERV\Desktop\Projekte\DDCFull>meteor npm install @google-storage/cloud@2.1.0 --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-storage%2fcloud - Not found
npm ERR! 404
npm ERR! 404  '@google-storage/cloud@2.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NERV\AppData\Roaming\npm-cache\_logs\2019-09-07T02_00_59_714Z-debug.log
```

#### Environment details

  - OS: Windows
  - Node.js version: Meteor.js
  - npm version: npm@6.4.1
  - `@google-cloud/storage` version: any older

#### Steps to reproduce

  1. meteor npm install @google-storage/cloud@2.1.0 --save

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by AVaksman** [comment]
@TomokoOG Readingyour example [here](https://github.com/VeliovGroup/Meteor-Files/issues/709)

Please try your code with the following changes

```ts
  const {Storage} = require('@google-cloud/storage');
  gcs = new Storage({
    projectId: 'my-project-123', // <-- Replace this with your project ID
    keyFilename: 'imports\api\bucketkey.json'  // <-- Replace this with the path to your key.json
  });
  // rest of your code
```ts

You shouldn't need to install an older version `@google-cloud/storage`

Please let us know if it worked for you.

**Comment by jkwlui** [comment]
> meteor npm install @google-storage/cloud@2.1.0 --save

It looks like the package name is wrong - it should be `@google-cloud/storage`.
