### ISSUE TITLE
CreateBucketRequest should support standard storage class

### ISSUE THREAD

**Issue by bowenshu** [googleapis/nodejs-storage#847]
CreateBucketRequest should support standard storage class.
https://github.com/googleapis/nodejs-storage/blob/706e059e01af65ccd85359a2c17f1fe7e4438332/src/storage.ts#L65-L75

**Comment by bowenshu** [comment]
@frankyn

**Comment by frankyn** [comment]
@jkwlui is taking a look. Based on a short discussion this only impacts the create bucket flow with the Node.js client.

**Comment by jkwlui** [comment]
Is there a specific case where we need to set default storage class to be `standard` explicitly on bucket creation?

**Comment by frankyn** [comment]
Other than explicitly setting the value `standard` not that I'm aware of, no.
