### ISSUE TITLE
Failed to create GCP bucket, error: "404 The requested URL /storage/v1/b was not found on this server."

### ISSUE THREAD

**Issue by serhiinikitenko** [googleapis/nodejs-storage#852]
When trying to create a bucket error occurred.

#### Environment details

  - OS: Windows 10
  - Node.js version: v10.16.3
  - npm version: 6.9.0
  - `@google-cloud/storage` version: 3.2.1

#### Steps to reproduce

1. Run this code:
`
    // Imports the Google Cloud client library
    const {Storage} = require('@google-cloud/storage');

    const storage = new Storage(gcpCredentials);
    const bucketName = 'bucket-name';

    async function createBucket() {
        // Creates the new bucket
        await storage.createBucket(bucketName);
        console.log(`Bucket ${bucketName} created.`);
    }

    createBucket();
`

Actual behavior:
Error was thrown
`
(node:22180) UnhandledPromiseRejectionWarning: Error: Cannot parse response as JSON: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/storage/v1/b</code> was not found on this server.  <ins>That’s all we know.</ins>
`
Expected behavior:
Bucket with name "bucket-name" should be created.

**Comment by AVaksman** [comment]
@serhiinikitenko can you also please show content of `gcpCredentials`

**Comment by AVaksman** [comment]
I was able to reproduce when override `apiEndpoint` to `'www.google.com'`
```ts
  const storage2 = new Storage({apiEndpoint: 'www.google.com'});
  const bucketName = 'alex-bucket-name-test-bucket';
  await storage2.createBucket(bucketName);
```
UnhandledPromiseRejectionWarning: Error: Cannot parse response as JSON: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/storage/v1/b</code> was not found on this server.  <ins>That’s all we know.</ins>

**Comment by serhiinikitenko** [comment]
@bcoe @AVaksman the still reproducible
`const gcpCredentials = {
    projectId: "account id",
    keyFilename: "path/to/service_account.json"
};`

'@google-cloud/storage' uses default apiEndpoint: "apiEndpoint": "www.googleapis.com"

**Comment by bcoe** [comment]
1. @serhiinikitenko could you provide a full example of the code you're running?
2. are you running on your personal computer? or is this a Windows server?

**Comment by serhiinikitenko** [comment]
@bcoe

**Comment by serhiinikitenko** [comment]
Hi,
I figured out what was the root cause of this error.
In my code I used two google npm packages '@google-cloud/compute' and '@google-cloud/storage', for both of them I used the same credentials("gcpCredentials" object)

See my code:
`
async function main() {
    const gcpCredentials = {
        projectId: 'ID',
        keyFilename: 'PATH',
    };

    // Imports the Google Cloud client library
    const Compute = require('@google-cloud/compute');
    const { Storage } = require('@google-cloud/storage');

    const compute = new Compute(gcpCredentials);
    console.log(JSON.stringify(gcpCredentials, 1, 1));
    // {
    //     "projectId": "ID",
    //     "keyFilename": "PATH",
    //      set property by default in line https://github.com/googleapis/nodejs-compute/blob/master/src/index.js#L83
    //     "apiEndpoint": "compute.googleapis.com"
    // }
    const storage = new Storage(gcpCredentials);
    await storage.createBucket('some-name-for-bucket');
}

main();
`

The problem becomes when in "Compute" class( '@google-cloud/compute' ) constructor set default "apiEndpoint" value('compute.googleapis.com'), this value then used for "Storage" class('@google-cloud/storage') since I used the same object for both classes.
