### ISSUE TITLE
Alternative to hash-stream-validation to be able to use fast crc32

### ISSUE THREAD

**Issue by radum** [googleapis/nodejs-storage#853]
This module uses `hash-stream-validation` which in its own turn does this:

```
var crc
try {
  crc = require('fast-crc32c')
} catch (e) {
  crc = require('./crc32c.js')
}
```

So to get faster crc32 checks we need to manually install `fast-crc32c`, as per the docs also, but that module uses `sse4_crc32` which fails on Node 12 because of the N-API thingy.

This explains it also https://github.com/ashi009/node-fast-crc32c/issues/14

I understand that this issue is not related to this module but indirectly using libs that are not supported anymore affects the performance when using `@google-cloud/storage`.

Not sure what is the best way forward here but an alternative should be found.

**Comment by stephenplusplus** [comment]
This is definitely tricky. I'm following the other issues and PR, and I hope to get an idea for what our expectations should be from sse4_crc32. Ideally, we wouldn't have to move away to a different solution, but we will if we have to.

**Comment by radum** [comment]
@stephenplusplus That PR will not move as it is sitting there for a while now. The point is that to have fast CRC checks we can't upgrade node. The use cases where a faster CRC check is needed I'm sure are rare but there [are cases](https://github.com/sitespeedio/sitespeed.io/issues/2633) so IMHO it sits with us on this module to fix it and not depend on `hash-stream-validation` as it currently stands.

**Comment by stephenplusplus** [comment]
> That PR will not move 

I'm more optimistic, but we'll not let it drag out for much longer.

**Comment by stephenplusplus** [comment]
We're almost there! https://github.com/ashi009/node-fast-crc32c/pull/15

**Comment by stephenplusplus** [comment]
We're there!

**Comment by anandsuresh** [comment]
Stumbled upon this discussion during a random google search. Glad to see `sse4_crc32` being put to good use. :)

FWIW, `sse4_crc32` supports hardware acceleration with a graceful fallback to a software implementation without having do these try-catch tricks. If this seems like something you might find useful, I can send you a PR.
