### ISSUE TITLE
Feature request: allow specifying the size of the chunks provided by File#createReadStream()

### ISSUE THREAD

**Issue by Dinduks** [googleapis/nodejs-storage#860]
Hello,

At the moment, the chunks returned by [`File#createReadStream()` method](https://googleapis.dev/nodejs/storage/latest/File.html#createReadStream) are 16kb long.  
I believe that's Node's default `highWaterMark` value.

The issue with this is that it consumes too much memory to read a big file.  

For a 250mb file, that's 16k chunks, and it consumes 2GB of memory before the process crashes. 

If you are okay with it, I'd like to submit a PR to specify the chunks size.

I will look into `createReadStream()` code tonight and see what I can do.

Meanwhile, any help or guidance is welcome.

Thanks,

Samy

**Comment by AVaksman** [comment]
@Dinduks Thank you for reporting this.
Could you please give more details, share your environment details
#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/storage` version:
  - related modules versions:

#### Please share a code snippet that causes the issue.

I've tried to reproduce in a couple of ways:
- `file.download` into file/buffer
- `file.createReadStream` into file/buffer
but unsuccessful

**Comment by Dinduks** [comment]
@AVaksman Hi Alex.

Indeed, there is no issue with @google-cloud/storage itself.

The memory issues come from the thousands of operations inside my `.on('data', () => {})` on the stream created by `createReadStream`.

I think being able to grab chunks bigger than 16kb would solve this problem by reduce the number of operations inside `.on('data', () => {})`.

Meanwhile, I'll try to optimize these operations.

I could provide the sample if you think it's relevant.

Also:  
* OS is Arch Linux kernel 5.2.8  
* Node version is v11.15.0  
* npm version is 6.10.3  
* GS version is 3.3.0 or 3.2.1
* Used lib inside `.on('data', () => {})` is https://www.npmjs.com/package/stream-buffers.

**Comment by jkwlui** [comment]
`highWaterMark` does not dictate the size of the chunk:

https://github.com/nodejs/node/issues/8855

**Comment by Dinduks** [comment]
What's your point @jkwlui?

**Comment by jkwlui** [comment]
Would you mind providing us with a simple reproduction code that we can try and replicate? You mentioned using `stream-buffers` inside the event callback, so if you could provide an example of that it'd be great, thanks!

**Comment by stephenplusplus** [comment]
@Dinduks please feel free to provide more information, but I believe this is an issue to solve at the application level as opposed to our level in the library. You could look into using something like [throttle](https://github.com/TooTallNate/node-throttle), or otherwise queueing the operations you're running in the `.on()` handler in steps. You can also use the `start` and `end` options when reading a file to only handle chunks of the file at once.

I'm going to close the issue, but I'm happy to re-open if there's more we should do on our side.
