### ISSUE TITLE
doc examples need to be cleaned up 

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/nodejs-storage#901]
I was just browsing the Storage API docs and it looks like they could use some love. Using [`bucket.getFiles`](https://googleapis.dev/nodejs/storage/latest/Bucket.html#getFiles) as an example, there are two obvious items that stick out to me.

1. We lump all examples together and use JS comments to caption each example. IMO this is a bad user experience because it is not obvious where one example ends and another begins, making it easy for users to miss the sample they're looking for.

2. The cloud site includes are being displayed incorrectly (e.g. `include:samples/files.js`). I'm not sure if these still get displayed on the cloud site, but it seems like we should either remove them or create a plugin to interpolate the desired sample file.

**Comment by stephenplusplus** [comment]
#&shy;2 looks to have been addressed, and re: #&shy;1-- true. I believe this will be naturally addressed by the solution we choose as doc generation evolves (snippets vs samples vs JSDocs + TS types combining).
