### ISSUE TITLE
The Stream returned by file.createWriteStream is readable too

### ISSUE THREAD

**Issue by julienw** [googleapis/nodejs-storage#937]
I tried to use Stream.finished on the stream returned by `file.createWritestream`, but this doesn't reliably work, while using the `finished` event works fine. From my investigation I found that this stream's `readable` property is `true` but the `writable` property is `false`, which seems incorrect ?

Here is the bit where we call the callback only if the stream isn't `readable`: https://github.com/nodejs/node/blob/9d09969f4c29b7f2bacc9cb44e210c4e269945a4/lib/internal/streams/end-of-stream.js#L42

**Comment by bcoe** [comment]
@AVaksman this might relate to some of the streaming issues you brought up this week?

**Comment by callmehiphop** [comment]
As it turns out `createWriteStream` actually returns a `Duplex` stream via duplexify, which would explain why `readable` is set to true. I assume we're using duplexify so that it can buffer writes until the request pipeline is finished being built. I'm not sure if we actually use the readable portion here, but we should be able to do something like this

```js
const duplex = duplexify(null, null, {readable: false});
```

**Comment by bcoe** [comment]
@callmehiphop potentially send a patch if you have the cycles?

**Comment by callmehiphop** [comment]
@julienw until we get a patch out for this, you can actually set `readable` to `false` via [`finished` options](https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback)

```js
const stream = file.createWriteStream();

finished(writable, {readable: false}, err => {
  // ...
});
```

@stephenplusplus is the readable portion of this stream used for anything?

**Comment by julienw** [comment]
This has been my workaround:
```js
    await new Promise((resolve, reject) => {
      googleStorageStream.on('error', reject);
      googleStorageStream.on('finish', resolve);
      googleStorageStream.end(fullContent);
    });
```
Like Irish people say: the old pipe (pun intended) gives the sweetest smoke.

**Comment by stephenplusplus** [comment]
`createWriteStream` returns a combined stream of many inner pieces:

```js
const stream = streamEvents(
  pumpify([
    gzip ? zlib.createGzip() : through(),
    validateStream,
    fileWriteStream,
  ])
) as Duplex;
```

- streamEvents - Returns the same stream as is passed in
  - pumpify - "Combines" streams, forwarding any error from an inner stream to the returned stream
    - gzip/validateStream/fileWriteStream - Compression -> validation -> API request stream

I don't believe we could return a plain Writable, as we need to further connect the incoming data to these other streams. Let me know if I'm overlooking another architecture we could make work here.

**Comment by julienw** [comment]
My understanding is that node's `finished` utility will call the callback when both the readable and writable finishes (we get both events `'finish'` and `'end'`).

If I understand properly what pumpify does:
* it pipes streams from one to the next, forwarding errors
* the first in the list is the Writable side
* the last in the list is the Readable side.

In this case, the Readable side is then `fileWriteStream`, which isn't a Readable. Probably that's why we never get the `'end'` event and so `finished` never calls the callback (I didn't check this is the reason, that's just a guess).

Maybe pumpify isn't so useful, now that node has `pipeline` and we don't need the "duplexify" ability?  With `pipeline` we would return the first stream in the list (the one to write to). Actually maybe we could return this one already now?

Do I miss something?

I'm not sure how you use the functionality provided by `streamEvents`  so this might be a problem with this suggestion.
