### ISSUE TITLE
Strange return value from fileRef.exists()

### ISSUE THREAD

**Issue by lborgman** [googleapis/nodejs-storage#939]
#### Environment details

  - OS: Windows 10
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `@google-cloud/storage` version: (not sure, please see linked issue)

#### Steps to reproduce
Please see the issue here:
https://github.com/firebase/firebase-tools/issues/1817

The variable "exists" is in a very strange state. At least if you try to handle it as a boolean variable.

I have no idea whether this is expected behavior or not. So I am asking you here to take a look.

**Comment by AVaksman** [comment]
The promise signature of `exists` function is `Promise<[boolean]`
The recommended usage is
```ts
const [exists] = await file.exists();
```
Does that help your issue?

**Comment by AVaksman** [comment]
If used as in your [firebase/firebase-tools#1817](https://github.com/firebase/firebase-tools/issues/1817) example
```ts
    const exists = await fileInRef.exists();
    console.log(exists, !exists) // -> this will print "[ false ] false"
```

**Comment by lborgman** [comment]
> The promise signature of `exists` function is `Promise<[boolean]`
> The recommended usage is
> 
> ```ts
> const [exists] = await file.exists();
> ```
> 
> Does that help your issue?

Yes, I am aware of this now. However it also worked with this syntax before just as I thought it should:

       const exists = await fileInRef.exists();

But the output right now is 

    console.log(exists, !exists) // -> prints "false false"

How does it come you see another output?

**Comment by stephenplusplus** [comment]
> Yes, I am aware of this now. However it also worked with this syntax before just as I thought it should:
>
> ```js
>       const exists = await fileInRef.exists();
> ```

If using our library directly, that wouldn't work. Our `exists()` method always resolves an array. Some of this is JavaScript trickery, where `!exists` isn't inverting a boolean, it's attempting to cast the array:

```sh
$ node -p '![]'
false
```

I would suggest adapting your code to assume you will always have to use the first argument from the resolved array:

```js
const [exists] = await fileInRef.exists();
```

> But the output right now after setting "exists" as above is
>
> ```js
>     console.log(exists, !exists) // -> prints "false false"
> ```

That appears to have been unique to firebase-tools and was fixed here: https://github.com/firebase/firebase-tools/pull/1824/files

Hopefully this resolves all of the confusion. Sorry about that-- we are working towards making `const exists = file.exists()` return the naturally expected argument of a simple boolean.

**Comment by lborgman** [comment]
> I would suggest adapting your code to assume you will always have to use the first argument from the resolved array:
> 
> ```js
> const [exists] = await fileInRef.exists();
> ```

Thanks. You have an interesting problem to solve there. If I use your advice now would not my code break later? (You said you are working towards making .exists() return a boolean.)

**Comment by stephenplusplus** [comment]
It wouldn't break your code automatically, we would release it as a semver-major bump so that `npm` won't update you without your knowing. You would have to manually install the new version and make the changes to your code at that time.
