### ISSUE TITLE
Storage.createBucket fails without callback

### ISSUE THREAD

**Issue by jasonpolites** [googleapis/nodejs-storage#94]
The [docs](https://cloud.google.com/nodejs/docs/reference/storage/1.4.x/Storage#createBucket) for `createBucket` indicate that it supports invocation without a callback and should return a promise:

```Javascript
//-
// If the callback is omitted, we'll return a Promise.
//-
storage.createBucket('new-bucket').then(function(data) {
  var bucket = data[0];
  var apiResponse = data[1];
});
```

In reality, this fails with:

```
TypeError: callback is not a function
```

Looking at the source, it seems to do some [weird things](https://github.com/googleapis/nodejs-storage/blob/master/src/index.js#L308) with treating `metadata` as a function:

```Javascript
if (!callback) {
    callback = metadata;
    metadata = {};
}
```

It seems this will either result in `callback` being `undefined` (as `metadata` is also optional), or `callback` will be an object but still not a function.

There doesn't appear to be any path in the [API callback](https://github.com/googleapis/nodejs-storage/blob/master/src/index.js#L356) to return a promise

**Comment by stephenplusplus** [comment]
Thanks! On it.

**Comment by stephenplusplus** [comment]
I wasn't able to reproduce. Your points about the code are correct, however, they do not factor in the "promisify" method that wraps all methods:

- [`common.util.promisifyAll(Storage)`](https://github.com/googleapis/nodejs-storage/blob/2dd79fa0d28df4f68eb849466f8c78b0219e66cd/src/index.js#L520)
- [`util.promisifyAll` definition](https://github.com/googleapis/nodejs-common/blob/0b7596d91a23d00eddd5d6bd01a5de355a75784c/src/util.js#L722)

How were you executing the code?

**Comment by jasonpolites** [comment]
Let me see if I can capture a repro.  I might be holding it wrong

**Comment by jasonpolites** [comment]
Yep.. Jason was holding it wrong.  Apologies.

**Comment by stephenplusplus** [comment]
It happens!
