### ISSUE TITLE
there is a flaky system-test resulting in frequent failing builds

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-storage#942]
There is a system test that is causing frequent failing builds:

```js

      it('should not upload a file', done => {
        file.save('new data', err => {
          assert(
            err!.message.indexOf('Could not load the default credentials') > -1
          );
          done();
        });
      });
```

It seems as though `file.save` occasionally gets an error related to missing credentials, and occasionally gets another error; it would be good to get to the root cause of this.

Refs: #940

**Comment by stephenplusplus** [comment]
This seems better now. I'll close, but just re-open it there are any lingering flaking builds.
