### ISSUE TITLE
files.js sample does not have upload and upload-directory possibility

### ISSUE THREAD

**Issue by Tim-Schwalbe** [googleapis/nodejs-storage#949]
Execute sample for file and directory upload. It will give you parameters unknown.

**Comment by vishald123** [comment]
Hi @Tim-Schwalbe, I tested it and it seems to work fine. Can you provide more details?

**Comment by Tim-Schwalbe** [comment]
if you look here: https://github.com/googleapis/nodejs-storage/blob/master/samples/files.js
There is no function to upload a directory if your search in the above file for `upload-directory`
There is a example but no function to call. Same for just `upload`.
I hope this helps
