### ISSUE TITLE
Upload file using Blob or Base64 String

### ISSUE THREAD

**Issue by jdnichollsc** [googleapis/nodejs-storage#954]
Hello guys,
Other npm packages are deprecated now to upload files to firebase storage, and I can't see any example uploading Blobs from NodeJS. Can you give me any advice please?
Thanks for your time 👍

**Comment by stephenplusplus** [comment]
Hello! I believe what you’re looking for is:

    bucket.file(‘filename.txt’).save(Buffer.from(‘abc’), callback)

Let me know if this isn’t what you need!

**Comment by jdnichollsc** [comment]
Awesome, thanks for your help! 🥇
