### ISSUE TITLE
progress tracking when uploading big file

### ISSUE THREAD

**Issue by gamaya-developer** [googleapis/nodejs-storage#956]
Maybe I missed something but couldn't find a way to track progress during uploading. Is it possible to do it now?

I think it would be great to have an option for example:

`const options = {
   onProgress: (data) => {
          console.log(data.loadedBytes)
       }
  };`

`await storage.bucket(bucketName).upload(filename, options);`

**Comment by 1c7** [comment]
Hi, can anyone update the document and provide an example on how to get upload progress?

**Comment by 1c7** [comment]
```javascript
const bucket = storage.bucket("[bucket_name]")
const remote_file = bucket.file("[file_name]")
fs.createReadStream("[file_path]")
  .pipe(remote_file.createWriteStream())
  .on('error', function (err) {})
  .on('progress', function (p) {
    console.log(`progress get called`);
    console.log(p);
    // { bytesWritten: 67371008, contentLength: '*' }
  })
  .on('finish', function () {
    // The file upload is complete.
  });
```
