### ISSUE TITLE
Cannot parse response as JSON: Invalid multipart request with 0 mime parts.

### ISSUE THREAD

**Issue by sachaw** [googleapis/nodejs-storage#958]
#### Environment details

  - OS: Win 10
  - Node.js version: 13.3
  - npm version: 6.13.1
  - `@google-cloud/storage` version: 4.1.3

creating a new upload script as per the docs, uploading a '.kml' file (and many other file types results in the following error:
```Cannot parse response as JSON: Invalid multipart request with 0 mime parts.```

**Comment by bcoe** [comment]
@sachaw could you provide a bit of code that demonstrates how you are performing the upload?

**Comment by sachaw** [comment]
```
this.bucket.upload(filePath, (err, file, apiResponse) => {
  console.dir(apiResponse)
})
```
the input filePath can be a number of files, I tried: kml, dll, ico and a heap more, however I tried uploading a jpeg and it works as intended

**Comment by laljikanjareeya** [comment]
@sachaw not able to re-produce it. can you provide more info like:
Any Options are you using while uploading file?
is it failing every time or irregular?
Could you post the complete stack trace?

**Comment by dmitry-fa** [comment]
Quoting Justin Beckwith: 
https://stackoverflow.com/questions/48526185/google-drive-upload-api-invalid-multipart-request-with-0-mime-parts?noredirect=1&lq=1
"Please, please make sure that you do not install your own version of google-auth-library along side googleapis"

**Comment by stephenplusplus** [comment]
@sachaw I tried the following with success:

```js
'use strict'

const storage = new (require('@google-cloud/storage')).Storage()
const bucket = storage.bucket('__mybucketname__')

;(async () => {
  try {
    await bucket.upload('./KML_Samples.kml')
    console.log('Successful upload')
  } catch (e) {
    console.log(e)
  }
})()
```

`.KML_Samples.kml` was downloaded from https://developers.google.com/kml/documentation/KML_Samples.kml.

As I cannot reproduce and we lack further details, I'll close for now. If there's something you can change with my example to demonstrate the error, please do.
