### ISSUE TITLE
Add refFromUrl equivalent from Firebase Web SDK

### ISSUE THREAD

**Issue by willbattel** [googleapis/nodejs-storage#962]
**Is your feature request related to a problem? Please describe.**
We're storing Cloud Storage URIs in Cloud Bigtable, and we want to be able to easily generate File references using those URIs in Cloud Functions. These URIs come from many different buckets, and we do not wish to keep these bucket objects in memory outside of the function scope.

 **Describe the solution you'd like**
The Firebase Web SDK has exactly the method we wish for in the GCS Node SDK: `refFromUrl`. https://firebase.google.com/docs/reference/js/firebase.storage.Storage.html#reffromurl

 **Describe alternatives you've considered**
It is possible to generate a File object reference by parsing the string, [as suggested on SO](https://stackoverflow.com/a/51200812/1500134). However, while this does work, I hardly consider this to be an elegant solution. I was sure there would be a way to generate a File reference from a GCS URI with one line of code. I understand that this library is entirely different than the Firebase Web SDK, serving different purposes, in different contexts, and that their only similarity is their relation to the underlying Google product. Despite this, I don't see why this library can't support features like `refFromUrl` that are useful in both contexts.

**Additional context**
This is what I would like to be able to do
```
const objectUrl = 'gs://some-bucket/path/to/object.ext'
const file = storage.refFromUrl(objectUrl)
const signedUrl = await file.getSignedUrl({action: 'read', expires: '03-17-2025'})
```

**Comment by stephenplusplus** [comment]
Thank you for the detailed request! Would you be interested in sending a PR to add the new method? I would lean towards a name like `storage.fileFromUrl()` so the return type is more clear.

**Comment by willbattel** [comment]
@stephenplusplus sure. I'll see about putting a PR together.

**Comment by frankyn** [comment]
Adding the following context from Python.
Python added helpers for referencing buckets and objects with `gs://...`, to help users get a reference easier.

PR: https://github.com/googleapis/google-cloud-python/pull/9143

I'd agree with the general storage.fileFromURI().

Thank @willbattel for your help!

**Comment by stephenplusplus** [comment]
At this point, I don't believe this change is necessary, since users with only a `gs://` URL still have ways of creating a File object. I believe since we haven't seen any other feedback wishing for this feature, we can close and revisit another time, if necessary.

**Comment by willbattel** [comment]
No worries about closing it, though I may still submit a PR in the future if I get around to it.
