### ISSUE TITLE
Constructor should not modify its options argument

### ISSUE THREAD

**Issue by justinwh** [googleapis/nodejs-storage#971]
**Problem**
I recently spent a frustrating afternoon debugging a problem that I finally figured out is an instance of this issue: https://github.com/googleapis/nodejs-storage/issues/852

The underlying problem is that the `Storage` constructor modifies its `options` argument in place, and the modified `options` is then invalid/incorrect when passed to other GCP client constructors.

To illustrate, here's a sample of how I was using the library alongside `@google-cloud/bigquery`:

```
const {BigQuery} = require('@google-cloud/bigquery');
const {Storage} = require('@google-cloud/storage');
function run (myConfig) {
  let gcpOptions = {keyFilename: myConfig.gcpKeyFile};
  let s = new Storage(gcpOptions);
  let b = new BigQuery(gcpOptions);
  // try to use `b` and get confusing errors like "Cannot parse response as JSON"
}
```

It's surprising that the above code fails to produce two working clients, since the `gcpOptions` object is a correct and valid argument for each constructor.  What's happening is that `new Storage` writes to `gcpOptions.apiEndpoint` and then `new BigQuery` tries to use that endpoint (and fails).

Storage constructor:
https://github.com/googleapis/nodejs-storage/blob/5ca0e4411861abfa7d2723b554a462609d2aad3f/src/storage.ts#L375

BigQuery constructor:
https://github.com/googleapis/nodejs-bigquery/blob/0cd043502dea137533549712a78c3fc4435803c0/src/bigquery.ts#L247

While this isn't a bug per se, it is unexpected (and unconventional) behavior that leads to very hard-to-diagnose errors (they only happen later on; the messages do not indicate misconfiguration; and seemingly unrelated changes to the order of the constructors change the behavior).

The "fix" I applied to my own code was to make a copy of `gcpOptions` before passing it to each constructor.  But in the interest of improving the ergonomics of the library, I'm also opening this ticket to propose a change.

**Solution**
I propose that the constructor should not modify its `options` argument.  If it needs a modified options, e.g. to pass to its superclass constructor, it should copy the options first and modify the copy.

Modifying the `options` in place seems to be a common pattern among the GCP client library constructors (as seen with BigQuery above, and Compute in the referenced issue).  If there's an advantage to doing it this way that I haven't noticed, please correct me—maybe we can come up with a solution that satisfies all use cases.

(If the nodejs-storage maintainers agree with the change, I'm curious what would be the best way to apply it across the GCP client libraries more broadly.  Would I file issues with each individual repo?)

**Comment by bcoe** [comment]
@justinwh thank you for the bug report, sorry for the frustration.
